/*
 * ชุดที่ 39 — วันกีฬาสี (ชุดผสม ใช้รูปที่มีอยู่แล้ว) แบบ 15 ข้อ
 * ช่วง 1 ฟังเรื่องแพรวแข่งวิ่งวันกีฬาสี ถาม 5 ข้อ: สีของแพรว ใครที่ 1 แพรวมาก่อนใคร ดื่มน้ำพักในร่ม น้ำใจนักกีฬา
 * ช่วง 2 ภาพลูกบอลกับรองเท้ากีฬาวางปนกัน ถาม 5 ข้อ: นับ เปรียบเทียบ เพิ่มให้เท่ากัน รองเท้ากี่ข้าง
 * ช่วง 3 ข้อเดี่ยว: อยู่ระหว่าง คำความหมายเหมือน เพื่อนหกล้ม 4 สีสีละ 3 คน เข้าเส้นชัยหลังต้นกี่คน
 * แต่งใหม่ทั้งหมด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const STORY = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const COUNT = 'ดูภาพแล้วนับให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const words = (...list) => list.map((text, i) => ({ id: 'abc'[i], text }));

const STORY_TEXT = 'โรงเรียนจัดงานกีฬาสี ห้องของแพรวอยู่สีฟ้า แพรววิ่งแข่ง 50 เมตร ได้ที่ 2 เพื่อนสีแดงได้ที่ 1 ส่วนเพื่อนสีเหลืองได้ที่ 3 ตอนพักทุกคนดื่มน้ำและนั่งพักในร่ม ครูชมว่าทุกคนเล่นอย่างมีน้ำใจนักกีฬา';
const GEAR = { type: 'scatter', items: [{ asset: 'pic-ball', count: 6 }, { asset: 'pic-sneakers', count: 4 }] };
const GEAR_TEXT = 'ในห้องเก็บอุปกรณ์กีฬา มีลูกบอลและรองเท้ากีฬาวางปนกัน รองเท้า 1 ภาพคือรองเท้า 1 คู่';

export default {
  id: 'set-39',
  version: 1,
  title: 'ชุดที่ 39',
  note: 'วันกีฬาสี นับอุปกรณ์กีฬา น้ำใจนักกีฬา ลำดับที่',
  order: [
    'g-sport-color', 'g-sport-first', 'r-sport-before', 'sc-sport-rest', 'th-sport-spirit',
    'm-gear-balls', 'm-gear-shoes', 'm-gear-more', 'r-gear-equal', 'm-gear-sides',
    'sp-gear-between', 'th-same-fast', 'g-race-fall', 'm-team-colors', 'r-race-after',
  ],
  stimuli: {
    story: { section: STORY, text: STORY_TEXT },
    gear: { section: COUNT, text: GEAR_TEXT, visual: GEAR },
  },
  items: [
    // ================================================================ ช่วงที่ 1: เรื่องวันกีฬาสี
    {
      id: 'g-sport-color', type: 'main', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ห้องของแพรวอยู่สีอะไร' },
      options: words('สีแดง', 'สีฟ้า', 'สีเหลือง'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจำรายละเอียดจากเรื่องที่ฟัง',
      review: {
        summary: 'ห้องของแพรวอยู่สีฟ้า',
        hints: ['ฟังประโยคที่สองของเรื่อง'],
        steps: ['เรื่องบอกว่า ห้องของแพรวอยู่สีฟ้า สีแดงและสีเหลืองเป็นสีของเพื่อน', 'ตอบข้อ 2'],
        transferIds: ['g-sport-color-t'],
      },
    },
    {
      id: 'g-sport-first', type: 'main', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ใครวิ่งเข้าเส้นชัยเป็นคนแรก' },
      options: words('เพื่อนสีแดง', 'แพรว', 'เพื่อนสีเหลือง'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจคำว่า ได้ที่ 1',
      review: {
        summary: 'ได้ที่ 1 คือเข้าเส้นชัยเป็นคนแรก เพื่อนสีแดงได้ที่ 1',
        hints: ['คนที่ได้ที่ 1 คือคนที่ถึงเส้นชัยก่อนทุกคน'],
        steps: ['แพรวได้ที่ 2 และเพื่อนสีเหลืองได้ที่ 3', 'เพื่อนสีแดงได้ที่ 1 จึงเข้าเส้นชัยเป็นคนแรก ตอบข้อ 1'],
        transferIds: ['g-sport-first-t'],
      },
    },
    {
      id: 'r-sport-before', type: 'main', subject: 'reasoning', skillIds: ['order-position'], familyId: 'race-order', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'แพรววิ่งเข้าเส้นชัยก่อนใคร' },
      options: words('เพื่อนสีแดง', 'เพื่อนสีเหลือง', 'ไม่ได้ก่อนใครเลย'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงลำดับที่ 1 2 3',
      review: {
        summary: 'แพรวได้ที่ 2 จึงมาก่อนคนที่ได้ที่ 3 คือเพื่อนสีเหลือง',
        hints: ['ที่ 2 มาก่อนที่ 3 แต่มาหลังที่ 1'],
        steps: ['ลำดับคือ เพื่อนสีแดงที่ 1 แพรวที่ 2 เพื่อนสีเหลืองที่ 3', 'แพรวมาก่อนเพื่อนสีเหลือง ตอบข้อ 2'],
        transferIds: ['r-sport-before-t'],
      },
    },
    {
      id: 'sc-sport-rest', type: 'main', subject: 'science', skillIds: ['health'], familyId: 'exercise-health', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ทำไมตอนพักทุกคนจึงดื่มน้ำและนั่งพักในร่ม' },
      options: words('เพราะเสียเหงื่อมากและแดดร้อน', 'เพราะอยากนอนหลับ', 'เพราะฝนตก'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องดูแลร่างกายเมื่อออกกำลังกาย',
      review: {
        summary: 'วิ่งแล้วเสียเหงื่อ ต้องดื่มน้ำ และหลบแดดร้อนในที่ร่ม',
        hints: ['หลังวิ่งเหนื่อยๆ กลางแดด ร่างกายเป็นอย่างไร'],
        steps: ['เรื่องไม่ได้บอกว่าฝนตกหรืออยากนอน', 'ออกกำลังกายแล้วเสียเหงื่อและแดดร้อน จึงต้องดื่มน้ำและพักในร่ม ตอบข้อ 1'],
        transferIds: ['sc-sport-rest-t'],
      },
    },
    {
      id: 'th-sport-spirit', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'มีน้ำใจนักกีฬา หมายถึงข้อใด' },
      options: words('ต้องชนะทุกครั้ง', 'ไม่ยอมเล่นกับคนอื่น', 'รู้แพ้ รู้ชนะ ไม่โกรธเมื่อแพ้'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความหมายของสำนวน',
      review: {
        summary: 'น้ำใจนักกีฬา คือรู้แพ้ รู้ชนะ และให้อภัยกัน',
        hints: ['ครูชมทุกคน ไม่ได้ชมแค่คนที่ชนะ'],
        steps: ['คนที่อยากชนะทุกครั้งหรือไม่ยอมเล่นกับคนอื่น ไม่ใช่น้ำใจนักกีฬา', 'น้ำใจนักกีฬาคือรู้แพ้ รู้ชนะ ไม่โกรธเมื่อแพ้ ตอบข้อ 3'],
        transferIds: ['th-sport-spirit-t'],
      },
    },

    // ================================================================ ช่วงที่ 2: นับอุปกรณ์กีฬา
    {
      id: 'm-gear-balls', compact: true, type: 'main', subject: 'math', skillIds: ['classify-count'], familyId: 'scatter-count', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'gear',
      prompt: { text: 'ในภาพมีลูกบอลกี่ลูก' },
      options: words('5 ลูก', '6 ลูก', '7 ลูก'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับสิ่งของที่วางปนกัน',
      review: {
        summary: 'นับลูกบอลได้ 6 ลูก',
        hints: ['นับเฉพาะลูกบอลทีละลูก แตะทีละลูกเพื่อไม่ให้นับซ้ำ'],
        steps: ['นับลูกบอลจากซ้ายไปขวา บนลงล่าง', 'ได้ 6 ลูก ตอบข้อ 2'],
        transferIds: ['m-gear-balls-t'],
      },
    },
    {
      id: 'm-gear-shoes', compact: true, type: 'main', subject: 'math', skillIds: ['classify-count'], familyId: 'scatter-count', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'gear',
      prompt: { text: 'ในภาพมีรองเท้ากีฬากี่คู่' },
      options: words('4 คู่', '3 คู่', '5 คู่'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการนับสิ่งของที่วางปนกัน',
      review: {
        summary: 'รองเท้ากีฬามี 4 ภาพ คือ 4 คู่',
        hints: ['รองเท้า 1 ภาพคือ 1 คู่'],
        steps: ['นับภาพรองเท้าได้ 4 ภาพ', 'จึงมีรองเท้า 4 คู่ ตอบข้อ 1'],
        transferIds: ['m-gear-shoes-t'],
      },
    },
    {
      id: 'm-gear-more', compact: true, type: 'main', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'scatter-compare', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'gear',
      prompt: { text: 'ในภาพ ลูกบอลมีมากกว่ารองเท้ากี่ภาพ' },
      options: words('1 ภาพ', '2 ภาพ', '3 ภาพ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการเปรียบเทียบจำนวนด้วยการลบ',
      review: {
        summary: 'ลูกบอล 6 ภาพ รองเท้า 4 ภาพ ต่างกัน 2 ภาพ',
        hints: ['นับทั้งสองอย่างก่อน แล้วลบกัน'],
        steps: ['ลูกบอล 6 ภาพ รองเท้า 4 ภาพ', '6 ลบ 4 เท่ากับ 2 ตอบข้อ 2'],
        column: { a: 6, op: '-', b: 4 },
        transferIds: ['m-gear-more-t'],
      },
    },
    {
      id: 'r-gear-equal', compact: true, type: 'main', subject: 'reasoning', skillIds: ['multi-step-picture'], familyId: 'make-equal', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'gear',
      prompt: { text: 'ต้องเพิ่มรองเท้าอีกกี่คู่ จึงจะมีจำนวนเท่ากับลูกบอล' },
      options: words('2 คู่', '3 คู่', '6 คู่'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการหาจำนวนที่ต้องเพิ่มให้เท่ากัน',
      review: {
        summary: 'รองเท้า 4 คู่ ต้องเพิ่มอีก 2 คู่จึงเท่ากับลูกบอล 6 ลูก',
        hints: ['รองเท้าน้อยกว่าลูกบอลอยู่เท่าไร'],
        steps: ['ลูกบอล 6 รองเท้า 4 ขาดอยู่ 2', 'เพิ่มรองเท้าอีก 2 คู่จะได้ 6 เท่ากัน ตอบข้อ 1'],
        transferIds: ['r-gear-equal-t'],
      },
    },
    {
      id: 'm-gear-sides', compact: true, type: 'main', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'gear',
      prompt: { text: 'รองเท้ากีฬา 4 คู่ มีรองเท้าทั้งหมดกี่ข้าง' },
      options: words('4 ข้าง', '6 ข้าง', '8 ข้าง'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการรู้ว่า 1 คู่มี 2 ข้าง แล้วบวกซ้ำ',
      review: {
        summary: '1 คู่มี 2 ข้าง 4 คู่เป็น 2 บวก 2 บวก 2 บวก 2 เท่ากับ 8 ข้าง',
        hints: ['รองเท้า 1 คู่มี 2 ข้าง ซ้ายและขวา'],
        steps: ['นับทีละคู่ 2 4 6 8', '4 คู่มี 8 ข้าง ตอบข้อ 3'],
        transferIds: ['m-gear-sides-t'],
      },
    },

    // ================================================================ ช่วงที่ 3: ข้อเดี่ยว
    {
      id: 'sp-gear-between', type: 'main', subject: 'spatial', skillIds: ['position-between'], familyId: 'position-between', difficulty: 1,
      sourceId: SRC, ...R, section: 'ดูภาพแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'อะไรอยู่ระหว่างลูกบอลกับจักรยาน' },
      visual: { type: 'row', items: ['pic-ball', 'pic-sneakers', 'pic-bicycle'], sides: true },
      options: words('รองเท้า', 'ลูกบอล', 'ไม่มีอะไร'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจคำว่า ระหว่าง',
      review: {
        summary: 'รองเท้าอยู่ตรงกลาง ระหว่างลูกบอลกับจักรยาน',
        hints: ['ระหว่าง คือตรงกลางของสองสิ่ง'],
        steps: ['ลูกบอลอยู่ซ้ายสุด จักรยานอยู่ขวาสุด', 'ตรงกลางคือรองเท้า ตอบข้อ 1'],
        transferIds: ['sp-gear-between-t'],
      },
    },
    {
      id: 'th-same-fast', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'same-meaning', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดมีความหมายเหมือนคำว่า เร็ว' },
      options: words('ช้า', 'หนัก', 'ไว'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดคำที่มีความหมายเหมือนกัน',
      review: {
        summary: 'เร็ว กับ ไว มีความหมายเหมือนกัน',
        hints: ['วิ่งเร็ว อาจพูดว่าวิ่งอะไรได้อีก'],
        steps: ['ช้าตรงข้ามกับเร็ว และหนักเป็นเรื่องน้ำหนัก', 'ไวมีความหมายเหมือนเร็ว ตอบข้อ 3'],
        transferIds: ['th-same-fast-t'],
      },
    },
    {
      id: 'g-race-fall', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'kindness', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อเพื่อนหกล้มระหว่างวิ่งแข่ง ควรทำอย่างไร' },
      options: words('หัวเราะเยาะเพื่อน', 'ช่วยพยุงเพื่อนและบอกครู', 'วิ่งต่อไปไม่สนใจ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการมีน้ำใจต่อเพื่อน',
      review: {
        summary: 'ช่วยพยุงเพื่อนและบอกครู เป็นการมีน้ำใจ',
        hints: ['ถ้าเราหกล้ม เราอยากให้เพื่อนทำอย่างไร'],
        steps: ['หัวเราะเยาะทำให้เพื่อนเสียใจ และไม่สนใจก็ไม่ช่วยเพื่อน', 'ช่วยพยุงเพื่อนและบอกครู ตอบข้อ 2'],
        transferIds: ['g-race-fall-t'],
      },
    },
    {
      id: 'm-team-colors', type: 'main', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีนักกีฬา 4 สี สีละ 3 คน รวมมีนักกีฬากี่คน' },
      options: words('7 คน', '12 คน', '10 คน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบวกซ้ำ',
      review: {
        summary: '3 บวก 3 บวก 3 บวก 3 เท่ากับ 12 คน',
        hints: ['นับทีละสี สีละ 3 คน'],
        steps: ['นับทีละสี 3 6 9 12', 'รวม 12 คน ตอบข้อ 2'],
        transferIds: ['m-team-colors-t'],
      },
    },
    {
      id: 'r-race-after', type: 'main', subject: 'reasoning', skillIds: ['order-position'], familyId: 'race-order', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'วิ่งแข่งกัน 5 คน ต้นเข้าเส้นชัยเป็นที่ 2 มีคนเข้าเส้นชัยหลังต้นกี่คน' },
      options: words('2 คน', '3 คน', '4 คน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการคิดลำดับที่ (ที่ 3 4 5 อยู่หลังที่ 2)',
      review: {
        summary: 'คนที่ได้ที่ 3 4 และ 5 เข้าเส้นชัยหลังต้น รวม 3 คน',
        hints: ['เขียนลำดับที่ 1 ถึง 5 แล้วดูว่าหลังที่ 2 มีกี่คน'],
        steps: ['ลำดับที่ 1 2 3 4 5 ต้นอยู่ที่ 2', 'หลังต้นมีที่ 3 4 5 รวม 3 คน ตอบข้อ 2'],
        transferIds: ['r-race-after-t'],
      },
    },

    // ================================================================ โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'g-sport-color-t', type: 'transfer', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 1,
      sourceId: SRC, ...R, section: STORY,
      prompt: { text: 'ต้นใส่เสื้อสีเขียวไปงานกีฬาสี เพราะห้องของต้นอยู่สีเขียว ห้องของต้นอยู่สีอะไร' },
      options: words('สีเขียว', 'สีชมพู', 'สีม่วง'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ห้องของต้นอยู่สีเขียว', hints: [], steps: ['เรื่องบอกว่า ห้องของต้นอยู่สีเขียว', 'ต้นจึงใส่เสื้อสีเขียว'] },
    },
    {
      id: 'g-sport-first-t', type: 'transfer', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 2,
      sourceId: SRC, ...R, section: STORY,
      prompt: { text: 'แข่งกระโดดเชือก นิดได้ที่ 3 หน่อยได้ที่ 1 แป้งได้ที่ 2 ใครกระโดดได้ดีที่สุด' },
      options: words('นิด', 'แป้ง', 'หน่อย'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'หน่อยได้ที่ 1 จึงดีที่สุด', hints: [], steps: ['ที่ 1 คือดีที่สุด', 'หน่อยได้ที่ 1'] },
    },
    {
      id: 'r-sport-before-t', type: 'transfer', subject: 'reasoning', skillIds: ['order-position'], familyId: 'race-order', difficulty: 3,
      sourceId: SRC, ...R, section: STORY,
      prompt: { text: 'เข้าแถวซื้อขนม ก้อยอยู่ที่ 1 บีมอยู่ที่ 2 ฝนอยู่ที่ 3 ใครได้ซื้อขนมหลังบีม' },
      options: words('ก้อย', 'ฝน', 'ไม่มีใคร'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ฝนอยู่ที่ 3 ได้ซื้อหลังบีมที่อยู่ที่ 2', hints: [], steps: ['ลำดับคือ ก้อย บีม ฝน', 'หลังบีมคือฝน'] },
    },
    {
      id: 'sc-sport-rest-t', type: 'transfer', subject: 'science', skillIds: ['health'], familyId: 'exercise-health', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'การออกกำลังกายทุกวันมีประโยชน์อย่างไร' },
      options: words('ทำให้ร่างกายแข็งแรง', 'ทำให้ป่วยบ่อย', 'ทำให้ง่วงตลอดวัน'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ออกกำลังกายทำให้ร่างกายแข็งแรง', hints: [], steps: ['การออกกำลังกายไม่ได้ทำให้ป่วยหรือง่วงตลอดวัน', 'ทำให้ร่างกายแข็งแรง'] },
    },
    {
      id: 'th-sport-spirit-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'มีน้ำใจ หมายถึงข้อใด' },
      options: words('ชอบช่วยเหลือผู้อื่น', 'ชอบดื่มน้ำ', 'ชอบเล่นคนเดียว'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มีน้ำใจ คือชอบช่วยเหลือผู้อื่น', hints: [], steps: ['มีน้ำใจไม่ได้หมายถึงการดื่มน้ำ', 'คนมีน้ำใจชอบช่วยเหลือผู้อื่น'] },
    },
    {
      id: 'm-gear-balls-t', compact: true, type: 'transfer', subject: 'math', skillIds: ['classify-count'], familyId: 'scatter-count', difficulty: 1,
      sourceId: SRC, ...R, section: COUNT,
      prompt: { text: 'ในภาพมีลูกบอลกี่ลูก' },
      visual: { type: 'scatter', items: [{ asset: 'pic-ball', count: 7 }, { asset: 'pic-sneakers', count: 2 }] },
      options: words('6 ลูก', '7 ลูก', '8 ลูก'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'นับลูกบอลได้ 7 ลูก', hints: [], steps: ['นับเฉพาะลูกบอลทีละลูก', 'ได้ 7 ลูก'] },
    },
    {
      id: 'm-gear-shoes-t', compact: true, type: 'transfer', subject: 'math', skillIds: ['classify-count'], familyId: 'scatter-count', difficulty: 1,
      sourceId: SRC, ...R, section: COUNT,
      prompt: { text: 'ในภาพมีรองเท้ากี่คู่ (รองเท้า 1 ภาพคือ 1 คู่)' },
      visual: { type: 'scatter', items: [{ asset: 'pic-ball', count: 3 }, { asset: 'pic-sneakers', count: 5 }] },
      options: words('3 คู่', '4 คู่', '5 คู่'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'รองเท้ามี 5 ภาพ คือ 5 คู่', hints: [], steps: ['นับภาพรองเท้าได้ 5 ภาพ', 'จึงมี 5 คู่'] },
    },
    {
      id: 'm-gear-more-t', compact: true, type: 'transfer', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'scatter-compare', difficulty: 2,
      sourceId: SRC, ...R, section: COUNT,
      prompt: { text: 'ในภาพ รองเท้ามีมากกว่าลูกบอลกี่ภาพ' },
      visual: { type: 'scatter', items: [{ asset: 'pic-ball', count: 3 }, { asset: 'pic-sneakers', count: 5 }] },
      options: words('1 ภาพ', '2 ภาพ', '3 ภาพ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'รองเท้า 5 ภาพ ลูกบอล 3 ภาพ ต่างกัน 2 ภาพ', hints: [], steps: ['รองเท้า 5 ลูกบอล 3', '5 ลบ 3 เท่ากับ 2'], column: { a: 5, op: '-', b: 3 } },
    },
    {
      id: 'r-gear-equal-t', compact: true, type: 'transfer', subject: 'reasoning', skillIds: ['multi-step-picture'], familyId: 'make-equal', difficulty: 3,
      sourceId: SRC, ...R, section: COUNT,
      prompt: { text: 'ต้องเพิ่มลูกบอลอีกกี่ลูก จึงจะมีจำนวนเท่ากับรองเท้า' },
      visual: { type: 'scatter', items: [{ asset: 'pic-ball', count: 3 }, { asset: 'pic-sneakers', count: 5 }] },
      options: words('1 ลูก', '2 ลูก', '3 ลูก'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ลูกบอล 3 ลูก ต้องเพิ่มอีก 2 ลูกจึงเท่ากับรองเท้า 5 คู่', hints: [], steps: ['รองเท้า 5 ลูกบอล 3 ขาดอยู่ 2', 'เพิ่มลูกบอลอีก 2 ลูก'] },
    },
    {
      id: 'm-gear-sides-t', compact: true, type: 'transfer', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ถุงเท้า 3 คู่ มีถุงเท้าทั้งหมดกี่ข้าง' },
      options: words('3 ข้าง', '5 ข้าง', '6 ข้าง'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '2 บวก 2 บวก 2 เท่ากับ 6 ข้าง', hints: [], steps: ['1 คู่มี 2 ข้าง', 'นับทีละคู่ 2 4 6'] },
    },
    {
      id: 'sp-gear-between-t', type: 'transfer', subject: 'spatial', skillIds: ['position-between'], familyId: 'position-between', difficulty: 1,
      sourceId: SRC, ...R, section: 'ดูภาพแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'อะไรอยู่ระหว่างรถกับเรือ' },
      visual: { type: 'row', items: ['pic-car', 'pic-train', 'pic-boat'], sides: true },
      options: words('รถไฟ', 'เรือ', 'รถ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'รถไฟอยู่ตรงกลางระหว่างรถกับเรือ', hints: [], steps: ['รถอยู่ซ้ายสุด เรืออยู่ขวาสุด', 'ตรงกลางคือรถไฟ'] },
    },
    {
      id: 'th-same-fast-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'same-meaning', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดมีความหมายเหมือนคำว่า ใหญ่' },
      options: words('โต', 'เล็ก', 'เตี้ย'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ใหญ่ กับ โต มีความหมายเหมือนกัน', hints: [], steps: ['เล็กตรงข้ามกับใหญ่ และเตี้ยเป็นเรื่องความสูง', 'โตมีความหมายเหมือนใหญ่'] },
    },
    {
      id: 'g-race-fall-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'kindness', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เพื่อนลืมเอาดินสอมา เราควรทำอย่างไร' },
      options: words('หัวเราะเพื่อน', 'ให้เพื่อนยืมดินสอ', 'บอกให้เพื่อนกลับบ้าน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ให้เพื่อนยืมดินสอ เป็นการมีน้ำใจ', hints: [], steps: ['หัวเราะเพื่อนทำให้เพื่อนอาย', 'ให้เพื่อนยืมดินสอคือการช่วยเหลือ'] },
    },
    {
      id: 'm-team-colors-t', type: 'transfer', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีทีมฟุตบอล 3 ทีม ทีมละ 5 คน รวมมีกี่คน' },
      options: words('8 คน', '15 คน', '20 คน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '5 บวก 5 บวก 5 เท่ากับ 15 คน', hints: [], steps: ['นับทีละทีม 5 10 15', 'รวม 15 คน'] },
    },
    {
      id: 'r-race-after-t', type: 'transfer', subject: 'reasoning', skillIds: ['order-position'], familyId: 'race-order', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'เข้าแถว 6 คน มายด์อยู่ที่ 4 มีคนอยู่หน้ามายด์กี่คน' },
      options: words('2 คน', '3 คน', '4 คน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'คนที่ 1 2 3 อยู่หน้ามายด์ รวม 3 คน', hints: [], steps: ['มายด์อยู่ที่ 4', 'หน้ามายด์คือที่ 1 2 3 รวม 3 คน'] },
    },
  ],
};
