/*
 * ชุดที่ 35 — ลูกบาศก์มองจากหลายด้าน (ภาพวาดด้วยโค้ดแบบใหม่ `cubes` ตัวเลือก `front` และ `top`) แบบ 15 ข้อ
 * ช่วง 1 ลูกบาศก์ 2 แถว (หลัง 2 2 1, หน้า 1 0 1) ถาม 5 ข้อ: นับทั้งหมด มองจากด้านหน้า มองจากด้านบน นับแถวหลัง เติมให้ครบ 10
 * ช่วง 2 ลูกบาศก์ 2 แถว (หลัง 3 2 1, หน้า 1 1 0) ถาม 5 ข้อ: นับทั้งหมด ด้านหน้า ด้านบน เพิ่มบนกองเตี้ยสุด กองสูงสุดอยู่ทางไหน
 * ช่วง 3 ข้อเดี่ยว: บันไดลูกบาศก์ ของที่เป็นทรงลูกบาศก์ น้ำแข็งละลาย คำว่า ซ้อน ลูกบาศก์ซ้อน 2 ชั้น
 * แต่งใหม่ทั้งหมด; เฉลยภาพมองจากด้านหน้า/บนและจำนวนก้อนตรวจกับภาพจริงใน tests/cubes.test.mjs
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const CUBES = 'ดูภาพลูกบาศก์แล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const VIEWS = 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการนึกภาพลูกบาศก์เมื่อมองจากอีกด้าน';
const cubes = (...rows) => ({ type: 'cubes', rows });
const front = (id, ...cols) => ({ id, svg: { front: cols } });
const top = (id, ...rows) => ({ id, svg: { top: rows } });
const words = (...list) => list.map((text, i) => ({ id: 'abc'[i], text }));

// แถวจากหลังไปหน้า
const A = cubes([2, 2, 1], [1, 0, 1]);   // 7 ก้อน มองหน้า 2 2 1
const B = cubes([3, 2, 1], [1, 1, 0]);   // 8 ก้อน มองหน้า 3 2 1

export default {
  id: 'set-35',
  version: 1,
  title: 'ชุดที่ 35',
  note: 'ลูกบาศก์ มองจากด้านหน้าและด้านบน นับก้อนที่ซ้อนกัน',
  order: [
    'm-cube-count-a', 'sp-cube-front-a', 'sp-cube-top-a', 'm-cube-back-a', 'm-cube-ten-a',
    'm-cube-count-b', 'sp-cube-front-b', 'sp-cube-top-b', 'r-cube-add-b', 'sp-cube-tallest-b',
    'sp-cube-stairs', 'g-cube-dice', 'sc-ice-cube', 'th-cube-stack', 'm-cube-layers',
  ],
  stimuli: {
    a: { section: CUBES, text: 'ลูกบาศก์ขนาดเท่ากันวางซ้อนกันเป็น 2 แถว คือแถวหน้าและแถวหลัง ดูภาพแล้วตอบคำถาม', visual: A },
    b: { section: CUBES, text: 'ลูกบาศก์ขนาดเท่ากันอีกชุดหนึ่ง วางซ้อนกันเป็น 2 แถว ดูภาพแล้วตอบคำถาม', visual: B },
  },
  items: [
    // ================================================================ ช่วงที่ 1: ลูกบาศก์ชุด ก
    {
      id: 'm-cube-count-a', type: 'main', subject: 'math', skillIds: ['count-blocks'], familyId: 'count-cubes', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'a',
      prompt: { text: 'ลูกบาศก์ในภาพมีทั้งหมดกี่ก้อน' },
      options: words('6 ก้อน', '7 ก้อน', '8 ก้อน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับลูกบาศก์รวมก้อนที่ถูกบังบางส่วน',
      review: {
        summary: 'แถวหลังมี 2 2 1 รวม 5 ก้อน แถวหน้ามี 1 0 1 รวม 2 ก้อน ทั้งหมด 7 ก้อน',
        hints: ['นับทีละกอง กองที่สูง 2 ก้อนต้องมีก้อนล่างรองรับอยู่เสมอ'],
        steps: ['แถวหลังซ้ายไปขวาสูง 2 ก้อน 2 ก้อน และ 1 ก้อน รวม 5 ก้อน แถวหน้ามีกองซ้ายและกองขวา กองละ 1 ก้อน รวม 2 ก้อน', '5 บวก 2 เท่ากับ 7 ตอบข้อ 2'],
        column: { a: 5, op: '+', b: 2 },
        transferIds: ['m-cube-count-a-t'],
      },
    },
    {
      id: 'sp-cube-front-a', type: 'main', subject: 'spatial', skillIds: ['cube-views'], familyId: 'cube-front', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'a',
      prompt: { text: 'ถ้ามองจากด้านหน้า จะเห็นภาพใด' },
      options: [front('a', 2, 1, 1), front('b', 2, 2, 1), front('c', 1, 0, 1), front('d', 1, 2, 2)],
      correctOptionId: 'b',
      narration: VIEWS,
      review: {
        summary: 'มองจากด้านหน้าเห็นกองที่สูงที่สุดของแต่ละแนว จากซ้ายไปขวาสูง 2 2 1',
        hints: ['มองจากด้านหน้า กองข้างหลังที่สูงกว่าจะโผล่ให้เห็นเหนือกองข้างหน้า'],
        steps: ['แนวซ้ายสูงสุด 2 ก้อน แนวกลางสูงสุด 2 ก้อน (กองหลัง) แนวขวาสูงสุด 1 ก้อน', 'จึงเห็นสูง 2 2 1 จากซ้ายไปขวา ตอบข้อ 2'],
        transferIds: ['sp-cube-front-a-t'],
      },
    },
    {
      id: 'sp-cube-top-a', type: 'main', subject: 'spatial', skillIds: ['cube-views'], familyId: 'cube-top', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'a',
      prompt: { text: 'ถ้ามองจากด้านบน จะเห็นภาพใด' },
      options: [top('a', [1, 1, 1], [1, 1, 1]), top('b', [1, 1, 1], [0, 1, 0]), top('c', [1, 0, 1], [1, 1, 1]), top('d', [1, 1, 1], [1, 0, 1])],
      correctOptionId: 'd',
      narration: VIEWS,
      review: {
        summary: 'มองจากด้านบนเห็นแถวหลังเต็ม 3 ช่อง แถวหน้ามีแค่ช่องซ้ายและช่องขวา',
        hints: ['มองจากด้านบน แถวหลังอยู่ด้านบนของภาพ แถวหน้าอยู่ด้านล่าง ตรงกลางแถวหน้าไม่มีลูกบาศก์'],
        steps: ['แถวหลังมีลูกบาศก์ครบทั้ง 3 แนว แถวหน้าว่างตรงกลาง', 'ภาพที่แถวบนเต็มและแถวล่างว่างตรงกลางคือข้อ 4 ตอบข้อ 4'],
        transferIds: ['sp-cube-top-a-t'],
      },
    },
    {
      id: 'm-cube-back-a', type: 'main', subject: 'math', skillIds: ['count-blocks'], familyId: 'count-cubes', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'a',
      prompt: { text: 'ลูกบาศก์แถวหลังมีกี่ก้อน' },
      options: words('4 ก้อน', '5 ก้อน', '6 ก้อน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับเฉพาะแถวหลัง (แถวที่อยู่ไกลออกไป)',
      review: {
        summary: 'แถวหลังสูง 2 2 1 รวม 5 ก้อน',
        hints: ['แถวหลังคือแถวที่อยู่ไกลจากเรา อยู่สูงขึ้นไปในภาพ'],
        steps: ['แถวหลังซ้ายไปขวามี 2 ก้อน 2 ก้อน และ 1 ก้อน', '2 บวก 2 บวก 1 เท่ากับ 5 ตอบข้อ 2'],
        transferIds: ['m-cube-back-a-t'],
      },
    },
    {
      id: 'm-cube-ten-a', type: 'main', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'make-ten', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'a',
      prompt: { text: 'ต้องเพิ่มลูกบาศก์อีกกี่ก้อน จึงจะมีครบ 10 ก้อน' },
      options: words('3 ก้อน', '4 ก้อน', '2 ก้อน'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการหาจำนวนที่ขาดไป (นับก่อนแล้วลบ)',
      review: {
        summary: 'ในภาพมี 7 ก้อน ขาดอีก 3 ก้อนจึงครบ 10',
        hints: ['นับลูกบาศก์ในภาพก่อน แล้วดูว่าขาดอีกเท่าไรจะครบ 10'],
        steps: ['ในภาพมีลูกบาศก์ 7 ก้อน', '10 ลบ 7 เท่ากับ 3 ตอบข้อ 1'],
        column: { a: 10, op: '-', b: 7 },
        transferIds: ['m-cube-ten-a-t'],
      },
    },

    // ================================================================ ช่วงที่ 2: ลูกบาศก์ชุด ข
    {
      id: 'm-cube-count-b', type: 'main', subject: 'math', skillIds: ['count-blocks'], familyId: 'count-cubes', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'b',
      prompt: { text: 'ลูกบาศก์ในภาพมีทั้งหมดกี่ก้อน' },
      options: words('9 ก้อน', '7 ก้อน', '8 ก้อน'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการนับลูกบาศก์รวมก้อนที่ถูกบังบางส่วน',
      review: {
        summary: 'แถวหลังมี 3 2 1 รวม 6 ก้อน แถวหน้ามี 1 1 รวม 2 ก้อน ทั้งหมด 8 ก้อน',
        hints: ['นับแถวหลังทีละกองก่อน แล้วค่อยนับแถวหน้า'],
        steps: ['แถวหลังซ้ายไปขวาสูง 3 2 1 รวม 6 ก้อน แถวหน้ามี 2 กอง กองละ 1 ก้อน', '6 บวก 2 เท่ากับ 8 ตอบข้อ 3'],
        column: { a: 6, op: '+', b: 2 },
        transferIds: ['m-cube-count-b-t'],
      },
    },
    {
      id: 'sp-cube-front-b', type: 'main', subject: 'spatial', skillIds: ['cube-views'], familyId: 'cube-front', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'b',
      prompt: { text: 'ถ้ามองจากด้านหน้า จะเห็นภาพใด' },
      options: [front('a', 1, 1, 0), front('b', 1, 2, 3), front('c', 3, 2, 1), front('d', 3, 3, 1)],
      correctOptionId: 'c',
      narration: VIEWS,
      review: {
        summary: 'มองจากด้านหน้าเห็นสูง 3 2 1 จากซ้ายไปขวา เหมือนขั้นบันไดลงทางขวา',
        hints: ['กองข้างหลังสูงกว่ากองข้างหน้า จึงเห็นความสูงของกองข้างหลัง'],
        steps: ['แนวซ้ายสูงสุด 3 ก้อน แนวกลาง 2 ก้อน แนวขวา 1 ก้อน', 'ภาพที่สูง 3 2 1 จากซ้ายไปขวาคือข้อ 3 (ข้อ 2 กลับด้าน) ตอบข้อ 3'],
        transferIds: ['sp-cube-front-b-t'],
      },
    },
    {
      id: 'sp-cube-top-b', type: 'main', subject: 'spatial', skillIds: ['cube-views'], familyId: 'cube-top', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'b',
      prompt: { text: 'ถ้ามองจากด้านบน จะเห็นภาพใด' },
      options: [top('a', [1, 1, 1], [1, 1, 0]), top('b', [1, 1, 0], [1, 1, 1]), top('c', [1, 1, 1], [0, 1, 1]), top('d', [1, 1, 1])],
      correctOptionId: 'a',
      narration: VIEWS,
      review: {
        summary: 'มองจากด้านบนเห็นแถวหลัง 3 ช่อง แถวหน้า 2 ช่องทางซ้าย',
        hints: ['แถวหน้าไม่มีลูกบาศก์ทางขวาสุด'],
        steps: ['แถวหลังมีครบ 3 แนว แถวหน้ามีแค่แนวซ้ายกับแนวกลาง', 'ภาพที่แถวบน 3 ช่องและแถวล่าง 2 ช่องชิดซ้ายคือข้อ 1 ตอบข้อ 1'],
        transferIds: ['sp-cube-top-b-t'],
      },
    },
    {
      id: 'r-cube-add-b', type: 'main', subject: 'reasoning', skillIds: ['multi-step-picture'], familyId: 'cube-add', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'b',
      prompt: { text: 'ถ้าวางลูกบาศก์เพิ่มบนกองที่เตี้ยที่สุดของแถวหลังอีก 2 ก้อน กองนั้นจะสูงกี่ก้อน' },
      options: words('2 ก้อน', '3 ก้อน', '4 ก้อน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการหากองที่เตี้ยที่สุดแล้วบวกเพิ่ม (สองขั้น)',
      review: {
        summary: 'กองที่เตี้ยที่สุดของแถวหลังสูง 1 ก้อน เพิ่ม 2 ก้อนเป็น 3 ก้อน',
        hints: ['หากองที่เตี้ยที่สุดในแถวหลังก่อน'],
        steps: ['แถวหลังสูง 3 2 1 กองที่เตี้ยที่สุดคือกองขวาสูง 1 ก้อน', '1 บวก 2 เท่ากับ 3 ตอบข้อ 2'],
        transferIds: ['r-cube-add-b-t'],
      },
    },
    {
      id: 'sp-cube-tallest-b', type: 'main', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'b',
      prompt: { text: 'กองลูกบาศก์ที่สูงที่สุดอยู่ทางด้านใดของภาพ' },
      options: words('ทางซ้ายมือของภาพ', 'ทางขวามือของภาพ', 'ตรงกลางของภาพ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการบอกตำแหน่งในภาพ',
      review: {
        summary: 'กองที่สูง 3 ก้อนอยู่ทางซ้ายของภาพ',
        hints: ['หากองที่สูงที่สุดก่อน แล้วดูว่าอยู่ด้านไหนของเรา'],
        steps: ['กองที่สูงที่สุดสูง 3 ก้อน อยู่แถวหลังแนวซ้าย', 'จึงอยู่ทางซ้ายมือของภาพ ตอบข้อ 1'],
        transferIds: ['sp-cube-tallest-b-t'],
      },
    },

    // ================================================================ ช่วงที่ 3: ข้อเดี่ยว
    {
      id: 'sp-cube-stairs', type: 'main', subject: 'spatial', skillIds: ['count-blocks'], familyId: 'count-cubes', difficulty: 2,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'บันไดลูกบาศก์นี้มีลูกบาศก์ทั้งหมดกี่ก้อน' },
      visual: cubes([1, 2, 3]),
      options: words('5 ก้อน', '7 ก้อน', '6 ก้อน'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการนับกองลูกบาศก์แบบขั้นบันได',
      review: {
        summary: 'บันไดสูง 1 2 3 ก้อน รวม 6 ก้อน',
        hints: ['นับทีละขั้น ขั้นละกี่ก้อน'],
        steps: ['ขั้นซ้ายสูง 1 ก้อน ขั้นกลาง 2 ก้อน ขั้นขวา 3 ก้อน', '1 บวก 2 บวก 3 เท่ากับ 6 ตอบข้อ 3'],
        transferIds: ['sp-cube-stairs-t'],
      },
    },
    {
      id: 'g-cube-dice', type: 'main', subject: 'general', skillIds: ['shape-in-objects'], familyId: 'shape-in-objects', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สิ่งของใดมีรูปร่างเป็นทรงลูกบาศก์' },
      options: words('ลูกบอล', 'ไข่', 'ลูกเต๋า'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการเชื่อมรูปทรงกับสิ่งของ',
      review: {
        summary: 'ลูกเต๋ามี 6 หน้า ทุกหน้าเป็นสี่เหลี่ยมจัตุรัส เป็นทรงลูกบาศก์',
        hints: ['ทรงลูกบาศก์มีหน้าเป็นสี่เหลี่ยมทุกด้าน วางซ้อนกันได้'],
        steps: ['ลูกบอลกลม และไข่รี ไม่มีหน้าแบน', 'ลูกเต๋ามีหน้าสี่เหลี่ยมจัตุรัส 6 หน้า ตอบข้อ 3'],
        transferIds: ['g-cube-dice-t'],
      },
    },
    {
      id: 'sc-ice-cube', type: 'main', subject: 'science', skillIds: ['states-of-matter'], familyId: 'melting', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'น้ำแข็งก้อนสี่เหลี่ยมวางไว้กลางแดดนานๆ จะเป็นอย่างไร' },
      options: words('ละลายเป็นน้ำ', 'แข็งขึ้นกว่าเดิม', 'กลายเป็นก้อนหิน'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการละลาย',
      review: {
        summary: 'ความร้อนจากแดดทำให้น้ำแข็งละลายเป็นน้ำ',
        hints: ['นึกถึงน้ำแข็งในแก้วน้ำที่วางไว้นานๆ'],
        steps: ['น้ำแข็งไม่แข็งขึ้นเมื่อโดนแดด และไม่กลายเป็นหิน', 'ความร้อนทำให้น้ำแข็งละลายเป็นน้ำ ตอบข้อ 1'],
        transferIds: ['sc-ice-cube-t'],
      },
    },
    {
      id: 'th-cube-stack', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'น้องวางกล่องซ้อนกันสามชั้น คำว่า ซ้อน หมายถึงข้อใด' },
      options: words('วางเรียงกันบนพื้น', 'วางทับกันขึ้นไป', 'วางห่างกัน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความหมายของคำในประโยค',
      review: {
        summary: 'ซ้อน คือวางทับกันขึ้นไปเป็นชั้นๆ',
        hints: ['สามชั้น แปลว่ากล่องอยู่สูงขึ้นไปทีละชั้น'],
        steps: ['วางเรียงกันบนพื้นหรือวางห่างกันจะไม่เป็นชั้น', 'ซ้อน คือวางทับกันขึ้นไป ตอบข้อ 2'],
        transferIds: ['th-cube-stack-t'],
      },
    },
    {
      id: 'm-cube-layers', type: 'main', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 2,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ลูกบาศก์วางเรียงแถวละ 4 ก้อน ซ้อนกัน 2 ชั้น มีลูกบาศก์ทั้งหมดกี่ก้อน' },
      visual: cubes([2, 2, 2, 2]),
      options: words('6 ก้อน', '10 ก้อน', '8 ก้อน'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการบวกซ้ำ (ชั้นละ 4 ก้อน 2 ชั้น)',
      review: {
        summary: 'ชั้นละ 4 ก้อน 2 ชั้น 4 บวก 4 เท่ากับ 8 ก้อน',
        hints: ['นับชั้นล่างก่อน แล้วชั้นบนมีเท่ากัน'],
        steps: ['ชั้นล่างมี 4 ก้อน ชั้นบนมีอีก 4 ก้อน', '4 บวก 4 เท่ากับ 8 ตอบข้อ 3'],
        column: { a: 4, op: '+', b: 4 },
        transferIds: ['m-cube-layers-t'],
      },
    },

    // ================================================================ โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'm-cube-count-a-t', type: 'transfer', subject: 'math', skillIds: ['count-blocks'], familyId: 'count-cubes', difficulty: 3,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ลูกบาศก์ในภาพมีทั้งหมดกี่ก้อน' },
      visual: cubes([1, 2], [1, 1]),
      options: words('4 ก้อน', '5 ก้อน', '6 ก้อน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แถวหลัง 1 2 รวม 3 ก้อน แถวหน้า 1 1 รวม 2 ก้อน ทั้งหมด 5 ก้อน', hints: [], steps: ['แถวหลังมี 3 ก้อน แถวหน้ามี 2 ก้อน', '3 บวก 2 เท่ากับ 5'] },
    },
    {
      id: 'sp-cube-front-a-t', type: 'transfer', subject: 'spatial', skillIds: ['cube-views'], familyId: 'cube-front', difficulty: 3,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ถ้ามองจากด้านหน้า จะเห็นภาพใด' },
      visual: cubes([1, 3], [1, 1]),
      options: [front('a', 1, 3), front('b', 3, 1), front('c', 1, 1), front('d', 2, 3)],
      correctOptionId: 'a',
      narration: VIEWS,
      review: { summary: 'มองจากด้านหน้าเห็นสูง 1 และ 3 จากซ้ายไปขวา', hints: [], steps: ['แนวซ้ายสูงสุด 1 ก้อน แนวขวาสูงสุด 3 ก้อน (กองหลัง)', 'จึงเห็นสูง 1 3 จากซ้ายไปขวา'] },
    },
    {
      id: 'sp-cube-top-a-t', type: 'transfer', subject: 'spatial', skillIds: ['cube-views'], familyId: 'cube-top', difficulty: 3,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ถ้ามองจากด้านบน จะเห็นภาพใด' },
      visual: cubes([1, 1], [1, 0]),
      options: [top('a', [1, 1], [0, 1]), top('b', [1, 1], [1, 0]), top('c', [1, 0], [1, 1]), top('d', [1, 1], [1, 1])],
      correctOptionId: 'b',
      narration: VIEWS,
      review: { summary: 'แถวหลังมี 2 ช่อง แถวหน้ามีช่องซ้ายช่องเดียว', hints: [], steps: ['มองจากด้านบน แถวหลังอยู่ด้านบนของภาพ', 'แถวหน้ามีลูกบาศก์แค่ช่องซ้าย'] },
    },
    {
      id: 'm-cube-back-a-t', type: 'transfer', subject: 'math', skillIds: ['count-blocks'], familyId: 'count-cubes', difficulty: 2,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ลูกบาศก์แถวหน้ามีกี่ก้อน' },
      visual: cubes([2, 1, 2], [1, 1, 1]),
      options: words('2 ก้อน', '3 ก้อน', '4 ก้อน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แถวหน้ามีกองละ 1 ก้อน 3 กอง รวม 3 ก้อน', hints: [], steps: ['แถวหน้าคือแถวที่อยู่ใกล้เรา อยู่ล่างสุดของภาพ', 'มี 3 กอง กองละ 1 ก้อน รวม 3 ก้อน'] },
    },
    {
      id: 'm-cube-ten-a-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'make-ten', difficulty: 3,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ต้องเพิ่มลูกบาศก์อีกกี่ก้อน จึงจะมีครบ 10 ก้อน' },
      visual: cubes([2, 2], [1, 1]),
      options: words('4 ก้อน', '5 ก้อน', '3 ก้อน'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ในภาพมี 6 ก้อน ขาดอีก 4 ก้อนจึงครบ 10', hints: [], steps: ['แถวหลังมี 4 ก้อน แถวหน้ามี 2 ก้อน รวม 6 ก้อน', '10 ลบ 6 เท่ากับ 4'], column: { a: 10, op: '-', b: 6 } },
    },
    {
      id: 'm-cube-count-b-t', type: 'transfer', subject: 'math', skillIds: ['count-blocks'], familyId: 'count-cubes', difficulty: 3,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ลูกบาศก์ในภาพมีทั้งหมดกี่ก้อน' },
      visual: cubes([3, 1], [2, 1]),
      options: words('6 ก้อน', '7 ก้อน', '8 ก้อน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แถวหลัง 3 1 รวม 4 ก้อน แถวหน้า 2 1 รวม 3 ก้อน ทั้งหมด 7 ก้อน', hints: [], steps: ['แถวหลังมี 4 ก้อน แถวหน้ามี 3 ก้อน', '4 บวก 3 เท่ากับ 7'] },
    },
    {
      id: 'sp-cube-front-b-t', type: 'transfer', subject: 'spatial', skillIds: ['cube-views'], familyId: 'cube-front', difficulty: 3,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ถ้ามองจากด้านหน้า จะเห็นภาพใด' },
      visual: cubes([2, 3, 1], [1, 1, 1]),
      options: [front('a', 1, 3, 2), front('b', 2, 3, 1), front('c', 1, 1, 1), front('d', 2, 2, 1)],
      correctOptionId: 'b',
      narration: VIEWS,
      review: { summary: 'มองจากด้านหน้าเห็นสูง 2 3 1 จากซ้ายไปขวา', hints: [], steps: ['แนวซ้ายสูงสุด 2 ก้อน แนวกลาง 3 ก้อน แนวขวา 1 ก้อน', 'จึงเห็นสูง 2 3 1'] },
    },
    {
      id: 'sp-cube-top-b-t', type: 'transfer', subject: 'spatial', skillIds: ['cube-views'], familyId: 'cube-top', difficulty: 3,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ถ้ามองจากด้านบน จะเห็นภาพใด' },
      visual: cubes([2, 1, 1], [1, 0, 0]),
      options: [top('a', [1, 1, 1], [0, 0, 1]), top('b', [1, 0, 0], [1, 1, 1]), top('c', [1, 1, 1], [1, 0, 0]), top('d', [1, 1, 1], [1, 1, 1])],
      correctOptionId: 'c',
      narration: VIEWS,
      review: { summary: 'แถวหลังมี 3 ช่อง แถวหน้ามีช่องซ้ายช่องเดียว', hints: [], steps: ['แถวหลังมีครบ 3 แนว', 'แถวหน้ามีแค่แนวซ้าย'] },
    },
    {
      id: 'r-cube-add-b-t', type: 'transfer', subject: 'reasoning', skillIds: ['multi-step-picture'], familyId: 'cube-add', difficulty: 3,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ถ้าหยิบลูกบาศก์ออกจากกองที่สูงที่สุด 1 ก้อน กองนั้นจะเหลือกี่ก้อน' },
      visual: cubes([3, 1, 2]),
      options: words('1 ก้อน', '2 ก้อน', '3 ก้อน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'กองที่สูงที่สุดมี 3 ก้อน หยิบออก 1 ก้อนเหลือ 2 ก้อน', hints: [], steps: ['กองที่สูงที่สุดคือกองซ้ายสูง 3 ก้อน', '3 ลบ 1 เท่ากับ 2'] },
    },
    {
      id: 'sp-cube-tallest-b-t', type: 'transfer', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 1,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'กองลูกบาศก์ที่สูงที่สุดอยู่ทางด้านใดของภาพ' },
      visual: cubes([1, 2, 3]),
      options: words('ทางซ้ายมือของภาพ', 'ทางขวามือของภาพ', 'ตรงกลางของภาพ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'กองที่สูง 3 ก้อนอยู่ทางขวาของภาพ', hints: [], steps: ['กองสูง 1 2 3 จากซ้ายไปขวา', 'กองที่สูงที่สุดอยู่ทางขวา'] },
    },
    {
      id: 'sp-cube-stairs-t', type: 'transfer', subject: 'spatial', skillIds: ['count-blocks'], familyId: 'count-cubes', difficulty: 2,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ลูกบาศก์ในภาพมีทั้งหมดกี่ก้อน' },
      visual: cubes([1, 2, 3], [1, 1, 1]),
      options: words('8 ก้อน', '9 ก้อน', '10 ก้อน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แถวหลัง 1 2 3 รวม 6 ก้อน แถวหน้า 3 ก้อน ทั้งหมด 9 ก้อน', hints: [], steps: ['แถวหลังเป็นบันไดสูง 1 2 3 รวม 6 ก้อน แถวหน้ามี 3 ก้อน', '6 บวก 3 เท่ากับ 9'] },
    },
    {
      id: 'g-cube-dice-t', type: 'transfer', subject: 'general', skillIds: ['shape-in-objects'], familyId: 'shape-in-objects', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สิ่งของใดมีรูปร่างเป็นทรงกระบอก' },
      options: words('ลูกเต๋า', 'กระป๋องนม', 'ลูกบอล'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'กระป๋องนมเป็นทรงกระบอก ด้านบนและด้านล่างเป็นวงกลม', hints: [], steps: ['ลูกเต๋าเป็นทรงลูกบาศก์ และลูกบอลเป็นทรงกลม', 'กระป๋องนมเป็นทรงกระบอก'] },
    },
    {
      id: 'sc-ice-cube-t', type: 'transfer', subject: 'science', skillIds: ['states-of-matter'], familyId: 'melting', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'นำน้ำใส่ช่องแช่แข็งของตู้เย็นไว้นานๆ น้ำจะเป็นอย่างไร' },
      options: words('ร้อนขึ้น', 'กลายเป็นน้ำแข็ง', 'หายไปหมด'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ความเย็นทำให้น้ำแข็งตัวกลายเป็นน้ำแข็ง', hints: [], steps: ['ช่องแช่แข็งเย็นมาก ไม่ทำให้น้ำร้อนหรือหายไป', 'น้ำจะแข็งตัวเป็นน้ำแข็ง'] },
    },
    {
      id: 'th-cube-stack-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'น้องเรียงลูกบาศก์เป็นแถวยาว คำว่า เรียง หมายถึงข้อใด' },
      options: words('วางต่อกันเป็นแถว', 'วางทับกันขึ้นไป', 'โยนทิ้งไป'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เรียง คือวางต่อกันเป็นแถว', hints: [], steps: ['วางทับกันขึ้นไปคือซ้อน ไม่ใช่เรียง', 'เรียงเป็นแถวยาว คือวางต่อกันไปทีละก้อน'] },
    },
    {
      id: 'm-cube-layers-t', type: 'transfer', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 2,
      sourceId: SRC, ...R, section: CUBES,
      prompt: { text: 'ลูกบาศก์วางเรียงแถวละ 3 ก้อน ซ้อนกัน 3 ชั้น มีลูกบาศก์ทั้งหมดกี่ก้อน' },
      visual: cubes([3, 3, 3]),
      options: words('6 ก้อน', '9 ก้อน', '12 ก้อน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ชั้นละ 3 ก้อน 3 ชั้น 3 บวก 3 บวก 3 เท่ากับ 9 ก้อน', hints: [], steps: ['แต่ละชั้นมี 3 ก้อน มี 3 ชั้น', '3 บวก 3 บวก 3 เท่ากับ 9'] },
    },
  ],
};
