/*
 * ชุดที่ 3 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 3) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * ใช้รูปเดิมจากแผ่น A/B; ตาราง แถวตัวเลข ภาพนับรูปทรง และรูปพับครึ่งวาดด้วยโค้ด (src/visuals/visuals.js)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const TABLE = 'อ่านตารางแล้วตอบคำถามให้ถูกต้อง';

export default {
  id: 'set-03',
  version: 1,
  title: 'ชุดที่ 3',
  note: 'ตาราง อนุกรม คำตรงข้าม พับครึ่ง นับรูปทรง บวกมีทด',
  order: [
    'r-table-most', 'm-table-diff', 'r-number-seq', 'th-opposite', 'sc-land-water',
    'sp-fold', 'g-weekday', 'th-initial-kai', 'sp-count-triangles', 'sc-root',
    'm-stickers-add', 'g-doctor',
  ],
  stimuli: {
    oranges: {
      section: TABLE,
      text: 'ตารางนี้บอกว่าเด็กแต่ละคนเก็บส้มได้กี่ผล',
      visual: { type: 'table', unit: 'ผล', rows: [{ name: 'ปอ', count: 8 }, { name: 'เปา', count: 5 }, { name: 'ปิ่น', count: 6 }] },
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'r-table-most', type: 'main', subject: 'reasoning', skillIds: ['read-table'], familyId: 'table-compare', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'oranges',
      prompt: { text: 'ใครเก็บส้มได้มากที่สุด' },
      options: [{ id: 'a', text: 'เปา' }, { id: 'b', text: 'ปิ่น' }, { id: 'c', text: 'ปอ' }],
      correctOptionId: 'c',
      narration: 'อ่านเรื่องและข้อมูลในตารางออกเสียงให้ฟัง (ผู้ปกครองขอ) วัดการเปรียบเทียบจำนวนจากข้อมูล',
      review: {
        summary: 'ปอเก็บส้มได้มากที่สุด 8 ผล',
        hints: ['ดูตัวเลขในตาราง เลขไหนมากที่สุด'],
        steps: ['ปอได้ 8 ผล เปาได้ 5 ผล ปิ่นได้ 6 ผล', '8 มากที่สุด ปอจึงเก็บได้มากที่สุด ตอบข้อ 3'],
        transferIds: ['r-table-least-t'],
      },
    },
    {
      id: 'm-table-diff', type: 'main', subject: 'math', skillIds: ['compare-difference'], familyId: 'difference', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'oranges',
      prompt: { text: 'ปอเก็บส้มได้มากกว่าเปากี่ผล' },
      options: [{ id: 'a', text: '2 ผล' }, { id: 'b', text: '3 ผล' }, { id: 'c', text: '4 ผล' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการหาผลต่าง',
      review: {
        summary: '8 ลบ 5 เท่ากับ 3 ปอได้มากกว่า 3 ผล',
        hints: ['มากกว่ากี่ผล ใช้การลบ'],
        steps: ['ปอได้ 8 ผล เปาได้ 5 ผล', 'หาว่ามากกว่ากี่ผล ใช้ 8 ลบ 5 เท่ากับ 3 ตอบข้อ 2'],
        column: { a: 8, op: '-', b: 5 },
        transferIds: ['m-table-diff-t'],
      },
    },
    {
      id: 'r-number-seq', type: 'main', subject: 'reasoning', skillIds: ['number-pattern'], familyId: 'number-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ตัวเลขเรียงกันแบบนี้ ช่องที่มีเครื่องหมายคำถามควรเป็นเลขใด' },
      visual: { type: 'number-row', items: [2, 4, 6, '?'] },
      options: [{ id: 'a', text: '8' }, { id: 'b', text: '7' }, { id: 'c', text: '10' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ เสียงไม่อ่านตัวเลขในแถว เด็กต้องดูเอง',
      review: {
        summary: 'เพิ่มทีละ 2 ต่อจาก 6 จึงเป็น 8',
        hints: ['ดูว่าแต่ละช่องเพิ่มขึ้นเท่าไร'],
        steps: ['2 ไป 4 เพิ่ม 2 และ 4 ไป 6 ก็เพิ่ม 2', 'ต่อจาก 6 เพิ่มอีก 2 ได้ 8 ตอบข้อ 1'],
        transferIds: ['r-number-seq-t'],
      },
    },
    {
      id: 'th-opposite', type: 'main', subject: 'thai', skillIds: ['antonyms'], familyId: 'antonyms', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'คำใดมีความหมายตรงข้ามกับคำว่า สูง' },
      options: [{ id: 'a', text: 'ใหญ่' }, { id: 'b', text: 'ยาว' }, { id: 'c', text: 'เตี้ย' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจความหมายคำ',
      review: {
        summary: 'สูง ตรงข้ามกับ เตี้ย',
        hints: ['ถ้าไม่สูง เราเรียกว่าอะไร'],
        steps: ['คำตรงข้ามคือคำที่มีความหมายกลับกัน', 'ต้นไม้สูง กับต้นไม้เตี้ย ความหมายกลับกัน ตอบข้อ 3'],
        transferIds: ['th-opposite-t'],
      },
    },
    {
      id: 'sc-land-water', type: 'main', subject: 'science', skillIds: ['animal-habitat'], familyId: 'habitat', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์ในข้อใดอยู่ได้ทั้งบนบกและในน้ำ' },
      options: [{ id: 'a', image: 'pic-frog', speech: 'กบ' }, { id: 'b', image: 'pic-cat', speech: 'แมว' }, { id: 'c', image: 'pic-fish', speech: 'ปลา' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อสัตว์ได้ วัดความรู้เรื่องที่อยู่ของสัตว์',
      review: {
        summary: 'กบอยู่ได้ทั้งบนบกและในน้ำ',
        hints: ['สัตว์ตัวไหนกระโดดบนบกได้ และว่ายน้ำได้ด้วย'],
        steps: ['แมวอยู่บนบก ปลาอยู่ในน้ำเท่านั้น', 'กบกระโดดบนบกได้ และว่ายน้ำได้ จึงอยู่ได้ทั้งสองที่ ตอบข้อ 1'],
        transferIds: ['sc-water-only-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'sp-fold', type: 'main', subject: 'spatial', skillIds: ['symmetry'], familyId: 'symmetry', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดพับครึ่งตามเส้นประแล้วทับกันสนิท' },
      options: [{ id: 'a', svg: { fold: 'crescent' } }, { id: 'b', svg: { fold: 'heart' } }, { id: 'c', svg: { fold: 'lshape' } }],
      correctOptionId: 'b',
      narration: 'ตัวเลือกอ่านแค่หมายเลข เพื่อให้เด็กดูรูปเอง',
      review: {
        summary: 'รูปหัวใจพับครึ่งแล้วทับกันสนิท',
        hints: ['ดูว่าซีกซ้ายกับซีกขวาของเส้นประเหมือนกันไหม'],
        steps: ['ถ้าพับตามเส้นประ ซีกซ้ายต้องเหมือนซีกขวาจึงจะทับกันสนิท', 'หัวใจสองซีกเหมือนกัน ส่วนรูปอื่นสองซีกไม่เหมือนกัน ตอบข้อ 2'],
        transferIds: ['sp-fold-t'],
      },
    },
    {
      id: 'g-weekday', type: 'main', subject: 'general', skillIds: ['days-of-week'], familyId: 'days-of-week', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'วันนี้เป็นวันจันทร์ พรุ่งนี้เป็นวันอะไร' },
      options: [{ id: 'a', text: 'วันอังคาร' }, { id: 'b', text: 'วันอาทิตย์' }, { id: 'c', text: 'วันพุธ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้ลำดับวันในสัปดาห์',
      review: {
        summary: 'ถัดจากวันจันทร์คือวันอังคาร',
        hints: ['ท่องวันในสัปดาห์ อาทิตย์ จันทร์ แล้วต่อด้วยอะไร'],
        steps: ['วันในสัปดาห์เรียงว่า อาทิตย์ จันทร์ อังคาร พุธ พฤหัสบดี ศุกร์ เสาร์', 'ต่อจากวันจันทร์คือวันอังคาร ตอบข้อ 1'],
        transferIds: ['g-weekday-t'],
      },
    },
    {
      id: 'th-initial-kai', type: 'main', subject: 'thai', skillIds: ['initial-consonant-sound'], familyId: 'initial-sound', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพนี้คือ ไก่ ข้อใดมีเสียงพยัญชนะต้นเหมือนกับคำว่า ไก่' },
      visual: { type: 'image', asset: 'pic-chicken' },
      options: [{ id: 'a', image: 'pic-horse', speech: 'ม้า' }, { id: 'b', image: 'pic-crab', speech: 'ปู' }, { id: 'c', image: 'pic-frog', speech: 'กบ' }],
      correctOptionId: 'c',
      narration: 'ฟังชื่อภาพได้ วัดการแยกเสียงต้นคำ (มีเสียงช่วย ไม่ได้วัดการอ่าน)',
      review: {
        summary: 'ไก่ กับ กบ ขึ้นต้นด้วยเสียง กอ เหมือนกัน',
        hints: ['พูดคำว่า ไก่ ช้าๆ ฟังเสียงแรก'],
        steps: ['ไก่ ขึ้นต้นด้วยเสียง กอ', 'ม้า ขึ้นต้นด้วย มอ ปู ขึ้นต้นด้วย ปอ กบ ขึ้นต้นด้วย กอ ตอบข้อ 3'],
        transferIds: ['th-initial-ped-t'],
      },
    },
    {
      id: 'sp-count-triangles', type: 'main', subject: 'spatial', skillIds: ['count-shapes'], familyId: 'count-shapes', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ในภาพมีรูปสามเหลี่ยมกี่รูป' },
      visual: { type: 'shape-count', shapes: ['triangle', 'circle', 'square', 'triangle', 'circle', 'square', 'triangle'] },
      options: [{ id: 'a', text: '2 รูป' }, { id: 'b', text: '3 รูป' }, { id: 'c', text: '4 รูป' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ เสียงไม่บอกจำนวน เด็กต้องนับจากภาพเอง',
      review: {
        summary: 'มีรูปสามเหลี่ยม 3 รูป',
        hints: ['สามเหลี่ยมมี 3 มุม แตะนับทีละรูป'],
        steps: ['รูปสามเหลี่ยมมี 3 ด้าน 3 มุม', 'นับได้หนึ่ง สอง สาม มี 3 รูป ตอบข้อ 2'],
        transferIds: ['sp-count-circles-t'],
      },
    },
    {
      id: 'sc-root', type: 'main', subject: 'science', skillIds: ['plant-parts'], familyId: 'plant-parts', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ส่วนใดของต้นไม้ที่อยู่ใต้ดิน' },
      options: [{ id: 'a', text: 'ใบ' }, { id: 'b', text: 'ดอก' }, { id: 'c', text: 'ราก' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องส่วนของพืช',
      review: {
        summary: 'รากอยู่ใต้ดิน',
        hints: ['ส่วนไหนที่ดูดน้ำจากดิน'],
        steps: ['ใบและดอกอยู่บนต้น เรามองเห็นได้', 'รากอยู่ใต้ดิน คอยดูดน้ำและยึดต้นไม้ไว้ ตอบข้อ 3'],
        transferIds: ['sc-flower-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-stickers-add', type: 'main', subject: 'math', skillIds: ['word-problem-add'], familyId: 'add-2digit-carry', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ลิลลี่มีสติกเกอร์ 27 แผ่น แม่ให้อีก 15 แผ่น ลิลลี่มีสติกเกอร์ทั้งหมดกี่แผ่น' },
      options: [{ id: 'a', text: '42 แผ่น' }, { id: 'b', text: '32 แผ่น' }, { id: 'c', text: '52 แผ่น' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการบวกที่มีทด',
      review: {
        summary: '27 บวก 15 เท่ากับ 42 แผ่น',
        hints: ['ได้เพิ่ม ต้องบวก หลักหน่วยครบสิบต้องทด'],
        steps: [
          'แม่ให้เพิ่ม จึงใช้การบวก 27 บวก 15',
          'หลักหน่วย 7 บวก 5 ได้ 12 เขียน 2 ทด 1 ไว้ที่หลักสิบ',
          'หลักสิบ 1 บวก 2 บวก 1 ได้ 4 รวมเป็น 42 แผ่น ตอบข้อ 1',
        ],
        column: { a: 27, op: '+', b: 15 },
        transferIds: ['m-add-carry-t'],
      },
    },
    {
      id: 'g-doctor', type: 'main', subject: 'general', skillIds: ['occupations'], familyId: 'occupations', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ใครทำหน้าที่รักษาคนป่วย' },
      options: [{ id: 'a', text: 'ตำรวจ' }, { id: 'b', text: 'หมอ' }, { id: 'c', text: 'ชาวนา' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องอาชีพ',
      review: {
        summary: 'หมอรักษาคนป่วย',
        hints: ['เวลาไม่สบาย เราไปหาใคร'],
        steps: ['ตำรวจดูแลความปลอดภัย ชาวนาปลูกข้าว', 'หมอตรวจและรักษาคนป่วยที่โรงพยาบาล ตอบข้อ 2'],
        transferIds: ['g-police-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'r-table-least-t', type: 'transfer', subject: 'reasoning', skillIds: ['read-table'], familyId: 'table-compare', difficulty: 1,
      sourceId: SRC, ...R, section: TABLE,
      prompt: {
        text: 'ตารางนี้บอกจำนวนไข่ที่เด็กแต่ละคนเก็บได้ ใครเก็บไข่ได้น้อยที่สุด',
        speech: 'ตารางนี้บอกจำนวนไข่ที่เด็กแต่ละคนเก็บได้ ต้น 4 ฟอง ตาล 7 ฟอง บัว 5 ฟอง ใครเก็บไข่ได้น้อยที่สุด',
      },
      visual: { type: 'table', unit: 'ฟอง', rows: [{ name: 'ต้น', count: 4 }, { name: 'ตาล', count: 7 }, { name: 'บัว', count: 5 }] },
      options: [{ id: 'a', text: 'ต้น' }, { id: 'b', text: 'ตาล' }, { id: 'c', text: 'บัว' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อได้',
      review: { summary: 'ต้นเก็บได้น้อยที่สุด 4 ฟอง', hints: [], steps: ['ต้นได้ 4 ฟอง ตาลได้ 7 ฟอง บัวได้ 5 ฟอง', '4 น้อยที่สุด ต้นจึงเก็บได้น้อยที่สุด'] },
    },
    {
      id: 'm-table-diff-t', type: 'transfer', subject: 'math', skillIds: ['compare-difference'], familyId: 'difference', difficulty: 2,
      sourceId: SRC, ...R, section: TABLE,
      prompt: { text: 'ตาลเก็บไข่ได้มากกว่าต้นกี่ฟอง' },
      visual: { type: 'table', unit: 'ฟอง', rows: [{ name: 'ต้น', count: 4 }, { name: 'ตาล', count: 7 }, { name: 'บัว', count: 5 }] },
      options: [{ id: 'a', text: '2 ฟอง' }, { id: 'b', text: '3 ฟอง' }, { id: 'c', text: '11 ฟอง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '7 ลบ 4 เท่ากับ 3 ฟอง', hints: [], steps: ['ตาลได้ 7 ฟอง ต้นได้ 4 ฟอง', 'มากกว่ากี่ฟองใช้การลบ 7 ลบ 4 เท่ากับ 3'], column: { a: 7, op: '-', b: 4 } },
    },
    {
      id: 'r-number-seq-t', type: 'transfer', subject: 'reasoning', skillIds: ['number-pattern'], familyId: 'number-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ตัวเลขเรียงกันแบบนี้ ช่องที่มีเครื่องหมายคำถามควรเป็นเลขใด' },
      visual: { type: 'number-row', items: [5, 10, 15, '?'] },
      options: [{ id: 'a', text: '16' }, { id: 'b', text: '20' }, { id: 'c', text: '25' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เพิ่มทีละ 5 ต่อจาก 15 จึงเป็น 20', hints: [], steps: ['5 ไป 10 เพิ่ม 5 และ 10 ไป 15 ก็เพิ่ม 5', 'ต่อจาก 15 เพิ่มอีก 5 ได้ 20'] },
    },
    {
      id: 'th-opposite-t', type: 'transfer', subject: 'thai', skillIds: ['antonyms'], familyId: 'antonyms', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'คำใดมีความหมายตรงข้ามกับคำว่า ร้อน' },
      options: [{ id: 'a', text: 'อุ่น' }, { id: 'b', text: 'สว่าง' }, { id: 'c', text: 'หนาว' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ร้อน ตรงข้ามกับ หนาว', hints: [], steps: ['หน้าร้อนอากาศร้อน หน้าหนาวอากาศหนาว', 'ร้อนกับหนาวความหมายกลับกัน'] },
    },
    {
      id: 'sc-water-only-t', type: 'transfer', subject: 'science', skillIds: ['animal-habitat'], familyId: 'habitat', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์ในข้อใดอยู่ได้ในน้ำเท่านั้น' },
      options: [{ id: 'a', image: 'pic-duck', speech: 'เป็ด' }, { id: 'b', image: 'pic-fish', speech: 'ปลา' }, { id: 'c', image: 'pic-frog', speech: 'กบ' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อสัตว์ได้',
      review: { summary: 'ปลาอยู่ได้ในน้ำเท่านั้น', hints: [], steps: ['เป็ดกับกบขึ้นมาเดินบนบกได้', 'ปลาหายใจด้วยเหงือก ต้องอยู่ในน้ำเท่านั้น'] },
    },
    {
      id: 'sp-fold-t', type: 'transfer', subject: 'spatial', skillIds: ['symmetry'], familyId: 'symmetry', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดพับครึ่งตามเส้นประแล้วไม่ทับกันสนิท' },
      options: [{ id: 'a', svg: { fold: 'star' } }, { id: 'b', svg: { fold: 'flag' } }, { id: 'c', svg: { fold: 'circle' } }],
      correctOptionId: 'b',
      narration: 'ตัวเลือกอ่านแค่หมายเลข',
      review: { summary: 'ธงพับครึ่งแล้วไม่ทับกันสนิท', hints: [], steps: ['ดาวกับวงกลม สองซีกของเส้นประเหมือนกัน', 'ธงมีผ้าอยู่ซีกเดียว พับแล้วจึงไม่ทับกันสนิท'] },
    },
    {
      id: 'g-weekday-t', type: 'transfer', subject: 'general', skillIds: ['days-of-week'], familyId: 'days-of-week', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'วันนี้เป็นวันศุกร์ เมื่อวานเป็นวันอะไร' },
      options: [{ id: 'a', text: 'วันเสาร์' }, { id: 'b', text: 'วันพฤหัสบดี' }, { id: 'c', text: 'วันอาทิตย์' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ก่อนวันศุกร์คือวันพฤหัสบดี', hints: [], steps: ['วันเรียงว่า พฤหัสบดี ศุกร์ เสาร์', 'เมื่อวานคือวันก่อนหน้า จึงเป็นวันพฤหัสบดี'] },
    },
    {
      id: 'th-initial-ped-t', type: 'transfer', subject: 'thai', skillIds: ['initial-consonant-sound'], familyId: 'initial-sound', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพนี้คือ เป็ด ข้อใดมีเสียงพยัญชนะต้นเหมือนกับคำว่า เป็ด' },
      visual: { type: 'image', asset: 'pic-duck' },
      options: [{ id: 'a', image: 'pic-chicken', speech: 'ไก่' }, { id: 'b', image: 'pic-horse', speech: 'ม้า' }, { id: 'c', image: 'pic-crab', speech: 'ปู' }],
      correctOptionId: 'c',
      narration: 'ฟังชื่อภาพได้',
      review: { summary: 'เป็ด กับ ปู ขึ้นต้นด้วยเสียง ปอ', hints: [], steps: ['เป็ด ขึ้นต้นด้วยเสียง ปอ', 'ปู ขึ้นต้นด้วยเสียง ปอ เหมือนกัน'] },
    },
    {
      id: 'sp-count-circles-t', type: 'transfer', subject: 'spatial', skillIds: ['count-shapes'], familyId: 'count-shapes', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ในภาพมีรูปวงกลมกี่รูป' },
      visual: { type: 'shape-count', shapes: ['circle', 'triangle', 'circle', 'square', 'circle', 'triangle', 'circle'] },
      options: [{ id: 'a', text: '3 รูป' }, { id: 'b', text: '4 รูป' }, { id: 'c', text: '5 รูป' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มีรูปวงกลม 4 รูป', hints: [], steps: ['วงกลมกลมไม่มีมุม', 'นับได้หนึ่ง สอง สาม สี่ มี 4 รูป'] },
    },
    {
      id: 'sc-flower-t', type: 'transfer', subject: 'science', skillIds: ['plant-parts'], familyId: 'plant-parts', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ส่วนใดของต้นไม้ที่มีสีสวยและมีกลิ่นหอม' },
      options: [{ id: 'a', text: 'ดอก' }, { id: 'b', text: 'ราก' }, { id: 'c', text: 'ลำต้น' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ดอกมีสีสวยและมีกลิ่นหอม', hints: [], steps: ['รากอยู่ใต้ดิน ลำต้นเป็นแกนของต้นไม้', 'ดอกมีสีสวยและกลิ่นหอม ผึ้งและผีเสื้อชอบมาหา'] },
    },
    {
      id: 'm-add-carry-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-add'], familyId: 'add-2digit-carry', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'มีลูกปัด 36 เม็ด ซื้อเพิ่มอีก 17 เม็ด มีลูกปัดทั้งหมดกี่เม็ด' },
      options: [{ id: 'a', text: '43 เม็ด' }, { id: 'b', text: '53 เม็ด' }, { id: 'c', text: '63 เม็ด' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '36 บวก 17 เท่ากับ 53 เม็ด', hints: [], steps: ['หลักหน่วย 6 บวก 7 ได้ 13 เขียน 3 ทด 1', 'หลักสิบ 1 บวก 3 บวก 1 ได้ 5 รวมเป็น 53'], column: { a: 36, op: '+', b: 17 } },
    },
    {
      id: 'g-police-t', type: 'transfer', subject: 'general', skillIds: ['occupations'], familyId: 'occupations', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ใครทำหน้าที่ดูแลความปลอดภัยและจับผู้ร้าย' },
      options: [{ id: 'a', text: 'ครู' }, { id: 'b', text: 'หมอ' }, { id: 'c', text: 'ตำรวจ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ตำรวจดูแลความปลอดภัยและจับผู้ร้าย', hints: [], steps: ['ครูสอนหนังสือ หมอรักษาคนป่วย', 'ตำรวจดูแลความปลอดภัยและจับผู้ร้าย'] },
    },
  ],
};
