/*
 * ชุดที่ 9 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 9) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * ใช้รูปแผ่น D (อาชีพ เครื่องมือ ยานพาหนะ; design/PROMPTS-gemini-4.md)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const GRID = 'ดูภาพในตารางแล้วตอบคำถามให้ถูกต้อง';
const JOBS = { type: 'grid', rows: [['pic-doctor', 'pic-police', 'pic-firefighter'], ['pic-farmer', 'pic-teacher', 'pic-cook'], ['pic-bus', 'pic-boat', 'pic-train']] };
const VEHICLES = { type: 'row', items: ['pic-firetruck', 'pic-ambulance', 'pic-bus', 'pic-boat', 'pic-airplane'], sides: true };
const CARS = { type: 'table', unit: 'คัน', rows: [{ name: 'รถโดยสาร', count: 6 }, { name: 'รถดับเพลิง', count: 1 }, { name: 'รถพยาบาล', count: 3 }] };

export default {
  id: 'set-09',
  version: 1,
  title: 'ชุดที่ 9',
  note: 'อาชีพ เครื่องมือ ยานพาหนะ ความปลอดภัย',
  order: [
    'th-uncle-cooking', 'th-fire-where', 'g-extinguisher', 'm-bus-riders', 'r-doctor-tool',
    'sp-jobs-under', 'sc-heart-sound', 'r-odd-vehicle', 'm-car-table', 'sp-count-from-right',
    'g-call-ambulance', 'sc-no-fuel',
  ],
  stimuli: {
    kitchen: {
      section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      text: 'วันเสาร์ ลุงสมชายทำอาหารอยู่ในครัว น้ำมันในกระทะร้อนมากจนมีไฟลุกขึ้น ลุงรีบปิดเตา แล้วใช้ถังดับเพลิงฉีดจนไฟดับ ทุกคนปลอดภัย',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'th-uncle-cooking', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'kitchen',
      prompt: { text: 'ลุงสมชายกำลังทำอะไรอยู่ในครัว' },
      options: [{ id: 'a', text: 'ล้างจาน' }, { id: 'b', text: 'ทำอาหาร' }, { id: 'c', text: 'กวาดบ้าน' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'ลุงสมชายทำอาหารอยู่',
        hints: ['ฟังประโยคแรกของเรื่องอีกครั้ง'],
        steps: ['เรื่องบอกว่า ลุงสมชายทำอาหารอยู่ในครัว', 'ลุงจึงกำลังทำอาหาร ตอบข้อ 2'],
        transferIds: ['th-market-buy-t'],
      },
    },
    {
      id: 'th-fire-where', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-where', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'kitchen',
      prompt: { text: 'ไฟลุกขึ้นที่ใด' },
      options: [{ id: 'a', text: 'ในห้องนอน' }, { id: 'b', text: 'ที่สนามหญ้า' }, { id: 'c', text: 'ในกระทะ' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'น้ำมันในกระทะร้อนจัด ไฟจึงลุกที่กระทะ',
        hints: ['อะไรร้อนมากจนมีไฟ'],
        steps: ['เรื่องบอกว่า น้ำมันในกระทะร้อนมากจนมีไฟลุกขึ้น', 'ไฟจึงลุกในกระทะ ตอบข้อ 3'],
        transferIds: ['th-ball-where-t'],
      },
    },
    {
      id: 'g-extinguisher', type: 'main', subject: 'general', skillIds: ['safety'], familyId: 'safety-fire', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'kitchen',
      prompt: { text: 'ลุงสมชายใช้สิ่งใดดับไฟ' },
      options: [{ id: 'a', image: 'pic-extinguisher', speech: 'ถังดับเพลิง' }, { id: 'b', image: 'pic-hoe', speech: 'จอบ' }, { id: 'c', image: 'pic-stethoscope', speech: 'หูฟัง' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ วัดการฟังและความรู้เรื่องความปลอดภัย',
      review: {
        summary: 'ลุงใช้ถังดับเพลิงฉีดดับไฟ',
        hints: ['สิ่งไหนใช้ฉีดดับไฟได้'],
        steps: ['จอบใช้ขุดดิน หูฟังใช้ตรวจคนไข้', 'ถังดับเพลิงใช้ฉีดดับไฟ ตอบข้อ 1'],
        transferIds: ['g-see-fire-t'],
      },
    },
    {
      id: 'm-bus-riders', type: 'main', subject: 'math', skillIds: ['word-problem-mixed'], familyId: 'in-out', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'บนรถโดยสารมีคน 8 คน ถึงป้ายแรก ลงไป 3 คน แล้วขึ้นมา 2 คน ตอนนี้บนรถมีคนกี่คน' },
      visual: { type: 'image', asset: 'pic-bus' },
      options: [{ id: 'a', text: '13 คน' }, { id: 'b', text: '9 คน' }, { id: 'c', text: '7 คน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการลบแล้วบวกต่อ',
      review: {
        summary: 'ลงไป 3 เหลือ 5 ขึ้นมา 2 รวมเป็น 7 คน',
        hints: ['ทำทีละขั้น คนลงก่อน แล้วคนขึ้น'],
        steps: ['คนลงไป คนบนรถน้อยลง 8 ลบ 3 เหลือ 5 คน', 'คนขึ้นมา คนบนรถมากขึ้น 5 บวก 2 เป็น 7 คน ตอบข้อ 3'],
        transferIds: ['m-boat-riders-t'],
      },
    },
    {
      id: 'r-doctor-tool', type: 'main', subject: 'reasoning', skillIds: ['relationship'], familyId: 'job-tool', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'หมอใช้สิ่งใดทำงาน' },
      visual: { type: 'image', asset: 'pic-doctor' },
      options: [{ id: 'a', image: 'pic-wok', speech: 'กระทะ' }, { id: 'b', image: 'pic-stethoscope', speech: 'หูฟัง' }, { id: 'c', image: 'pic-hoe', speech: 'จอบ' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ วัดการจับคู่อาชีพกับเครื่องมือ',
      review: {
        summary: 'หมอใช้หูฟังตรวจคนไข้',
        hints: ['หมอใช้อะไรฟังเสียงในตัวเรา'],
        steps: ['กระทะเป็นของแม่ครัว จอบเป็นของชาวนา', 'หมอใช้หูฟังตรวจคนไข้ ตอบข้อ 2'],
        transferIds: ['r-cook-tool-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'sp-jobs-under', type: 'main', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-position', difficulty: 2,
      sourceId: SRC, ...R, section: GRID,
      prompt: { text: 'ใครอยู่ใต้ตำรวจติดกันพอดี' },
      visual: JOBS,
      options: [{ id: 'a', image: 'pic-teacher', speech: 'ครู' }, { id: 'b', image: 'pic-cook', speech: 'แม่ครัว' }, { id: 'c', image: 'pic-boat', speech: 'เรือ' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกตำแหน่ง เด็กต้องดูตารางเอง',
      review: {
        summary: 'ใต้ตำรวจติดกันคือครู',
        hints: ['หาตำรวจก่อน แล้วมองลงมาหนึ่งช่อง'],
        steps: ['ตำรวจอยู่แถวบน ตรงกลาง', 'ช่องที่อยู่ใต้ตำรวจพอดีคือครู เรืออยู่ต่ำลงไปอีกแถว ตอบข้อ 1'],
        transferIds: ['sp-jobs-above-t'],
      },
    },
    {
      id: 'sc-heart-sound', type: 'main', subject: 'science', skillIds: ['body'], familyId: 'body-organs', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'หมอใช้หูฟังแตะที่หน้าอก เพื่อฟังเสียงอะไร' },
      visual: { type: 'image', asset: 'pic-stethoscope' },
      options: [{ id: 'a', text: 'เสียงเพลง' }, { id: 'b', text: 'เสียงนก' }, { id: 'c', text: 'เสียงหัวใจ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องร่างกาย',
      review: {
        summary: 'หัวใจอยู่ในอก หมอฟังว่าหัวใจเต้นดีไหม',
        hints: ['ในหน้าอกของเรามีอะไรเต้นตุบๆ'],
        steps: ['หัวใจอยู่ในหน้าอก เต้นตุบๆ ตลอดเวลา', 'หมอใช้หูฟังฟังเสียงหัวใจเต้น ตอบข้อ 3'],
        transferIds: ['sc-heart-where-t'],
      },
    },
    {
      id: 'r-odd-vehicle', type: 'main', subject: 'reasoning', skillIds: ['odd-one-out'], familyId: 'odd-one-out', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดไม่เข้าพวก' },
      options: [{ id: 'a', image: 'pic-bus', speech: 'รถโดยสาร' }, { id: 'b', image: 'pic-airplane', speech: 'เครื่องบิน' }, { id: 'c', image: 'pic-firetruck', speech: 'รถดับเพลิง' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ วัดการจัดกลุ่ม',
      review: {
        summary: 'เครื่องบินบินในอากาศ อีกสองคันวิ่งบนถนน',
        hints: ['ยานพาหนะแต่ละอย่างไปทางไหน'],
        steps: ['รถโดยสารกับรถดับเพลิงวิ่งบนถนน', 'เครื่องบินบินไปในอากาศ จึงไม่เข้าพวก ตอบข้อ 2'],
        transferIds: ['r-odd-job-t'],
      },
    },
    {
      id: 'm-car-table', type: 'main', subject: 'math', skillIds: ['read-table', 'compare-difference'], familyId: 'table-difference', difficulty: 2,
      sourceId: SRC, ...R, section: 'ดูตารางแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ตารางบอกจำนวนรถที่ผ่านหน้าโรงเรียน รถโดยสารมากกว่ารถพยาบาลกี่คัน' },
      visual: CARS,
      options: [{ id: 'a', text: '3 คัน' }, { id: 'b', text: '9 คัน' }, { id: 'c', text: '2 คัน' }],
      correctOptionId: 'a',
      narration: 'อ่านตารางและตัวเลือกได้ วัดการอ่านตารางและหาผลต่าง',
      review: {
        summary: '6 ลบ 3 เท่ากับ 3 คัน',
        hints: ['หาจำนวนรถโดยสารกับรถพยาบาลในตารางก่อน'],
        steps: ['รถโดยสาร 6 คัน รถพยาบาล 3 คัน', 'หาว่ามากกว่ากี่คัน ใช้การลบ 6 ลบ 3 เท่ากับ 3 ตอบข้อ 1'],
        column: { a: 6, op: '-', b: 3 },
        transferIds: ['m-car-total-t'],
      },
    },
    {
      id: 'sp-count-from-right', type: 'main', subject: 'spatial', skillIds: ['ordinal-position'], familyId: 'count-from-side', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'นับจากทางขวา ภาพที่ 4 คือภาพใด' },
      visual: VEHICLES,
      options: [{ id: 'a', image: 'pic-boat', speech: 'เรือ' }, { id: 'b', image: 'pic-bus', speech: 'รถโดยสาร' }, { id: 'c', image: 'pic-ambulance', speech: 'รถพยาบาล' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกลำดับ เด็กต้องนับเอง',
      review: {
        summary: 'นับจากขวา เครื่องบิน เรือ รถโดยสาร รถพยาบาล',
        hints: ['เริ่มนับจากภาพขวาสุดเป็นหนึ่ง'],
        steps: ['เริ่มที่ด้านขวา เครื่องบินคือหนึ่ง เรือคือสอง รถโดยสารคือสาม', 'รถพยาบาลคือสี่ ตอบข้อ 3'],
        transferIds: ['sp-count-left-vehicles-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'g-call-ambulance', type: 'main', subject: 'general', skillIds: ['community-helpers'], familyId: 'community-helpers', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'มีคนบาดเจ็บ ต้องรีบไปหาหมอ ควรเรียกรถใด' },
      options: [{ id: 'a', image: 'pic-firetruck', speech: 'รถดับเพลิง' }, { id: 'b', image: 'pic-ambulance', speech: 'รถพยาบาล' }, { id: 'c', image: 'pic-bus', speech: 'รถโดยสาร' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ วัดความรู้เรื่องผู้ช่วยเหลือในชุมชน',
      review: {
        summary: 'รถพยาบาลพาคนเจ็บไปหาหมอ',
        hints: ['รถคันไหนมีพยาบาลและเตียงคนไข้'],
        steps: ['รถดับเพลิงไปดับไฟ รถโดยสารรับส่งคนทั่วไป', 'รถพยาบาลรีบพาคนเจ็บไปโรงพยาบาล ตอบข้อ 2'],
        transferIds: ['g-lost-police-t'],
      },
    },
    {
      id: 'sc-no-fuel', type: 'main', subject: 'science', skillIds: ['energy'], familyId: 'energy-move', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ยานพาหนะใดไม่ต้องเติมน้ำมันก็ไปได้' },
      options: [{ id: 'a', image: 'pic-bicycle', speech: 'จักรยาน' }, { id: 'b', image: 'pic-bus', speech: 'รถโดยสาร' }, { id: 'c', image: 'pic-airplane', speech: 'เครื่องบิน' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ วัดความรู้เรื่องแรงและพลังงาน',
      review: {
        summary: 'จักรยานไปได้ด้วยแรงปั่นของเรา',
        hints: ['ยานพาหนะใดใช้แรงคนปั่น'],
        steps: ['รถโดยสารและเครื่องบินต้องเติมน้ำมันจึงจะไปได้', 'จักรยานใช้แรงขาของเราปั่น ไม่ต้องเติมน้ำมัน ตอบข้อ 1'],
        transferIds: ['sc-pedal-power-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-market-buy-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'แม่ไปตลาดซื้อปลากับผัก แล้วกลับมาทำแกงให้ลูกกิน แม่ซื้ออะไรมาจากตลาด' },
      options: [{ id: 'a', text: 'ไก่กับไข่' }, { id: 'b', text: 'ปลากับผัก' }, { id: 'c', text: 'ขนมกับนม' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'แม่ซื้อปลากับผัก', hints: [], steps: ['เรื่องบอกว่า แม่ไปตลาดซื้อปลากับผัก', 'แล้วนำมาทำแกง'] },
    },
    {
      id: 'th-ball-where-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-where', difficulty: 2,
      sourceId: SRC, ...R, section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'น้องเตะลูกบอลในสวน ลูกบอลกลิ้งไปอยู่ใต้เก้าอี้ ลูกบอลอยู่ที่ใด' },
      options: [{ id: 'a', text: 'ใต้เก้าอี้' }, { id: 'b', text: 'บนต้นไม้' }, { id: 'c', text: 'ในบ้าน' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ลูกบอลกลิ้งไปใต้เก้าอี้', hints: [], steps: ['เรื่องบอกว่า ลูกบอลกลิ้งไปอยู่ใต้เก้าอี้', 'ลูกบอลจึงอยู่ใต้เก้าอี้'] },
    },
    {
      id: 'g-see-fire-t', type: 'transfer', subject: 'general', skillIds: ['safety'], familyId: 'safety-fire', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าเห็นไฟไหม้ หนูควรทำอย่างไร' },
      options: [{ id: 'a', text: 'เข้าไปดูใกล้ๆ' }, { id: 'b', text: 'ซ่อนตัวในตู้' }, { id: 'c', text: 'รีบออกไปแล้วบอกผู้ใหญ่' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ออกห่างจากไฟ แล้วบอกผู้ใหญ่ทันที', hints: [], steps: ['ไฟร้อนและควันทำให้หายใจไม่ออก', 'ต้องรีบออกไปที่ปลอดภัย แล้วบอกผู้ใหญ่'] },
    },
    {
      id: 'm-boat-riders-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-mixed'], familyId: 'in-out', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'บนเรือมีคน 5 คน ขึ้นมาอีก 4 คน แล้วลงไป 2 คน บนเรือมีคนกี่คน' },
      options: [{ id: 'a', text: '11 คน' }, { id: 'b', text: '7 คน' }, { id: 'c', text: '3 คน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ขึ้นมา 4 เป็น 9 ลงไป 2 เหลือ 7 คน', hints: [], steps: ['คนขึ้นมา 5 บวก 4 เป็น 9 คน', 'คนลงไป 9 ลบ 2 เหลือ 7 คน'] },
    },
    {
      id: 'r-cook-tool-t', type: 'transfer', subject: 'reasoning', skillIds: ['relationship'], familyId: 'job-tool', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'แม่ครัวใช้สิ่งใดทำงาน' },
      visual: { type: 'image', asset: 'pic-cook' },
      options: [{ id: 'a', image: 'pic-hoe', speech: 'จอบ' }, { id: 'b', image: 'pic-extinguisher', speech: 'ถังดับเพลิง' }, { id: 'c', image: 'pic-wok', speech: 'กระทะ' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'แม่ครัวใช้กระทะผัดอาหาร', hints: [], steps: ['แม่ครัวทำอาหารให้คนกิน', 'จึงใช้กระทะผัดและทอดอาหาร'] },
    },
    {
      id: 'sp-jobs-above-t', type: 'transfer', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-position', difficulty: 2,
      sourceId: SRC, ...R, section: GRID,
      prompt: { text: 'ใครอยู่บนแม่ครัวติดกันพอดี' },
      visual: JOBS,
      options: [{ id: 'a', image: 'pic-police', speech: 'ตำรวจ' }, { id: 'b', image: 'pic-firefighter', speech: 'นักดับเพลิง' }, { id: 'c', image: 'pic-train', speech: 'รถไฟ' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'บนแม่ครัวติดกันคือนักดับเพลิง', hints: [], steps: ['แม่ครัวอยู่แถวกลาง ขวาสุด', 'ช่องที่อยู่บนแม่ครัวพอดีคือนักดับเพลิง'] },
    },
    {
      id: 'sc-heart-where-t', type: 'transfer', subject: 'science', skillIds: ['body'], familyId: 'body-organs', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'หัวใจของเราอยู่ส่วนใดของร่างกาย' },
      options: [{ id: 'a', text: 'ในหน้าอก' }, { id: 'b', text: 'ในศีรษะ' }, { id: 'c', text: 'ในเท้า' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'หัวใจอยู่ในอก ค่อนไปทางซ้าย', hints: [], steps: ['เอามือแตะหน้าอกจะรู้สึกหัวใจเต้น', 'หัวใจจึงอยู่ในหน้าอก'] },
    },
    {
      id: 'r-odd-job-t', type: 'transfer', subject: 'reasoning', skillIds: ['odd-one-out'], familyId: 'odd-one-out', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดไม่เข้าพวก' },
      options: [{ id: 'a', image: 'pic-boat', speech: 'เรือ' }, { id: 'b', image: 'pic-train', speech: 'รถไฟ' }, { id: 'c', image: 'pic-cook', speech: 'แม่ครัว' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'แม่ครัวเป็นคน อีกสองอย่างเป็นยานพาหนะ', hints: [], steps: ['เรือกับรถไฟเป็นยานพาหนะ', 'แม่ครัวเป็นอาชีพ จึงไม่เข้าพวก'] },
    },
    {
      id: 'm-car-total-t', type: 'transfer', subject: 'math', skillIds: ['read-table'], familyId: 'table-difference', difficulty: 2,
      sourceId: SRC, ...R, section: 'ดูตารางแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'จากตารางเดิม มีรถผ่านหน้าโรงเรียนทั้งหมดกี่คัน' },
      visual: CARS,
      options: [{ id: 'a', text: '9 คัน' }, { id: 'b', text: '4 คัน' }, { id: 'c', text: '10 คัน' }],
      correctOptionId: 'c',
      narration: 'อ่านตารางได้',
      review: { summary: '6 บวก 1 บวก 3 เท่ากับ 10 คัน', hints: [], steps: ['รถโดยสาร 6 รถดับเพลิง 1 รถพยาบาล 3', '6 บวก 1 ได้ 7 บวกอีก 3 ได้ 10 คัน'] },
    },
    {
      id: 'sp-count-left-vehicles-t', type: 'transfer', subject: 'spatial', skillIds: ['ordinal-position'], familyId: 'count-from-side', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'นับจากทางซ้าย ภาพที่ 4 คือภาพใด' },
      visual: VEHICLES,
      options: [{ id: 'a', image: 'pic-airplane', speech: 'เครื่องบิน' }, { id: 'b', image: 'pic-boat', speech: 'เรือ' }, { id: 'c', image: 'pic-bus', speech: 'รถโดยสาร' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'นับจากซ้าย ภาพที่ 4 คือเรือ', hints: [], steps: ['เริ่มที่ด้านซ้าย รถดับเพลิง รถพยาบาล รถโดยสาร', 'ภาพต่อไปคือเรือ เป็นภาพที่ 4'] },
    },
    {
      id: 'g-lost-police-t', type: 'transfer', subject: 'general', skillIds: ['community-helpers'], familyId: 'community-helpers', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ถ้าหลงทางอยู่ริมถนน ควรขอความช่วยเหลือจากใคร' },
      options: [{ id: 'a', image: 'pic-police', speech: 'ตำรวจ' }, { id: 'b', image: 'pic-farmer', speech: 'ชาวนา' }, { id: 'c', image: 'pic-cook', speech: 'แม่ครัว' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ตำรวจช่วยพาเด็กหลงทางกลับบ้าน', hints: [], steps: ['ตำรวจมีหน้าที่ดูแลความปลอดภัย', 'ถ้าหลงทางให้บอกตำรวจ'] },
    },
    {
      id: 'sc-pedal-power-t', type: 'transfer', subject: 'science', skillIds: ['energy'], familyId: 'energy-move', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'จักรยานเคลื่อนที่ไปได้เพราะอะไร' },
      visual: { type: 'image', asset: 'pic-bicycle' },
      options: [{ id: 'a', text: 'เพราะเติมน้ำมัน' }, { id: 'b', text: 'เพราะเราใช้ขาปั่น' }, { id: 'c', text: 'เพราะมีลมพัด' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แรงขาของเราทำให้ล้อหมุน', hints: [], steps: ['เราปั่นบันไดจักรยานด้วยขา', 'ล้อจึงหมุนและจักรยานเคลื่อนที่'] },
    },
  ],
};
