/*
 * ชุดที่ 24 — รูปแบบใหม่ 15 ข้อ (ดู docs/QUESTION-TYPES.md หัวข้อ "รูปแบบชุด 12 ขึ้นไป")
 * ช่วง 1 เรื่องวันเกิดของน้องแก้ว ถาม 5 ข้อ: ใครทำเค้ก ลูกโป่งทั้งหมด จำนวนคนในงาน ความหมายคำ มารยาทไปงานวันเกิด
 * ช่วง 2 ข้อเดี่ยว: ตัวสะกดแม่ กด, สระเสียงยาว, สิ่งมีชีวิต, เงา, น้ำใจต่อเพื่อนที่ล้ม
 * ช่วง 3 ข้อเดี่ยว: ค่าประจำหลัก (สิบ/หน่วย) นับกล่องซ้อน พับครึ่งทับกันสนิท (สมมาตร) เปรียบเทียบสัมพันธ์ (ไก่-ไข่ วัว-นม) เรียงเลขน้อยไปมาก
 * แต่งใหม่ทั้งหมด ตั้งชื่อตัวละคร สถานที่ และตัวเลขใหม่ตามแนวข้อสอบเก่า; ใช้รูปที่มีอยู่แล้ว ไม่ต้องสร้างรูปใหม่จาก Gemini
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LISTEN = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const fold = (id, shape) => ({ id, svg: { fold: shape } });

export default {
  id: 'set-24',
  version: 1,
  title: 'ชุดที่ 24',
  note: 'วันเกิดน้องแก้ว ตัวสะกด สิ่งมีชีวิต เงา หลักสิบ พับครึ่ง',
  order: [
    'th-party-cake', 'm-party-balloons', 'r-party-people', 'th-word-wish', 'g-party-polite',
    'th-final-kd', 'th-vowel-long', 'sc-living', 'sc-shadow', 'g-friend-fall',
    'm-tens', 'sp-stack-count', 'sp-fold-star', 'r-analogy-milk', 'r-order-numbers',
  ],
  stimuli: {
    party: {
      section: LISTEN,
      text: 'วันเสาร์นี้เป็นวันเกิดของน้องแก้ว อายุครบ 7 ปี แม่ทำเค้กช็อกโกแลตให้หนึ่งก้อน พ่อซื้อลูกโป่งสีแดง 5 ลูก และสีเหลือง 3 ลูก มาตกแต่งห้อง เพื่อนๆ 4 คนมาร่วมงาน ทุกคนร้องเพลงอวยพรวันเกิดให้น้องแก้ว น้องแก้วเป่าเทียนแล้วขอพร จากนั้นทุกคนก็แบ่งเค้กกินกันอย่างมีความสุข',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: เรื่องวันเกิดของน้องแก้ว 5 ข้อ
    {
      id: 'th-party-cake', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-who', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'party',
      prompt: { text: 'ใครทำเค้กให้น้องแก้ว' },
      options: [{ id: 'a', text: 'พ่อ' }, { id: 'b', text: 'แม่' }, { id: 'c', text: 'เพื่อนๆ' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังจับรายละเอียดว่าใครทำอะไร',
      review: {
        summary: 'แม่เป็นคนทำเค้กช็อกโกแลต',
        hints: ['ฟังประโยคที่พูดถึงเค้ก'],
        steps: ['เรื่องบอกว่า แม่ทำเค้กช็อกโกแลตให้หนึ่งก้อน', 'พ่อซื้อลูกโป่ง ส่วนเพื่อนๆ มาร่วมงาน ตอบข้อ 2'],
        transferIds: ['th-party-cake-t'],
      },
    },
    {
      id: 'm-party-balloons', type: 'main', subject: 'math', skillIds: ['word-problem-add'], familyId: 'story-number', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'party',
      prompt: { text: 'พ่อซื้อลูกโป่งมาทั้งหมดกี่ลูก' },
      options: [{ id: 'a', text: '8 ลูก' }, { id: 'b', text: '9 ลูก' }, { id: 'c', text: '15 ลูก' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการฟังตัวเลขสองจำนวนแล้วบวก',
      review: {
        summary: 'ลูกโป่งสีแดง 5 ลูก บวกสีเหลือง 3 ลูก เป็น 8 ลูก',
        hints: ['เอาจำนวนลูกโป่งสองสีมาบวกกัน'],
        steps: ['เรื่องบอกว่า ลูกโป่งสีแดง 5 ลูก และสีเหลือง 3 ลูก', '5 บวก 3 เท่ากับ 8 ตอบข้อ 1'],
        column: { a: 5, op: '+', b: 3 },
        transferIds: ['m-party-balloons-t'],
      },
    },
    {
      id: 'r-party-people', type: 'main', subject: 'reasoning', skillIds: ['story-count'], familyId: 'story-count', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'party',
      prompt: { text: 'ในงานวันเกิดมีคนทั้งหมดกี่คน (นับน้องแก้ว เพื่อนๆ แม่ และพ่อ)' },
      options: [{ id: 'a', text: '5 คน' }, { id: 'b', text: '6 คน' }, { id: 'c', text: '7 คน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการนับคนจากเรื่อง (เพื่อน 4 คน ต้องนับรวมด้วย)',
      review: {
        summary: 'น้องแก้ว 1 เพื่อน 4 แม่ 1 และพ่อ 1 รวม 7 คน',
        hints: ['อย่าลืมว่าเพื่อนมา 4 คน ไม่ใช่คนเดียว'],
        steps: ['น้องแก้ว 1 คน เพื่อนๆ 4 คน แม่ 1 คน และพ่ออีก 1 คน', '1 บวก 4 บวก 1 บวก 1 เท่ากับ 7 ตอบข้อ 3'],
        transferIds: ['r-party-people-t'],
      },
    },
    {
      id: 'th-word-wish', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'party',
      prompt: { text: 'คำว่า อวยพร หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'พูดให้คนอื่นมีความสุขและโชคดี' }, { id: 'b', text: 'พูดเสียงดังใส่คนอื่น' }, { id: 'c', text: 'พูดกับตัวเองคนเดียว' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ วัดความเข้าใจความหมายคำจากเรื่อง',
      review: {
        summary: 'อวยพร คือกล่าวคำดีๆ ให้คนอื่นมีความสุข',
        hints: ['ทุกคนร้องเพลงอวยพรวันเกิดให้น้องแก้วเพื่ออะไร'],
        steps: ['ทุกคนร้องเพลงอวยพรวันเกิด เพื่อให้น้องแก้วมีความสุข', 'อวยพรจึงหมายถึงพูดให้คนอื่นมีความสุขและโชคดี ตอบข้อ 1'],
        transferIds: ['th-word-wish-t'],
      },
    },
    {
      id: 'g-party-polite', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'manners-greet', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'party',
      prompt: { text: 'เมื่อได้รับเชิญไปงานวันเกิดของเพื่อน ควรทำอย่างไร' },
      options: [{ id: 'a', text: 'ไปสายและไม่ทักใคร' }, { id: 'b', text: 'ไปตรงเวลาและทักทายเจ้าของงาน' }, { id: 'c', text: 'ไปกินอย่างเดียว ไม่สนใจใคร' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องมารยาทในการไปงาน',
      review: {
        summary: 'ไปตรงเวลา ทักทายเจ้าของงาน แสดงความเคารพและยินดีด้วย',
        hints: ['คนที่เชิญเรา ควรได้รับการปฏิบัติอย่างไร'],
        steps: ['ไปสายและไม่ทักใคร หรือไปกินอย่างเดียว เป็นการไม่ให้เกียรติเจ้าของงาน', 'ควรไปตรงเวลาและทักทายเจ้าของงาน ตอบข้อ 2'],
        transferIds: ['g-party-polite-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: ภาษาไทย วิทยาศาสตร์ น้ำใจ
    {
      id: 'th-final-kd', type: 'main', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีตัวสะกดในแม่ กด' },
      options: [{ id: 'a', text: 'นก' }, { id: 'b', text: 'ลิง' }, { id: 'c', text: 'รถ' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูพยัญชนะท้ายคำเอง (ท้ายคำ ถ อ่านออกเสียงเหมือน ด)',
      review: {
        summary: 'รถมี ถ เป็นตัวสะกด อ่านออกเสียงท้ายเหมือน ด จึงอยู่ในแม่ กด',
        hints: ['แม่ กด ตัวสะกดออกเสียงท้ายเหมือนตัว ด เช่น รถ รส'],
        steps: ['นกมี ก เป็นตัวสะกด อยู่ในแม่ กก และลิงมี ง เป็นตัวสะกด อยู่ในแม่ กง', 'รถมี ถ เป็นตัวสะกด เสียงท้ายเหมือน ด จึงอยู่ในแม่ กด ตอบข้อ 3'],
        transferIds: ['th-final-kd-t'],
      },
    },
    {
      id: 'th-vowel-long', type: 'main', subject: 'thai', skillIds: ['vowel-length'], familyId: 'vowel-length', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดใช้สระเสียงยาว' },
      options: [{ id: 'a', text: 'จะ' }, { id: 'b', text: 'ปู' }, { id: 'c', text: 'นะ' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ ฟังเสียงสั้นยาวของคำประกอบการตัดสิน (วัดการฟังและความรู้เรื่องสระ)',
      review: {
        summary: 'ปูใช้สระอู ซึ่งเป็นเสียงยาว',
        hints: ['ลองออกเสียง คำไหนลากเสียงยาว คำไหนเสียงสั้นห้วนๆ'],
        steps: ['จะและนะใช้สระอะ ซึ่งเป็นเสียงสั้น', 'ปูใช้สระอู เป็นเสียงยาว ตอบข้อ 2'],
        transferIds: ['th-vowel-long-t'],
      },
    },
    {
      id: 'sc-living', type: 'main', subject: 'science', skillIds: ['living-things'], familyId: 'living-things', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สิ่งใดเป็นสิ่งมีชีวิต' },
      options: [{ id: 'a', text: 'ต้นไม้' }, { id: 'b', text: 'ก้อนหิน' }, { id: 'c', text: 'โต๊ะ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสิ่งมีชีวิต',
      review: {
        summary: 'ต้นไม้กินอาหาร เติบโต และออกลูกได้ จึงเป็นสิ่งมีชีวิต',
        hints: ['สิ่งมีชีวิตต้องเติบโตได้'],
        steps: ['ก้อนหินและโต๊ะไม่เติบโต ไม่กินอาหาร จึงไม่ใช่สิ่งมีชีวิต', 'ต้นไม้เติบโตและต้องการน้ำ เป็นสิ่งมีชีวิต ตอบข้อ 1'],
        transferIds: ['sc-living-t'],
      },
    },
    {
      id: 'sc-shadow', type: 'main', subject: 'science', skillIds: ['shadow'], familyId: 'shadow', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ทำไมเราจึงเห็นเงาของตัวเองเมื่อยืนกลางแดด' },
      options: [{ id: 'a', text: 'เพราะดวงอาทิตย์ทำให้เกิดลม' }, { id: 'b', text: 'เพราะดินร้อน' }, { id: 'c', text: 'เพราะตัวเรากั้นแสงอาทิตย์ไว้' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจการเกิดเงา',
      review: {
        summary: 'ตัวเรากั้นแสง แสงผ่านไม่ได้ จึงเกิดเงาบนพื้น',
        hints: ['เงาคือบริเวณที่แสงส่องไปไม่ถึง'],
        steps: ['ลมและดินร้อนไม่ทำให้เกิดเงา', 'ตัวเรากั้นแสงอาทิตย์ แสงส่องผ่านไม่ได้ จึงเกิดเงา ตอบข้อ 3'],
        transferIds: ['sc-shadow-t'],
      },
    },
    {
      id: 'g-friend-fall', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'manners-help', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าเพื่อนล้มลงตอนวิ่งเล่น ควรทำอย่างไร' },
      options: [{ id: 'a', text: 'หัวเราะเยาะ' }, { id: 'b', text: 'ช่วยพยุงและถามว่าเจ็บไหม' }, { id: 'c', text: 'เดินหนีไป' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องน้ำใจต่อเพื่อน',
      review: {
        summary: 'ช่วยพยุงเพื่อนและถามว่าเจ็บไหม',
        hints: ['ถ้าเราล้มบ้าง อยากให้เพื่อนทำอย่างไรกับเรา'],
        steps: ['หัวเราะเยาะหรือเดินหนี ทำให้เพื่อนเสียใจ', 'ควรช่วยพยุงและถามว่าเจ็บไหม ตอบข้อ 2'],
        transferIds: ['g-friend-fall-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3: ค่าประจำหลัก กล่องซ้อน พับครึ่ง เปรียบเทียบสัมพันธ์ เรียงเลข
    {
      id: 'm-tens', type: 'main', subject: 'math', skillIds: ['place-value'], familyId: 'place-value', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เลข 35 มีกี่สิบกี่หน่วย' },
      options: [{ id: 'a', text: '3 สิบ 5 หน่วย' }, { id: 'b', text: '5 สิบ 3 หน่วย' }, { id: 'c', text: '3 สิบ 3 หน่วย' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจค่าประจำหลักสิบและหลักหน่วย',
      review: {
        summary: '35 คือ 3 สิบ กับ 5 หน่วย',
        hints: ['เลขตัวหน้าคือหลักสิบ เลขตัวหลังคือหลักหน่วย'],
        steps: ['35 ตัวหน้าคือ 3 อยู่หลักสิบ แปลว่า 3 สิบ', 'ตัวหลังคือ 5 อยู่หลักหน่วย แปลว่า 5 หน่วย ตอบข้อ 1'],
        transferIds: ['m-tens-t'],
      },
    },
    {
      id: 'sp-stack-count', type: 'main', subject: 'spatial', skillIds: ['count-blocks'], familyId: 'stacks', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'กล่องซ้อนกันดังภาพ มีกล่องทั้งหมดกี่กล่อง' },
      visual: { type: 'stack', columns: [2, 4, 1] },
      options: [{ id: 'a', text: '6 กล่อง' }, { id: 'b', text: '8 กล่อง' }, { id: 'c', text: '7 กล่อง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ เสียงไม่บอกจำนวน เด็กต้องนับจากภาพเอง',
      review: {
        summary: 'มีกล่อง 2 บวก 4 บวก 1 เท่ากับ 7 กล่อง',
        hints: ['นับทีละแถวตั้ง จากซ้ายไปขวา'],
        steps: ['แถวแรกมี 2 กล่อง แถวที่สองมี 4 กล่อง แถวที่สามมี 1 กล่อง', '2 บวก 4 บวก 1 เท่ากับ 7 กล่อง ตอบข้อ 3'],
        transferIds: ['sp-stack-count-t'],
      },
    },
    {
      id: 'sp-fold-star', type: 'main', subject: 'spatial', skillIds: ['symmetry'], familyId: 'symmetry', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดพับครึ่งตามเส้นประแล้วทับกันสนิท' },
      options: [fold('a', 'flag'), fold('b', 'star'), fold('c', 'lshape')],
      correctOptionId: 'b',
      narration: 'ตัวเลือกอ่านแค่หมายเลข เพื่อให้เด็กดูรูปเอง',
      review: {
        summary: 'ดาวพับครึ่งแล้วทับกันสนิท',
        hints: ['ดูว่าซีกซ้ายกับซีกขวาของเส้นประเหมือนกันไหม'],
        steps: ['ถ้าพับตามเส้นประ ซีกซ้ายต้องเหมือนซีกขวาจึงจะทับกันสนิท', 'ดาวสองซีกเหมือนกัน ส่วนธงและตัว L สองซีกไม่เหมือนกัน ตอบข้อ 2'],
        transferIds: ['sp-fold-star-t'],
      },
    },
    {
      id: 'r-analogy-milk', type: 'main', subject: 'reasoning', skillIds: ['analogy'], familyId: 'analogy', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ไก่ให้ไข่ วัวให้อะไร' },
      options: [{ id: 'a', text: 'ผัก' }, { id: 'b', text: 'น้ำ' }, { id: 'c', text: 'นม' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการเทียบความสัมพันธ์ระหว่างสัตว์กับสิ่งที่ได้จากสัตว์',
      review: {
        summary: 'ไก่ให้ไข่ วัวให้นม',
        hints: ['เราได้อะไรมาจากวัวเลี้ยง'],
        steps: ['ไก่ให้ไข่ คือสัตว์กับสิ่งที่ได้จากสัตว์นั้น', 'วัวให้นม ตอบข้อ 3'],
        transferIds: ['r-analogy-milk-t'],
      },
    },
    {
      id: 'r-order-numbers', type: 'main', subject: 'reasoning', skillIds: ['order-numbers'], familyId: 'order-numbers', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เรียงเลขจากน้อยไปมาก ข้อใดถูกต้อง' },
      options: [{ id: 'a', text: '12, 18, 21' }, { id: 'b', text: '21, 12, 18' }, { id: 'c', text: '18, 12, 21' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงลำดับจำนวน',
      review: {
        summary: '12 น้อยที่สุด ตามด้วย 18 แล้ว 21',
        hints: ['เทียบเลขหลักสิบก่อน ถ้าเท่ากันค่อยดูหลักหน่วย'],
        steps: ['12 กับ 18 หลักสิบเป็น 1 เท่ากัน 12 หลักหน่วยน้อยกว่า ส่วน 21 หลักสิบเป็น 2 จึงมากที่สุด', 'เรียงได้ 12, 18, 21 ตอบข้อ 1'],
        transferIds: ['r-order-numbers-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-party-cake-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-who', difficulty: 1,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ที่บ้านของน้องบี แม่ทำขนมปัง พ่อซื้อนมมาให้ ใครทำขนมปัง' },
      options: [{ id: 'a', text: 'แม่' }, { id: 'b', text: 'พ่อ' }, { id: 'c', text: 'น้องบี' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'แม่ทำขนมปัง', hints: [], steps: ['โจทย์บอกว่า แม่ทำขนมปัง', 'พ่อซื้อนมมาให้ ไม่ได้ทำขนมปัง'] },
    },
    {
      id: 'm-party-balloons-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-add'], familyId: 'story-number', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'แม่ซื้อลูกโป่งสีฟ้า 6 ลูก และสีขาว 4 ลูก แม่ซื้อลูกโป่งทั้งหมดกี่ลูก' },
      options: [{ id: 'a', text: '2 ลูก' }, { id: 'b', text: '10 ลูก' }, { id: 'c', text: '24 ลูก' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '6 บวก 4 เท่ากับ 10 ลูก', hints: [], steps: ['ลูกโป่งสีฟ้า 6 ลูก และสีขาว 4 ลูก ต้องเอามาบวกกัน', '6 บวก 4 เท่ากับ 10'], column: { a: 6, op: '+', b: 4 } },
    },
    {
      id: 'r-party-people-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-count'], familyId: 'story-count', difficulty: 3,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ในห้องมีครู เด็กชาย 3 คน และเด็กหญิง 2 คน ในห้องมีคนทั้งหมดกี่คน' },
      options: [{ id: 'a', text: '5 คน' }, { id: 'b', text: '6 คน' }, { id: 'c', text: '7 คน' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ครู 1 เด็กชาย 3 เด็กหญิง 2 รวม 6 คน', hints: [], steps: ['ครู 1 คน เด็กชาย 3 คน และเด็กหญิง 2 คน', '1 บวก 3 บวก 2 เท่ากับ 6'] },
    },
    {
      id: 'th-word-wish-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า แสดงความยินดี หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'บอกให้รู้ว่าเรารู้สึกดีใจไปด้วย' }, { id: 'b', text: 'บอกให้เพื่อนเสียใจ' }, { id: 'c', text: 'ไม่พูดอะไรเลย' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'แสดงความยินดี คือบอกให้รู้ว่าเราดีใจด้วย', hints: [], steps: ['เมื่อเพื่อนมีเรื่องดีๆ เราดีใจไปด้วยและบอกเพื่อน', 'ทำให้เพื่อนเสียใจหรือไม่พูดอะไร ไม่ใช่การแสดงความยินดี'] },
    },
    {
      id: 'g-party-polite-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'manners-greet', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อไปบ้านเพื่อน ควรทำอย่างไรเมื่อพบพ่อแม่ของเพื่อน' },
      options: [{ id: 'a', text: 'ทักทายอย่างสุภาพ' }, { id: 'b', text: 'เดินผ่านไปเฉยๆ' }, { id: 'c', text: 'วิ่งหนีเข้าห้อง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ทักทายพ่อแม่ของเพื่อนอย่างสุภาพ', hints: [], steps: ['เดินผ่านไปเฉยๆ หรือวิ่งหนี ไม่สุภาพ', 'ควรทักทายผู้ใหญ่อย่างสุภาพ'] },
    },
    {
      id: 'th-final-kd-t', type: 'transfer', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีตัวสะกดในแม่ กด' },
      options: [{ id: 'a', text: 'ปู' }, { id: 'b', text: 'รส' }, { id: 'c', text: 'นม' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูพยัญชนะท้ายคำเอง',
      review: { summary: 'รสมี ส เป็นตัวสะกด เสียงท้ายเหมือน ด จึงอยู่ในแม่ กด', hints: [], steps: ['ปูไม่มีตัวสะกด และนมมี ม เป็นตัวสะกด อยู่ในแม่ กม', 'รสมี ส เป็นตัวสะกด อ่านท้ายเหมือน ด จึงอยู่ในแม่ กด'] },
    },
    {
      id: 'th-vowel-long-t', type: 'transfer', subject: 'thai', skillIds: ['vowel-length'], familyId: 'vowel-length', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดใช้สระเสียงสั้น' },
      options: [{ id: 'a', text: 'ขา' }, { id: 'b', text: 'ละ' }, { id: 'c', text: 'ดี' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ละใช้สระอะ ซึ่งเป็นเสียงสั้น', hints: [], steps: ['ขาใช้สระอา และดีใช้สระอี ทั้งสองเป็นเสียงยาว', 'ละใช้สระอะ เป็นเสียงสั้น'] },
    },
    {
      id: 'sc-living-t', type: 'transfer', subject: 'science', skillIds: ['living-things'], familyId: 'living-things', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สิ่งใดเป็นสิ่งมีชีวิต' },
      options: [{ id: 'a', text: 'จาน' }, { id: 'b', text: 'ไก่' }, { id: 'c', text: 'ร่ม' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไก่กินอาหารและเติบโตได้ เป็นสิ่งมีชีวิต', hints: [], steps: ['จานและร่มเป็นของใช้ ไม่เติบโต', 'ไก่กินอาหารและเติบโตได้ จึงเป็นสิ่งมีชีวิต'] },
    },
    {
      id: 'sc-shadow-t', type: 'transfer', subject: 'science', skillIds: ['shadow'], familyId: 'shadow', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เงาของต้นไม้จะเกิดขึ้นเมื่อใด' },
      options: [{ id: 'a', text: 'ตอนฟ้ามืดสนิท' }, { id: 'b', text: 'เมื่อมีแสงแดดส่องมา' }, { id: 'c', text: 'ตอนฝนตกหนัก' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ต้องมีแสงส่องมา ต้นไม้กั้นแสง จึงเกิดเงา', hints: [], steps: ['ตอนมืดสนิทไม่มีแสงให้เกิดเงา และตอนฝนตกหนักแสงน้อยมาก', 'เมื่อมีแสงแดดส่อง ต้นไม้กั้นแสงไว้ จึงเกิดเงา'] },
    },
    {
      id: 'g-friend-fall-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'manners-help', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าเพื่อนทำดินสอตกพื้น ควรทำอย่างไร' },
      options: [{ id: 'a', text: 'เตะดินสอไปไกลๆ' }, { id: 'b', text: 'เฉยๆ ไม่สนใจ' }, { id: 'c', text: 'ช่วยเก็บให้' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ช่วยเก็บดินสอให้เพื่อน', hints: [], steps: ['เตะดินสอหรือเฉยๆ ไม่ใช่การช่วยเหลือ', 'ควรช่วยเก็บให้เพื่อน'] },
    },
    {
      id: 'm-tens-t', type: 'transfer', subject: 'math', skillIds: ['place-value'], familyId: 'place-value', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เลข 52 มีกี่สิบกี่หน่วย' },
      options: [{ id: 'a', text: '2 สิบ 5 หน่วย' }, { id: 'b', text: '5 สิบ 5 หน่วย' }, { id: 'c', text: '5 สิบ 2 หน่วย' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '52 คือ 5 สิบ กับ 2 หน่วย', hints: [], steps: ['เลขตัวหน้าคือ 5 อยู่หลักสิบ แปลว่า 5 สิบ', 'เลขตัวหลังคือ 2 อยู่หลักหน่วย แปลว่า 2 หน่วย'] },
    },
    {
      id: 'sp-stack-count-t', type: 'transfer', subject: 'spatial', skillIds: ['count-blocks'], familyId: 'stacks', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'กล่องซ้อนกันดังภาพ มีกล่องทั้งหมดกี่กล่อง' },
      visual: { type: 'stack', columns: [3, 3, 1] },
      options: [{ id: 'a', text: '6 กล่อง' }, { id: 'b', text: '7 กล่อง' }, { id: 'c', text: '8 กล่อง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '3 บวก 3 บวก 1 เท่ากับ 7 กล่อง', hints: [], steps: ['แถวแรกมี 3 กล่อง แถวที่สองมี 3 กล่อง แถวที่สามมี 1 กล่อง', '3 บวก 3 บวก 1 เท่ากับ 7'] },
    },
    {
      id: 'sp-fold-star-t', type: 'transfer', subject: 'spatial', skillIds: ['symmetry'], familyId: 'symmetry', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดพับครึ่งตามเส้นประแล้วไม่ทับกันสนิท' },
      options: [fold('a', 'circle'), fold('b', 'lshape'), fold('c', 'star')],
      correctOptionId: 'b',
      narration: 'ตัวเลือกอ่านแค่หมายเลข',
      review: { summary: 'ตัว L พับครึ่งแล้วไม่ทับกันสนิท', hints: [], steps: ['วงกลมและดาว สองซีกของเส้นประเหมือนกัน', 'ตัว L สองซีกไม่เหมือนกัน จึงไม่ทับกันสนิท'] },
    },
    {
      id: 'r-analogy-milk-t', type: 'transfer', subject: 'reasoning', skillIds: ['analogy'], familyId: 'analogy', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'วัวให้นม เป็ดให้อะไร' },
      options: [{ id: 'a', text: 'ผัก' }, { id: 'b', text: 'ไข่' }, { id: 'c', text: 'น้ำ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เป็ดให้ไข่', hints: [], steps: ['วัวให้นม คือสัตว์กับสิ่งที่ได้จากสัตว์', 'เป็ดให้ไข่'] },
    },
    {
      id: 'r-order-numbers-t', type: 'transfer', subject: 'reasoning', skillIds: ['order-numbers'], familyId: 'order-numbers', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เรียงเลขจากมากไปน้อย ข้อใดถูกต้อง' },
      options: [{ id: 'a', text: '9, 7, 5' }, { id: 'b', text: '5, 7, 9' }, { id: 'c', text: '7, 9, 5' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '9 มากที่สุด ตามด้วย 7 แล้ว 5', hints: [], steps: ['เลข 9 มากที่สุด และ 5 น้อยที่สุด', 'เรียงจากมากไปน้อยได้ 9, 7, 5'] },
    },
  ],
};
