/*
 * ชุดที่ 34 — ความปลอดภัยบนถนน (แผ่นรูป Q: design/PROMPTS-gemini-12.md) แบบ 15 ข้อ
 * ช่วง 1: ไฟแดง ไฟเขียว ไฟเหลือง ที่ข้ามถนน (ตัวเลือกเป็นภาพ ใช้ scene: true) ซ้าย-ขวาของรถในภาพ
 * ช่วง 2: หมวกกันน็อก เข็มขัดนิรภัย ภาพที่ไม่ปลอดภัย นับแถบทางม้าลาย เรียงคำเป็นประโยค
 * ช่วง 3: ลำดับสีไฟจราจร สะพานลอย ลูกบอลกลิ้งลงถนน ไฟจราจรใช้ไฟฟ้า ที่ที่ไม่ควรเล่น
 * แต่งใหม่ทั้งหมด; ภาพไฟจราจรบอกว่ารถต้องหยุดหรือไป (ไม่ใช่สัญญาณของคนเดินเท้า)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const ROAD = 'ดูภาพความปลอดภัยบนถนนแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const PICS = 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดความรู้เรื่องความปลอดภัยบนถนน';
const road = (id, name) => ({ id, image: `pic-road-${name}` });
const scene = (name) => ({ type: 'image', asset: `pic-road-${name}` });
const words = (...list) => list.map((text, i) => ({ id: 'abc'[i], text }));

export default {
  id: 'set-34',
  version: 1,
  title: 'ชุดที่ 34',
  note: 'ความปลอดภัยบนถนน ไฟจราจร ทางม้าลาย หมวกกันน็อก เข็มขัดนิรภัย',
  order: [
    'g-road-stop', 'g-road-go', 'g-road-yellow', 'g-road-cross', 'sp-road-car',
    'g-road-helmet', 'g-road-belt', 'g-road-unsafe', 'm-road-stripes', 'th-road-sentence',
    'r-road-cycle', 'g-road-bridge', 'g-road-ball', 'sc-road-light', 'g-road-play',
  ],
  stimuli: {},
  items: [
    // ================================================================ ช่วงที่ 1: ไฟจราจรและที่ข้ามถนน
    {
      id: 'g-road-stop', type: 'main', subject: 'general', skillIds: ['road-safety'], familyId: 'traffic-light', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD, scene: true,
      prompt: { text: 'ภาพใดแสดงว่าไฟจราจรเป็นสีแดง รถต้องหยุดรอ' },
      options: [road('a', 'green'), road('b', 'red'), road('c', 'yellow')],
      correctOptionId: 'b',
      narration: PICS,
      review: {
        summary: 'ไฟสีแดงบอกให้รถหยุดรอ',
        hints: ['ดูว่าหลอดไฟดวงบนสุดสีแดงติดสว่างอยู่ภาพไหน'],
        steps: ['ภาพที่ติดสีเขียวและสีเหลืองไม่ใช่ไฟสีแดง', 'ภาพที่หลอดบนสุดสีแดงติดสว่างคือไฟแดง รถต้องหยุด ตอบข้อ 2'],
        transferIds: ['g-road-stop-t'],
      },
    },
    {
      id: 'g-road-go', type: 'main', subject: 'general', skillIds: ['road-safety'], familyId: 'traffic-light', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD, scene: true,
      prompt: { text: 'ภาพใดแสดงว่าไฟจราจรเป็นสีเขียว รถไปได้' },
      options: [road('a', 'red'), road('b', 'yellow'), road('c', 'green')],
      correctOptionId: 'c',
      narration: PICS,
      review: {
        summary: 'ไฟสีเขียวบอกว่ารถไปได้',
        hints: ['ดูว่าหลอดไฟดวงล่างสุดสีเขียวติดสว่างอยู่ภาพไหน'],
        steps: ['ภาพที่ติดสีแดงให้รถหยุด และสีเหลืองให้ชะลอ', 'ภาพที่หลอดล่างสุดสีเขียวติดสว่างคือไฟเขียว รถไปได้ ตอบข้อ 3'],
        transferIds: ['g-road-go-t'],
      },
    },
    {
      id: 'g-road-yellow', type: 'main', subject: 'general', skillIds: ['road-safety'], familyId: 'traffic-light', difficulty: 2,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'ไฟจราจรสีเหลืองบอกให้ผู้ขับรถทำอย่างไร' },
      visual: scene('yellow'),
      options: words('ชะลอความเร็วและเตรียมหยุดรถ', 'เร่งความเร็วให้ผ่านไปเร็วๆ', 'ถอยรถกลับหลัง'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องความหมายของไฟสีเหลือง',
      review: {
        summary: 'ไฟสีเหลืองให้ชะลอรถและเตรียมหยุด',
        hints: ['ในภาพรถกำลังค่อยๆ ช้าลงใกล้เส้นสีขาว'],
        steps: ['การเร่งรถหรือถอยรถเมื่อไฟเหลืองอันตราย', 'ไฟสีเหลืองให้ชะลอและเตรียมหยุด ตอบข้อ 1'],
        transferIds: ['g-road-yellow-t'],
      },
    },
    {
      id: 'g-road-cross', type: 'main', subject: 'general', skillIds: ['road-safety'], familyId: 'cross-road', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD, scene: true,
      prompt: { text: 'ภาพใดแสดงที่ข้ามถนนของคนเดินเท้าบนพื้นถนน ซึ่งมีแถบสีขาว' },
      options: [road('a', 'helmet'), road('b', 'zebra'), road('c', 'belt')],
      correctOptionId: 'b',
      narration: PICS,
      review: {
        summary: 'ทางม้าลายเป็นแถบสีขาวบนถนน ให้คนเดินข้าม',
        hints: ['ดูภาพที่มีแถบสีขาวหลายแถบบนพื้นถนน'],
        steps: ['ภาพหมวกกันน็อกและเข็มขัดนิรภัยไม่ใช่ที่ข้ามถนน', 'ทางม้าลายมีแถบสีขาวบนถนน ตอบข้อ 2'],
        transferIds: ['g-road-cross-t'],
      },
    },
    {
      id: 'sp-road-car', type: 'main', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 2,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'ในภาพไฟเขียว รถสีฟ้าอยู่ทางด้านใดของภาพ' },
      visual: scene('green'),
      options: words('ทางซ้ายมือของภาพ', 'ทางขวามือของภาพ', 'ตรงกลางของภาพ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบอกตำแหน่งซ้ายขวาในภาพ (ซ้ายขวาของภาพ ไม่ใช่ของรถ)',
      review: {
        summary: 'รถสีฟ้าอยู่ทางขวามือของภาพ',
        hints: ['มองภาพ แล้วดูว่ารถสีฟ้าอยู่ด้านซ้ายหรือด้านขวามือของเรา'],
        steps: ['รถสีเขียวอยู่ทางซ้ายของภาพ', 'รถสีฟ้าอยู่ทางขวาของภาพ ตอบข้อ 2'],
        transferIds: ['sp-road-car-t'],
      },
    },

    // ================================================================ ช่วงที่ 2
    {
      id: 'g-road-helmet', type: 'main', subject: 'general', skillIds: ['road-safety'], familyId: 'safety-gear', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'เหตุใดจึงต้องสวมหมวกกันน็อกเมื่อนั่งรถจักรยานยนต์' },
      visual: scene('helmet'),
      options: words('เพื่อป้องกันศีรษะเมื่อเกิดอุบัติเหตุ', 'เพื่อให้ดูสวยงามเท่านั้น', 'เพื่อกันฝนเท่านั้น'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจเหตุผลของการสวมหมวกกันน็อก',
      review: {
        summary: 'หมวกกันน็อกป้องกันศีรษะเมื่อเกิดอุบัติเหตุ',
        hints: ['ศีรษะของเรามีสมอง เป็นส่วนที่ต้องปกป้อง'],
        steps: ['หมวกกันน็อกไม่ได้มีไว้เพื่อความสวยงามหรือกันฝนเท่านั้น', 'มีไว้ป้องกันศีรษะเมื่อเกิดอุบัติเหตุ ตอบข้อ 1'],
        transferIds: ['g-road-helmet-t'],
      },
    },
    {
      id: 'g-road-belt', type: 'main', subject: 'general', skillIds: ['road-safety'], familyId: 'safety-gear', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'เหตุใดจึงต้องคาดเข็มขัดนิรภัยเมื่อนั่งรถยนต์' },
      visual: scene('belt'),
      options: words('เพื่อให้รถวิ่งเร็วขึ้น', 'เพื่อป้องกันตัวเราเมื่อรถหยุดกะทันหัน', 'เพื่อให้นั่งได้นานขึ้น'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจเหตุผลของการคาดเข็มขัดนิรภัย',
      review: {
        summary: 'เข็มขัดนิรภัยยึดตัวเราไว้ ไม่ให้พุ่งไปข้างหน้าเมื่อรถหยุดกะทันหัน',
        hints: ['นึกว่าถ้ารถเบรกแรงๆ ตัวเราจะเป็นอย่างไร'],
        steps: ['เข็มขัดนิรภัยไม่ได้ทำให้รถเร็วขึ้นหรือทำให้นั่งนานขึ้น', 'ช่วยป้องกันตัวเราเมื่อรถหยุดกะทันหัน ตอบข้อ 2'],
        transferIds: ['g-road-belt-t'],
      },
    },
    {
      id: 'g-road-unsafe', type: 'main', subject: 'general', skillIds: ['safety'], familyId: 'safe-unsafe', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD, scene: true,
      prompt: { text: 'ภาพใดเป็นเหตุการณ์ที่ไม่ปลอดภัย' },
      options: [road('a', 'zebra'), road('b', 'helmet'), road('c', 'ball')],
      correctOptionId: 'c',
      narration: PICS,
      review: {
        summary: 'เด็กที่วิ่งตามลูกบอลลงถนนไม่ปลอดภัย เพราะอาจมีรถมา',
        hints: ['ดูภาพที่เด็กกำลังจะวิ่งลงไปบนถนน'],
        steps: ['ภาพทางม้าลายและหมวกกันน็อกเป็นการระวังความปลอดภัย', 'ภาพเด็กวิ่งตามลูกบอลลงถนนไม่ปลอดภัย ตอบข้อ 3'],
        transferIds: ['g-road-unsafe-t'],
      },
    },
    {
      id: 'm-road-stripes', type: 'main', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'word-problem-sub', difficulty: 2,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'ทางม้าลายมีแถบสีขาว 7 แถบ เด็กหญิงเดินข้ามไปแล้ว 3 แถบ เหลืออีกกี่แถบ' },
      visual: scene('zebra'),
      options: words('3 แถบ', '4 แถบ', '5 แถบ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดโจทย์ลบ (ข้ามไปแล้วเอาออกจากทั้งหมด)',
      review: {
        summary: '7 ลบ 3 เท่ากับ 4 แถบ',
        hints: ['เหลืออีกเท่าไรคือเอาที่ข้ามไปแล้วออกจากทั้งหมด'],
        steps: ['ทั้งหมดมี 7 แถบ ข้ามไปแล้ว 3 แถบ ต้องเอา 3 ออกจาก 7', '7 ลบ 3 เท่ากับ 4 ตอบข้อ 2'],
        column: { a: 7, op: '-', b: 3 },
        transferIds: ['m-road-stripes-t'],
      },
    },
    {
      id: 'th-road-sentence', type: 'main', subject: 'thai', skillIds: ['sentence-type'], familyId: 'sentence-order', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ข้อใดเรียงคำเป็นประโยคได้ถูกต้อง' },
      options: words('ข้ามถนนต้องดูรถ', 'ต้องข้ามถนนดูรถ', 'ดูถนนข้ามรถต้อง'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงคำเป็นประโยค',
      review: {
        summary: 'ข้ามถนนต้องดูรถ เรียงเป็นประโยคที่มีความหมาย',
        hints: ['ประโยคต้องอ่านแล้วเข้าใจว่าต้องทำอะไรเมื่อข้ามถนน'],
        steps: ['ต้องข้ามถนนดูรถ และดูถนนข้ามรถต้อง อ่านแล้วสับสน', 'ข้ามถนนต้องดูรถ อ่านแล้วเข้าใจ ตอบข้อ 1'],
        transferIds: ['th-road-sentence-t'],
      },
    },

    // ================================================================ ช่วงที่ 3
    {
      id: 'r-road-cycle', type: 'main', subject: 'reasoning', skillIds: ['pattern-continue'], familyId: 'pattern-cycle', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ไฟจราจรเปลี่ยนสีวนไปเรื่อยๆ เป็น เขียว เหลือง แดง เขียว เหลือง แดง ถัดจากสีแดงตัวสุดท้ายคือสีอะไร' },
      options: words('สีเหลือง', 'สีแดง', 'สีเขียว'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการต่อรูปแบบที่วนซ้ำ',
      review: {
        summary: 'ลำดับวนซ้ำ เขียว เหลือง แดง ต่อจากแดงจึงกลับมาเป็นเขียว',
        hints: ['สามสีเรียงซ้ำกันเป็นชุดๆ ชุดใหม่เริ่มด้วยสีเขียว'],
        steps: ['แต่ละชุดเรียง เขียว เหลือง แดง แล้วขึ้นชุดใหม่', 'ต่อจากสีแดงคือสีเขียว ตอบข้อ 3'],
        transferIds: ['r-road-cycle-t'],
      },
    },
    {
      id: 'g-road-bridge', type: 'main', subject: 'general', skillIds: ['road-safety'], familyId: 'cross-road', difficulty: 2,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'สะพานลอยมีไว้เพื่ออะไร' },
      visual: scene('bridge'),
      options: words('ให้คนเดินข้ามถนนที่รถวิ่งเร็วได้อย่างปลอดภัย', 'ให้รถจอดบนสะพาน', 'ให้เด็กวิ่งไล่จับกัน'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสะพานลอย',
      review: {
        summary: 'สะพานลอยให้คนเดินข้ามถนนโดยไม่ต้องเดินบนถนน',
        hints: ['ดูว่าคนในภาพเดินอยู่ตรงไหน และรถวิ่งอยู่ตรงไหน'],
        steps: ['สะพานลอยไม่ใช่ที่จอดรถ และไม่ใช่ที่วิ่งเล่น', 'คนเดินข้ามถนนบนสะพานได้อย่างปลอดภัย ตอบข้อ 1'],
        transferIds: ['g-road-bridge-t'],
      },
    },
    {
      id: 'g-road-ball', type: 'main', subject: 'general', skillIds: ['safety'], familyId: 'safe-unsafe', difficulty: 2,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'ถ้าลูกบอลกลิ้งลงไปบนถนน เด็กควรทำอย่างไร' },
      visual: scene('ball'),
      options: words('วิ่งตามไปเก็บทันที', 'บอกผู้ใหญ่ให้ช่วยเก็บ', 'ยืนรอบนถนนให้รถหยุด'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการตัดสินใจอย่างปลอดภัย',
      review: {
        summary: 'บอกผู้ใหญ่ให้ช่วยเก็บลูกบอล ไม่วิ่งลงถนนเอง',
        hints: ['ถนนมีรถวิ่ง เด็กไม่ควรลงไปเองเพียงคนเดียว'],
        steps: ['การวิ่งตามหรือยืนรอบนถนนอันตราย อาจถูกรถชน', 'บอกผู้ใหญ่ให้ช่วยเก็บจึงปลอดภัย ตอบข้อ 2'],
        transferIds: ['g-road-ball-t'],
      },
    },
    {
      id: 'sc-road-light', type: 'main', subject: 'science', skillIds: ['electricity'], familyId: 'electricity', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ไฟจราจรติดสว่างได้เพราะมีสิ่งใด' },
      options: words('ลม', 'น้ำ', 'ไฟฟ้า'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องไฟฟ้า',
      review: {
        summary: 'ไฟจราจรติดสว่างได้เพราะใช้ไฟฟ้า',
        hints: ['หลอดไฟต้องมีพลังงานชนิดเดียวกับไฟที่บ้าน'],
        steps: ['ลมและน้ำไม่ทำให้หลอดไฟติดสว่าง', 'ไฟฟ้าทำให้ไฟจราจรติดสว่าง ตอบข้อ 3'],
        transferIds: ['sc-road-light-t'],
      },
    },
    {
      id: 'g-road-play', type: 'main', subject: 'general', skillIds: ['safety'], familyId: 'safe-unsafe', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ที่ใดไม่ควรเล่นเด็ดขาดเพราะอันตราย' },
      options: words('กลางถนน', 'สนามเด็กเล่น', 'สวนสาธารณะ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการเลือกที่เล่นที่ปลอดภัย',
      review: {
        summary: 'กลางถนนมีรถวิ่ง ไม่ควรเล่น',
        hints: ['ที่ไหนมีรถวิ่งผ่านไปมา'],
        steps: ['สนามเด็กเล่นและสวนสาธารณะเป็นที่เล่นที่ปลอดภัย', 'กลางถนนมีรถวิ่ง ไม่ควรเล่น ตอบข้อ 1'],
        transferIds: ['g-road-play-t'],
      },
    },

    // ================================================================ โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'g-road-stop-t', type: 'transfer', subject: 'general', skillIds: ['road-safety'], familyId: 'traffic-light', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD, scene: true,
      prompt: { text: 'ภาพใดแสดงว่าไฟจราจรเป็นสีเหลือง รถต้องชะลอและเตรียมหยุด' },
      options: [road('a', 'red'), road('b', 'yellow'), road('c', 'green')],
      correctOptionId: 'b',
      narration: PICS,
      review: { summary: 'ไฟสีเหลืองให้ชะลอและเตรียมหยุด', hints: [], steps: ['ไฟสีแดงให้หยุด และสีเขียวให้ไป', 'หลอดกลางสีเหลืองติดสว่างคือไฟเหลือง'] },
    },
    {
      id: 'g-road-go-t', type: 'transfer', subject: 'general', skillIds: ['road-safety'], familyId: 'traffic-light', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD, scene: true,
      prompt: { text: 'ภาพใดแสดงว่าไฟจราจรเป็นสีแดง' },
      options: [road('a', 'green'), road('b', 'yellow'), road('c', 'red')],
      correctOptionId: 'c',
      narration: PICS,
      review: { summary: 'ไฟสีแดงติดที่หลอดบนสุด', hints: [], steps: ['ไฟสีเขียวอยู่ล่างสุด และสีเหลืองอยู่กลาง', 'หลอดบนสุดสีแดงติดสว่างคือไฟแดง'] },
    },
    {
      id: 'g-road-yellow-t', type: 'transfer', subject: 'general', skillIds: ['road-safety'], familyId: 'traffic-light', difficulty: 2,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'ไฟจราจรสีแดงบอกให้ผู้ขับรถทำอย่างไร' },
      visual: scene('red'),
      options: words('ขับต่อไปเร็วๆ', 'หยุดรถรอที่เส้นสีขาว', 'บีบแตรเสียงดัง'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไฟสีแดงให้หยุดรถรอที่เส้นสีขาว', hints: [], steps: ['การขับต่อหรือบีบแตรไม่ช่วยให้ปลอดภัย', 'ไฟแดงต้องหยุดรอที่เส้นสีขาว'] },
    },
    {
      id: 'g-road-cross-t', type: 'transfer', subject: 'general', skillIds: ['road-safety'], familyId: 'cross-road', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD, scene: true,
      prompt: { text: 'ภาพใดแสดงที่ข้ามถนนบนอากาศ ซึ่งมีบันไดและหลังคา' },
      options: [road('a', 'bridge'), road('b', 'zebra'), road('c', 'ball')],
      correctOptionId: 'a',
      narration: PICS,
      review: { summary: 'สะพานลอยอยู่เหนือถนน มีบันไดและหลังคา', hints: [], steps: ['ทางม้าลายอยู่บนพื้นถนน และภาพลูกบอลไม่ใช่ที่ข้ามถนน', 'สะพานลอยอยู่เหนือถนน'] },
    },
    {
      id: 'sp-road-car-t', type: 'transfer', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 2,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'ในภาพไฟเขียว รถสีเขียวอยู่ทางด้านใดของภาพ' },
      visual: scene('green'),
      options: words('ทางขวามือของภาพ', 'ตรงกลางของภาพ', 'ทางซ้ายมือของภาพ'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'รถสีเขียวอยู่ทางซ้ายมือของภาพ', hints: [], steps: ['รถสีฟ้าอยู่ทางขวาของภาพ', 'รถสีเขียวอยู่ทางซ้ายของภาพ'] },
    },
    {
      id: 'g-road-helmet-t', type: 'transfer', subject: 'general', skillIds: ['road-safety'], familyId: 'safety-gear', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'ผู้ขับขี่และเด็กที่นั่งซ้อนรถจักรยานยนต์ต้องสวมอะไร' },
      visual: scene('helmet'),
      options: words('หมวกแก๊ป', 'หมวกกันน็อก', 'หมวกสานกันแดด'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ต้องสวมหมวกกันน็อกและรัดสายคางให้แน่น', hints: [], steps: ['หมวกแก๊ปและหมวกสานกันแดดไม่ช่วยป้องกันศีรษะเมื่อเกิดอุบัติเหตุ', 'หมวกกันน็อกป้องกันศีรษะได้'] },
    },
    {
      id: 'g-road-belt-t', type: 'transfer', subject: 'general', skillIds: ['road-safety'], familyId: 'safety-gear', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'เด็กที่นั่งในรถยนต์ควรนั่งอย่างไร' },
      visual: scene('belt'),
      options: words('ยืนบนเบาะ', 'นั่งและคาดเข็มขัดนิรภัย', 'โผล่หัวออกนอกหน้าต่าง'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เด็กควรนั่งและคาดเข็มขัดนิรภัย', hints: [], steps: ['การยืนบนเบาะและโผล่หัวออกนอกหน้าต่างอันตราย', 'การนั่งและคาดเข็มขัดนิรภัยปลอดภัย'] },
    },
    {
      id: 'g-road-unsafe-t', type: 'transfer', subject: 'general', skillIds: ['safety'], familyId: 'safe-unsafe', difficulty: 1,
      sourceId: SRC, ...R, section: ROAD, scene: true,
      prompt: { text: 'ภาพใดเป็นเหตุการณ์ที่ไม่ปลอดภัย' },
      options: [road('a', 'belt'), road('b', 'ball'), road('c', 'bridge')],
      correctOptionId: 'b',
      narration: PICS,
      review: { summary: 'เด็กวิ่งตามลูกบอลลงถนนไม่ปลอดภัย', hints: [], steps: ['ภาพเข็มขัดนิรภัยและสะพานลอยเป็นการระวังความปลอดภัย', 'ภาพเด็กวิ่งตามลูกบอลลงถนนไม่ปลอดภัย'] },
    },
    {
      id: 'm-road-stripes-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'word-problem-sub', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ทางม้าลายมีแถบสีขาว 8 แถบ เด็กๆ เดินข้ามไปแล้ว 5 แถบ เหลืออีกกี่แถบ' },
      options: words('2 แถบ', '3 แถบ', '4 แถบ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '8 ลบ 5 เท่ากับ 3 แถบ', hints: [], steps: ['ทั้งหมด 8 แถบ ข้ามไปแล้ว 5 แถบ ต้องเอา 5 ออกจาก 8', '8 ลบ 5 เท่ากับ 3'], column: { a: 8, op: '-', b: 5 } },
    },
    {
      id: 'th-road-sentence-t', type: 'transfer', subject: 'thai', skillIds: ['sentence-type'], familyId: 'sentence-order', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ข้อใดเรียงคำเป็นประโยคได้ถูกต้อง' },
      options: words('ใส่หมวกกันน็อกต้อง', 'ต้องใส่หมวกกันน็อก', 'กันน็อกหมวกต้องใส่'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ต้องใส่หมวกกันน็อก เรียงเป็นประโยคที่มีความหมาย', hints: [], steps: ['ใส่หมวกกันน็อกต้อง และกันน็อกหมวกต้องใส่ อ่านแล้วสับสน', 'ต้องใส่หมวกกันน็อก อ่านแล้วเข้าใจ'] },
    },
    {
      id: 'r-road-cycle-t', type: 'transfer', subject: 'reasoning', skillIds: ['pattern-continue'], familyId: 'pattern-cycle', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ไฟจราจรเปลี่ยนสีวนไปเรื่อยๆ เป็น เขียว เหลือง แดง เขียว เหลือง แดง ถัดจากสีเขียวตัวสุดท้ายคือสีอะไร' },
      options: words('สีแดง', 'สีเหลือง', 'สีฟ้า'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ต่อจากสีเขียวคือสีเหลือง', hints: [], steps: ['แต่ละชุดเรียง เขียว เหลือง แดง', 'ต่อจากเขียวคือเหลือง'] },
    },
    {
      id: 'g-road-bridge-t', type: 'transfer', subject: 'general', skillIds: ['road-safety'], familyId: 'cross-road', difficulty: 2,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'ทางม้าลายมีไว้เพื่ออะไร' },
      visual: scene('zebra'),
      options: words('ให้รถจอดทิ้งไว้', 'ให้เด็กวิ่งเล่น', 'ให้คนเดินข้ามถนนได้อย่างปลอดภัย'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ทางม้าลายให้คนเดินข้ามถนนได้อย่างปลอดภัย', hints: [], steps: ['ทางม้าลายไม่ใช่ที่จอดรถและไม่ใช่ที่วิ่งเล่น', 'เป็นที่ข้ามถนนของคนเดินเท้า'] },
    },
    {
      id: 'g-road-ball-t', type: 'transfer', subject: 'general', skillIds: ['safety'], familyId: 'safe-unsafe', difficulty: 2,
      sourceId: SRC, ...R, section: ROAD,
      prompt: { text: 'ถ้าเห็นเพื่อนจะวิ่งตามลูกบอลออกไปบนถนน เราควรทำอย่างไร' },
      visual: scene('ball'),
      options: words('วิ่งตามเพื่อนไปด้วย', 'ปล่อยให้เพื่อนวิ่งไป', 'ร้องเตือนเพื่อนให้หยุดและเรียกผู้ใหญ่'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ร้องเตือนเพื่อนให้หยุดและเรียกผู้ใหญ่มาช่วย', hints: [], steps: ['การวิ่งตามไปหรือปล่อยให้เพื่อนวิ่งไปอันตราย', 'ร้องเตือนและเรียกผู้ใหญ่ช่วยให้ปลอดภัย'] },
    },
    {
      id: 'sc-road-light-t', type: 'transfer', subject: 'science', skillIds: ['electricity'], familyId: 'electricity', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ตอนกลางคืนเรามองเห็นไฟจราจรได้ เพราะเหตุใด' },
      options: words('เพราะไฟจราจรมีหลอดไฟที่ติดสว่างด้วยไฟฟ้า', 'เพราะดวงอาทิตย์ส่องสว่าง', 'เพราะมีรุ้งอยู่บนท้องฟ้า'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไฟจราจรใช้หลอดไฟและมีไฟฟ้าทำให้ติดสว่าง', hints: [], steps: ['กลางคืนไม่มีดวงอาทิตย์ และรุ้งเกิดตอนกลางวัน', 'ไฟจราจรติดสว่างด้วยไฟฟ้า'] },
    },
    {
      id: 'g-road-play-t', type: 'transfer', subject: 'general', skillIds: ['safety'], familyId: 'safe-unsafe', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดเป็นการข้ามถนนที่ปลอดภัย' },
      options: words('วิ่งข้ามระหว่างรถที่จอดอยู่', 'ข้ามตรงทางโค้งโดยไม่ดูรถ', 'ข้ามที่ทางม้าลายและจับมือผู้ใหญ่'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ข้ามที่ทางม้าลายและจับมือผู้ใหญ่ปลอดภัยที่สุด', hints: [], steps: ['การวิ่งข้ามระหว่างรถและข้ามตรงทางโค้งอันตราย', 'ข้ามที่ทางม้าลายและจับมือผู้ใหญ่ปลอดภัย'] },
    },
  ],
};
