/*
 * ชุดที่ 33 — สัตว์กับลูกสัตว์ (แผ่นรูป P: design/PROMPTS-gemini-12.md) แบบ 15 ข้อ
 * ช่วง 1 แผ่นภาพสัตว์ 12 ภาพ (วัว ลูกวัว สุนัข ลูกสุนัข แมว ลูกแมว เป็ด ลูกเป็ด หมู ลูกหมู แกะ ลูกแกะ) ถาม 5 ข้อ:
 *        ลูกของวัว แม่ของลูกสุนัข สัตว์ที่ออกไข่ ขนแกะ นับแม่ลูกกี่คู่ (ตอบเป็นภาพ 4 ข้อ)
 * ช่วง 2 ข้อเดี่ยว: เสียงร้อง อาหารของวัว นับขา ซ้าย-ขวาของแม่ลูกแมว จับคู่แม่กับลูก
 * ช่วง 3 ข้อเดี่ยว: นมวัว สุนัขเฝ้าบ้าน พยัญชนะต้นของ แกะ ลูกหมูของแม่หมู 2 ตัว ชื่อสัตว์เลี้ยง
 * แต่งใหม่ทั้งหมด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const ANIMALS = 'ดูภาพสัตว์แล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const PICS = 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดความรู้เรื่องสัตว์และลูกสัตว์';
const animal = (id, name) => ({ id, image: `pic-animal-${name}` });
const one = (name) => ({ type: 'image', asset: `pic-animal-${name}` });
const words = (...list) => list.map((text, i) => ({ id: 'abc'[i], text }));
const letters = (...list) => list.map((text, i) => ({ id: 'abc'[i], text, speech: '' }));
const BOARD = { type: 'board', items: ['cow', 'calf', 'dog', 'puppy', 'cat', 'kitten', 'duck', 'duckling', 'pig', 'piglet', 'sheep', 'lamb'].map((n) => `pic-animal-${n}`) };
const BOARD_TEXT = 'ในภาพมีสัตว์ 12 ภาพ คือ วัว ลูกวัว สุนัข ลูกสุนัข แมว ลูกแมว เป็ด ลูกเป็ด หมู ลูกหมู แกะ และลูกแกะ ดูภาพแล้วตอบคำถาม';

export default {
  id: 'set-33',
  version: 1,
  title: 'ชุดที่ 33',
  note: 'สัตว์กับลูกสัตว์ วัว สุนัข แมว เป็ด หมู แกะ',
  order: [
    'sc-animal-calf', 'g-animal-mother', 'sc-animal-egg', 'sc-animal-wool', 'm-animal-pairs',
    'g-animal-sound', 'sc-animal-cowfood', 'm-animal-legsfarm', 'sp-animal-right', 'r-animal-pair',
    'sc-animal-milk', 'g-animal-guard', 'th-animal-initial', 'm-animal-piglets', 'th-animal-words',
  ],
  stimuli: {
    board: { section: ANIMALS, text: BOARD_TEXT, visual: BOARD },
  },
  items: [
    // ================================================================ ช่วงที่ 1: แผ่นภาพสัตว์
    {
      id: 'sc-animal-calf', type: 'main', subject: 'science', skillIds: ['animal-babies'], familyId: 'animal-babies', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'board',
      prompt: { text: 'ภาพใดเป็นลูกของวัว' },
      options: [animal('a', 'puppy'), animal('b', 'kitten'), animal('c', 'calf'), animal('d', 'duckling')],
      correctOptionId: 'c',
      narration: PICS,
      review: {
        summary: 'ลูกของวัวเรียกว่าลูกวัว มีลายสีน้ำตาลขาวเหมือนแม่',
        hints: ['ดูลูกสัตว์ที่ลายสีน้ำตาลขาวเหมือนวัว'],
        steps: ['ลูกสุนัข ลูกแมว และลูกเป็ดเป็นลูกของสัตว์ชนิดอื่น', 'ลูกวัวมีลายสีน้ำตาลขาวเหมือนแม่ ตอบข้อ 3'],
        transferIds: ['sc-animal-calf-t'],
      },
    },
    {
      id: 'g-animal-mother', type: 'main', subject: 'general', skillIds: ['animal-babies'], familyId: 'animal-babies', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'board',
      prompt: { text: 'ภาพใดเป็นแม่ของลูกสุนัข' },
      options: [animal('a', 'cat'), animal('b', 'dog'), animal('c', 'pig'), animal('d', 'sheep')],
      correctOptionId: 'b',
      narration: PICS,
      review: {
        summary: 'แม่ของลูกสุนัขคือสุนัข สีขนเหมือนกัน',
        hints: ['ดูสัตว์ที่ขนสีน้ำตาลทองเหมือนลูกสุนัข'],
        steps: ['แมว หมู และแกะเป็นแม่ของลูกสัตว์ชนิดอื่น', 'สุนัขขนสีน้ำตาลทองเหมือนลูกสุนัข ตอบข้อ 2'],
        transferIds: ['g-animal-mother-t'],
      },
    },
    {
      id: 'sc-animal-egg', type: 'main', subject: 'science', skillIds: ['animal-features'], familyId: 'animal-features', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'board',
      prompt: { text: 'ภาพใดเป็นสัตว์ที่ออกลูกเป็นไข่' },
      options: [animal('a', 'duck'), animal('b', 'pig'), animal('c', 'sheep')],
      correctOptionId: 'a',
      narration: PICS,
      review: {
        summary: 'เป็ดออกไข่ ส่วนหมูและแกะออกลูกเป็นตัว',
        hints: ['ลูกเป็ดฟักออกมาจากไข่'],
        steps: ['หมูและแกะออกลูกเป็นตัวและให้นมลูก', 'เป็ดออกไข่แล้วฟักเป็นลูกเป็ด ตอบข้อ 1'],
        transferIds: ['sc-animal-egg-t'],
      },
    },
    {
      id: 'sc-animal-wool', type: 'main', subject: 'science', skillIds: ['animal-uses'], familyId: 'animal-uses', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'board',
      prompt: { text: 'ภาพใดเป็นสัตว์ที่มีขนฟู นำขนไปทอเป็นผ้าห่มและเสื้อกันหนาวได้' },
      options: [animal('a', 'cat'), animal('b', 'sheep'), animal('c', 'cow')],
      correctOptionId: 'b',
      narration: PICS,
      review: {
        summary: 'ขนแกะนำไปทอเป็นผ้าห่มและเสื้อกันหนาว',
        hints: ['ดูสัตว์ที่ขนหนาฟูเป็นก้อนๆ'],
        steps: ['ขนแมวและขนวัวสั้นไม่นิยมนำไปทอผ้า', 'ขนแกะหนาฟู นำไปทอผ้าได้ ตอบข้อ 2'],
        transferIds: ['sc-animal-wool-t'],
      },
    },
    {
      id: 'm-animal-pairs', type: 'main', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'board',
      prompt: { text: 'ในภาพมีแม่ลูกสัตว์กี่คู่' },
      options: words('4 คู่', '6 คู่', '12 คู่'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับแม่ลูกเป็นคู่',
      review: {
        summary: 'มีแม่ลูก 6 คู่ คือ วัว สุนัข แมว เป็ด หมู และแกะ',
        hints: ['สัตว์ใหญ่ 1 ตัวกับลูกของมัน 1 ตัว นับเป็น 1 คู่'],
        steps: ['ในภาพมีสัตว์ทั้งหมด 12 ภาพ จับคู่แม่กับลูก คู่ละ 2 ภาพ', '12 แบ่งเป็นคู่ได้ 6 คู่ ตอบข้อ 2'],
        transferIds: ['m-animal-pairs-t'],
      },
    },

    // ================================================================ ช่วงที่ 2: ข้อเดี่ยว
    {
      id: 'g-animal-sound', type: 'main', subject: 'general', skillIds: ['animal-sounds'], familyId: 'animal-sounds', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'สุนัขส่งเสียงร้องว่าอย่างไร' },
      visual: one('dog'),
      options: words('โฮ่งๆ', 'เหมียวๆ', 'ก้าบๆ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องเสียงร้องของสัตว์',
      review: {
        summary: 'สุนัขร้อง โฮ่งๆ',
        hints: ['นึกถึงเสียงสุนัขเห่า'],
        steps: ['เหมียวๆ เป็นเสียงแมว และ ก้าบๆ เป็นเสียงเป็ด', 'สุนัขเห่า โฮ่งๆ ตอบข้อ 1'],
        transferIds: ['g-animal-sound-t'],
      },
    },
    {
      id: 'sc-animal-cowfood', type: 'main', subject: 'science', skillIds: ['animal-food'], familyId: 'animal-food', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'วัวกินอะไรเป็นอาหาร' },
      visual: one('cow'),
      options: words('เนื้อสัตว์', 'ปลา', 'หญ้า'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องอาหารของสัตว์',
      review: {
        summary: 'วัวกินหญ้าเป็นอาหาร',
        hints: ['นึกถึงวัวที่เล็มอยู่ในทุ่งหญ้า'],
        steps: ['วัวไม่กินเนื้อสัตว์และไม่กินปลา', 'วัวกินหญ้า ตอบข้อ 3'],
        transferIds: ['sc-animal-cowfood-t'],
      },
    },
    {
      id: 'm-animal-legsfarm', type: 'main', subject: 'math', skillIds: ['count-legs'], familyId: 'count-legs', difficulty: 3,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'ในคอกมีสุนัข 2 ตัว และเป็ด 2 ตัว รวมมีขากี่ขา' },
      options: words('8 ขา', '12 ขา', '16 ขา'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับขาสองขั้น (สุนัข 4 ขา เป็ด 2 ขา)',
      review: {
        summary: 'สุนัข 2 ตัวมี 8 ขา เป็ด 2 ตัวมี 4 ขา รวม 12 ขา',
        hints: ['สุนัขมี 4 ขา เป็ดมี 2 ขา นับแยกแล้วค่อยบวกกัน'],
        steps: ['สุนัข 2 ตัว ตัวละ 4 ขา เป็น 4 บวก 4 เท่ากับ 8 ขา เป็ด 2 ตัว ตัวละ 2 ขา เป็น 2 บวก 2 เท่ากับ 4 ขา', '8 บวก 4 เท่ากับ 12 ตอบข้อ 2'],
        column: { a: 8, op: '+', b: 4 },
        transferIds: ['m-animal-legsfarm-t'],
      },
    },
    {
      id: 'sp-animal-right', type: 'main', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 2,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'ในภาพ ลูกแมวอยู่ทางด้านใดของแม่แมว' },
      visual: { type: 'row', items: ['pic-animal-cat', 'pic-animal-kitten'] },
      options: words('ทางขวาของแม่แมว', 'ทางซ้ายของแม่แมว', 'ใต้ท้องแม่แมว'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการบอกตำแหน่งซ้ายขวาในภาพ',
      review: {
        summary: 'ลูกแมวอยู่ทางขวามือของแม่แมวในภาพ',
        hints: ['มองภาพ แล้วดูว่าแม่แมวอยู่ซ้ายและลูกแมวอยู่ด้านใด'],
        steps: ['แม่แมวตัวใหญ่อยู่ทางซ้ายของภาพ', 'ลูกแมวตัวเล็กอยู่ทางขวา ไม่ได้อยู่ใต้ท้องแม่ ตอบข้อ 1'],
        transferIds: ['sp-animal-right-t'],
      },
    },
    {
      id: 'r-animal-pair', type: 'main', subject: 'reasoning', skillIds: ['relationship'], familyId: 'animal-babies-words', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ข้อใดจับคู่แม่กับลูกได้ถูกต้อง' },
      options: words('วัวกับลูกแกะ', 'เป็ดกับลูกแมว', 'หมูกับลูกหมู'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการจับคู่แม่กับลูกของสัตว์ชนิดเดียวกัน',
      review: {
        summary: 'แม่หมูคู่กับลูกหมู เป็นสัตว์ชนิดเดียวกัน',
        hints: ['แม่กับลูกต้องเป็นสัตว์ชนิดเดียวกัน'],
        steps: ['วัวกับลูกแกะ และเป็ดกับลูกแมว เป็นสัตว์คนละชนิดกัน', 'หมูกับลูกหมูเป็นชนิดเดียวกัน ตอบข้อ 3'],
        transferIds: ['r-animal-pair-t'],
      },
    },

    // ================================================================ ช่วงที่ 3
    {
      id: 'sc-animal-milk', type: 'main', subject: 'science', skillIds: ['animal-uses'], familyId: 'animal-uses', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'สัตว์ในข้อใดให้นมที่คนนำมาดื่ม' },
      options: words('ไก่', 'ปลา', 'วัว'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องประโยชน์ของสัตว์ (นมวัว)',
      review: {
        summary: 'แม่วัวให้นม คนนำนมวัวมาดื่ม',
        hints: ['นมกล่องที่เราดื่มมาจากสัตว์อะไร'],
        steps: ['ไก่ให้ไข่ และปลาเป็นอาหาร ไม่ได้ให้นม', 'วัวให้นมที่คนนำมาดื่ม ตอบข้อ 3'],
        transferIds: ['sc-animal-milk-t'],
      },
    },
    {
      id: 'g-animal-guard', type: 'main', subject: 'general', skillIds: ['pets'], familyId: 'pets', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'สัตว์เลี้ยงในข้อใดช่วยเฝ้าบ้านและเห่าเตือนเมื่อมีคนแปลกหน้า' },
      options: words('แมว', 'สุนัข', 'เป็ด'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสัตว์เลี้ยง',
      review: {
        summary: 'สุนัขช่วยเฝ้าบ้านและเห่าเตือน',
        hints: ['สัตว์ชนิดไหนส่งเสียงเห่า'],
        steps: ['แมวและเป็ดไม่ได้เห่าเตือน', 'สุนัขเฝ้าบ้านและเห่าเตือน ตอบข้อ 2'],
        transferIds: ['g-animal-guard-t'],
      },
    },
    {
      id: 'th-animal-initial', type: 'main', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ภาพนี้คือ แกะ คำว่า แกะ ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: one('sheep'),
      options: letters('ม', 'ก', 'ข'),
      correctOptionId: 'b',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก เด็กต้องรู้จักตัวอักษรเอง',
      review: {
        summary: 'แกะ ขึ้นต้นด้วย กอ ไก่',
        hints: ['ออกเสียงคำว่า แกะ ช้าๆ'],
        steps: ['ออกเสียง แกะ ขึ้นต้นด้วยเสียง กอ', 'ตัวอักษรเสียงกอคือ กอ ไก่ ตอบข้อ 2'],
        transferIds: ['th-animal-initial-t'],
      },
    },
    {
      id: 'm-animal-piglets', type: 'main', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'แม่หมูแต่ละตัวมีลูก 3 ตัว ถ้ามีแม่หมู 2 ตัว จะมีลูกหมูรวมกันกี่ตัว' },
      options: words('6 ตัว', '5 ตัว', '7 ตัว'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการบวกซ้ำ',
      review: {
        summary: 'แม่หมู 2 ตัว มีลูกหมู 3 บวก 3 เท่ากับ 6 ตัว',
        hints: ['แม่หมูตัวแรกมีลูก 3 ตัว แม่หมูอีกตัวมีลูก 3 ตัว เอามาบวกกัน'],
        steps: ['แม่หมูตัวที่ 1 มีลูก 3 ตัว แม่หมูตัวที่ 2 มีลูกอีก 3 ตัว', '3 บวก 3 เท่ากับ 6 ตอบข้อ 1'],
        column: { a: 3, op: '+', b: 3 },
        transferIds: ['m-animal-piglets-t'],
      },
    },
    {
      id: 'th-animal-words', type: 'main', subject: 'thai', skillIds: ['classify-words'], familyId: 'classify-words', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ข้อใดเป็นชื่อสัตว์เลี้ยงทั้งหมด' },
      options: words('หมู วัว แกะ', 'หมู โต๊ะ แกะ', 'เก้าอี้ วัว แกะ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการแยกคำที่เป็นสัตว์ออกจากสิ่งของ',
      review: {
        summary: 'หมู วัว แกะ เป็นสัตว์เลี้ยงทั้งหมด',
        hints: ['ดูว่าแต่ละข้อมีคำที่ไม่ใช่สัตว์ปนอยู่หรือไม่'],
        steps: ['โต๊ะและเก้าอี้เป็นสิ่งของ ไม่ใช่สัตว์', 'หมู วัว แกะ เป็นสัตว์ทั้งหมด ตอบข้อ 1'],
        transferIds: ['th-animal-words-t'],
      },
    },

    // ================================================================ โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'sc-animal-calf-t', type: 'transfer', subject: 'science', skillIds: ['animal-babies'], familyId: 'animal-babies', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS, scene: true,
      prompt: { text: 'ภาพใดเป็นลูกของหมู' },
      options: [animal('a', 'lamb'), animal('b', 'piglet'), animal('c', 'puppy')],
      correctOptionId: 'b',
      narration: PICS,
      review: { summary: 'ลูกของหมูเรียกว่าลูกหมู ตัวสีชมพูเหมือนแม่', hints: [], steps: ['ลูกแกะและลูกสุนัขเป็นลูกของสัตว์ชนิดอื่น', 'ลูกหมูตัวสีชมพูมีหางเป็นห่วงเหมือนแม่'] },
    },
    {
      id: 'g-animal-mother-t', type: 'transfer', subject: 'general', skillIds: ['animal-babies'], familyId: 'animal-babies', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS, scene: true,
      prompt: { text: 'ภาพใดเป็นแม่ของลูกแกะ' },
      options: [animal('a', 'cow'), animal('b', 'sheep'), animal('c', 'cat')],
      correctOptionId: 'b',
      narration: PICS,
      review: { summary: 'แม่ของลูกแกะคือแกะ ขนฟูสีขาวเหมือนกัน', hints: [], steps: ['วัวและแมวไม่ใช่แม่ของลูกแกะ', 'แกะขนฟูสีขาวเหมือนลูกแกะ'] },
    },
    {
      id: 'sc-animal-egg-t', type: 'transfer', subject: 'science', skillIds: ['animal-features'], familyId: 'animal-features', difficulty: 2,
      sourceId: SRC, ...R, section: ANIMALS, scene: true,
      prompt: { text: 'ภาพใดเป็นสัตว์ที่มีสองขา' },
      options: [animal('a', 'cow'), animal('b', 'dog'), animal('c', 'duck')],
      correctOptionId: 'c',
      narration: PICS,
      review: { summary: 'เป็ดมีสองขา ส่วนวัวและสุนัขมีสี่ขา', hints: [], steps: ['วัวและสุนัขเดินสี่ขา', 'เป็ดเดินสองขา'] },
    },
    {
      id: 'sc-animal-wool-t', type: 'transfer', subject: 'science', skillIds: ['animal-uses'], familyId: 'animal-uses', difficulty: 2,
      sourceId: SRC, ...R, section: ANIMALS, scene: true,
      prompt: { text: 'หมูร้องว่า อู๊ดๆ ภาพใดเป็นหมู' },
      options: [animal('a', 'duck'), animal('b', 'pig'), animal('c', 'sheep')],
      correctOptionId: 'b',
      narration: PICS,
      review: { summary: 'หมูตัวสีชมพู จมูกแบน หางเป็นห่วง', hints: [], steps: ['เป็ดมีปากแหลมสีส้ม และแกะขนฟูสีขาว', 'หมูตัวสีชมพูหางเป็นห่วง'] },
    },
    {
      id: 'm-animal-pairs-t', type: 'transfer', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'แม่ลูกสัตว์ 1 คู่มีสัตว์ 2 ตัว ถ้ามีแม่ลูกสัตว์ 4 คู่ จะมีสัตว์รวมกันกี่ตัว' },
      options: words('6 ตัว', '8 ตัว', '10 ตัว'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '2 บวก 2 บวก 2 บวก 2 เท่ากับ 8 ตัว', hints: [], steps: ['แต่ละคู่มี 2 ตัว 4 คู่ต้องบวก 2 สี่ครั้ง', '2 บวก 2 บวก 2 บวก 2 เท่ากับ 8'] },
    },
    {
      id: 'g-animal-sound-t', type: 'transfer', subject: 'general', skillIds: ['animal-sounds'], familyId: 'animal-sounds', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'แมวส่งเสียงร้องว่าอย่างไร' },
      visual: one('cat'),
      options: words('โฮ่งๆ', 'ก้าบๆ', 'เหมียวๆ'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แมวร้อง เหมียวๆ', hints: [], steps: ['โฮ่งๆ เป็นเสียงสุนัข และ ก้าบๆ เป็นเสียงเป็ด', 'แมวร้อง เหมียวๆ'] },
    },
    {
      id: 'sc-animal-cowfood-t', type: 'transfer', subject: 'science', skillIds: ['animal-food'], familyId: 'animal-food', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'แกะกินอะไรเป็นอาหาร' },
      visual: one('sheep'),
      options: words('เนื้อสัตว์', 'ปลา', 'หญ้า'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แกะกินหญ้า', hints: [], steps: ['แกะไม่กินเนื้อสัตว์และไม่กินปลา', 'แกะกินหญ้า'] },
    },
    {
      id: 'm-animal-legsfarm-t', type: 'transfer', subject: 'math', skillIds: ['count-legs'], familyId: 'count-legs', difficulty: 3,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'ในฟาร์มมีวัว 2 ตัว และไก่ 3 ตัว รวมมีขากี่ขา' },
      options: words('12 ขา', '14 ขา', '16 ขา'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วัว 2 ตัวมี 8 ขา ไก่ 3 ตัวมี 6 ขา รวม 14 ขา', hints: [], steps: ['วัว 2 ตัว ตัวละ 4 ขา เป็น 8 ขา ไก่ 3 ตัว ตัวละ 2 ขา เป็น 6 ขา', '8 บวก 6 เท่ากับ 14'], column: { a: 8, op: '+', b: 6 } },
    },
    {
      id: 'sp-animal-right-t', type: 'transfer', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 2,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'ในภาพ ลูกสุนัขอยู่ทางด้านใดของแม่สุนัข' },
      visual: { type: 'row', items: ['pic-animal-dog', 'pic-animal-puppy'] },
      options: words('ทางซ้ายของแม่สุนัข', 'ทางขวาของแม่สุนัข', 'อยู่บนหลังแม่สุนัข'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ลูกสุนัขอยู่ทางขวามือของแม่สุนัขในภาพ', hints: [], steps: ['แม่สุนัขตัวใหญ่อยู่ทางซ้ายของภาพ', 'ลูกสุนัขตัวเล็กอยู่ทางขวา'] },
    },
    {
      id: 'r-animal-pair-t', type: 'transfer', subject: 'reasoning', skillIds: ['relationship'], familyId: 'animal-babies-words', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ข้อใดจับคู่แม่กับลูกได้ถูกต้อง' },
      options: words('เป็ดกับลูกหมู', 'แมวกับลูกแมว', 'วัวกับลูกเป็ด'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แม่แมวคู่กับลูกแมว เป็นสัตว์ชนิดเดียวกัน', hints: [], steps: ['เป็ดกับลูกหมู และวัวกับลูกเป็ด เป็นสัตว์คนละชนิดกัน', 'แมวกับลูกแมวเป็นชนิดเดียวกัน'] },
    },
    {
      id: 'sc-animal-milk-t', type: 'transfer', subject: 'science', skillIds: ['animal-uses'], familyId: 'animal-uses', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'สัตว์ในข้อใดออกไข่ให้เรานำมาทำอาหาร' },
      options: words('หมู', 'ไก่', 'วัว'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไก่ออกไข่ให้เรานำมาทำอาหาร', hints: [], steps: ['หมูและวัวไม่ออกไข่', 'ไก่ออกไข่'] },
    },
    {
      id: 'g-animal-guard-t', type: 'transfer', subject: 'general', skillIds: ['pets'], familyId: 'pets', difficulty: 1,
      sourceId: SRC, ...R, section: ANIMALS,
      prompt: { text: 'สัตว์เลี้ยงในข้อใดชอบจับหนู' },
      options: words('สุนัข', 'แมว', 'วัว'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แมวชอบจับหนู', hints: [], steps: ['สุนัขเฝ้าบ้าน และวัวกินหญ้า', 'แมวชอบจับหนู'] },
    },
    {
      id: 'th-animal-initial-t', type: 'transfer', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ภาพนี้คือ วัว คำว่า วัว ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: one('cow'),
      options: letters('ร', 'ว', 'ม'),
      correctOptionId: 'b',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก',
      review: { summary: 'วัว ขึ้นต้นด้วย วอ แหวน', hints: [], steps: ['ออกเสียงคำว่า วัว ช้าๆ', 'เสียงแรกคือ วอ แหวน'] },
    },
    {
      id: 'm-animal-piglets-t', type: 'transfer', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'แม่แมวแต่ละตัวมีลูก 3 ตัว ถ้ามีแม่แมว 3 ตัว จะมีลูกแมวรวมกันกี่ตัว' },
      options: words('6 ตัว', '9 ตัว', '12 ตัว'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '3 บวก 3 บวก 3 เท่ากับ 9 ตัว', hints: [], steps: ['แม่แมวตัวที่ 1 มีลูก 3 ตัว ตัวที่ 2 มีอีก 3 ตัว รวมเป็น 6 ตัว', 'ตัวที่ 3 มีอีก 3 ตัว รวมเป็น 9 ตัว'] },
    },
    {
      id: 'th-animal-words-t', type: 'transfer', subject: 'thai', skillIds: ['classify-words'], familyId: 'classify-words', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ข้อใดเป็นชื่อสัตว์ทั้งหมด' },
      options: words('แมว โต๊ะ ม้า', 'ช้าง ม้า ถนน', 'แมว ช้าง ม้า'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แมว ช้าง ม้า เป็นสัตว์ทั้งหมด', hints: [], steps: ['โต๊ะและถนนไม่ใช่สัตว์', 'แมว ช้าง ม้า เป็นสัตว์ทั้งหมด'] },
    },
  ],
};
