/*
 * ชุดที่ 37 — ปลูกผักบุ้ง (ชุดผสม ใช้รูปที่มีอยู่แล้ว) แบบ 15 ข้อ
 * ช่วง 1 ฟังเรื่องต้นกับพ่อปลูกผักบุ้ง ถาม 5 ข้อ: ปลูกอะไร รดน้ำเมื่อไร 3 สัปดาห์กี่วัน รากดูดน้ำ คำว่า ภูมิใจ
 * ช่วง 2 เทียบปริมาตร (เหยือก 1 ใบ = แก้ว 3 ใบ, ขวด 1 ขวด = แก้ว 2 ใบ) ถาม 5 ข้อ
 * ช่วง 3 ข้อเดี่ยว: ทิศบนแผนที่ พยัญชนะต้น เก็บจาน โจทย์ลบ 15 − 9 แบบรูปตัวเลขทีละ 7
 * แต่งใหม่ทั้งหมด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const STORY = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const WATER_SECTION = 'ดูภาพเทียบปริมาณน้ำแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const words = (...list) => list.map((text, i) => ({ id: 'abc'[i], text }));
const letters = (...list) => list.map((text, i) => ({ id: 'abc'[i], text, speech: '' }));

const STORY_TEXT = 'ต้นกับพ่อปลูกผักบุ้งในกระบะหลังบ้าน ทุกเช้าต้นรดน้ำผักก่อนไปโรงเรียน ผ่านไป 7 วัน ผักบุ้งงอกเป็นต้นเล็กๆ ผ่านไปอีก 3 สัปดาห์ แม่เก็บผักบุ้งมาผัดให้ทุกคนกิน ต้นภูมิใจมากที่ได้ช่วยปลูกผัก';
const WATER = { type: 'equivalence', rows: [{ left: 'pic-jug', right: 'pic-glass', count: 3 }, { left: 'pic-bottle', right: 'pic-glass', count: 2 }] };
const WATER_TEXT = 'เหยือก 1 ใบ ใส่น้ำได้เท่ากับแก้ว 3 ใบ ขวด 1 ขวด ใส่น้ำได้เท่ากับแก้ว 2 ใบ';
const MAP = { type: 'compass-map', center: 'บ้านของต้น', places: { north: 'สวนผัก', east: 'บ่อปลา', south: 'ถนน', west: 'ต้นมะม่วง' } };

export default {
  id: 'set-37',
  version: 1,
  title: 'ชุดที่ 37',
  note: 'ปลูกผักบุ้ง เทียบปริมาณน้ำ ทิศ สัปดาห์ละ 7 วัน',
  order: [
    'g-veg-what', 'g-veg-when', 'm-veg-weeks', 'sc-veg-root', 'th-veg-proud',
    'm-water-jugs', 'm-water-bottles', 'm-water-both', 'r-water-more', 'sc-water-shape',
    'sp-garden-north', 'th-veg-letter', 'g-help-dishes', 'm-veg-left', 'r-seven-pattern',
  ],
  stimuli: {
    story: { section: STORY, text: STORY_TEXT },
    water: { section: WATER_SECTION, text: WATER_TEXT, visual: WATER },
  },
  items: [
    // ================================================================ ช่วงที่ 1: เรื่องปลูกผักบุ้ง
    {
      id: 'g-veg-what', type: 'main', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ต้นกับพ่อปลูกผักอะไร' },
      options: words('ผักบุ้ง', 'คะน้า', 'กะหล่ำปลี'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการจำรายละเอียดจากเรื่องที่ฟัง',
      review: {
        summary: 'ต้นกับพ่อปลูกผักบุ้ง',
        hints: ['ฟังประโยคแรกของเรื่อง'],
        steps: ['ประโยคแรกบอกว่า ต้นกับพ่อปลูกผักบุ้งในกระบะหลังบ้าน', 'เรื่องไม่ได้พูดถึงคะน้าและกะหล่ำปลี ตอบข้อ 1'],
        transferIds: ['g-veg-what-t'],
      },
    },
    {
      id: 'g-veg-when', type: 'main', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ต้นรดน้ำผักตอนไหน' },
      options: words('ตอนเย็นหลังเลิกเรียน', 'ตอนเช้าก่อนไปโรงเรียน', 'ตอนกลางคืน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจำรายละเอียดเรื่องเวลา',
      review: {
        summary: 'ทุกเช้าต้นรดน้ำผักก่อนไปโรงเรียน',
        hints: ['ฟังคำว่า ทุกเช้า ในเรื่อง'],
        steps: ['เรื่องบอกว่า ทุกเช้าต้นรดน้ำผักก่อนไปโรงเรียน', 'จึงรดน้ำตอนเช้าก่อนไปโรงเรียน ตอบข้อ 2'],
        transferIds: ['g-veg-when-t'],
      },
    },
    {
      id: 'm-veg-weeks', type: 'main', subject: 'math', skillIds: ['repeated-addition'], familyId: 'weeks-days', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ในเรื่อง ผ่านไปอีก 3 สัปดาห์ คิดเป็นกี่วัน' },
      options: words('14 วัน', '30 วัน', '21 วัน'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการรู้ว่า 1 สัปดาห์มี 7 วัน แล้วบวกซ้ำ',
      review: {
        summary: '1 สัปดาห์มี 7 วัน 3 สัปดาห์เป็น 7 บวก 7 บวก 7 เท่ากับ 21 วัน',
        hints: ['1 สัปดาห์มี 7 วัน'],
        steps: ['สัปดาห์ที่ 1 มี 7 วัน สัปดาห์ที่ 2 อีก 7 วัน รวม 14 วัน', 'สัปดาห์ที่ 3 อีก 7 วัน 14 บวก 7 เท่ากับ 21 ตอบข้อ 3'],
        column: { a: 14, op: '+', b: 7 },
        transferIds: ['m-veg-weeks-t'],
      },
    },
    {
      id: 'sc-veg-root', type: 'main', subject: 'science', skillIds: ['plant-parts'], familyId: 'plant-parts', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'เมื่อต้นรดน้ำ ส่วนใดของผักบุ้งดูดน้ำจากดิน' },
      options: words('ใบ', 'ราก', 'ดอก'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องหน้าที่ของรากพืช',
      review: {
        summary: 'รากอยู่ในดิน ทำหน้าที่ดูดน้ำ',
        hints: ['ส่วนไหนของพืชที่อยู่ใต้ดิน'],
        steps: ['ใบและดอกอยู่เหนือดิน', 'รากอยู่ในดินและดูดน้ำ ตอบข้อ 2'],
        transferIds: ['sc-veg-root-t'],
      },
    },
    {
      id: 'th-veg-proud', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ต้นภูมิใจมากที่ได้ช่วยปลูกผัก คำว่า ภูมิใจ หมายถึงข้อใด' },
      options: words('รู้สึกดีใจกับสิ่งดีที่ตนเองทำ', 'รู้สึกเสียใจ', 'รู้สึกง่วงนอน'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความหมายของคำจากเรื่อง',
      review: {
        summary: 'ภูมิใจ คือรู้สึกดีใจกับสิ่งดีที่ตนเองทำได้',
        hints: ['ต้นช่วยปลูกผักจนได้กิน ต้นจะรู้สึกอย่างไร'],
        steps: ['ต้นไม่ได้เสียใจหรือง่วงนอน', 'ต้นดีใจที่ตนเองช่วยปลูกผักได้ เรียกว่าภูมิใจ ตอบข้อ 1'],
        transferIds: ['th-veg-proud-t'],
      },
    },

    // ================================================================ ช่วงที่ 2: เทียบปริมาณน้ำ
    {
      id: 'm-water-jugs', type: 'main', subject: 'math', skillIds: ['volume-multiply'], familyId: 'volume', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'water',
      prompt: { text: 'เหยือก 2 ใบ ใส่น้ำได้เท่ากับแก้วกี่ใบ' },
      options: words('5 ใบ', '6 ใบ', '8 ใบ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการเทียบปริมาตรแล้วบวกซ้ำ',
      review: {
        summary: 'เหยือก 1 ใบเท่ากับแก้ว 3 ใบ 2 ใบจึงเท่ากับ 3 บวก 3 เท่ากับ 6 ใบ',
        hints: ['เหยือกแต่ละใบเท่ากับแก้ว 3 ใบ'],
        steps: ['เหยือกใบแรกเท่ากับแก้ว 3 ใบ เหยือกใบที่สองอีก 3 ใบ', '3 บวก 3 เท่ากับ 6 ตอบข้อ 2'],
        column: { a: 3, op: '+', b: 3 },
        transferIds: ['m-water-jugs-t'],
      },
    },
    {
      id: 'm-water-bottles', type: 'main', subject: 'math', skillIds: ['volume-multiply'], familyId: 'volume', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'water',
      prompt: { text: 'ขวด 3 ขวด ใส่น้ำได้เท่ากับแก้วกี่ใบ' },
      options: words('6 ใบ', '5 ใบ', '9 ใบ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการเทียบปริมาตรแล้วบวกซ้ำ',
      review: {
        summary: 'ขวด 1 ขวดเท่ากับแก้ว 2 ใบ 3 ขวดเป็น 2 บวก 2 บวก 2 เท่ากับ 6 ใบ',
        hints: ['ขวดแต่ละขวดเท่ากับแก้ว 2 ใบ'],
        steps: ['ขวดละ 2 ใบ นับ 2 4 6', '3 ขวดเท่ากับแก้ว 6 ใบ ตอบข้อ 1'],
        transferIds: ['m-water-bottles-t'],
      },
    },
    {
      id: 'm-water-both', type: 'main', subject: 'math', skillIds: ['volume-multiply'], familyId: 'volume', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'water',
      prompt: { text: 'เหยือก 1 ใบ กับขวด 1 ขวด รวมกันใส่น้ำได้เท่ากับแก้วกี่ใบ' },
      options: words('4 ใบ', '6 ใบ', '5 ใบ'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการเทียบปริมาตรสองอย่างแล้วบวก',
      review: {
        summary: 'เหยือกเท่ากับแก้ว 3 ใบ ขวดเท่ากับแก้ว 2 ใบ รวม 5 ใบ',
        hints: ['หาว่าแต่ละอย่างเท่ากับแก้วกี่ใบ แล้วบวกกัน'],
        steps: ['เหยือก 1 ใบเท่ากับแก้ว 3 ใบ ขวด 1 ขวดเท่ากับแก้ว 2 ใบ', '3 บวก 2 เท่ากับ 5 ตอบข้อ 3'],
        column: { a: 3, op: '+', b: 2 },
        transferIds: ['m-water-both-t'],
      },
    },
    {
      id: 'r-water-more', type: 'main', subject: 'reasoning', skillIds: ['measurement'], familyId: 'volume-compare', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'water',
      prompt: { text: 'ภาชนะใดใส่น้ำได้มากกว่ากัน' },
      options: words('ขวด 1 ขวด', 'เหยือก 1 ใบ', 'ใส่ได้เท่ากัน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการเปรียบเทียบปริมาตรด้วยหน่วยเดียวกัน',
      review: {
        summary: 'เหยือกเท่ากับแก้ว 3 ใบ ขวดเท่ากับแก้ว 2 ใบ เหยือกจึงใส่ได้มากกว่า',
        hints: ['เทียบด้วยจำนวนแก้ว ข้างไหนมากกว่า'],
        steps: ['เหยือก 1 ใบเท่ากับแก้ว 3 ใบ ขวด 1 ขวดเท่ากับแก้ว 2 ใบ', '3 มากกว่า 2 เหยือกใส่น้ำได้มากกว่า ตอบข้อ 2'],
        transferIds: ['r-water-more-t'],
      },
    },
    {
      id: 'sc-water-shape', type: 'main', subject: 'science', skillIds: ['states-of-matter'], familyId: 'liquid-shape', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'water',
      prompt: { text: 'เมื่อเทน้ำจากเหยือกลงในแก้ว น้ำจะมีรูปร่างเป็นอย่างไร' },
      options: words('มีรูปร่างตามแก้วที่ใส่', 'เป็นก้อนเหมือนเหยือกเดิม', 'หายไปหมด'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้ว่าของเหลวเปลี่ยนรูปร่างตามภาชนะ',
      review: {
        summary: 'น้ำเป็นของเหลว เปลี่ยนรูปร่างตามภาชนะที่ใส่',
        hints: ['น้ำในขวดกับน้ำในแก้วมีรูปร่างเหมือนกันไหม'],
        steps: ['น้ำไม่เป็นก้อนแข็ง และไม่หายไปเมื่อเท', 'น้ำมีรูปร่างตามแก้วที่ใส่ ตอบข้อ 1'],
        transferIds: ['sc-water-shape-t'],
      },
    },

    // ================================================================ ช่วงที่ 3: ข้อเดี่ยว
    {
      id: 'sp-garden-north', type: 'main', subject: 'spatial', skillIds: ['map-direction'], familyId: 'compass', difficulty: 2,
      sourceId: SRC, ...R, section: 'ดูแผนที่และทิศ แล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'สวนผักอยู่ทิศใดของบ้านของต้น' },
      visual: MAP,
      options: words('ทิศใต้', 'ทิศเหนือ', 'ทิศตะวันออก'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการอ่านทิศบนแผนที่',
      review: {
        summary: 'สวนผักอยู่ด้านบนของแผนที่ คือทิศเหนือ',
        hints: ['บนแผนที่ ด้านบนคือทิศเหนือ'],
        steps: ['ถนนอยู่ทิศใต้ และบ่อปลาอยู่ทิศตะวันออก', 'สวนผักอยู่ด้านบนของบ้าน คือทิศเหนือ ตอบข้อ 2'],
        transferIds: ['sp-garden-north-t'],
      },
    },
    {
      id: 'th-veg-letter', type: 'main', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำว่า ผักบุ้ง ขึ้นต้นด้วยพยัญชนะตัวใด' },
      options: letters('พ', 'ฟ', 'ผ'),
      correctOptionId: 'c',
      narration: 'เสียงอ่านคำ แต่ไม่อ่านตัวอักษรในตัวเลือก เด็กต้องแยก ผ พ ฟ ที่หน้าตาคล้ายกันเอง',
      review: {
        summary: 'ผักบุ้ง ขึ้นต้นด้วย ผอ ผึ้ง',
        hints: ['ผักบุ้ง ขึ้นต้นด้วยเสียงเดียวกับคำว่า ผึ้ง'],
        steps: ['พ คือ พอ พาน และ ฟ คือ ฟอ ฟัน ออกเสียงต่างจาก ผัก', 'ผักบุ้งขึ้นต้นด้วย ผอ ผึ้ง ตอบข้อ 3'],
        transferIds: ['th-veg-letter-t'],
      },
    },
    {
      id: 'g-help-dishes', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'helping-home', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'กินข้าวเสร็จแล้ว ควรทำอย่างไรกับจานของตนเอง' },
      options: words('ทิ้งไว้บนโต๊ะ', 'นำไปเก็บที่อ่างล้างจาน', 'ซ่อนไว้ใต้โต๊ะ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรับผิดชอบช่วยงานบ้าน',
      review: {
        summary: 'นำจานไปเก็บที่อ่างล้างจาน ช่วยแบ่งเบางานของพ่อแม่',
        hints: ['ทำอย่างไรให้โต๊ะสะอาดและช่วยพ่อแม่'],
        steps: ['ทิ้งไว้บนโต๊ะหรือซ่อนไว้ไม่ช่วยใคร', 'นำจานไปเก็บที่อ่างล้างจาน ตอบข้อ 2'],
        transferIds: ['g-help-dishes-t'],
      },
    },
    {
      id: 'm-veg-left', type: 'main', subject: 'math', skillIds: ['sub-borrow'], familyId: 'word-problem-sub', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีผักบุ้ง 15 ต้น แม่เก็บไปผัด 9 ต้น เหลือผักบุ้งกี่ต้น' },
      options: words('5 ต้น', '7 ต้น', '6 ต้น'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดโจทย์ลบที่ต้องยืม',
      review: {
        summary: '15 ลบ 9 เท่ากับ 6 ต้น',
        hints: ['เหลือเท่าไร ใช้การลบ'],
        steps: ['มี 15 ต้น เก็บไป 9 ต้น ต้องเอา 9 ออกจาก 15', '15 ลบ 9 เท่ากับ 6 ตอบข้อ 3'],
        column: { a: 15, op: '-', b: 9 },
        transferIds: ['m-veg-left-t'],
      },
    },
    {
      id: 'r-seven-pattern', type: 'main', subject: 'reasoning', skillIds: ['pattern-continue'], familyId: 'number-pattern', difficulty: 2,
      sourceId: SRC, ...R, section: 'ตัวเลขเรียงตามแบบรูป ตัวเลขที่หายไปคือเลขใด',
      prompt: { text: 'ตัวเลขเพิ่มขึ้นทีละเท่ากัน ช่อง ? ควรเป็นเลขใด' },
      visual: { type: 'number-row', items: [7, 14, 21, '?'] },
      options: words('27', '28', '30'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดแบบรูปของจำนวนที่เพิ่มทีละ 7',
      review: {
        summary: 'เพิ่มทีละ 7 ต่อจาก 21 คือ 28',
        hints: ['ดูว่าตัวเลขเพิ่มขึ้นทีละเท่าไร'],
        steps: ['7 ไป 14 เพิ่ม 7 และ 14 ไป 21 ก็เพิ่ม 7', '21 บวก 7 เท่ากับ 28 ตอบข้อ 2'],
        column: { a: 21, op: '+', b: 7 },
        transferIds: ['r-seven-pattern-t'],
      },
    },

    // ================================================================ โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'g-veg-what-t', type: 'transfer', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 1,
      sourceId: SRC, ...R, section: STORY,
      prompt: { text: 'มายด์กับยายปลูกดอกทานตะวันหน้าบ้าน มายด์กับยายปลูกอะไร' },
      options: words('ดอกกุหลาบ', 'ดอกทานตะวัน', 'ต้นมะม่วง'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มายด์กับยายปลูกดอกทานตะวัน', hints: [], steps: ['ประโยคบอกว่า ปลูกดอกทานตะวันหน้าบ้าน', 'จึงปลูกดอกทานตะวัน'] },
    },
    {
      id: 'g-veg-when-t', type: 'transfer', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 1,
      sourceId: SRC, ...R, section: STORY,
      prompt: { text: 'ทุกเย็นหลังเลิกเรียน พลอยพาสุนัขไปเดินเล่น พลอยพาสุนัขไปเดินเล่นตอนไหน' },
      options: words('ตอนเช้าก่อนไปโรงเรียน', 'ตอนกลางวัน', 'ตอนเย็นหลังเลิกเรียน'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ทุกเย็นหลังเลิกเรียน', hints: [], steps: ['ประโยคบอกว่า ทุกเย็นหลังเลิกเรียน', 'จึงพาไปตอนเย็นหลังเลิกเรียน'] },
    },
    {
      id: 'm-veg-weeks-t', type: 'transfer', subject: 'math', skillIds: ['repeated-addition'], familyId: 'weeks-days', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ปิดเทอม 2 สัปดาห์ คิดเป็นกี่วัน' },
      options: words('12 วัน', '14 วัน', '20 วัน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '7 บวก 7 เท่ากับ 14 วัน', hints: [], steps: ['1 สัปดาห์มี 7 วัน', '2 สัปดาห์เป็น 7 บวก 7 เท่ากับ 14'], column: { a: 7, op: '+', b: 7 } },
    },
    {
      id: 'sc-veg-root-t', type: 'transfer', subject: 'science', skillIds: ['plant-parts'], familyId: 'plant-parts', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ส่วนใดของต้นไม้ที่มักมีสีเขียวและรับแสงแดด' },
      options: words('ราก', 'ใบ', 'เมล็ด'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ใบสีเขียวรับแสงแดด', hints: [], steps: ['รากอยู่ในดิน และเมล็ดอยู่ในผล', 'ใบสีเขียวรับแสงแดด'] },
    },
    {
      id: 'th-veg-proud-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'น้องร้องไห้เพราะตุ๊กตาหาย คำว่า ร้องไห้ บอกว่าน้องรู้สึกอย่างไร' },
      options: words('ดีใจ', 'เสียใจ', 'ตื่นเต้น'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ร้องไห้เพราะของหาย แสดงว่าเสียใจ', hints: [], steps: ['ตุ๊กตาหายไม่ทำให้ดีใจหรือตื่นเต้น', 'น้องเสียใจจึงร้องไห้'] },
    },
    {
      id: 'm-water-jugs-t', type: 'transfer', subject: 'math', skillIds: ['volume-multiply'], familyId: 'volume', difficulty: 2,
      sourceId: SRC, ...R, section: WATER_SECTION,
      prompt: { text: 'เหยือก 1 ใบ ใส่น้ำได้เท่ากับแก้ว 3 ใบ เหยือก 3 ใบ ใส่น้ำได้เท่ากับแก้วกี่ใบ' },
      visual: WATER,
      options: words('6 ใบ', '9 ใบ', '12 ใบ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '3 บวก 3 บวก 3 เท่ากับ 9 ใบ', hints: [], steps: ['เหยือกละ 3 ใบ นับ 3 6 9', '3 เหยือกเท่ากับแก้ว 9 ใบ'] },
    },
    {
      id: 'm-water-bottles-t', type: 'transfer', subject: 'math', skillIds: ['volume-multiply'], familyId: 'volume', difficulty: 2,
      sourceId: SRC, ...R, section: WATER_SECTION,
      prompt: { text: 'ขวด 1 ขวด ใส่น้ำได้เท่ากับแก้ว 2 ใบ ขวด 4 ขวด ใส่น้ำได้เท่ากับแก้วกี่ใบ' },
      visual: WATER,
      options: words('6 ใบ', '8 ใบ', '10 ใบ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '2 บวก 2 บวก 2 บวก 2 เท่ากับ 8 ใบ', hints: [], steps: ['ขวดละ 2 ใบ นับ 2 4 6 8', '4 ขวดเท่ากับแก้ว 8 ใบ'] },
    },
    {
      id: 'm-water-both-t', type: 'transfer', subject: 'math', skillIds: ['volume-multiply'], familyId: 'volume', difficulty: 3,
      sourceId: SRC, ...R, section: WATER_SECTION,
      prompt: { text: 'เหยือก 1 ใบ เท่ากับแก้ว 3 ใบ ขวด 1 ขวด เท่ากับแก้ว 2 ใบ เหยือก 1 ใบกับขวด 2 ขวด รวมเท่ากับแก้วกี่ใบ' },
      visual: WATER,
      options: words('5 ใบ', '7 ใบ', '8 ใบ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '3 บวก 2 บวก 2 เท่ากับ 7 ใบ', hints: [], steps: ['เหยือก 1 ใบเท่ากับ 3 ใบ ขวด 2 ขวดเท่ากับ 4 ใบ', '3 บวก 4 เท่ากับ 7'], column: { a: 3, op: '+', b: 4 } },
    },
    {
      id: 'r-water-more-t', type: 'transfer', subject: 'reasoning', skillIds: ['measurement'], familyId: 'volume-compare', difficulty: 2,
      sourceId: SRC, ...R, section: WATER_SECTION,
      prompt: { text: 'เหยือก 1 ใบ เท่ากับแก้ว 3 ใบ ขวด 1 ขวด เท่ากับแก้ว 2 ใบ ขวด 3 ขวด กับเหยือก 2 ใบ อะไรใส่น้ำได้มากกว่า' },
      visual: WATER,
      options: words('ขวด 3 ขวด', 'เหยือก 2 ใบ', 'ใส่ได้เท่ากัน'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ขวด 3 ขวดเท่ากับแก้ว 6 ใบ เหยือก 2 ใบก็เท่ากับแก้ว 6 ใบ เท่ากัน', hints: [], steps: ['ขวด 3 ขวด 2 บวก 2 บวก 2 เท่ากับ 6 ใบ เหยือก 2 ใบ 3 บวก 3 เท่ากับ 6 ใบ', 'ทั้งสองอย่างเท่ากับแก้ว 6 ใบ จึงเท่ากัน'] },
    },
    {
      id: 'sc-water-shape-t', type: 'transfer', subject: 'science', skillIds: ['states-of-matter'], familyId: 'liquid-shape', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'สิ่งใดเป็นของแข็ง มีรูปร่างแน่นอน' },
      options: words('น้ำส้ม', 'ก้อนหิน', 'นม'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ก้อนหินเป็นของแข็ง มีรูปร่างแน่นอน', hints: [], steps: ['น้ำส้มและนมเป็นของเหลว เปลี่ยนรูปร่างตามภาชนะ', 'ก้อนหินเป็นของแข็ง'] },
    },
    {
      id: 'sp-garden-north-t', type: 'transfer', subject: 'spatial', skillIds: ['map-direction'], familyId: 'compass', difficulty: 2,
      sourceId: SRC, ...R, section: 'ดูแผนที่และทิศ แล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'บ่อปลาอยู่ทิศใดของบ้านของต้น' },
      visual: MAP,
      options: words('ทิศตะวันออก', 'ทิศตะวันตก', 'ทิศเหนือ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'บ่อปลาอยู่ทางขวาของแผนที่ คือทิศตะวันออก', hints: [], steps: ['บนแผนที่ ด้านขวาคือทิศตะวันออก', 'บ่อปลาอยู่ทางขวาของบ้าน'] },
    },
    {
      id: 'th-veg-letter-t', type: 'transfer', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำว่า ฟักทอง ขึ้นต้นด้วยพยัญชนะตัวใด' },
      options: letters('ฟ', 'พ', 'ผ'),
      correctOptionId: 'a',
      narration: 'เสียงอ่านคำ แต่ไม่อ่านตัวอักษรในตัวเลือก',
      review: { summary: 'ฟักทอง ขึ้นต้นด้วย ฟอ ฟัน', hints: [], steps: ['ฟักทอง ขึ้นต้นด้วยเสียงเดียวกับคำว่า ฟัน', 'คือ ฟอ ฟัน'] },
    },
    {
      id: 'g-help-dishes-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'helping-home', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เล่นของเล่นเสร็จแล้ว ควรทำอย่างไร' },
      options: words('ทิ้งไว้บนพื้น', 'เก็บเข้าที่ให้เรียบร้อย', 'ให้แม่เก็บให้ทุกครั้ง'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เก็บของเล่นเข้าที่ให้เรียบร้อย', hints: [], steps: ['ของเล่นบนพื้นทำให้คนอื่นเหยียบและหกล้มได้', 'เราควรเก็บของเล่นเองให้เรียบร้อย'] },
    },
    {
      id: 'm-veg-left-t', type: 'transfer', subject: 'math', skillIds: ['sub-borrow'], familyId: 'word-problem-sub', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีมะเขือเทศ 13 ผล นำไปทำอาหาร 8 ผล เหลือมะเขือเทศกี่ผล' },
      options: words('4 ผล', '5 ผล', '6 ผล'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '13 ลบ 8 เท่ากับ 5 ผล', hints: [], steps: ['มี 13 ผล ใช้ไป 8 ผล', '13 ลบ 8 เท่ากับ 5'], column: { a: 13, op: '-', b: 8 } },
    },
    {
      id: 'r-seven-pattern-t', type: 'transfer', subject: 'reasoning', skillIds: ['pattern-continue'], familyId: 'number-pattern', difficulty: 2,
      sourceId: SRC, ...R, section: 'ตัวเลขเรียงตามแบบรูป ตัวเลขที่หายไปคือเลขใด',
      prompt: { text: 'ตัวเลขเพิ่มขึ้นทีละเท่ากัน ช่อง ? ควรเป็นเลขใด' },
      visual: { type: 'number-row', items: [4, 8, 12, '?'] },
      options: words('14', '16', '18'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เพิ่มทีละ 4 ต่อจาก 12 คือ 16', hints: [], steps: ['4 ไป 8 และ 8 ไป 12 เพิ่มทีละ 4', '12 บวก 4 เท่ากับ 16'] },
    },
  ],
};
