/*
 * ชุดที่ 11 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 11) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * ใช้รูปแผ่น F (ท้องฟ้า เสื้อผ้า อาหาร ผลไม้ สัตว์ตัวเล็ก; design/PROMPTS-gemini-6.md)
 * ยังไม่ใช้รูปแมงมุมกับโจทย์นับขา (รูปมีปุ่มเล็กใต้หน้า อาจนับผิด)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const GRID = 'ดูภาพในตารางแล้วตอบคำถามให้ถูกต้อง';
const LETTER = 'ฟังชื่อภาพแล้วตอบคำถามให้ถูกต้อง';
const SKY = { type: 'grid', rows: [['pic-sun', 'pic-rain-cloud', 'pic-rainbow'], ['pic-raincoat', 'pic-sweater', 'pic-sneakers'], ['pic-mango', 'pic-durian', 'pic-rambutan']] };
const GARDEN = { type: 'scatter', items: [{ asset: 'pic-bee', count: 5 }, { asset: 'pic-snail', count: 3 }] };

export default {
  id: 'set-11',
  version: 1,
  title: 'ชุดที่ 11',
  note: 'ฝน รุ้ง เสื้อผ้าตามฤดู อาหาร ผลไม้ไทย ผึ้ง',
  order: [
    'th-raincoat-colour', 'sc-rainbow-when', 'm-order-numbers', 'r-slowest', 'g-sweater-cool',
    'sp-count-bees', 'r-odd-food', 'sc-milk-bones', 'sp-grid-under-cloud', 'm-rambutan-left',
    'th-first-letter-ngo', 'g-bee-safety',
  ],
  stimuli: {
    rainy: {
      section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      text: 'เช้าวันนี้ฝนตกหนัก ลิลลี่ใส่เสื้อกันฝนสีเหลืองไปโรงเรียน ตอนบ่ายฝนหยุด แดดออก ลิลลี่มองขึ้นไปบนท้องฟ้า เห็นรุ้งสวยงามหลายสี',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'th-raincoat-colour', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'rainy',
      prompt: { text: 'ลิลลี่ใส่เสื้อกันฝนสีอะไร' },
      options: [{ id: 'a', text: 'สีแดง' }, { id: 'b', text: 'สีเหลือง' }, { id: 'c', text: 'สีฟ้า' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'เสื้อกันฝนของลิลลี่เป็นสีเหลือง',
        hints: ['ฟังตอนที่เรื่องพูดถึงเสื้อกันฝน'],
        steps: ['เรื่องบอกว่า ลิลลี่ใส่เสื้อกันฝนสีเหลือง', 'จึงเป็นสีเหลือง ตอบข้อ 2'],
        transferIds: ['th-sneaker-colour-t'],
      },
    },
    {
      id: 'sc-rainbow-when', type: 'main', subject: 'science', skillIds: ['weather'], familyId: 'rainbow', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'rainy',
      prompt: { text: 'จากเรื่อง รุ้งเกิดขึ้นตอนไหน' },
      options: [{ id: 'a', text: 'ตอนกลางคืน' }, { id: 'b', text: 'ตอนที่ไม่มีแดดเลย' }, { id: 'c', text: 'หลังฝนหยุดและมีแดดออก' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการฟังและความรู้เรื่องธรรมชาติ',
      review: {
        summary: 'รุ้งเกิดจากแสงแดดส่องผ่านละอองน้ำฝน',
        hints: ['ลิลลี่เห็นรุ้งตอนไหนในเรื่อง'],
        steps: ['เรื่องบอกว่า ฝนหยุด แดดออก แล้วลิลลี่จึงเห็นรุ้ง', 'รุ้งต้องมีทั้งละอองน้ำและแสงแดด ตอบข้อ 3'],
        transferIds: ['sc-rain-from-t'],
      },
    },
    {
      id: 'm-order-numbers', type: 'main', subject: 'math', skillIds: ['order-numbers'], familyId: 'order-numbers', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดเรียงจำนวนจากน้อยไปมาก' },
      options: [{ id: 'a', text: '12 15 21' }, { id: 'b', text: '21 15 12' }, { id: 'c', text: '15 12 21' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการเปรียบเทียบและเรียงจำนวน',
      review: {
        summary: '12 น้อยที่สุด ตามด้วย 15 แล้ว 21',
        hints: ['หาจำนวนที่น้อยที่สุดก่อน'],
        steps: ['ดูหลักสิบก่อน 21 มี 2 สิบ มากที่สุด', '12 กับ 15 มี 1 สิบเท่ากัน ดูหลักหน่วย 2 น้อยกว่า 5', 'เรียงได้ 12 15 21 ตอบข้อ 1'],
        transferIds: ['m-order-down-t'],
      },
    },
    {
      id: 'r-slowest', type: 'main', subject: 'reasoning', skillIds: ['compare-speed'], familyId: 'compare-animals', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สัตว์ใดเคลื่อนที่ช้าที่สุด' },
      options: [{ id: 'a', image: 'pic-bee', speech: 'ผึ้ง' }, { id: 'b', image: 'pic-snail', speech: 'หอยทาก' }, { id: 'c', image: 'pic-horse', speech: 'ม้า' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ วัดการเปรียบเทียบ',
      review: {
        summary: 'หอยทากค่อยๆ คลานไปช้าๆ',
        hints: ['สัตว์ตัวไหนแบกบ้านไว้บนหลัง'],
        steps: ['ม้าวิ่งเร็ว ผึ้งบินเร็ว', 'หอยทากคลานช้ามาก จึงช้าที่สุด ตอบข้อ 2'],
        transferIds: ['r-can-fly-t'],
      },
    },
    {
      id: 'g-sweater-cool', type: 'main', subject: 'general', skillIds: ['clothing-season'], familyId: 'clothing-season', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ฤดูหนาว อากาศเย็นตอนเช้า ควรใส่สิ่งใด' },
      options: [{ id: 'a', image: 'pic-raincoat', speech: 'เสื้อกันฝน' }, { id: 'b', image: 'pic-sneakers', speech: 'รองเท้าผ้าใบ' }, { id: 'c', image: 'pic-sweater', speech: 'เสื้อไหมพรม' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้ (เรียกเสื้อไหมพรมเพื่อไม่ให้เสียงบอกเฉลย) วัดความรู้เรื่องการแต่งกายตามฤดู',
      review: {
        summary: 'เสื้อไหมพรมหนาๆ ช่วยให้ตัวอุ่น',
        hints: ['เสื้อตัวไหนหนาและอุ่น'],
        steps: ['เสื้อกันฝนใช้ตอนฝนตก รองเท้าใส่ที่เท้า', 'อากาศเย็นควรใส่เสื้อหนาๆ ที่อุ่น ตอบข้อ 3'],
        transferIds: ['g-rain-wear-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'sp-count-bees', type: 'main', subject: 'spatial', skillIds: ['count-scattered'], familyId: 'scatter-count', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ในภาพมีผึ้งกี่ตัว' },
      visual: GARDEN,
      options: [{ id: 'a', text: '5 ตัว' }, { id: 'b', text: '3 ตัว' }, { id: 'c', text: '8 ตัว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ เด็กต้องนับเฉพาะผึ้งเอง',
      review: {
        summary: 'นับเฉพาะผึ้ง ได้ 5 ตัว',
        hints: ['แตะผึ้งทีละตัว อย่านับหอยทาก'],
        steps: ['ในภาพมีผึ้งกับหอยทากปนกัน', 'นับเฉพาะผึ้ง หนึ่ง สอง สาม สี่ ห้า ได้ 5 ตัว ตอบข้อ 1'],
        transferIds: ['sp-count-snails-t'],
      },
    },
    {
      id: 'r-odd-food', type: 'main', subject: 'reasoning', skillIds: ['odd-one-out'], familyId: 'odd-one-out', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดไม่เข้าพวก' },
      options: [{ id: 'a', image: 'pic-mango', speech: 'มะม่วง' }, { id: 'b', image: 'pic-fried-egg', speech: 'ไข่ดาว' }, { id: 'c', image: 'pic-durian', speech: 'ทุเรียน' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ วัดการจัดกลุ่ม',
      review: {
        summary: 'มะม่วงกับทุเรียนเป็นผลไม้ ไข่ดาวไม่ใช่',
        hints: ['สองภาพเป็นพวกเดียวกัน คือพวกอะไร'],
        steps: ['มะม่วงและทุเรียนเป็นผลไม้ที่ขึ้นบนต้น', 'ไข่ดาวทำจากไข่ไก่ ไม่ใช่ผลไม้ ตอบข้อ 2'],
        transferIds: ['r-odd-sky-t'],
      },
    },
    {
      id: 'sc-milk-bones', type: 'main', subject: 'science', skillIds: ['nutrition'], familyId: 'nutrition', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'การดื่มนมทุกวันช่วยให้ร่างกายเป็นอย่างไร' },
      visual: { type: 'image', asset: 'pic-milk' },
      options: [{ id: 'a', text: 'ทำให้ง่วงนอนทั้งวัน' }, { id: 'b', text: 'ทำให้ฟันผุ' }, { id: 'c', text: 'ช่วยให้กระดูกและฟันแข็งแรง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องอาหาร',
      review: {
        summary: 'นมมีแคลเซียม ช่วยสร้างกระดูกและฟัน',
        hints: ['เด็กๆ ดื่มนมแล้วจะตัวสูงแข็งแรง'],
        steps: ['นมมีสารอาหารชื่อ แคลเซียม', 'แคลเซียมช่วยให้กระดูกและฟันแข็งแรง ตอบข้อ 3'],
        transferIds: ['sc-egg-from-t'],
      },
    },
    {
      id: 'sp-grid-under-cloud', type: 'main', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-position', difficulty: 2,
      sourceId: SRC, ...R, section: GRID,
      prompt: { text: 'ภาพใดอยู่ใต้เมฆฝนติดกันพอดี' },
      visual: SKY,
      options: [{ id: 'a', image: 'pic-sweater', speech: 'เสื้อไหมพรม' }, { id: 'b', image: 'pic-raincoat', speech: 'เสื้อกันฝน' }, { id: 'c', image: 'pic-durian', speech: 'ทุเรียน' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกตำแหน่ง เด็กต้องดูตารางเอง',
      review: {
        summary: 'ใต้เมฆฝนติดกันคือเสื้อไหมพรม',
        hints: ['หาเมฆฝนก่อน แล้วมองลงมาหนึ่งช่อง'],
        steps: ['เมฆฝนอยู่แถวบน ตรงกลาง', 'ช่องที่อยู่ใต้เมฆฝนพอดีคือเสื้อไหมพรม ทุเรียนอยู่ต่ำลงไปอีกแถว ตอบข้อ 1'],
        transferIds: ['sp-grid-above-rambutan-t'],
      },
    },
    {
      id: 'm-rambutan-left', type: 'main', subject: 'math', skillIds: ['sub-borrow'], familyId: 'sub-borrow', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีเงาะ 15 ผล กินไป 6 ผล เหลือเงาะกี่ผล' },
      visual: { type: 'image', asset: 'pic-rambutan' },
      options: [{ id: 'a', text: '11 ผล' }, { id: 'b', text: '9 ผล' }, { id: 'c', text: '21 ผล' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการลบมีการยืม',
      review: {
        summary: '15 ลบ 6 เท่ากับ 9 ผล',
        hints: ['กินไปแล้วเหลือน้อยลง ต้องลบ'],
        steps: ['กินไปแล้วเงาะน้อยลง จึงใช้การลบ 15 ลบ 6', '5 ลบ 6 ไม่พอ ยืมหนึ่งสิบ ได้ 15 ลบ 6 เท่ากับ 9', 'เหลือเงาะ 9 ผล ตอบข้อ 2'],
        column: { a: 15, op: '-', b: 6 },
        transferIds: ['m-mango-left-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'th-first-letter-ngo', type: 'main', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: LETTER,
      prompt: { text: 'ภาพนี้คือ เงาะ คำว่า เงาะ ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: { type: 'image', asset: 'pic-rambutan' },
      options: [{ id: 'a', text: 'ช', speech: '' }, { id: 'b', text: 'ด', speech: '' }, { id: 'c', text: 'ง', speech: '' }],
      correctOptionId: 'c',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก เด็กต้องรู้จักตัวอักษรเอง',
      review: {
        summary: 'เงาะ ขึ้นต้นด้วย งอ งู',
        hints: ['สระ เ อยู่ข้างหน้า แต่พยัญชนะคือตัวที่ตามมา'],
        steps: ['คำว่า เงาะ มีสระ เ กับ าะ อยู่หน้าและหลัง', 'พยัญชนะที่อยู่ตรงกลางคือ งอ งู ตอบข้อ 3'],
        transferIds: ['th-first-letter-mango-t'],
      },
    },
    {
      id: 'g-bee-safety', type: 'main', subject: 'general', skillIds: ['safety'], familyId: 'safety-animals', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้ามีผึ้งบินมาใกล้ตัว หนูควรทำอย่างไร' },
      visual: { type: 'image', asset: 'pic-bee' },
      options: [{ id: 'a', text: 'อยู่นิ่งๆ แล้วค่อยๆ เดินออกห่าง' }, { id: 'b', text: 'ใช้มือตีผึ้ง' }, { id: 'c', text: 'วิ่งไล่จับผึ้ง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องความปลอดภัย',
      review: {
        summary: 'ไม่ตีหรือแกล้งผึ้ง ผึ้งจะได้ไม่ต่อย',
        hints: ['ถ้าเราตีผึ้ง ผึ้งจะทำอย่างไร'],
        steps: ['ถ้าตีหรือไล่จับ ผึ้งจะตกใจและต่อยเรา', 'ให้อยู่นิ่งๆ แล้วค่อยๆ เดินออกไป ตอบข้อ 1'],
        transferIds: ['g-honey-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-sneaker-colour-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ต้นใส่รองเท้าผ้าใบสีขาวไปวิ่งเล่นที่สนาม ต้นใส่รองเท้าสีอะไร' },
      options: [{ id: 'a', text: 'สีดำ' }, { id: 'b', text: 'สีขาว' }, { id: 'c', text: 'สีแดง' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'รองเท้าของต้นเป็นสีขาว', hints: [], steps: ['เรื่องบอกว่า ต้นใส่รองเท้าผ้าใบสีขาว', 'จึงเป็นสีขาว'] },
    },
    {
      id: 'sc-rain-from-t', type: 'transfer', subject: 'science', skillIds: ['weather'], familyId: 'rainbow', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ฝนตกลงมาจากสิ่งใด' },
      options: [{ id: 'a', image: 'pic-sun', speech: 'ดวงอาทิตย์' }, { id: 'b', image: 'pic-rain-cloud', speech: 'เมฆ' }, { id: 'c', image: 'pic-rainbow', speech: 'รุ้ง' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'เมฆสีเทามีหยดน้ำ แล้วตกลงมาเป็นฝน', hints: [], steps: ['เมฆเกิดจากไอน้ำรวมกัน', 'เมื่อหยดน้ำหนักมาก จึงตกลงมาเป็นฝน'] },
    },
    {
      id: 'm-order-down-t', type: 'transfer', subject: 'math', skillIds: ['order-numbers'], familyId: 'order-numbers', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดเรียงจำนวนจากมากไปน้อย' },
      options: [{ id: 'a', text: '18 25 30' }, { id: 'b', text: '30 25 18' }, { id: 'c', text: '25 30 18' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '30 มากที่สุด ตามด้วย 25 แล้ว 18', hints: [], steps: ['ดูหลักสิบ 30 มี 3 สิบ 25 มี 2 สิบ 18 มี 1 สิบ', 'เรียงจากมากไปน้อยได้ 30 25 18'] },
    },
    {
      id: 'r-can-fly-t', type: 'transfer', subject: 'reasoning', skillIds: ['compare-speed'], familyId: 'compare-animals', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สัตว์ใดบินได้' },
      options: [{ id: 'a', image: 'pic-snail', speech: 'หอยทาก' }, { id: 'b', image: 'pic-spider', speech: 'แมงมุม' }, { id: 'c', image: 'pic-bee', speech: 'ผึ้ง' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ผึ้งมีปีก จึงบินได้', hints: [], steps: ['หอยทากคลาน แมงมุมเดิน', 'ผึ้งมีปีกบางๆ จึงบินได้'] },
    },
    {
      id: 'g-rain-wear-t', type: 'transfer', subject: 'general', skillIds: ['clothing-season'], familyId: 'clothing-season', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ฝนกำลังตก ถ้าต้องเดินออกไปข้างนอก ควรใส่สิ่งใด' },
      options: [{ id: 'a', image: 'pic-sweater', speech: 'เสื้อไหมพรม' }, { id: 'b', image: 'pic-raincoat', speech: 'เสื้อตัวสีเหลือง' }, { id: 'c', image: 'pic-sneakers', speech: 'รองเท้าผ้าใบ' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ (ไม่เรียกเสื้อกันฝนเพื่อไม่ให้เสียงบอกเฉลย)',
      review: { summary: 'เสื้อกันฝนกันไม่ให้ตัวเปียก', hints: [], steps: ['เสื้อไหมพรมเปียกน้ำแล้วจะหนักและหนาว', 'ฝนตกควรใส่เสื้อกันฝน'] },
    },
    {
      id: 'sp-count-snails-t', type: 'transfer', subject: 'spatial', skillIds: ['count-scattered'], familyId: 'scatter-count', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ในภาพมีหอยทากกี่ตัว' },
      visual: GARDEN,
      options: [{ id: 'a', text: '5 ตัว' }, { id: 'b', text: '2 ตัว' }, { id: 'c', text: '3 ตัว' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'นับเฉพาะหอยทาก ได้ 3 ตัว', hints: [], steps: ['แตะหอยทากทีละตัว', 'หนึ่ง สอง สาม ได้ 3 ตัว'] },
    },
    {
      id: 'r-odd-sky-t', type: 'transfer', subject: 'reasoning', skillIds: ['odd-one-out'], familyId: 'odd-one-out', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดไม่เข้าพวก' },
      options: [{ id: 'a', image: 'pic-sneakers', speech: 'รองเท้าผ้าใบ' }, { id: 'b', image: 'pic-sun', speech: 'ดวงอาทิตย์' }, { id: 'c', image: 'pic-rainbow', speech: 'รุ้ง' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ดวงอาทิตย์กับรุ้งอยู่บนท้องฟ้า รองเท้าไม่ใช่', hints: [], steps: ['ดวงอาทิตย์และรุ้งเห็นได้บนท้องฟ้า', 'รองเท้าผ้าใบเป็นของใช้ จึงไม่เข้าพวก'] },
    },
    {
      id: 'sc-egg-from-t', type: 'transfer', subject: 'science', skillIds: ['nutrition'], familyId: 'nutrition', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'อาหารใดได้มาจากแม่ไก่' },
      options: [{ id: 'a', image: 'pic-rice', speech: 'ข้าว' }, { id: 'b', image: 'pic-mango', speech: 'มะม่วง' }, { id: 'c', image: 'pic-fried-egg', speech: 'ไข่ดาว' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ไข่ดาวทำจากไข่ของแม่ไก่', hints: [], steps: ['ข้าวมาจากต้นข้าว มะม่วงมาจากต้นมะม่วง', 'ไข่ดาวทำจากไข่ไก่ ได้มาจากแม่ไก่'] },
    },
    {
      id: 'sp-grid-above-rambutan-t', type: 'transfer', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-position', difficulty: 2,
      sourceId: SRC, ...R, section: GRID,
      prompt: { text: 'ภาพใดอยู่บนเงาะติดกันพอดี' },
      visual: SKY,
      options: [{ id: 'a', image: 'pic-rainbow', speech: 'รุ้ง' }, { id: 'b', image: 'pic-sneakers', speech: 'รองเท้าผ้าใบ' }, { id: 'c', image: 'pic-mango', speech: 'มะม่วง' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'บนเงาะติดกันคือรองเท้าผ้าใบ', hints: [], steps: ['เงาะอยู่มุมล่างด้านขวา', 'ช่องที่อยู่บนเงาะพอดีคือรองเท้าผ้าใบ'] },
    },
    {
      id: 'm-mango-left-t', type: 'transfer', subject: 'math', skillIds: ['sub-borrow'], familyId: 'sub-borrow', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีมะม่วง 12 ผล แจกเพื่อนไป 5 ผล เหลือมะม่วงกี่ผล' },
      options: [{ id: 'a', text: '7 ผล' }, { id: 'b', text: '17 ผล' }, { id: 'c', text: '8 ผล' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '12 ลบ 5 เท่ากับ 7 ผล', hints: [], steps: ['2 ลบ 5 ไม่พอ ยืมหนึ่งสิบ', '12 ลบ 5 เท่ากับ 7 ผล'], column: { a: 12, op: '-', b: 5 } },
    },
    {
      id: 'th-first-letter-mango-t', type: 'transfer', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: LETTER,
      prompt: { text: 'ภาพนี้คือ มะม่วง คำว่า มะม่วง ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: { type: 'image', asset: 'pic-mango' },
      options: [{ id: 'a', text: 'น', speech: '' }, { id: 'b', text: 'ม', speech: '' }, { id: 'c', text: 'ว', speech: '' }],
      correctOptionId: 'b',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก',
      review: { summary: 'มะม่วง ขึ้นต้นด้วย มอ ม้า', hints: [], steps: ['พยางค์แรกคือ มะ', 'มะ ขึ้นต้นด้วย มอ ม้า'] },
    },
    {
      id: 'g-honey-t', type: 'transfer', subject: 'general', skillIds: ['safety'], familyId: 'safety-animals', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ผึ้งทำอาหารอะไรให้เรากินได้' },
      options: [{ id: 'a', text: 'นม' }, { id: 'b', text: 'ไข่' }, { id: 'c', text: 'น้ำผึ้ง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ผึ้งเก็บน้ำหวานจากดอกไม้ไปทำน้ำผึ้ง', hints: [], steps: ['ผึ้งบินไปดูดน้ำหวานจากดอกไม้', 'แล้วนำไปทำเป็นน้ำผึ้งในรัง'] },
    },
  ],
};
