/*
 * ชุดที่ 6 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 6 และ docs/QUESTION-TYPES.md) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * ใช้รูปเดิมจากแผ่น A/B/C และรูปเพื่อน; กล่องซ้อนวาดด้วยโค้ด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';

export default {
  id: 'set-06',
  version: 1,
  title: 'ชุดที่ 6',
  note: 'วันเด็ก เข้าแถว อวัยวะ หันหน้า อายุ นับกล่อง ลบมียืม',
  order: [
    'th-kids-day-balloon', 'g-kids-day-date', 'r-line-behind', 'sc-paired-organ', 'th-nickname-rooster',
    'sp-facing-north', 'm-sister-age', 'r-skip-three', 'sp-count-boxes', 'g-flag-colours',
    'm-stickers-sub', 'sc-ice-melt',
  ],
  stimuli: {
    kidsDay: {
      section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      text: 'วันเสาร์ที่สองของเดือนมกราคมเป็นวันเด็ก ต้นกับแม่ไปงานวันเด็กที่โรงเรียน ต้นได้ลูกโป่งสีแดงและขนม 3 ถุง แล้วต้นแบ่งขนมให้น้อง 1 ถุง',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'th-kids-day-balloon', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'kidsDay',
      prompt: { text: 'ต้นได้ลูกโป่งสีอะไร' },
      options: [{ id: 'a', text: 'สีเขียว' }, { id: 'b', text: 'สีแดง' }, { id: 'c', text: 'สีเหลือง' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'ต้นได้ลูกโป่งสีแดง',
        hints: ['ฟังตอนที่เรื่องพูดถึงลูกโป่ง'],
        steps: ['เรื่องบอกว่า ต้นได้ลูกโป่งสีแดงและขนม 3 ถุง', 'ลูกโป่งเป็นสีแดง ตอบข้อ 2'],
        transferIds: ['th-new-year-shirt-t'],
      },
    },
    {
      id: 'g-kids-day-date', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'kidsDay',
      prompt: { text: 'วันเด็กตรงกับวันใด' },
      options: [{ id: 'a', text: 'วันเสาร์ที่สองของเดือนมกราคม' }, { id: 'b', text: 'วันที่ 1 มกราคม' }, { id: 'c', text: 'วันที่ 13 เมษายน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องวันสำคัญ (เรื่องที่ฟังบอกไว้ด้วย)',
      review: {
        summary: 'วันเด็กคือวันเสาร์ที่สองของเดือนมกราคม',
        hints: ['ฟังประโยคแรกของเรื่อง'],
        steps: ['วันเด็กแห่งชาติตรงกับวันเสาร์ที่สองของเดือนมกราคมทุกปี', '1 มกราคมคือวันขึ้นปีใหม่ 13 เมษายนคือวันสงกรานต์ ตอบข้อ 1'],
        transferIds: ['g-new-year-date-t'],
      },
    },
    {
      id: 'r-line-behind', type: 'main', subject: 'reasoning', skillIds: ['order-position'], familyId: 'line-position', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สัตว์ 5 ตัวเข้าแถว หัวแถวอยู่ทางซ้าย กระต่ายยืนเป็นตัวที่ 2 จากหัวแถว มีสัตว์ยืนข้างหลังกระต่ายกี่ตัว' },
      visual: { type: 'row', sides: true, items: ['friend-cat', 'friend-rabbit', 'friend-seal', 'friend-penguin', 'friend-turtle'] },
      options: [{ id: 'a', text: '2 ตัว' }, { id: 'b', text: '4 ตัว' }, { id: 'c', text: '3 ตัว' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการคิดเรื่องลำดับที่',
      review: {
        summary: 'ข้างหลังกระต่ายมีแมวน้ำ เพนกวิน และเต่า 3 ตัว',
        hints: ['นับเฉพาะตัวที่อยู่ทางขวาของกระต่าย'],
        steps: ['หัวแถวอยู่ทางซ้าย แมวเป็นตัวที่ 1 กระต่ายเป็นตัวที่ 2', 'ข้างหลังกระต่ายคือแมวน้ำ เพนกวิน และเต่า นับได้ 3 ตัว ตอบข้อ 3'],
        transferIds: ['r-line-front-t'],
      },
    },
    {
      id: 'sc-paired-organ', type: 'main', subject: 'science', skillIds: ['body-parts'], familyId: 'body-parts', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'อวัยวะใดที่เรามีเป็นคู่ ซ้ายและขวา' },
      options: [{ id: 'a', text: 'จมูก' }, { id: 'b', text: 'ตา' }, { id: 'c', text: 'ปาก' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องร่างกาย',
      review: {
        summary: 'ตามีสองข้าง ซ้ายและขวา',
        hints: ['ลองจับที่หน้าตัวเอง อะไรมีสองข้าง'],
        steps: ['จมูกและปากเรามีอย่างละหนึ่ง', 'ตามีสองข้าง ซ้ายและขวา เหมือนหูและมือ ตอบข้อ 2'],
        transferIds: ['sc-single-organ-t'],
      },
    },
    {
      id: 'th-nickname-rooster', type: 'main', subject: 'thai', skillIds: ['listening-inference'], familyId: 'animal-nickname', difficulty: 2,
      sourceId: SRC, ...R, section: 'ฟังข้อความแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'เจ้าโต้งขันเสียงดังทุกเช้า ปลุกให้ทุกคนตื่นนอน เจ้าโต้งคือสัตว์ชนิดใด' },
      options: [{ id: 'a', image: 'pic-chicken', speech: 'ไก่' }, { id: 'b', image: 'pic-duck', speech: 'เป็ด' }, { id: 'c', image: 'pic-cat', speech: 'แมว' }],
      correctOptionId: 'a',
      narration: 'ฟังข้อความและชื่อสัตว์ได้ วัดการฟังแล้วคิดจากเบาะแส',
      review: {
        summary: 'เจ้าโต้งคือไก่ ไก่ตัวผู้ขันตอนเช้า',
        hints: ['สัตว์ตัวไหนขันเสียงดังตอนเช้า'],
        steps: ['เบาะแสคือ ขันเสียงดังทุกเช้า', 'ไก่ตัวผู้ขันตอนเช้า คนไทยเรียกไก่ตัวผู้ว่าเจ้าโต้ง ตอบข้อ 1'],
        transferIds: ['th-nickname-cat-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'sp-facing-north', type: 'main', subject: 'spatial', skillIds: ['compass-direction'], familyId: 'facing', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าเรายืนหันหน้าไปทางทิศเหนือ ทิศตะวันออกจะอยู่ทางไหนของเรา' },
      options: [{ id: 'a', text: 'มือซ้าย' }, { id: 'b', text: 'ข้างหลัง' }, { id: 'c', text: 'มือขวา' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการนึกภาพทิศในใจ (ไม่มีภาพช่วย)',
      review: {
        summary: 'หันหน้าทิศเหนือ ทิศตะวันออกอยู่ทางมือขวา',
        hints: ['นึกถึงลูกศรบอกทิศ ข้างบนคือเหนือ ข้างขวาคืออะไร'],
        steps: ['หันหน้าไปทางทิศเหนือ ทิศเหนือจึงอยู่ข้างหน้า', 'บนลูกศรบอกทิศ ทิศตะวันออกอยู่ทางขวาของทิศเหนือ จึงอยู่ทางมือขวา ตอบข้อ 3'],
        transferIds: ['sp-facing-behind-t'],
      },
    },
    {
      id: 'm-sister-age', type: 'main', subject: 'math', skillIds: ['word-problem-add'], familyId: 'age', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ฉันอายุ 6 ปี พี่อายุมากกว่าฉัน 2 ปี พี่อายุกี่ปี' },
      options: [{ id: 'a', text: '8 ปี' }, { id: 'b', text: '4 ปี' }, { id: 'c', text: '6 ปี' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการบวกจากโจทย์ปัญหา',
      review: {
        summary: '6 บวก 2 เท่ากับ 8 ปี',
        hints: ['มากกว่า แปลว่าต้องบวก'],
        steps: ['พี่อายุมากกว่าฉัน 2 ปี จึงเอา 6 บวก 2', '6 บวก 2 เท่ากับ 8 พี่อายุ 8 ปี ตอบข้อ 1'],
        column: { a: 6, op: '+', b: 2 },
        transferIds: ['m-older-age-t'],
      },
    },
    {
      id: 'r-skip-three', type: 'main', subject: 'reasoning', skillIds: ['number-pattern'], familyId: 'skip-count', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ตัวเลขเรียงกันแบบนี้ ช่องที่มีเครื่องหมายคำถามควรเป็นเลขใด' },
      visual: { type: 'number-row', items: [3, 6, 9, '?'] },
      options: [{ id: 'a', text: '10' }, { id: 'b', text: '12' }, { id: 'c', text: '15' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ เสียงไม่อ่านตัวเลขในแถว เด็กต้องดูเอง',
      review: {
        summary: 'นับเพิ่มทีละ 3 ต่อจาก 9 จึงเป็น 12',
        hints: ['แต่ละช่องเพิ่มขึ้นเท่าไร'],
        steps: ['3 ไป 6 เพิ่ม 3 และ 6 ไป 9 ก็เพิ่ม 3', 'ต่อจาก 9 เพิ่มอีก 3 ได้ 12 ตอบข้อ 2'],
        transferIds: ['r-skip-four-t'],
      },
    },
    {
      id: 'sp-count-boxes', type: 'main', subject: 'spatial', skillIds: ['count-blocks'], familyId: 'stacks', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'กล่องซ้อนกันเป็นขั้นบันได มีกล่องทั้งหมดกี่กล่อง' },
      visual: { type: 'stack', columns: [1, 2, 3] },
      options: [{ id: 'a', text: '5 กล่อง' }, { id: 'b', text: '7 กล่อง' }, { id: 'c', text: '6 กล่อง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ เสียงไม่บอกจำนวน เด็กต้องนับจากภาพเอง',
      review: {
        summary: 'มีกล่อง 1 บวก 2 บวก 3 เท่ากับ 6 กล่อง',
        hints: ['นับทีละแถวตั้ง จากซ้ายไปขวา'],
        steps: ['แถวแรกมี 1 กล่อง แถวที่สองมี 2 กล่อง แถวที่สามมี 3 กล่อง', '1 บวก 2 บวก 3 เท่ากับ 6 กล่อง ตอบข้อ 3'],
        transferIds: ['sp-count-boxes-t'],
      },
    },
    {
      id: 'g-flag-colours', type: 'main', subject: 'general', skillIds: ['nation-symbols'], familyId: 'thai-flag', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ธงชาติไทยมีกี่สี' },
      options: [{ id: 'a', text: '3 สี' }, { id: 'b', text: '2 สี' }, { id: 'c', text: '5 สี' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสัญลักษณ์ของชาติ',
      review: {
        summary: 'ธงชาติไทยมี 3 สี แดง ขาว น้ำเงิน',
        hints: ['นึกถึงธงที่เสาหน้าโรงเรียน'],
        steps: ['ธงชาติไทยเรียกว่าธงไตรรงค์', 'มี 3 สี คือ สีแดง สีขาว และสีน้ำเงิน ตอบข้อ 1'],
        transferIds: ['g-flag-missing-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-stickers-sub', type: 'main', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'sub-2digit-borrow', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ลิลลี่มีสติกเกอร์ 32 แผ่น ให้เพื่อนไป 15 แผ่น ลิลลี่เหลือสติกเกอร์กี่แผ่น' },
      options: [{ id: 'a', text: '23 แผ่น' }, { id: 'b', text: '17 แผ่น' }, { id: 'c', text: '27 แผ่น' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการลบที่ต้องยืม',
      review: {
        summary: '32 ลบ 15 เท่ากับ 17 แผ่น',
        hints: ['ให้เพื่อนไปแล้วเหลือน้อยลง ต้องลบ'],
        steps: [
          'ให้เพื่อนไป สติกเกอร์น้อยลง จึงใช้การลบ 32 ลบ 15',
          'หลักหน่วย 2 ลบ 5 ไม่พอ ยืม 1 สิบ มาเป็น 12 แล้ว 12 ลบ 5 ได้ 7',
          'หลักสิบเหลือ 2 ลบ 1 ได้ 1 รวมเป็น 17 แผ่น ตอบข้อ 2',
        ],
        column: { a: 32, op: '-', b: 15 },
        transferIds: ['m-sub-borrow-t'],
      },
    },
    {
      id: 'sc-ice-melt', type: 'main', subject: 'science', skillIds: ['states-of-matter'], familyId: 'water-states', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าวางน้ำแข็งไว้กลางแดดนานๆ น้ำแข็งจะเป็นอย่างไร' },
      options: [{ id: 'a', text: 'แข็งขึ้น' }, { id: 'b', text: 'กลายเป็นหิน' }, { id: 'c', text: 'ละลายเป็นน้ำ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องน้ำ',
      review: {
        summary: 'น้ำแข็งโดนความร้อนจะละลายเป็นน้ำ',
        hints: ['ไอศกรีมกลางแดดเป็นอย่างไร'],
        steps: ['แดดร้อน ทำให้น้ำแข็งอุ่นขึ้น', 'น้ำแข็งจึงละลายกลายเป็นน้ำ ตอบข้อ 3'],
        transferIds: ['sc-freeze-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-new-year-shirt-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'วันปีใหม่ พ่อพาใบเตยไปทำบุญที่วัด ใบเตยใส่เสื้อสีฟ้ากับกระโปรงสีขาว ใบเตยใส่เสื้อสีอะไร' },
      options: [{ id: 'a', text: 'สีขาว' }, { id: 'b', text: 'สีชมพู' }, { id: 'c', text: 'สีฟ้า' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ใบเตยใส่เสื้อสีฟ้า', hints: [], steps: ['เรื่องบอกว่า เสื้อสีฟ้ากับกระโปรงสีขาว', 'เสื้อเป็นสีฟ้า ส่วนสีขาวคือกระโปรง'] },
    },
    {
      id: 'g-new-year-date-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'วันขึ้นปีใหม่ตรงกับวันที่เท่าไร' },
      options: [{ id: 'a', text: '12 สิงหาคม' }, { id: 'b', text: '1 มกราคม' }, { id: 'c', text: '5 ธันวาคม' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วันขึ้นปีใหม่คือวันที่ 1 มกราคม', hints: [], steps: ['มกราคมเป็นเดือนแรกของปี', 'วันแรกของปีคือวันที่ 1 มกราคม'] },
    },
    {
      id: 'r-line-front-t', type: 'transfer', subject: 'reasoning', skillIds: ['order-position'], familyId: 'line-position', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สัตว์ 4 ตัวเข้าแถว หัวแถวอยู่ทางซ้าย เต่ายืนอยู่ท้ายแถว มีสัตว์ยืนข้างหน้าเต่ากี่ตัว' },
      visual: { type: 'row', sides: true, items: ['friend-seal', 'friend-penguin', 'friend-cat', 'friend-turtle'] },
      options: [{ id: 'a', text: '2 ตัว' }, { id: 'b', text: '3 ตัว' }, { id: 'c', text: '4 ตัว' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ข้างหน้าเต่ามี 3 ตัว', hints: [], steps: ['เต่าอยู่ท้ายแถว ทางขวาสุด', 'ข้างหน้าเต่าคือแมวน้ำ เพนกวิน และแมว นับได้ 3 ตัว'] },
    },
    {
      id: 'sc-single-organ-t', type: 'transfer', subject: 'science', skillIds: ['body-parts'], familyId: 'body-parts', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'อวัยวะใดที่เรามีเพียงหนึ่งเดียว' },
      options: [{ id: 'a', text: 'หู' }, { id: 'b', text: 'จมูก' }, { id: 'c', text: 'มือ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'จมูกมีเพียงหนึ่งเดียว', hints: [], steps: ['หูและมือมีสองข้าง ซ้ายและขวา', 'จมูกมีเพียงหนึ่งเดียวอยู่กลางหน้า'] },
    },
    {
      id: 'th-nickname-cat-t', type: 'transfer', subject: 'thai', skillIds: ['listening-inference'], familyId: 'animal-nickname', difficulty: 2,
      sourceId: SRC, ...R, section: 'ฟังข้อความแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'เจ้าเหมียวร้องเหมียวๆ ชอบนอนขดตัวบนเก้าอี้ เจ้าเหมียวคือสัตว์ชนิดใด' },
      options: [{ id: 'a', image: 'pic-duck', speech: 'เป็ด' }, { id: 'b', image: 'pic-fish', speech: 'ปลา' }, { id: 'c', image: 'pic-cat', speech: 'แมว' }],
      correctOptionId: 'c',
      narration: 'ฟังข้อความและชื่อสัตว์ได้',
      review: { summary: 'เจ้าเหมียวคือแมว', hints: [], steps: ['เบาะแสคือ ร้องเหมียวๆ', 'แมวร้องเหมียว จึงเป็นแมว'] },
    },
    {
      id: 'sp-facing-behind-t', type: 'transfer', subject: 'spatial', skillIds: ['compass-direction'], familyId: 'facing', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าเรายืนหันหน้าไปทางทิศเหนือ ข้างหลังของเราเป็นทิศใด' },
      options: [{ id: 'a', text: 'ทิศใต้' }, { id: 'b', text: 'ทิศตะวันออก' }, { id: 'c', text: 'ทิศเหนือ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'หันหน้าทิศเหนือ ข้างหลังคือทิศใต้', hints: [], steps: ['ทิศเหนือกับทิศใต้อยู่ตรงข้ามกัน', 'หันหน้าทิศเหนือ ข้างหลังจึงเป็นทิศใต้'] },
    },
    {
      id: 'm-older-age-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-add'], familyId: 'age', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'น้องอายุ 4 ปี ฉันอายุมากกว่าน้อง 3 ปี ฉันอายุกี่ปี' },
      options: [{ id: 'a', text: '7 ปี' }, { id: 'b', text: '1 ปี' }, { id: 'c', text: '8 ปี' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '4 บวก 3 เท่ากับ 7 ปี', hints: [], steps: ['ฉันอายุมากกว่าน้อง 3 ปี จึงเอา 4 บวก 3', '4 บวก 3 เท่ากับ 7 ปี'], column: { a: 4, op: '+', b: 3 } },
    },
    {
      id: 'r-skip-four-t', type: 'transfer', subject: 'reasoning', skillIds: ['number-pattern'], familyId: 'skip-count', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ตัวเลขเรียงกันแบบนี้ ช่องที่มีเครื่องหมายคำถามควรเป็นเลขใด' },
      visual: { type: 'number-row', items: [4, 8, 12, '?'] },
      options: [{ id: 'a', text: '14' }, { id: 'b', text: '13' }, { id: 'c', text: '16' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เพิ่มทีละ 4 ต่อจาก 12 จึงเป็น 16', hints: [], steps: ['4 ไป 8 เพิ่ม 4 และ 8 ไป 12 ก็เพิ่ม 4', 'ต่อจาก 12 เพิ่มอีก 4 ได้ 16'] },
    },
    {
      id: 'sp-count-boxes-t', type: 'transfer', subject: 'spatial', skillIds: ['count-blocks'], familyId: 'stacks', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'กล่องซ้อนกันแบบนี้ มีกล่องทั้งหมดกี่กล่อง' },
      visual: { type: 'stack', columns: [3, 2, 2] },
      options: [{ id: 'a', text: '6 กล่อง' }, { id: 'b', text: '7 กล่อง' }, { id: 'c', text: '8 กล่อง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มีกล่อง 3 บวก 2 บวก 2 เท่ากับ 7 กล่อง', hints: [], steps: ['แถวตั้งแรกมี 3 กล่อง แถวที่สองและสามมีแถวละ 2 กล่อง', '3 บวก 2 บวก 2 เท่ากับ 7 กล่อง'] },
    },
    {
      id: 'g-flag-missing-t', type: 'transfer', subject: 'general', skillIds: ['nation-symbols'], familyId: 'thai-flag', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สีใดไม่มีในธงชาติไทย' },
      options: [{ id: 'a', text: 'สีแดง' }, { id: 'b', text: 'สีขาว' }, { id: 'c', text: 'สีเขียว' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ธงชาติไทยไม่มีสีเขียว', hints: [], steps: ['ธงชาติไทยมีสีแดง สีขาว และสีน้ำเงิน', 'สีเขียวไม่มีในธงชาติไทย'] },
    },
    {
      id: 'm-sub-borrow-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'sub-2digit-borrow', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'มีดินสอสี 41 แท่ง แจกเพื่อนไป 16 แท่ง เหลือดินสอสีกี่แท่ง' },
      options: [{ id: 'a', text: '25 แท่ง' }, { id: 'b', text: '35 แท่ง' }, { id: 'c', text: '37 แท่ง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '41 ลบ 16 เท่ากับ 25 แท่ง', hints: [], steps: ['หลักหน่วย 1 ลบ 6 ไม่พอ ยืม 1 สิบ มาเป็น 11 ลบ 6 ได้ 5', 'หลักสิบเหลือ 3 ลบ 1 ได้ 2 รวมเป็น 25 แท่ง'], column: { a: 41, op: '-', b: 16 } },
    },
    {
      id: 'sc-freeze-t', type: 'transfer', subject: 'science', skillIds: ['states-of-matter'], familyId: 'water-states', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าใส่น้ำไว้ในช่องแข็งของตู้เย็น น้ำจะกลายเป็นอะไร' },
      options: [{ id: 'a', text: 'ไอน้ำ' }, { id: 'b', text: 'น้ำแข็ง' }, { id: 'c', text: 'ทราย' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'น้ำในช่องแข็งกลายเป็นน้ำแข็ง', hints: [], steps: ['ช่องแข็งของตู้เย็นเย็นมาก', 'น้ำเย็นจัดจะแข็งตัวกลายเป็นน้ำแข็ง'] },
    },
  ],
};
