/*
 * ชุดที่ 12 — รูปแบบใหม่ตามการอ่านข้อสอบเก่ารอบ 2 (2026-09-27, docs/QUESTION-TYPES.md หัวข้อ "รูปแบบชุด 12 ขึ้นไป")
 * 15 ข้อหลัก 3 ช่วง: ช่วง 1 ฟังเรื่องเดียวถาม 5 ข้อ / ช่วง 2 แผ่นรูปของใช้ถาม 5 ข้อ / ช่วง 3 เลขหลายขั้น ภาพต่อเนื่อง มารยาท เครือญาติ
 * แต่งใหม่ทั้งหมด ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพจากข้อสอบเก่า; ภาพต่อเนื่องวาดด้วยโค้ด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LISTEN = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const BOARD_SECTION = 'ดูภาพของใช้แล้วตอบคำถามให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';
const BOARD = { type: 'board', items: ['pic-fan', 'pic-tv', 'pic-broom', 'pic-dustpan', 'pic-pencil', 'pic-eraser', 'pic-ruler', 'pic-wok', 'pic-spoon', 'pic-ball', 'pic-sweater', 'pic-raincoat'] };
const BOARD_TEXT = 'ในภาพมีของ 12 อย่าง คือ พัดลม โทรทัศน์ ไม้กวาด ที่ตักผง ดินสอ ยางลบ ไม้บรรทัด กระทะ ช้อน ลูกบอล เสื้อไหมพรม และเสื้อกันฝน';

export default {
  id: 'set-12',
  version: 1,
  title: 'ชุดที่ 12',
  note: 'แบบใหม่ 15 ข้อ: เรื่องกระรอก ภาพของใช้ ภาพต่อเนื่อง',
  order: [
    'th-squirrel-home', 'r-squirrel-count', 'th-squirrel-why', 'th-word-ashamed', 'g-squirrel-lesson',
    'sc-board-electric', 'r-board-pair', 'g-board-clothes', 'm-board-count', 'sc-board-no-power',
    'm-two-things', 'sp-wheel-next', 'sp-arrow-turn', 'g-say-sorry', 'th-kin-grandma',
  ],
  stimuli: {
    squirrels: {
      section: LISTEN,
      text: 'ที่สวนหลังบ้าน มีกระรอก 3 ตัว อาศัยอยู่บนต้นมะม่วงต้นใหญ่ ทุกวันกระรอกพี่ใหญ่ออกไปเก็บลูกไม้มาเก็บไว้ในโพรงต้นไม้ แต่กระรอกน้องสองตัวชอบวิ่งเล่นทั้งวัน ไม่ยอมช่วยพี่ วันหนึ่งฝนตกหนักติดกันหลายวัน กระรอกออกไปหาอาหารไม่ได้ กระรอกน้องหิวมาก พี่ใหญ่จึงแบ่งลูกไม้ในโพรงให้น้องกิน กระรอกน้องรู้สึกละอายใจ และสัญญาว่าจะช่วยพี่เก็บอาหารทุกวัน',
    },
    things: { section: BOARD_SECTION, text: BOARD_TEXT, visual: BOARD },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: เรื่องเดียว 5 ข้อ
    {
      id: 'th-squirrel-home', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-where', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'squirrels',
      prompt: { text: 'กระรอกอาศัยอยู่ที่ไหน' },
      options: [{ id: 'a', text: 'บนต้นมะม่วง' }, { id: 'b', text: 'ใต้ต้นมะพร้าว' }, { id: 'c', text: 'ในบ้าน' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'กระรอกทั้งสามตัวอยู่บนต้นมะม่วงต้นใหญ่',
        hints: ['ฟังประโยคแรกของเรื่องอีกครั้ง'],
        steps: ['ต้นเรื่องบอกว่า กระรอกอาศัยอยู่บนต้นมะม่วงต้นใหญ่', 'จึงอยู่บนต้นมะม่วง ตอบข้อ 1'],
        transferIds: ['th-bird-home-t'],
      },
    },
    {
      id: 'r-squirrel-count', type: 'main', subject: 'reasoning', skillIds: ['story-count'], familyId: 'story-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'squirrels',
      prompt: { text: 'เรื่องนี้มีกระรอกทั้งหมดกี่ตัว' },
      options: [{ id: 'a', text: '2 ตัว' }, { id: 'b', text: '3 ตัว' }, { id: 'c', text: '4 ตัว' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการฟังและนับ (ระวังคำว่า น้องสองตัว)',
      review: {
        summary: 'พี่ใหญ่ 1 ตัว กับน้องอีก 2 ตัว รวมเป็น 3 ตัว',
        hints: ['นับพี่ใหญ่ด้วย อย่านับแค่น้อง'],
        steps: ['เรื่องบอกว่ามีกระรอกพี่ใหญ่ และกระรอกน้องสองตัว', 'พี่ 1 ตัว บวกน้อง 2 ตัว เท่ากับ 3 ตัว ตอบข้อ 2'],
        transferIds: ['r-cat-dog-count-t'],
      },
    },
    {
      id: 'th-squirrel-why', type: 'main', subject: 'thai', skillIds: ['cause-effect'], familyId: 'story-why', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'squirrels',
      prompt: { text: 'ทำไมกระรอกจึงออกไปหาอาหารไม่ได้' },
      options: [{ id: 'a', text: 'เพราะกระรอกป่วย' }, { id: 'b', text: 'เพราะกระรอกหลงทาง' }, { id: 'c', text: 'เพราะฝนตกหนักหลายวัน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการฟังหาเหตุผล',
      review: {
        summary: 'ฝนตกหนักติดต่อกัน กระรอกจึงออกไปไม่ได้',
        hints: ['ฟังว่าเกิดอะไรขึ้นในวันหนึ่ง'],
        steps: ['เรื่องไม่ได้บอกว่ากระรอกป่วยหรือหลงทาง', 'เรื่องบอกว่าฝนตกหนักติดกันหลายวัน จึงออกไปหาอาหารไม่ได้ ตอบข้อ 3'],
        transferIds: ['th-fever-why-t'],
      },
    },
    {
      id: 'th-word-ashamed', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'squirrels',
      prompt: { text: 'คำว่า ละอายใจ หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'ดีใจมาก' }, { id: 'b', text: 'รู้สึกผิด และอยากทำให้ดีขึ้น' }, { id: 'c', text: 'โกรธพี่' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ วัดความเข้าใจความหมายคำจากเรื่อง',
      review: {
        summary: 'ละอายใจ คือรู้สึกผิดกับสิ่งที่ทำไป',
        hints: ['น้องไม่ช่วยพี่ แต่พี่ยังแบ่งอาหารให้ น้องจะรู้สึกอย่างไร'],
        steps: ['น้องไม่ช่วยเก็บอาหาร แต่พี่ยังใจดีแบ่งให้กิน', 'น้องจึงรู้สึกผิด และสัญญาว่าจะช่วยพี่ นี่คือละอายใจ ตอบข้อ 2'],
        transferIds: ['th-word-diligent-t'],
      },
    },
    {
      id: 'g-squirrel-lesson', type: 'main', subject: 'general', skillIds: ['story-moral'], familyId: 'story-moral', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'squirrels',
      prompt: { text: 'เรื่องนี้สอนให้รู้ว่าอย่างไร' },
      options: [{ id: 'a', text: 'ควรช่วยกันทำงาน และเก็บไว้ใช้ยามจำเป็น' }, { id: 'b', text: 'ควรวิ่งเล่นให้มากที่สุด' }, { id: 'c', text: 'ไม่ควรแบ่งของให้ใคร' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการจับข้อคิดของเรื่อง',
      review: {
        summary: 'ขยันช่วยกันเก็บอาหาร จะมีกินตอนลำบาก',
        hints: ['ใครมีอาหารกินตอนฝนตก เพราะอะไร'],
        steps: ['พี่ใหญ่ขยันเก็บอาหาร จึงมีกินตอนฝนตก และยังแบ่งให้น้องได้', 'เรื่องนี้สอนให้ช่วยกันทำงานและเก็บไว้ใช้ ตอบข้อ 1'],
        transferIds: ['g-ants-lesson-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: แผ่นรูปของใช้ 5 ข้อ
    {
      id: 'sc-board-electric', type: 'main', subject: 'science', skillIds: ['electricity'], familyId: 'board-classify', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'things',
      prompt: { text: 'ข้อใดเป็นเครื่องใช้ไฟฟ้าทั้งสองอย่าง' },
      options: [{ id: 'a', text: 'ไม้กวาด, พัดลม' }, { id: 'b', text: 'พัดลม, โทรทัศน์' }, { id: 'c', text: 'ดินสอ, ยางลบ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มของใช้',
      review: {
        summary: 'พัดลมกับโทรทัศน์ต้องเสียบปลั๊กทั้งคู่',
        hints: ['ต้องเป็นเครื่องใช้ไฟฟ้าครบทั้งสองอย่าง'],
        steps: ['ข้อ 1 ไม้กวาดไม่ใช้ไฟฟ้า ข้อ 3 ดินสอกับยางลบไม่ใช้ไฟฟ้า', 'พัดลมและโทรทัศน์ใช้ไฟฟ้าทั้งคู่ ตอบข้อ 2'],
        transferIds: ['sc-board-electric-count-t'],
      },
    },
    {
      id: 'r-board-pair', type: 'main', subject: 'reasoning', skillIds: ['relationship'], familyId: 'board-pair', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'things',
      prompt: { text: 'ของสองอย่างในข้อใดต้องใช้ด้วยกัน' },
      options: [{ id: 'a', text: 'ไม้กวาด, ที่ตักผง' }, { id: 'b', text: 'ลูกบอล, กระทะ' }, { id: 'c', text: 'ช้อน, ไม้บรรทัด' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการจับคู่ของที่ใช้ด้วยกัน',
      review: {
        summary: 'กวาดขยะแล้วใช้ที่ตักผงตักขึ้นมา',
        hints: ['คิดว่าของคู่ไหนทำงานเดียวกัน'],
        steps: ['ลูกบอลกับกระทะ ช้อนกับไม้บรรทัด ใช้ทำงานคนละอย่าง', 'ไม้กวาดกับที่ตักผงใช้ทำความสะอาดด้วยกัน ตอบข้อ 1'],
        transferIds: ['r-board-writing-t'],
      },
    },
    {
      id: 'g-board-clothes', type: 'main', subject: 'general', skillIds: ['classify'], familyId: 'board-classify', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'things',
      prompt: { text: 'ข้อใดเป็นเครื่องแต่งกาย' },
      options: [{ id: 'a', text: 'กระทะ, ช้อน' }, { id: 'b', text: 'ดินสอ, ลูกบอล' }, { id: 'c', text: 'เสื้อไหมพรม, เสื้อกันฝน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการรู้จักคำเรียกกลุ่มของ',
      review: {
        summary: 'เครื่องแต่งกายคือของที่สวมใส่บนตัวเรา',
        hints: ['ของอะไรที่เราใส่ได้'],
        steps: ['กระทะกับช้อนเป็นเครื่องครัว ดินสอเป็นเครื่องเขียน ลูกบอลเป็นของเล่น', 'เสื้อทั้งสองตัวใส่บนตัว จึงเป็นเครื่องแต่งกาย ตอบข้อ 3'],
        transferIds: ['g-board-rain-t'],
      },
    },
    {
      id: 'm-board-count', type: 'main', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'things',
      prompt: { text: 'ในภาพมีเครื่องเขียนกี่อย่าง' },
      options: [{ id: 'a', text: '2 อย่าง' }, { id: 'b', text: '3 อย่าง' }, { id: 'c', text: '4 อย่าง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มแล้วนับ',
      review: {
        summary: 'ดินสอ ยางลบ ไม้บรรทัด เป็นเครื่องเขียน 3 อย่าง',
        hints: ['หาของที่ใช้ตอนเขียนหนังสือ แล้วนับ'],
        steps: ['เครื่องเขียนในภาพมี ดินสอ ยางลบ และไม้บรรทัด', 'นับได้ หนึ่ง สอง สาม เป็น 3 อย่าง ตอบข้อ 2'],
        transferIds: ['m-board-kitchen-t'],
      },
    },
    {
      id: 'sc-board-no-power', type: 'main', subject: 'science', skillIds: ['electricity'], familyId: 'board-no-power', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'things',
      prompt: { text: 'ข้อใดใช้แรงคนทำงาน ไม่ต้องใช้ไฟฟ้าทั้งสองอย่าง' },
      options: [{ id: 'a', text: 'โทรทัศน์, ไม้กวาด' }, { id: 'b', text: 'พัดลม, โทรทัศน์' }, { id: 'c', text: 'ไม้กวาด, ช้อน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องไฟฟ้าและแรง',
      review: {
        summary: 'ไม้กวาดกับช้อนใช้มือเราทำงาน',
        hints: ['ต้องไม่ใช้ไฟฟ้าครบทั้งสองอย่าง'],
        steps: ['ข้อ 1 มีโทรทัศน์ที่ใช้ไฟฟ้า ข้อ 2 ใช้ไฟฟ้าทั้งคู่', 'ไม้กวาดกับช้อนใช้แรงมือ ไม่ใช้ไฟฟ้า ตอบข้อ 3'],
        transferIds: ['sc-board-power-cut-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-two-things', type: 'main', subject: 'math', skillIds: ['multi-step'], familyId: 'two-quantities', difficulty: 3,
      sourceId: SRC, ...R, section: 'ฟังโจทย์แล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ในจานมีส้ม 5 ผล กล้วย 3 ลูก น้องกินส้มไป 2 ผล แม่เอากล้วยมาเพิ่มอีก 4 ลูก ตอนนี้ในจานมีส้มและกล้วยอย่างละเท่าไร' },
      visual: { type: 'scatter', items: [{ asset: 'pic-orange', count: 5 }, { asset: 'pic-banana', count: 3 }] },
      options: [{ id: 'a', text: 'ส้ม 3 ผล กล้วย 7 ลูก' }, { id: 'b', text: 'ส้ม 7 ผล กล้วย 3 ลูก' }, { id: 'c', text: 'ส้ม 3 ผล กล้วย 3 ลูก' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการคิดสองขั้นและติดตามของสองอย่าง',
      review: {
        summary: 'ส้มเหลือ 3 ผล กล้วยเพิ่มเป็น 7 ลูก',
        hints: ['คิดทีละอย่าง ส้มก่อน แล้วค่อยกล้วย'],
        steps: ['ส้ม: มี 5 ผล กินไป 2 ผล 5 ลบ 2 เหลือ 3 ผล', 'กล้วย: มี 3 ลูก เพิ่มอีก 4 ลูก 3 บวก 4 เป็น 7 ลูก', 'ส้ม 3 ผล กล้วย 7 ลูก ตอบข้อ 1'],
        transferIds: ['m-fridge-things-t'],
      },
    },
    {
      id: 'sp-wheel-next', type: 'main', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'wheel-sequence', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ช่องที่ระบายสีเลื่อนไปทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ wheel: 0 }, { wheel: 2 }, { wheel: 4 }, '?'] },
      options: [{ id: 'a', svg: { figure: { wheel: 5 } } }, { id: 'b', svg: { figure: { wheel: 7 } } }, { id: 'c', svg: { figure: { wheel: 0 } } }, { id: 'd', svg: { figure: { wheel: 6 } } }],
      correctOptionId: 'd',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหาแบบรูปของการหมุน',
      review: {
        summary: 'ช่องสีดำเลื่อนตามเข็มนาฬิกาทีละ 2 ช่อง',
        hints: ['ดูว่าจากภาพแรกไปภาพที่สอง ช่องสีดำเลื่อนไปกี่ช่อง'],
        steps: ['จากภาพแรกไปภาพที่สอง ช่องสีดำเลื่อนตามเข็มนาฬิกา 2 ช่อง ภาพที่สามก็เลื่อนอีก 2 ช่อง', 'ช่องสีดำอยู่ ด้านบน ด้านขวา ด้านล่าง ภาพต่อไปจึงเลื่อนอีก 2 ช่อง ไปอยู่ด้านซ้าย ตอบข้อ 4'],
        transferIds: ['sp-wheel-one-step-t'],
      },
    },
    {
      id: 'sp-arrow-turn', type: 'main', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'arrow-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ลูกศรหมุนไปทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ arrow: 'up' }, { arrow: 'right' }, { arrow: 'down' }, '?'] },
      options: [{ id: 'a', svg: { figure: { arrow: 'up' } } }, { id: 'b', svg: { figure: { arrow: 'right' } } }, { id: 'c', svg: { figure: { arrow: 'left' } } }, { id: 'd', svg: { figure: { arrow: 'down' } } }],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหาแบบรูปของการหมุน',
      review: {
        summary: 'ลูกศรหมุนตามเข็มนาฬิกา ขึ้น ขวา ลง ซ้าย',
        hints: ['ลูกศรชี้ ขึ้น แล้วขวา แล้วลง ต่อไปชี้ทางไหน'],
        steps: ['ลูกศรหมุนตามเข็มนาฬิกาทีละหนึ่งในสี่รอบ ขึ้น ขวา ลง', 'ต่อจากลง จึงชี้ไปทางซ้าย ตอบข้อ 3'],
        transferIds: ['sp-dots-grow-t'],
      },
    },
    {
      id: 'g-say-sorry', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'manners-words', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าหนูเดินชนเพื่อน จนหนังสือของเพื่อนตกพื้น หนูควรพูดว่าอย่างไร' },
      options: [{ id: 'a', text: 'สวัสดีค่ะ' }, { id: 'b', text: 'ขอบคุณค่ะ' }, { id: 'c', text: 'ขอโทษค่ะ' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ วัดมารยาทในการพูด',
      review: {
        summary: 'ทำให้เพื่อนเดือดร้อน ต้องพูดขอโทษ แล้วช่วยเก็บ',
        hints: ['เราทำผิดกับเพื่อน ควรพูดคำไหน'],
        steps: ['สวัสดีใช้ทักทาย ขอบคุณใช้เมื่อมีคนช่วยเรา', 'เมื่อเราทำให้เพื่อนเดือดร้อน ต้องพูดขอโทษ ตอบข้อ 3'],
        transferIds: ['g-say-thanks-t'],
      },
    },
    {
      id: 'th-kin-grandma', type: 'main', subject: 'thai', skillIds: ['kinship-words'], familyId: 'kinship', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'คุณย่าของหนู คือใคร' },
      options: [{ id: 'a', text: 'แม่ของพ่อ' }, { id: 'b', text: 'แม่ของแม่' }, { id: 'c', text: 'พี่สาวของแม่' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ วัดการรู้จักคำเรียกญาติ',
      review: {
        summary: 'ย่าเป็นแม่ของพ่อ ส่วนยายเป็นแม่ของแม่',
        hints: ['ปู่กับย่าเป็นพ่อแม่ของพ่อ'],
        steps: ['ฝั่งพ่อ เรียกว่า ปู่ และ ย่า ฝั่งแม่ เรียกว่า ตา และ ยาย', 'คุณย่าจึงเป็นแม่ของพ่อ ตอบข้อ 1'],
        transferIds: ['th-kin-uncle-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-bird-home-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-where', difficulty: 1,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ลูกนกสามตัวอาศัยอยู่ในรังบนต้นมะขาม ทุกเช้าแม่นกบินไปหาหนอนมาป้อน ลูกนกอาศัยอยู่ที่ไหน' },
      options: [{ id: 'a', text: 'ในบ่อน้ำ' }, { id: 'b', text: 'ในรังบนต้นมะขาม' }, { id: 'c', text: 'ในถ้ำ' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ลูกนกอยู่ในรังบนต้นมะขาม', hints: [], steps: ['เรื่องบอกว่า ลูกนกอยู่ในรังบนต้นมะขาม', 'จึงตอบว่าในรังบนต้นมะขาม'] },
    },
    {
      id: 'r-cat-dog-count-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-count'], familyId: 'story-count', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'แม่แมวพาลูกแมว 2 ตัวไปเดินเล่น แล้วเจอหมาอีก 1 ตัว เรื่องนี้มีสัตว์ทั้งหมดกี่ตัว' },
      options: [{ id: 'a', text: '3 ตัว' }, { id: 'b', text: '2 ตัว' }, { id: 'c', text: '4 ตัว' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'แม่แมว 1 ลูกแมว 2 หมา 1 รวม 4 ตัว', hints: [], steps: ['นับแม่แมวด้วย 1 ตัว ลูกแมว 2 ตัว และหมา 1 ตัว', '1 บวก 2 บวก 1 เท่ากับ 4 ตัว'] },
    },
    {
      id: 'th-fever-why-t', type: 'transfer', subject: 'thai', skillIds: ['cause-effect'], familyId: 'story-why', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'วันนี้ต้นไม่ได้ไปโรงเรียน เพราะมีไข้สูงตั้งแต่เมื่อคืน ทำไมต้นจึงไม่ได้ไปโรงเรียน' },
      options: [{ id: 'a', text: 'เพราะไม่สบาย' }, { id: 'b', text: 'เพราะเป็นวันหยุด' }, { id: 'c', text: 'เพราะตื่นสาย' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ต้นมีไข้ จึงไม่สบาย', hints: [], steps: ['เรื่องบอกว่า ต้นมีไข้สูง', 'มีไข้คือไม่สบาย จึงไปโรงเรียนไม่ได้'] },
    },
    {
      id: 'th-word-diligent-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า ขยัน หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'ชอบนอนทั้งวัน' }, { id: 'b', text: 'ร้องไห้บ่อย' }, { id: 'c', text: 'ตั้งใจทำงาน ไม่เกียจคร้าน' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ขยัน คือตั้งใจทำงานเสมอ', hints: [], steps: ['กระรอกพี่ใหญ่ออกไปเก็บอาหารทุกวัน เป็นตัวอย่างของคนขยัน', 'ขยันจึงหมายถึงตั้งใจทำงาน ไม่เกียจคร้าน'] },
    },
    {
      id: 'g-ants-lesson-t', type: 'transfer', subject: 'general', skillIds: ['story-moral'], familyId: 'story-moral', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'มดหลายตัวช่วยกันแบกเม็ดข้าวกลับรัง จนเก็บอาหารได้มากมาย เรื่องนี้สอนเรื่องใด' },
      options: [{ id: 'a', text: 'ความสามัคคี' }, { id: 'b', text: 'ความขี้เกียจ' }, { id: 'c', text: 'ความซุกซน' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ช่วยกันทำงานคือความสามัคคี', hints: [], steps: ['มดตัวเดียวแบกได้นิดเดียว', 'แต่มดหลายตัวช่วยกันจึงเก็บได้มาก นี่คือความสามัคคี'] },
    },
    {
      id: 'sc-board-electric-count-t', type: 'transfer', subject: 'science', skillIds: ['electricity'], familyId: 'board-classify', difficulty: 1,
      sourceId: SRC, ...R, section: BOARD_SECTION,
      prompt: { text: 'ในภาพมีเครื่องใช้ไฟฟ้ากี่อย่าง' },
      visual: BOARD,
      options: [{ id: 'a', text: '1 อย่าง' }, { id: 'b', text: '2 อย่าง' }, { id: 'c', text: '3 อย่าง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'พัดลมกับโทรทัศน์ เป็นเครื่องใช้ไฟฟ้า 2 อย่าง', hints: [], steps: ['ของในภาพที่ต้องเสียบปลั๊กคือ พัดลม และโทรทัศน์', 'นับได้ 2 อย่าง'] },
    },
    {
      id: 'r-board-writing-t', type: 'transfer', subject: 'reasoning', skillIds: ['relationship'], familyId: 'board-pair', difficulty: 1,
      sourceId: SRC, ...R, section: BOARD_SECTION,
      prompt: { text: 'ของสองอย่างในข้อใดใช้ด้วยกันเวลาเขียนหนังสือ' },
      visual: BOARD,
      options: [{ id: 'a', text: 'กระทะ, ลูกบอล' }, { id: 'b', text: 'ดินสอ, ยางลบ' }, { id: 'c', text: 'พัดลม, ช้อน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เขียนด้วยดินสอ เขียนผิดใช้ยางลบ', hints: [], steps: ['ดินสอใช้เขียน', 'ยางลบใช้ลบเมื่อเขียนผิด จึงใช้ด้วยกัน'] },
    },
    {
      id: 'g-board-rain-t', type: 'transfer', subject: 'general', skillIds: ['classify'], familyId: 'board-classify', difficulty: 1,
      sourceId: SRC, ...R, section: BOARD_SECTION,
      prompt: { text: 'ถ้าฝนกำลังตก ควรหยิบของอย่างใดในภาพไปใช้' },
      visual: BOARD,
      options: [{ id: 'a', text: 'ลูกบอล' }, { id: 'b', text: 'พัดลม' }, { id: 'c', text: 'เสื้อกันฝน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เสื้อกันฝนช่วยไม่ให้ตัวเปียก', hints: [], steps: ['ฝนตกต้องกันไม่ให้ตัวเปียก', 'จึงใส่เสื้อกันฝน'] },
    },
    {
      id: 'm-board-kitchen-t', type: 'transfer', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R, section: BOARD_SECTION,
      prompt: { text: 'ในภาพมีของใช้ในครัวกี่อย่าง' },
      visual: BOARD,
      options: [{ id: 'a', text: '2 อย่าง' }, { id: 'b', text: '4 อย่าง' }, { id: 'c', text: '1 อย่าง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'กระทะกับช้อน เป็นของใช้ในครัว 2 อย่าง', hints: [], steps: ['ของที่ใช้ทำอาหารและกินข้าวคือ กระทะ และช้อน', 'นับได้ 2 อย่าง'] },
    },
    {
      id: 'sc-board-power-cut-t', type: 'transfer', subject: 'science', skillIds: ['electricity'], familyId: 'board-no-power', difficulty: 2,
      sourceId: SRC, ...R, section: BOARD_SECTION,
      prompt: { text: 'ถ้าไฟดับ ของในข้อใดยังใช้ได้ทั้งสองอย่าง' },
      visual: BOARD,
      options: [{ id: 'a', text: 'พัดลม, ลูกบอล' }, { id: 'b', text: 'ลูกบอล, ดินสอ' }, { id: 'c', text: 'โทรทัศน์, พัดลม' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ลูกบอลกับดินสอไม่ต้องใช้ไฟฟ้า', hints: [], steps: ['พัดลมและโทรทัศน์ใช้ไฟฟ้า ไฟดับจึงใช้ไม่ได้', 'ลูกบอลกับดินสอยังใช้ได้'] },
    },
    {
      id: 'm-fridge-things-t', type: 'transfer', subject: 'math', skillIds: ['multi-step'], familyId: 'two-quantities', difficulty: 3,
      sourceId: SRC, ...R, section: 'ฟังโจทย์แล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ในตู้เย็นมีนม 4 กล่อง ไข่ 6 ฟอง แม่ใช้ไข่ทำกับข้าว 3 ฟอง แล้วซื้อนมมาเพิ่ม 2 กล่อง ตอนนี้มีนมและไข่อย่างละเท่าไร' },
      options: [{ id: 'a', text: 'นม 2 กล่อง ไข่ 9 ฟอง' }, { id: 'b', text: 'นม 6 กล่อง ไข่ 6 ฟอง' }, { id: 'c', text: 'นม 6 กล่อง ไข่ 3 ฟอง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'นมเพิ่มเป็น 6 กล่อง ไข่เหลือ 3 ฟอง', hints: [], steps: ['นม: 4 บวก 2 เป็น 6 กล่อง', 'ไข่: 6 ลบ 3 เหลือ 3 ฟอง'] },
    },
    {
      id: 'sp-wheel-one-step-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'wheel-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ช่องที่ระบายสีเลื่อนไปทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ wheel: 1 }, { wheel: 2 }, { wheel: 3 }, '?'] },
      options: [{ id: 'a', svg: { figure: { wheel: 4 } } }, { id: 'b', svg: { figure: { wheel: 5 } } }, { id: 'c', svg: { figure: { wheel: 2 } } }, { id: 'd', svg: { figure: { wheel: 0 } } }],
      correctOptionId: 'a',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'ช่องสีดำเลื่อนตามเข็มนาฬิกาทีละ 1 ช่อง', hints: [], steps: ['แต่ละภาพ ช่องสีดำเลื่อนไป 1 ช่องตามเข็มนาฬิกา', 'ภาพต่อไปจึงเลื่อนอีก 1 ช่อง'] },
    },
    {
      id: 'sp-dots-grow-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'arrow-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'จำนวนจุดเพิ่มขึ้นทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ dots: 1 }, { dots: 3 }, { dots: 5 }, '?'] },
      options: [{ id: 'a', svg: { figure: { dots: 6 } } }, { id: 'b', svg: { figure: { dots: 8 } } }, { id: 'c', svg: { figure: { dots: 7 } } }, { id: 'd', svg: { figure: { dots: 9 } } }],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'จุดเพิ่มทีละ 2 คือ 1 3 5 7', hints: [], steps: ['จาก 1 จุดเป็น 3 จุด แล้วเป็น 5 จุด เพิ่มทีละ 2', 'ภาพต่อไปจึงมี 7 จุด'] },
    },
    {
      id: 'g-say-thanks-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'manners-words', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อเพื่อนให้หนูยืมดินสอ หนูควรพูดว่าอย่างไร' },
      options: [{ id: 'a', text: 'ขอโทษค่ะ' }, { id: 'b', text: 'ขอบคุณค่ะ' }, { id: 'c', text: 'ลาก่อนค่ะ' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'มีคนช่วยเรา ต้องพูดขอบคุณ', hints: [], steps: ['เพื่อนช่วยให้เรามีดินสอใช้', 'เราจึงพูดขอบคุณ'] },
    },
    {
      id: 'th-kin-uncle-t', type: 'transfer', subject: 'thai', skillIds: ['kinship-words'], familyId: 'kinship', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'คุณลุงของหนู คือใคร' },
      options: [{ id: 'a', text: 'น้องชายของพ่อ' }, { id: 'b', text: 'พ่อของแม่' }, { id: 'c', text: 'พี่ชายของพ่อหรือแม่' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ลุงเป็นพี่ชายของพ่อหรือของแม่', hints: [], steps: ['พี่ของพ่อหรือแม่ ผู้ชายเรียกลุง ผู้หญิงเรียกป้า', 'น้องชายของพ่อเรียก อา พ่อของแม่เรียก ตา'] },
    },
  ],
};
