/*
 * ชุดที่ 4 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 4 และ docs/QUESTION-TYPES.md) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * ใช้รูปเดิมจากแผ่น A/B เท่านั้น (ไม่ต้องสร้างรูปใหม่)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';

export default {
  id: 'set-04',
  version: 1,
  title: 'ชุดที่ 4',
  note: 'กิจวัตร นับขาสัตว์ อนุกรมลด ตัวอักษร ทิศ โหล',
  order: [
    'th-routine-first', 'sc-brush-teeth', 'm-count-legs', 'r-seq-down', 'g-first-month',
    'th-initial-letters', 'sp-sunrise', 'r-pairs', 'sc-color-mix', 'g-hospital',
    'm-dozen', 'sp-row-middle',
  ],
  stimuli: {
    routine: {
      section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      text: 'ตอนเช้านิดตื่นนอนแล้วเก็บที่นอนก่อน จากนั้นแปรงฟันและอาบน้ำ แต่งตัวไปโรงเรียน แล้วนั่งกินข้าวกับแม่ก่อนออกจากบ้าน',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'th-routine-first', type: 'main', subject: 'thai', skillIds: ['listening-sequence'], familyId: 'listen-sequence', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'routine',
      prompt: { text: 'หลังจากตื่นนอน นิดทำอะไรเป็นอย่างแรก' },
      options: [{ id: 'a', text: 'แปรงฟัน' }, { id: 'b', text: 'เก็บที่นอน' }, { id: 'c', text: 'กินข้าว' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังลำดับเหตุการณ์',
      review: {
        summary: 'ตื่นนอนแล้ว นิดเก็บที่นอนก่อน',
        hints: ['ฟังคำว่า ก่อน ในเรื่อง'],
        steps: ['เรื่องเล่าว่า ตื่นนอนแล้วเก็บที่นอนก่อน จากนั้นแปรงฟันและอาบน้ำ', 'อย่างแรกคือเก็บที่นอน ตอบข้อ 2'],
        transferIds: ['th-routine-t'],
      },
    },
    {
      id: 'sc-brush-teeth', type: 'main', subject: 'science', skillIds: ['hygiene'], familyId: 'hygiene', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'routine',
      prompt: { text: 'เราควรแปรงฟันเวลาใด' },
      options: [{ id: 'a', text: 'เฉพาะวันหยุด' }, { id: 'b', text: 'เมื่อรู้สึกหิว' }, { id: 'c', text: 'ตอนเช้าและก่อนเข้านอน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการดูแลสุขภาพ',
      review: {
        summary: 'ควรแปรงฟันตอนเช้าและก่อนเข้านอน',
        hints: ['วันละกี่ครั้ง ตอนไหนบ้าง'],
        steps: ['เราควรแปรงฟันทุกวัน อย่างน้อยวันละ 2 ครั้ง', 'ตอนเช้าหลังตื่นนอน และก่อนเข้านอน ฟันจะได้ไม่ผุ ตอบข้อ 3'],
        transferIds: ['sc-handwash-t'],
      },
    },
    {
      id: 'm-count-legs', type: 'main', subject: 'math', skillIds: ['count-legs'], familyId: 'count-legs', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ไก่ 2 ตัว และแมว 1 ตัว มีขารวมกันกี่ขา' },
      visual: { type: 'row', items: ['pic-chicken', 'pic-chicken', 'pic-cat'] },
      options: [{ id: 'a', text: '8 ขา' }, { id: 'b', text: '6 ขา' }, { id: 'c', text: '10 ขา' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการนับและบวกจำนวนขา',
      review: {
        summary: 'ไก่ 2 ตัวมี 4 ขา แมวมี 4 ขา รวม 8 ขา',
        hints: ['ไก่มีกี่ขา แมวมีกี่ขา'],
        steps: ['ไก่ 1 ตัวมี 2 ขา ไก่ 2 ตัวจึงมี 4 ขา', 'แมว 1 ตัวมี 4 ขา 4 บวก 4 เท่ากับ 8 ขา ตอบข้อ 1'],
        transferIds: ['m-legs-t'],
      },
    },
    {
      id: 'r-seq-down', type: 'main', subject: 'reasoning', skillIds: ['number-pattern'], familyId: 'number-sequence-down', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ตัวเลขเรียงกันแบบนี้ ช่องที่มีเครื่องหมายคำถามควรเป็นเลขใด' },
      visual: { type: 'number-row', items: [20, 18, 16, '?'] },
      options: [{ id: 'a', text: '15' }, { id: 'b', text: '14' }, { id: 'c', text: '12' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ เสียงไม่อ่านตัวเลขในแถว เด็กต้องดูเอง',
      review: {
        summary: 'ลดลงทีละ 2 ต่อจาก 16 จึงเป็น 14',
        hints: ['ตัวเลขมากขึ้นหรือน้อยลง ทีละเท่าไร'],
        steps: ['20 ไป 18 ลดลง 2 และ 18 ไป 16 ก็ลดลง 2', 'ต่อจาก 16 ลดลงอีก 2 ได้ 14 ตอบข้อ 2'],
        transferIds: ['r-seq-down-t'],
      },
    },
    {
      id: 'g-first-month', type: 'main', subject: 'general', skillIds: ['months'], familyId: 'months', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เดือนแรกของปีคือเดือนอะไร' },
      options: [{ id: 'a', text: 'ธันวาคม' }, { id: 'b', text: 'เมษายน' }, { id: 'c', text: 'มกราคม' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องเดือน',
      review: {
        summary: 'เดือนแรกของปีคือมกราคม',
        hints: ['วันขึ้นปีใหม่คือวันที่ 1 ของเดือนอะไร'],
        steps: ['วันขึ้นปีใหม่คือวันที่ 1 มกราคม', 'มกราคมจึงเป็นเดือนแรกของปี ส่วนธันวาคมเป็นเดือนสุดท้าย ตอบข้อ 3'],
        transferIds: ['g-last-month-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'th-initial-letters', type: 'main', subject: 'thai', skillIds: ['letter-sound'], familyId: 'initial-letters', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพเรียงจากซ้ายไปขวา ข้อใดเป็นพยัญชนะต้นของภาพตามลำดับ' },
      visual: { type: 'row', items: ['pic-fish', 'pic-horse', 'pic-chicken'] },
      options: [{ id: 'a', text: 'ป ม ก', speech: '' }, { id: 'b', text: 'ม ป ก', speech: '' }, { id: 'c', text: 'ป ก ม', speech: '' }],
      correctOptionId: 'a',
      narration: 'ตัวเลือกอ่านแค่หมายเลข เพราะข้อนี้วัดการรู้จักตัวอักษร (อ่านชื่อตัวอักษรให้ฟังจะเฉลย)',
      review: {
        summary: 'ปลา ม้า ไก่ ขึ้นต้นด้วย ป ม ก',
        hints: ['พูดชื่อภาพทีละภาพ ฟังเสียงแรก'],
        steps: ['ภาพแรกคือปลา ขึ้นต้นด้วย ปอ ภาพที่สองคือม้า ขึ้นต้นด้วย มอ', 'ภาพสุดท้ายคือไก่ ขึ้นต้นด้วย กอ เรียงได้ ปอ มอ กอ ตอบข้อ 1'],
        transferIds: ['th-letters-t'],
      },
    },
    {
      id: 'sp-sunrise', type: 'main', subject: 'spatial', skillIds: ['sun-direction'], familyId: 'sun-direction', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ตอนเช้า ดวงอาทิตย์ขึ้นทางทิศใด' },
      options: [{ id: 'a', text: 'ทิศตะวันออก' }, { id: 'b', text: 'ทิศตะวันตก' }, { id: 'c', text: 'ทิศเหนือ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องทิศ',
      review: {
        summary: 'ดวงอาทิตย์ขึ้นทางทิศตะวันออก',
        hints: ['ทิศที่ดวงอาทิตย์ขึ้นมีคำว่า ออก'],
        steps: ['ตอนเช้าดวงอาทิตย์ขึ้นทางทิศตะวันออก', 'ตอนเย็นดวงอาทิตย์ตกทางทิศตะวันตก ตอบข้อ 1'],
        transferIds: ['sp-sunset-t'],
      },
    },
    {
      id: 'r-pairs', type: 'main', subject: 'reasoning', skillIds: ['analogy'], familyId: 'analogy', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ช้อนใช้คู่กับข้าว แปรงสีฟันใช้คู่กับอะไร' },
      options: [{ id: 'a', text: 'ผม' }, { id: 'b', text: 'ฟัน' }, { id: 'c', text: 'รองเท้า' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการหาความสัมพันธ์ของสิ่งของ',
      review: {
        summary: 'แปรงสีฟันใช้คู่กับฟัน',
        hints: ['แปรงสีฟันใช้ทำอะไร'],
        steps: ['เราใช้ช้อนตักข้าว ช้อนจึงคู่กับข้าว', 'เราใช้แปรงสีฟันแปรงฟัน แปรงสีฟันจึงคู่กับฟัน ตอบข้อ 2'],
        transferIds: ['r-pairs-t'],
      },
    },
    {
      id: 'sc-color-mix', type: 'main', subject: 'science', skillIds: ['color-mixing'], familyId: 'color-mixing', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สีแดงผสมกับสีเหลือง จะได้สีอะไร' },
      options: [{ id: 'a', text: 'สีเขียว' }, { id: 'b', text: 'สีม่วง' }, { id: 'c', text: 'สีส้ม' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการผสมสี',
      review: {
        summary: 'แดงผสมเหลืองได้สีส้ม',
        hints: ['นึกถึงสีของผลส้ม'],
        steps: ['สีแดงผสมกับสีเหลือง จะได้สีส้ม', 'เหมือนสีของผลส้ม ตอบข้อ 3'],
        transferIds: ['sc-color-mix-t'],
      },
    },
    {
      id: 'g-hospital', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อไม่สบาย เราควรไปที่ใด' },
      options: [{ id: 'a', text: 'โรงพยาบาล' }, { id: 'b', text: 'ตลาด' }, { id: 'c', text: 'สวนสนุก' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสถานที่ในชุมชน',
      review: {
        summary: 'ไม่สบายควรไปโรงพยาบาล',
        hints: ['ที่ไหนมีหมอ'],
        steps: ['ตลาดใช้ซื้อของ สวนสนุกใช้เล่น', 'โรงพยาบาลมีหมอคอยรักษาคนป่วย ตอบข้อ 1'],
        transferIds: ['g-fire-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-dozen', type: 'main', subject: 'math', skillIds: ['dozen'], familyId: 'dozen', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ไข่ 1 โหล มีกี่ฟอง' },
      options: [{ id: 'a', text: '10 ฟอง' }, { id: 'b', text: '12 ฟอง' }, { id: 'c', text: '20 ฟอง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องหน่วยโหล',
      review: {
        summary: '1 โหล เท่ากับ 12',
        hints: ['โหลเป็นหน่วยนับของที่มีจำนวนเท่ากับเท่าไร'],
        steps: ['1 โหล คือของ 12 ชิ้น', 'ไข่ 1 โหลจึงมี 12 ฟอง ตอบข้อ 2'],
        transferIds: ['m-half-dozen-t'],
      },
    },
    {
      id: 'sp-row-middle', type: 'main', subject: 'spatial', skillIds: ['position-middle'], familyId: 'position', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดอยู่ตรงกลางแถว' },
      visual: { type: 'row', items: ['pic-egg', 'pic-spoon', 'pic-orange', 'pic-umbrella', 'pic-chair'] },
      options: [{ id: 'a', image: 'pic-egg', speech: 'ไข่' }, { id: 'b', image: 'pic-umbrella', speech: 'ร่ม' }, { id: 'c', image: 'pic-orange', speech: 'ส้ม' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกตำแหน่ง เด็กต้องดูแถวเอง',
      review: {
        summary: 'ส้มอยู่ตรงกลางแถว',
        hints: ['นับจากซ้ายและจากขวาให้เท่ากัน'],
        steps: ['แถวนี้มี 5 ภาพ ไข่ ช้อน ส้ม ร่ม เก้าอี้', 'ส้มมีภาพอยู่ทางซ้าย 2 ภาพ ทางขวา 2 ภาพ จึงอยู่ตรงกลาง ตอบข้อ 3'],
        transferIds: ['sp-row-middle-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-routine-t', type: 'transfer', subject: 'thai', skillIds: ['listening-sequence'], familyId: 'listen-sequence', difficulty: 1,
      sourceId: SRC, ...R, section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ตอนเย็นต้นกลับจากโรงเรียน ล้างมือ แล้วทำการบ้าน จากนั้นจึงดูการ์ตูน หลังจากล้างมือ ต้นทำอะไร' },
      options: [{ id: 'a', text: 'ดูการ์ตูน' }, { id: 'b', text: 'ทำการบ้าน' }, { id: 'c', text: 'อาบน้ำ' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ล้างมือแล้วต้นทำการบ้าน', hints: [], steps: ['ต้นล้างมือ แล้วทำการบ้าน จากนั้นจึงดูการ์ตูน', 'ต่อจากล้างมือคือทำการบ้าน'] },
    },
    {
      id: 'sc-handwash-t', type: 'transfer', subject: 'science', skillIds: ['hygiene'], familyId: 'hygiene', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ก่อนกินข้าว เราควรทำอะไร' },
      options: [{ id: 'a', text: 'ล้างมือ' }, { id: 'b', text: 'นอนหลับ' }, { id: 'c', text: 'เล่นของเล่น' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ก่อนกินข้าวควรล้างมือ', hints: [], steps: ['มือเราจับของหลายอย่าง อาจมีเชื้อโรค', 'ล้างมือก่อนกินข้าวจะได้ไม่ป่วย'] },
    },
    {
      id: 'm-legs-t', type: 'transfer', subject: 'math', skillIds: ['count-legs'], familyId: 'count-legs', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'เป็ด 1 ตัว และแมว 2 ตัว มีขารวมกันกี่ขา' },
      visual: { type: 'row', items: ['pic-duck', 'pic-cat', 'pic-cat'] },
      options: [{ id: 'a', text: '8 ขา' }, { id: 'b', text: '10 ขา' }, { id: 'c', text: '12 ขา' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เป็ดมี 2 ขา แมว 2 ตัวมี 8 ขา รวม 10 ขา', hints: [], steps: ['เป็ด 1 ตัวมี 2 ขา แมว 1 ตัวมี 4 ขา แมว 2 ตัวจึงมี 8 ขา', '2 บวก 8 เท่ากับ 10 ขา'] },
    },
    {
      id: 'r-seq-down-t', type: 'transfer', subject: 'reasoning', skillIds: ['number-pattern'], familyId: 'number-sequence-down', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ตัวเลขเรียงกันแบบนี้ ช่องที่มีเครื่องหมายคำถามควรเป็นเลขใด' },
      visual: { type: 'number-row', items: [15, 12, 9, '?'] },
      options: [{ id: 'a', text: '3' }, { id: 'b', text: '7' }, { id: 'c', text: '6' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ลดลงทีละ 3 ต่อจาก 9 จึงเป็น 6', hints: [], steps: ['15 ไป 12 ลดลง 3 และ 12 ไป 9 ก็ลดลง 3', 'ต่อจาก 9 ลดลงอีก 3 ได้ 6'] },
    },
    {
      id: 'g-last-month-t', type: 'transfer', subject: 'general', skillIds: ['months'], familyId: 'months', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เดือนสุดท้ายของปีคือเดือนอะไร' },
      options: [{ id: 'a', text: 'ธันวาคม' }, { id: 'b', text: 'มกราคม' }, { id: 'c', text: 'พฤศจิกายน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เดือนสุดท้ายของปีคือธันวาคม', hints: [], steps: ['หนึ่งปีมี 12 เดือน เริ่มที่มกราคม', 'เดือนที่ 12 เป็นเดือนสุดท้ายคือธันวาคม'] },
    },
    {
      id: 'th-letters-t', type: 'transfer', subject: 'thai', skillIds: ['letter-sound'], familyId: 'initial-letters', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพเรียงจากซ้ายไปขวา ข้อใดเป็นพยัญชนะต้นของภาพตามลำดับ' },
      visual: { type: 'row', items: ['pic-crab', 'pic-chicken', 'pic-horse'] },
      options: [{ id: 'a', text: 'ก ป ม', speech: '' }, { id: 'b', text: 'ป ก ม', speech: '' }, { id: 'c', text: 'ม ก ป', speech: '' }],
      correctOptionId: 'b',
      narration: 'ตัวเลือกอ่านแค่หมายเลข',
      review: { summary: 'ปู ไก่ ม้า ขึ้นต้นด้วย ป ก ม', hints: [], steps: ['ปู ขึ้นต้นด้วย ปอ ไก่ ขึ้นต้นด้วย กอ', 'ม้า ขึ้นต้นด้วย มอ เรียงได้ ปอ กอ มอ'] },
    },
    {
      id: 'sp-sunset-t', type: 'transfer', subject: 'spatial', skillIds: ['sun-direction'], familyId: 'sun-direction', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ตอนเย็น ดวงอาทิตย์ตกทางทิศใด' },
      options: [{ id: 'a', text: 'ทิศตะวันออก' }, { id: 'b', text: 'ทิศใต้' }, { id: 'c', text: 'ทิศตะวันตก' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ดวงอาทิตย์ตกทางทิศตะวันตก', hints: [], steps: ['ดวงอาทิตย์ขึ้นทางทิศตะวันออก', 'แล้วตกทางทิศตะวันตก'] },
    },
    {
      id: 'r-pairs-t', type: 'transfer', subject: 'reasoning', skillIds: ['analogy'], familyId: 'analogy', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ถุงมือใส่ที่มือ ถุงเท้าใส่ที่ไหน' },
      options: [{ id: 'a', text: 'หู' }, { id: 'b', text: 'เท้า' }, { id: 'c', text: 'หัว' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ถุงเท้าใส่ที่เท้า', hints: [], steps: ['ถุงมือใส่ที่มือ ชื่อบอกอยู่แล้ว', 'ถุงเท้าก็ใส่ที่เท้า'] },
    },
    {
      id: 'sc-color-mix-t', type: 'transfer', subject: 'science', skillIds: ['color-mixing'], familyId: 'color-mixing', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สีน้ำเงินผสมกับสีเหลือง จะได้สีอะไร' },
      options: [{ id: 'a', text: 'สีเขียว' }, { id: 'b', text: 'สีส้ม' }, { id: 'c', text: 'สีชมพู' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'น้ำเงินผสมเหลืองได้สีเขียว', hints: [], steps: ['สีน้ำเงินผสมกับสีเหลือง จะได้สีเขียว', 'เหมือนสีของใบไม้'] },
    },
    {
      id: 'g-fire-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าเห็นไฟไหม้บ้าน ควรโทรเรียกใครมาช่วย' },
      options: [{ id: 'a', text: 'ครู' }, { id: 'b', text: 'นักดับเพลิง' }, { id: 'c', text: 'หมอฟัน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไฟไหม้ต้องเรียกนักดับเพลิง', hints: [], steps: ['นักดับเพลิงมีรถดับเพลิงและอุปกรณ์ดับไฟ', 'เด็กๆ ควรรีบออกห่างจากไฟ แล้วบอกผู้ใหญ่ให้โทรเรียกนักดับเพลิง'] },
    },
    {
      id: 'm-half-dozen-t', type: 'transfer', subject: 'math', skillIds: ['dozen'], familyId: 'dozen', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ดินสอครึ่งโหล มีกี่แท่ง' },
      options: [{ id: 'a', text: '5 แท่ง' }, { id: 'b', text: '12 แท่ง' }, { id: 'c', text: '6 แท่ง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ครึ่งโหล เท่ากับ 6', hints: [], steps: ['1 โหล คือ 12', 'ครึ่งหนึ่งของ 12 คือ 6 ดินสอครึ่งโหลจึงมี 6 แท่ง'] },
    },
    {
      id: 'sp-row-middle-t', type: 'transfer', subject: 'spatial', skillIds: ['position-middle'], familyId: 'position', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดอยู่ตรงกลางแถว' },
      visual: { type: 'row', items: ['pic-car', 'pic-leaf', 'pic-coin', 'pic-stone', 'pic-ball'] },
      options: [{ id: 'a', image: 'pic-leaf', speech: 'ใบไม้' }, { id: 'b', image: 'pic-coin', speech: 'เหรียญ' }, { id: 'c', image: 'pic-stone', speech: 'ก้อนหิน' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'เหรียญอยู่ตรงกลางแถว', hints: [], steps: ['แถวนี้มี 5 ภาพ รถ ใบไม้ เหรียญ ก้อนหิน ลูกบอล', 'เหรียญมีภาพอยู่สองข้างข้างละ 2 ภาพ จึงอยู่ตรงกลาง'] },
    },
  ],
};
