/*
 * ชุดที่ 13 — รูปแบบใหม่ 15 ข้อ (ดู docs/QUESTION-TYPES.md หัวข้อ "รูปแบบชุด 12 ขึ้นไป")
 * ช่วง 1 บทความความรู้เรื่องผึ้ง 5 ข้อ / ช่วง 2 เรื่องที่มีวันที่ 5 ข้อ / ช่วง 3 ประโยคสั้น ภาพต่อเนื่อง มารยาท เครือญาติ
 * แต่งใหม่ทั้งหมด ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพจากข้อสอบเก่า
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LISTEN = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const SHORT = 'ฟังข้อความแล้วตอบคำถามให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';

export default {
  id: 'set-13',
  version: 1,
  title: 'ชุดที่ 13',
  note: 'แบบใหม่ 15 ข้อ: ความรู้เรื่องผึ้ง เรื่องมีวันที่ ประโยคสั้น',
  order: [
    'th-bee-topic', 'sc-bee-not', 'm-bee-wings', 'th-bee-main', 'sc-bee-fruit',
    'r-date-first', 'm-date-gap', 'r-date-weekday', 'r-date-second', 'm-date-next',
    'th-sentence-warning', 'th-group-stationery', 'sp-wheel-back', 'g-queue', 'g-kin-aunt',
  ],
  stimuli: {
    bees: {
      section: LISTEN,
      text: 'ผึ้งเป็นแมลงตัวเล็ก มีปีก 4 ปีก และมีขา 6 ขา ผึ้งอาศัยอยู่รวมกันเป็นฝูงใหญ่ในรัง ผึ้งงานจะบินไปดูดน้ำหวานจากดอกไม้ แล้วนำกลับมาทำเป็นน้ำผึ้งเก็บไว้ในรัง ขณะที่ผึ้งบินจากดอกหนึ่งไปอีกดอกหนึ่ง ละอองเกสรจะติดตัวผึ้งไปด้วย ช่วยให้ดอกไม้กลายเป็นผลได้ ผึ้งจึงมีประโยชน์ทั้งต่อต้นไม้และต่อคน',
    },
    dates: {
      section: LISTEN,
      text: 'เดือนนี้ วันที่ 3 เป็นวันจันทร์ ลิลลี่มีนัดหลายอย่าง วันที่ 5 ไปหาหมอฟัน วันที่ 6 ไปเที่ยวสวนสัตว์กับคุณตา และวันที่ 8 ไปงานวันเกิดของเพื่อน',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: บทความความรู้ 5 ข้อ
    {
      id: 'th-bee-topic', type: 'main', subject: 'thai', skillIds: ['main-idea'], familyId: 'passage-topic', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'bees',
      prompt: { text: 'เรื่องนี้พูดถึงสัตว์ชนิดใด' },
      options: [{ id: 'a', image: 'pic-butterfly', speech: 'ผีเสื้อ' }, { id: 'b', image: 'pic-ant', speech: 'มด' }, { id: 'c', image: 'pic-bee', speech: 'ผึ้ง' }, { id: 'd', image: 'pic-bat', speech: 'ค้างคาว' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้ วัดการจับใจความว่าเรื่องพูดถึงอะไร',
      review: {
        summary: 'ทั้งเรื่องเล่าเรื่องผึ้ง',
        hints: ['ฟังคำแรกของเรื่อง'],
        steps: ['เรื่องเริ่มว่า ผึ้งเป็นแมลงตัวเล็ก และเล่าเรื่องผึ้งจนจบ', 'เรื่องนี้จึงพูดถึงผึ้ง ตอบข้อ 3'],
        transferIds: ['th-bat-topic-t'],
      },
    },
    {
      id: 'sc-bee-not', type: 'main', subject: 'science', skillIds: ['passage-detail'], familyId: 'passage-not', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'bees',
      prompt: { text: 'ข้อใด ไม่ใช่ ลักษณะของผึ้งตามเรื่องนี้' },
      options: [{ id: 'a', text: 'มีขา 6 ขา' }, { id: 'b', text: 'อยู่รวมกันเป็นฝูง' }, { id: 'c', text: 'ออกลูกเป็นตัว' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการฟังรายละเอียดและคำว่า ไม่ใช่',
      review: {
        summary: 'เรื่องไม่ได้บอกว่าผึ้งออกลูกเป็นตัว ผึ้งเป็นแมลงที่วางไข่',
        hints: ['หาข้อที่เรื่องไม่ได้บอกไว้'],
        steps: ['เรื่องบอกว่าผึ้งมีขา 6 ขา และอยู่รวมกันเป็นฝูงใหญ่', 'ข้อที่ไม่ใช่คือ ออกลูกเป็นตัว เพราะผึ้งวางไข่ ตอบข้อ 3'],
        transferIds: ['sc-fish-not-t'],
      },
    },
    {
      id: 'm-bee-wings', type: 'main', subject: 'math', skillIds: ['repeated-addition'], familyId: 'passage-math', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'bees',
      prompt: { text: 'ผึ้ง 2 ตัว มีปีกรวมกันกี่ปีก' },
      options: [{ id: 'a', text: '8 ปีก' }, { id: 'b', text: '6 ปีก' }, { id: 'c', text: '4 ปีก' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการใช้ข้อมูลจากเรื่องมาคิดเลข',
      review: {
        summary: 'ผึ้งตัวละ 4 ปีก 2 ตัวจึงมี 8 ปีก',
        hints: ['เรื่องบอกว่าผึ้ง 1 ตัวมีปีกกี่ปีก'],
        steps: ['เรื่องบอกว่าผึ้งมีปีก 4 ปีก', 'ผึ้ง 2 ตัว 4 บวก 4 เท่ากับ 8 ปีก ตอบข้อ 1'],
        column: { a: 4, op: '+', b: 4 },
        transferIds: ['m-bird-wings-t'],
      },
    },
    {
      id: 'th-bee-main', type: 'main', subject: 'thai', skillIds: ['main-idea'], familyId: 'passage-main', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'bees',
      prompt: { text: 'เรื่องนี้พูดถึงเรื่องใดมากที่สุด' },
      options: [{ id: 'a', text: 'วิธีปลูกดอกไม้' }, { id: 'b', text: 'ผึ้งและประโยชน์ของผึ้ง' }, { id: 'c', text: 'การทำขนม' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจับใจความสำคัญ',
      review: {
        summary: 'เรื่องเล่าว่าผึ้งเป็นอย่างไร และช่วยอะไรเราบ้าง',
        hints: ['ทั้งเรื่องพูดถึงอะไรบ่อยที่สุด'],
        steps: ['เรื่องเล่าลักษณะของผึ้ง การทำน้ำผึ้ง และการช่วยให้ดอกไม้เป็นผล', 'จึงพูดถึงผึ้งและประโยชน์ของผึ้งมากที่สุด ตอบข้อ 2'],
        transferIds: ['th-banana-main-t'],
      },
    },
    {
      id: 'sc-bee-fruit', type: 'main', subject: 'science', skillIds: ['pollination'], familyId: 'pollination', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'bees',
      prompt: { text: 'ผึ้งช่วยต้นไม้อย่างไร' },
      options: [{ id: 'a', text: 'พาละอองเกสรไป ช่วยให้ดอกกลายเป็นผล' }, { id: 'b', text: 'ช่วยรดน้ำต้นไม้' }, { id: 'c', text: 'ช่วยกินใบไม้ที่แห้ง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการฟังและความรู้เรื่องพืช',
      review: {
        summary: 'ผึ้งพาละอองเกสรจากดอกหนึ่งไปอีกดอก ดอกไม้จึงติดผล',
        hints: ['ฟังตอนที่ผึ้งบินจากดอกหนึ่งไปอีกดอกหนึ่ง'],
        steps: ['เรื่องบอกว่าละอองเกสรติดตัวผึ้งไปด้วย', 'ช่วยให้ดอกไม้กลายเป็นผลได้ ตอบข้อ 1'],
        transferIds: ['sc-flower-sweet-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: เรื่องที่มีวันที่ 5 ข้อ
    {
      id: 'r-date-first', type: 'main', subject: 'reasoning', skillIds: ['date-order'], familyId: 'date-order', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'dates',
      prompt: { text: 'ลิลลี่ไปที่ใดก่อน' },
      options: [{ id: 'a', text: 'งานวันเกิดเพื่อน' }, { id: 'b', text: 'หาหมอฟัน' }, { id: 'c', text: 'สวนสัตว์' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการเปรียบเทียบวันที่',
      review: {
        summary: 'วันที่ 5 มาก่อนวันที่ 6 และวันที่ 8',
        hints: ['ดูว่าวันที่ไหนน้อยที่สุด'],
        steps: ['หาหมอฟันวันที่ 5 สวนสัตว์วันที่ 6 งานวันเกิดวันที่ 8', 'วันที่ 5 น้อยที่สุด จึงไปหาหมอฟันก่อน ตอบข้อ 2'],
        transferIds: ['r-date-first-t'],
      },
    },
    {
      id: 'm-date-gap', type: 'main', subject: 'math', skillIds: ['date-difference'], familyId: 'date-gap', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'dates',
      prompt: { text: 'จากวันไปหาหมอฟัน ถึงวันงานวันเกิดเพื่อน ห่างกันกี่วัน' },
      options: [{ id: 'a', text: '2 วัน' }, { id: 'b', text: '13 วัน' }, { id: 'c', text: '3 วัน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการหาผลต่างของวันที่',
      review: {
        summary: 'วันที่ 8 ลบวันที่ 5 ห่างกัน 3 วัน',
        hints: ['นับจากวันที่ 5 ไปถึงวันที่ 8'],
        steps: ['หาหมอฟันวันที่ 5 งานวันเกิดวันที่ 8', 'นับต่อจาก 5 ไป 6 7 8 ได้ 3 วัน หรือ 8 ลบ 5 เท่ากับ 3 ตอบข้อ 3'],
        transferIds: ['m-date-gap-t'],
      },
    },
    {
      id: 'r-date-weekday', type: 'main', subject: 'reasoning', skillIds: ['calendar'], familyId: 'date-weekday', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'dates',
      prompt: { text: 'วันที่ 5 ที่ลิลลี่ไปหาหมอฟัน ตรงกับวันอะไร' },
      options: [{ id: 'a', text: 'วันพุธ' }, { id: 'b', text: 'วันอังคาร' }, { id: 'c', text: 'วันพฤหัสบดี' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการคิดวันในสัปดาห์จากวันที่',
      review: {
        summary: 'วันที่ 3 วันจันทร์ วันที่ 4 วันอังคาร วันที่ 5 วันพุธ',
        hints: ['เรื่องบอกว่าวันที่ 3 เป็นวันจันทร์ นับต่อไปทีละวัน'],
        steps: ['วันที่ 3 เป็นวันจันทร์ วันต่อไปคือวันอังคาร เป็นวันที่ 4', 'วันที่ 5 จึงเป็นวันพุธ ตอบข้อ 1'],
        transferIds: ['r-date-weekday-t'],
      },
    },
    {
      id: 'r-date-second', type: 'main', subject: 'reasoning', skillIds: ['date-order'], familyId: 'date-order', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'dates',
      prompt: { text: 'ลิลลี่ไปที่ใดเป็นอันดับที่สอง' },
      options: [{ id: 'a', text: 'หาหมอฟัน' }, { id: 'b', text: 'งานวันเกิดเพื่อน' }, { id: 'c', text: 'สวนสัตว์' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงลำดับ',
      review: {
        summary: 'เรียงได้ หาหมอฟัน สวนสัตว์ งานวันเกิด',
        hints: ['เรียงวันที่จากน้อยไปมากก่อน'],
        steps: ['เรียงวันที่ได้ 5 6 8 คือ หาหมอฟัน สวนสัตว์ งานวันเกิด', 'อันดับที่สองคือสวนสัตว์ ตอบข้อ 3'],
        transferIds: ['r-date-second-t'],
      },
    },
    {
      id: 'm-date-next', type: 'main', subject: 'math', skillIds: ['number-before-after'], familyId: 'date-next', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'dates',
      prompt: { text: 'วันถัดจากวันงานวันเกิดเพื่อน คือวันที่เท่าไร' },
      options: [{ id: 'a', text: 'วันที่ 7' }, { id: 'b', text: 'วันที่ 9' }, { id: 'c', text: 'วันที่ 10' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดจำนวนที่มากกว่าอยู่ 1',
      review: {
        summary: 'งานวันเกิดวันที่ 8 วันถัดไปคือวันที่ 9',
        hints: ['วันถัดไป คือเพิ่มอีก 1 วัน'],
        steps: ['งานวันเกิดเพื่อนวันที่ 8', 'วันถัดไป 8 บวก 1 เท่ากับ 9 ตอบข้อ 2'],
        transferIds: ['m-date-before-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'th-sentence-warning', type: 'main', subject: 'thai', skillIds: ['sentence-type'], familyId: 'sentence-type', difficulty: 2,
      sourceId: SRC, ...R, section: SHORT,
      prompt: { text: 'ข้อความ "ระวัง พื้นเปียก อาจลื่นล้มได้" เป็นข้อความแบบใด' },
      options: [{ id: 'a', text: 'คำเตือน' }, { id: 'b', text: 'คำถาม' }, { id: 'c', text: 'คำขอบคุณ' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ วัดการรู้จักชนิดของข้อความ',
      review: {
        summary: 'บอกให้ระวังอันตราย คือคำเตือน',
        hints: ['ข้อความนี้บอกให้เราทำอะไร'],
        steps: ['ข้อความนี้บอกให้ระวัง เพราะอาจเกิดอันตราย', 'ข้อความที่บอกให้ระวังอันตรายเรียกว่า คำเตือน ตอบข้อ 1'],
        transferIds: ['th-sentence-question-t'],
      },
    },
    {
      id: 'th-group-stationery', type: 'main', subject: 'thai', skillIds: ['group-words'], familyId: 'group-words', difficulty: 2,
      sourceId: SRC, ...R, section: SHORT,
      prompt: { text: 'ดินสอ ยางลบ ไม้บรรทัด สมุด เป็นของพวกใด' },
      options: [{ id: 'a', text: 'เครื่องครัว' }, { id: 'b', text: 'เครื่องแต่งกาย' }, { id: 'c', text: 'เครื่องเขียน' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ วัดการรู้จักคำเรียกกลุ่ม',
      review: {
        summary: 'ของที่ใช้เขียนหนังสือ เรียกว่าเครื่องเขียน',
        hints: ['ของพวกนี้ใช้ทำอะไร'],
        steps: ['ของทุกอย่างใช้ตอนเขียนหนังสือและทำการบ้าน', 'จึงเป็นเครื่องเขียน ตอบข้อ 3'],
        transferIds: ['th-group-vehicles-t'],
      },
    },
    {
      id: 'sp-wheel-back', type: 'main', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'wheel-sequence', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ช่องที่ระบายสีเลื่อนไปทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ wheel: 0 }, { wheel: 7 }, { wheel: 6 }, '?'] },
      options: [{ id: 'a', svg: { figure: { wheel: 4 } } }, { id: 'b', svg: { figure: { wheel: 5 } } }, { id: 'c', svg: { figure: { wheel: 1 } } }, { id: 'd', svg: { figure: { wheel: 7 } } }],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหาแบบรูปของการหมุนทวนเข็มนาฬิกา',
      review: {
        summary: 'ช่องสีดำเลื่อนทวนเข็มนาฬิกาทีละ 1 ช่อง',
        hints: ['ครั้งนี้ช่องสีดำเลื่อนไปทางซ้าย ไม่ใช่ทางขวา'],
        steps: ['ช่องสีดำเริ่มที่ด้านบน แล้วเลื่อนไปทางซ้ายทีละ 1 ช่อง จนถึงด้านซ้าย', 'ภาพต่อไปจึงเลื่อนลงไปอีก 1 ช่อง อยู่ด้านล่างซ้าย ตอบข้อ 2'],
        transferIds: ['sp-wheel-back-t'],
      },
    },
    {
      id: 'g-queue', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'manners-queue', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'มีเพื่อนต่อแถวรอเล่นชิงช้าอยู่ หนูควรทำอย่างไร' },
      options: [{ id: 'a', text: 'แซงไปข้างหน้า' }, { id: 'b', text: 'ต่อท้ายแถว แล้วรอตามลำดับ' }, { id: 'c', text: 'ผลักเพื่อนออกจากชิงช้า' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดมารยาทการต่อแถว',
      review: {
        summary: 'มาทีหลัง ต้องต่อท้ายแถวและรอ',
        hints: ['ใครมาก่อนควรได้เล่นก่อน'],
        steps: ['การแซงหรือผลักเพื่อนทำให้เพื่อนเสียใจและอาจเจ็บ', 'ต้องต่อท้ายแถวแล้วรอตามลำดับ ตอบข้อ 2'],
        transferIds: ['g-wait-rice-t'],
      },
    },
    {
      id: 'g-kin-aunt', type: 'main', subject: 'general', skillIds: ['kinship-words'], familyId: 'kinship', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'น้องสาวของแม่ หนูเรียกว่าอะไร' },
      options: [{ id: 'a', text: 'ป้า' }, { id: 'b', text: 'อา' }, { id: 'c', text: 'น้า' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ วัดการรู้จักคำเรียกญาติ',
      review: {
        summary: 'น้องของแม่ เรียกว่า น้า',
        hints: ['น้องของพ่อเรียก อา น้องของแม่เรียกอะไร'],
        steps: ['พี่ของพ่อหรือแม่เรียก ลุง ป้า น้องของพ่อเรียก อา', 'น้องของแม่เรียก น้า ตอบข้อ 3'],
        transferIds: ['g-kin-big-aunt-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-bat-topic-t', type: 'transfer', subject: 'thai', skillIds: ['main-idea'], familyId: 'passage-topic', difficulty: 1,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'สัตว์ชนิดนี้นอนห้อยหัวตอนกลางวัน และบินออกหากินตอนกลางคืน เรื่องนี้พูดถึงสัตว์ชนิดใด' },
      options: [{ id: 'a', image: 'pic-owl', speech: 'นกฮูก' }, { id: 'b', image: 'pic-bat', speech: 'ค้างคาว' }, { id: 'c', image: 'pic-bee', speech: 'ผึ้ง' }, { id: 'd', image: 'pic-cat', speech: 'แมว' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'สัตว์ที่นอนห้อยหัวคือค้างคาว', hints: [], steps: ['นกฮูกก็หากินกลางคืน แต่ไม่นอนห้อยหัว', 'ค้างคาวนอนห้อยหัว จึงตอบค้างคาว'] },
    },
    {
      id: 'sc-fish-not-t', type: 'transfer', subject: 'science', skillIds: ['passage-detail'], familyId: 'passage-not', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใด ไม่ใช่ ลักษณะของปลา' },
      options: [{ id: 'a', text: 'มีครีบไว้ว่ายน้ำ' }, { id: 'b', text: 'มีขา 4 ขา' }, { id: 'c', text: 'อาศัยอยู่ในน้ำ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ปลาไม่มีขา ใช้ครีบว่ายน้ำ', hints: [], steps: ['ปลามีครีบและอยู่ในน้ำ', 'ปลาไม่มีขา ข้อที่ไม่ใช่จึงเป็น มีขา 4 ขา'] },
    },
    {
      id: 'm-bird-wings-t', type: 'transfer', subject: 'math', skillIds: ['repeated-addition'], familyId: 'passage-math', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'นก 1 ตัวมี 2 ปีก นก 3 ตัวมีปีกรวมกันกี่ปีก' },
      options: [{ id: 'a', text: '5 ปีก' }, { id: 'b', text: '3 ปีก' }, { id: 'c', text: '6 ปีก' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '2 บวก 2 บวก 2 เท่ากับ 6 ปีก', hints: [], steps: ['นกตัวละ 2 ปีก มี 3 ตัว', '2 บวก 2 บวก 2 เท่ากับ 6 ปีก'] },
    },
    {
      id: 'th-banana-main-t', type: 'transfer', subject: 'thai', skillIds: ['main-idea'], familyId: 'passage-main', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ต้นกล้วยให้ผลกล้วยไว้กิน ใบกล้วยใช้ห่อขนม ต้นกล้วยใช้เลี้ยงหมูได้ เรื่องนี้พูดถึงเรื่องใดมากที่สุด' },
      options: [{ id: 'a', text: 'ประโยชน์ของต้นกล้วย' }, { id: 'b', text: 'การเลี้ยงหมู' }, { id: 'c', text: 'สีของใบไม้' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ทุกประโยคบอกว่าต้นกล้วยใช้ทำอะไรได้', hints: [], steps: ['เรื่องบอกว่าผล ใบ และต้นของกล้วยใช้ประโยชน์ได้', 'จึงพูดถึงประโยชน์ของต้นกล้วยมากที่สุด'] },
    },
    {
      id: 'sc-flower-sweet-t', type: 'transfer', subject: 'science', skillIds: ['pollination'], familyId: 'pollination', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ดอกไม้มีสีสวยและมีน้ำหวาน ช่วยเรียกสัตว์ใดให้มาหา' },
      options: [{ id: 'a', text: 'ปลาและกบ' }, { id: 'b', text: 'ผึ้งและผีเสื้อ' }, { id: 'c', text: 'ช้างและม้า' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ผึ้งและผีเสื้อชอบน้ำหวานจากดอกไม้', hints: [], steps: ['ผึ้งและผีเสื้อบินมาดูดน้ำหวาน', 'แล้วช่วยพาละอองเกสรไปให้ดอกอื่น'] },
    },
    {
      id: 'r-date-first-t', type: 'transfer', subject: 'reasoning', skillIds: ['date-order'], familyId: 'date-order', difficulty: 1,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ต้นไปห้องสมุดวันที่ 14 บัวไปวันที่ 11 ตาลไปวันที่ 16 ใครไปห้องสมุดก่อน' },
      options: [{ id: 'a', text: 'ต้น' }, { id: 'b', text: 'ตาล' }, { id: 'c', text: 'บัว' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'วันที่ 11 น้อยที่สุด บัวจึงไปก่อน', hints: [], steps: ['เทียบวันที่ 14 11 16', '11 น้อยที่สุด บัวไปก่อน'] },
    },
    {
      id: 'm-date-gap-t', type: 'transfer', subject: 'math', skillIds: ['date-difference'], familyId: 'date-gap', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'จากวันที่ 4 ถึงวันที่ 9 ห่างกันกี่วัน' },
      options: [{ id: 'a', text: '5 วัน' }, { id: 'b', text: '4 วัน' }, { id: 'c', text: '13 วัน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '9 ลบ 4 เท่ากับ 5 วัน', hints: [], steps: ['นับต่อจาก 4 ไป 5 6 7 8 9', 'ได้ 5 วัน'], column: { a: 9, op: '-', b: 4 } },
    },
    {
      id: 'r-date-weekday-t', type: 'transfer', subject: 'reasoning', skillIds: ['calendar'], familyId: 'date-weekday', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าวันที่ 1 เป็นวันศุกร์ วันที่ 3 จะเป็นวันอะไร' },
      options: [{ id: 'a', text: 'วันเสาร์' }, { id: 'b', text: 'วันจันทร์' }, { id: 'c', text: 'วันอาทิตย์' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วันที่ 1 ศุกร์ วันที่ 2 เสาร์ วันที่ 3 อาทิตย์', hints: [], steps: ['วันต่อจากวันศุกร์คือวันเสาร์ เป็นวันที่ 2', 'วันที่ 3 จึงเป็นวันอาทิตย์'] },
    },
    {
      id: 'r-date-second-t', type: 'transfer', subject: 'reasoning', skillIds: ['date-order'], familyId: 'date-order', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'แม่ไปตลาดวันที่ 2 ไปวัดวันที่ 9 และไปธนาคารวันที่ 5 แม่ไปที่ใดเป็นอันดับที่สอง' },
      options: [{ id: 'a', text: 'ธนาคาร' }, { id: 'b', text: 'ตลาด' }, { id: 'c', text: 'วัด' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'เรียงได้ ตลาด ธนาคาร วัด', hints: [], steps: ['เรียงวันที่ 2 5 9', 'อันดับที่สองคือวันที่ 5 ไปธนาคาร'] },
    },
    {
      id: 'm-date-before-t', type: 'transfer', subject: 'math', skillIds: ['number-before-after'], familyId: 'date-next', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'วันก่อนวันที่ 20 คือวันที่เท่าไร' },
      options: [{ id: 'a', text: 'วันที่ 21' }, { id: 'b', text: 'วันที่ 19' }, { id: 'c', text: 'วันที่ 10' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วันก่อนคือน้อยกว่า 1 วัน 20 ลบ 1 เท่ากับ 19', hints: [], steps: ['วันก่อน คือถอยหลังไป 1 วัน', '20 ลบ 1 เท่ากับ 19'] },
    },
    {
      id: 'th-sentence-question-t', type: 'transfer', subject: 'thai', skillIds: ['sentence-type'], familyId: 'sentence-type', difficulty: 2,
      sourceId: SRC, ...R, section: SHORT,
      prompt: { text: 'ข้อความ "หนูชอบกินผลไม้อะไร" เป็นข้อความแบบใด' },
      options: [{ id: 'a', text: 'คำเตือน' }, { id: 'b', text: 'คำสั่ง' }, { id: 'c', text: 'คำถาม' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'มีคำว่า อะไร และรอให้ตอบ จึงเป็นคำถาม', hints: [], steps: ['ข้อความนี้ถามให้เราตอบว่าชอบผลไม้อะไร', 'ข้อความที่ถามเรียกว่า คำถาม'] },
    },
    {
      id: 'th-group-vehicles-t', type: 'transfer', subject: 'thai', skillIds: ['group-words'], familyId: 'group-words', difficulty: 2,
      sourceId: SRC, ...R, section: SHORT,
      prompt: { text: 'รถยนต์ รถไฟ เรือ เครื่องบิน เป็นของพวกใด' },
      options: [{ id: 'a', text: 'ยานพาหนะ' }, { id: 'b', text: 'เครื่องเขียน' }, { id: 'c', text: 'เครื่องครัว' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ของที่พาคนไปที่ต่างๆ เรียกว่ายานพาหนะ', hints: [], steps: ['ทุกอย่างใช้เดินทางไปที่ต่างๆ', 'จึงเป็นยานพาหนะ'] },
    },
    {
      id: 'sp-wheel-back-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'wheel-sequence', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ช่องที่ระบายสีเลื่อนไปทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ wheel: 4 }, { wheel: 3 }, { wheel: 2 }, '?'] },
      options: [{ id: 'a', svg: { figure: { wheel: 3 } } }, { id: 'b', svg: { figure: { wheel: 0 } } }, { id: 'c', svg: { figure: { wheel: 5 } } }, { id: 'd', svg: { figure: { wheel: 1 } } }],
      correctOptionId: 'd',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'ช่องสีดำเลื่อนทวนเข็มนาฬิกาทีละ 1 ช่อง', hints: [], steps: ['ช่องสีดำเริ่มที่ด้านล่าง แล้วขึ้นไปทางขวาทีละช่อง', 'ภาพต่อไปจึงอยู่ด้านบนขวา'] },
    },
    {
      id: 'g-wait-rice-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'manners-queue', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ตอนตักข้าวที่โรงเรียน ถ้าเพื่อนข้างหน้ายังตักไม่เสร็จ หนูควรทำอย่างไร' },
      options: [{ id: 'a', text: 'แย่งทัพพีจากเพื่อน' }, { id: 'b', text: 'ตะโกนให้เพื่อนรีบ' }, { id: 'c', text: 'รอให้เพื่อนตักเสร็จก่อน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'รอคอยตามลำดับอย่างสุภาพ', hints: [], steps: ['การแย่งหรือตะโกนไม่สุภาพ', 'ต้องรอให้เพื่อนตักเสร็จก่อน'] },
    },
    {
      id: 'g-kin-big-aunt-t', type: 'transfer', subject: 'general', skillIds: ['kinship-words'], familyId: 'kinship', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'พี่สาวของพ่อ หนูเรียกว่าอะไร' },
      options: [{ id: 'a', text: 'ป้า' }, { id: 'b', text: 'น้า' }, { id: 'c', text: 'ยาย' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'พี่สาวของพ่อหรือแม่ เรียกว่า ป้า', hints: [], steps: ['พี่ผู้หญิงของพ่อหรือแม่เรียก ป้า', 'น้าเป็นน้องของแม่ ยายเป็นแม่ของแม่'] },
    },
  ],
};
