/*
 * ชุดที่ 19 — รูปแบบใหม่ 15 ข้อ (ดู docs/QUESTION-TYPES.md หัวข้อ "รูปแบบชุด 12 ขึ้นไป")
 * ช่วง 1 เรื่องเดียวถาม 5 ข้อ (ครอบครัวน้องใบเฟิร์น: นับสมาชิก คำเรียกญาติ ความรู้สึกจากคำพูด เหตุผลความปลอดภัย ข้อที่ไม่เกี่ยวกับเรื่อง)
 * ช่วง 2 ข้อเดี่ยว: ครึ่งหนึ่งของเลขสองหลัก เท่าตัว อวัยวะที่เป็นคู่ สัตว์กินหญ้า การไปพบหมอ
 * ช่วง 3 ข้อเดี่ยว: สระเสียงสั้น ตัวสะกดแม่ กน ลูกศรหมุน ตารางลูกศร เรียงความสูง
 * แต่งใหม่ทั้งหมด ตั้งชื่อตัวละคร สถานที่ และตัวเลขใหม่ตามแนวข้อสอบเก่า; ไม่ต้องใช้รูปใหม่จาก Gemini
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LISTEN = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';
const fig = (id, figure) => ({ id, svg: { figure } });
const arrow = (direction) => ({ arrow: direction });
const RULE = 'ภาพในแถวบนเปลี่ยนจากซ้ายไปขวา แถวล่างเปลี่ยนแบบเดียวกัน ช่อง ? ควรเป็นภาพใด';

export default {
  id: 'set-19',
  version: 1,
  title: 'ชุดที่ 19',
  note: 'ครอบครัวน้องใบเฟิร์น ครึ่งหนึ่ง เท่าตัว สระสั้น ตัวสะกด',
  order: [
    'r-family-count', 'th-family-grandpa', 'th-family-feel', 'g-family-why', 'r-family-not',
    'm-half-48', 'm-times-marbles', 'sc-body-pairs', 'sc-animal-grass', 'g-sick-doctor',
    'th-short-vowel', 'th-final-kon', 'sp-arrow-quarter', 'sp-arrow-latin', 'r-chain-trees',
  ],
  stimuli: {
    family: {
      section: LISTEN,
      text: 'ที่บ้านของน้องใบเฟิร์น มีพ่อ แม่ ตา ยาย พี่ชาย และน้องใบเฟิร์น น้องใบเฟิร์นเป็นคนเล็กที่สุดในบ้าน ทุกเช้ายายจะพาน้องใบเฟิร์นเดินไปโรงเรียน ยายบอกเสมอว่า เวลาข้ามถนนต้องจับมือผู้ใหญ่ไว้ เพราะรถวิ่งเร็ว พอกลับถึงบ้าน ตาจะชวนน้องรดน้ำต้นไม้ที่สวนหน้าบ้าน',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: เรื่องเดียว 5 ข้อ
    {
      id: 'r-family-count', type: 'main', subject: 'reasoning', skillIds: ['story-count'], familyId: 'story-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'family',
      prompt: { text: 'ที่บ้านของน้องใบเฟิร์นมีสมาชิกทั้งหมดกี่คน' },
      options: [{ id: 'a', text: '5 คน' }, { id: 'b', text: '6 คน' }, { id: 'c', text: '7 คน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการฟังชื่อสมาชิกแล้วนับ (ต้องนับน้องใบเฟิร์นด้วย)',
      review: {
        summary: 'พ่อ แม่ ตา ยาย พี่ชาย และน้องใบเฟิร์น รวม 6 คน',
        hints: ['นับทีละคนตามที่เรื่องบอกชื่อ อย่าลืมนับน้องใบเฟิร์นด้วย'],
        steps: ['เรื่องบอกว่ามี พ่อ หนึ่ง แม่ สอง ตา สาม ยาย สี่ พี่ชาย ห้า และน้องใบเฟิร์น หก', 'รวมเป็น 6 คน ตอบข้อ 2'],
        transferIds: ['r-family-count-t'],
      },
    },
    {
      id: 'th-family-grandpa', type: 'main', subject: 'thai', skillIds: ['kinship-words'], familyId: 'kinship', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'family',
      prompt: { text: 'ตาเป็นพ่อของใคร' },
      options: [{ id: 'a', text: 'พ่อ' }, { id: 'b', text: 'พี่ชาย' }, { id: 'c', text: 'แม่' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องคำเรียกญาติ (ตาเป็นพ่อของแม่)',
      review: {
        summary: 'ตาเป็นพ่อของแม่ ส่วนพ่อของพ่อเรียกว่าปู่',
        hints: ['ตากับยายเป็นพ่อแม่ของใคร'],
        steps: ['ตาและยายเป็นพ่อแม่ของแม่ ส่วนพ่อของพ่อเรียกว่าปู่', 'ตาจึงเป็นพ่อของแม่ ตอบข้อ 3'],
        transferIds: ['th-family-grandma-t'],
      },
    },
    {
      id: 'th-family-feel', type: 'main', subject: 'thai', skillIds: ['feelings'], familyId: 'feelings', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'family',
      prompt: { text: 'ที่ยายพูดว่า "เวลาข้ามถนนต้องจับมือผู้ใหญ่ไว้" ให้ความรู้สึกอย่างไร' },
      options: [{ id: 'a', text: 'ห่วงใย' }, { id: 'b', text: 'โกรธ' }, { id: 'c', text: 'เบื่อหน่าย' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการเข้าใจความรู้สึกจากคำพูด',
      review: {
        summary: 'ยายพูดเพราะอยากให้น้องปลอดภัย จึงรู้สึกห่วงใย',
        hints: ['ยายอยากให้น้องเป็นอย่างไรตอนข้ามถนน'],
        steps: ['ยายเตือนให้จับมือผู้ใหญ่ เพราะอยากให้น้องปลอดภัย', 'คนที่พูดแบบนี้รู้สึกห่วงใย ตอบข้อ 1'],
        transferIds: ['th-family-feel-t'],
      },
    },
    {
      id: 'g-family-why', type: 'main', subject: 'general', skillIds: ['road-safety'], familyId: 'safety-road', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'family',
      prompt: { text: 'ทำไมยายจึงบอกให้จับมือผู้ใหญ่ไว้ตอนข้ามถนน' },
      options: [{ id: 'a', text: 'เพราะอยากให้ผู้ใหญ่ซื้อขนมให้' }, { id: 'b', text: 'เพราะรถวิ่งเร็ว อาจเกิดอันตราย' }, { id: 'c', text: 'เพราะเด็กเดินช้า' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการฟังเหตุผลและความรู้เรื่องความปลอดภัยบนถนน',
      review: {
        summary: 'รถวิ่งเร็ว เด็กอาจโดนชนได้',
        hints: ['ฟังประโยคที่ยายบอกเหตุผล'],
        steps: ['เรื่องบอกว่า ต้องจับมือผู้ใหญ่ เพราะรถวิ่งเร็ว', 'รถที่วิ่งเร็วอาจชนเด็ก จึงต้องจับมือผู้ใหญ่ ตอบข้อ 2'],
        transferIds: ['g-family-why-t'],
      },
    },
    {
      id: 'r-family-not', type: 'main', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'family',
      prompt: { text: 'ข้อใดไม่เกี่ยวข้องกับเรื่องนี้' },
      options: [{ id: 'a', text: 'ยายพาน้องเดินไปโรงเรียน' }, { id: 'b', text: 'ตาชวนน้องรดน้ำต้นไม้' }, { id: 'c', text: 'พี่ชายชวนน้องไปว่ายน้ำ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการฟังและแยกสิ่งที่มีในเรื่องกับสิ่งที่ไม่มี',
      review: {
        summary: 'เรื่องนี้ไม่มีการไปว่ายน้ำ',
        hints: ['ตรวจทีละข้อว่าเรื่องพูดถึงหรือไม่'],
        steps: ['ยายพาน้องไปโรงเรียน และตาชวนน้องรดน้ำต้นไม้ มีอยู่ในเรื่อง', 'เรื่องไม่ได้พูดถึงการไปว่ายน้ำ ตอบข้อ 3'],
        transferIds: ['r-family-not-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: ข้อเดี่ยว
    {
      id: 'm-half-48', type: 'main', subject: 'math', skillIds: ['half-of-number'], familyId: 'half', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ครึ่งหนึ่งของ 48 คือเท่าไร' },
      options: [{ id: 'a', text: '24' }, { id: 'b', text: '26' }, { id: 'c', text: '96' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการแบ่งครึ่งของจำนวนสองหลัก',
      review: {
        summary: 'แบ่ง 48 เป็นสองส่วนเท่ากัน ได้ส่วนละ 24',
        hints: ['ครึ่งหนึ่งคือแบ่งเป็นสองส่วนเท่ากัน'],
        steps: ['40 แบ่งครึ่งได้ 20 และ 8 แบ่งครึ่งได้ 4', '20 บวก 4 เท่ากับ 24 ตอบข้อ 1'],
        transferIds: ['m-half-36-t'],
      },
    },
    {
      id: 'm-times-marbles', type: 'main', subject: 'math', skillIds: ['times-as-many'], familyId: 'times-as-many', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'น้องมีลูกแก้ว 8 เม็ด พี่มีลูกแก้วเป็น 2 เท่าของน้อง พี่มีลูกแก้วกี่เม็ด' },
      options: [{ id: 'a', text: '10 เม็ด' }, { id: 'b', text: '4 เม็ด' }, { id: 'c', text: '16 เม็ด' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจคำว่า 2 เท่า',
      review: {
        summary: '2 เท่าของ 8 คือ 8 บวก 8',
        hints: ['2 เท่า คือมีของน้องสองชุด'],
        steps: ['2 เท่าของ 8 คือมี 8 สองชุด', '8 บวก 8 เท่ากับ 16 ตอบข้อ 3'],
        column: { a: 8, op: '+', b: 8 },
        transferIds: ['m-times-stickers-t'],
      },
    },
    {
      id: 'sc-body-pairs', type: 'main', subject: 'science', skillIds: ['body-parts'], familyId: 'body-pairs', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'อวัยวะในข้อใดมีเป็นคู่ทั้งสองอย่าง' },
      options: [{ id: 'a', text: 'จมูก, ปาก' }, { id: 'b', text: 'ตา, หู' }, { id: 'c', text: 'หู, ปาก' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องอวัยวะที่มีสองข้าง',
      review: {
        summary: 'ตาและหูมีสองข้าง จึงเป็นคู่',
        hints: ['ลองนับดูว่าบนใบหน้ามีกี่ข้าง'],
        steps: ['จมูกและปากมีอย่างละหนึ่ง ไม่เป็นคู่', 'ตามีสองข้าง หูมีสองข้าง จึงเป็นคู่ ตอบข้อ 2'],
        transferIds: ['sc-body-pairs-t'],
      },
    },
    {
      id: 'sc-animal-grass', type: 'main', subject: 'science', skillIds: ['animal-food'], familyId: 'animal-food', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์สองชนิดใดกินหญ้าเป็นอาหาร' },
      options: [{ id: 'a', text: 'วัว, ม้า' }, { id: 'b', text: 'แมว, เสือ' }, { id: 'c', text: 'เหยี่ยว, งู' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องอาหารของสัตว์',
      review: {
        summary: 'วัวและม้ากินหญ้า',
        hints: ['สัตว์ที่เรามักเห็นเดินกินหญ้าในทุ่ง'],
        steps: ['แมวและเสือกินเนื้อ เหยี่ยวและงูกินสัตว์เล็กๆ', 'วัวและม้ากินหญ้า ตอบข้อ 1'],
        transferIds: ['sc-animal-grass-t'],
      },
    },
    {
      id: 'g-sick-doctor', type: 'main', subject: 'general', skillIds: ['occupations'], familyId: 'occupations', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อเด็กๆ เจ็บป่วยไม่สบาย ควรไปพบใคร' },
      options: [{ id: 'a', text: 'ตำรวจ' }, { id: 'b', text: 'หมอ' }, { id: 'c', text: 'ชาวนา' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องอาชีพที่ช่วยเหลือเรา',
      review: {
        summary: 'หมอตรวจและรักษาคนที่ไม่สบาย',
        hints: ['ใครเป็นคนช่วยรักษาเวลาเราป่วย'],
        steps: ['ตำรวจดูแลความปลอดภัย ชาวนาปลูกข้าว', 'หมอรักษาคนป่วย ตอบข้อ 2'],
        transferIds: ['g-sick-dentist-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3: คำในภาษาไทย ลูกศร เรียงความสูง
    {
      id: 'th-short-vowel', type: 'main', subject: 'thai', skillIds: ['vowel-length'], familyId: 'vowel-length', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดใช้สระเสียงสั้น' },
      options: [{ id: 'a', text: 'ตา' }, { id: 'b', text: 'ดี' }, { id: 'c', text: 'จะ' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ ฟังเสียงสั้นยาวของคำประกอบการตัดสิน (วัดการฟังและความรู้เรื่องสระ)',
      review: {
        summary: 'จะใช้สระอะ ซึ่งเป็นเสียงสั้น',
        hints: ['ลองออกเสียง คำไหนเสียงสั้นห้วนๆ คำไหนลากเสียงยาว'],
        steps: ['ตาใช้สระอา และดีใช้สระอี ทั้งสองเป็นเสียงยาว', 'จะใช้สระอะ เป็นเสียงสั้น ตอบข้อ 3'],
        transferIds: ['th-short-vowel-t'],
      },
    },
    {
      id: 'th-final-kon', type: 'main', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีตัวสะกดในแม่ กน' },
      options: [{ id: 'a', text: 'บ้าน' }, { id: 'b', text: 'ส้ม' }, { id: 'c', text: 'นก' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูพยัญชนะท้ายคำเอง',
      review: {
        summary: 'บ้านมี น เป็นตัวสะกด อยู่ในแม่ กน',
        hints: ['ดูพยัญชนะท้ายคำ ว่าเสียงท้ายเหมือนตัว น หรือไม่'],
        steps: ['ส้มมี ม เป็นตัวสะกด และนกมี ก เป็นตัวสะกด', 'บ้านมี น เป็นตัวสะกด ตอบข้อ 1'],
        transferIds: ['th-final-kom-t'],
      },
    },
    {
      id: 'sp-arrow-quarter', type: 'main', subject: 'spatial', skillIds: ['figure-analogy'], familyId: 'grid-analogy', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: RULE },
      visual: { type: 'figure-grid', rows: [[arrow('up'), arrow('right')], [arrow('down'), '?']] },
      options: [fig('a', arrow('up')), fig('b', arrow('right')), fig('c', arrow('left')), fig('d', arrow('down'))],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหากฎการหมุนของแถวบนแล้วใช้กับแถวล่าง',
      review: {
        summary: 'ลูกศรหมุนตามเข็มนาฬิกาไปหนึ่งในสี่ของรอบ',
        hints: ['แถวบน ลูกศรชี้ขึ้น แล้วเปลี่ยนเป็นชี้ไปทางไหน'],
        steps: ['แถวบนจากลูกศรชี้ขึ้น เป็นชี้ไปทางขวา คือหมุนตามเข็มนาฬิกาไปหนึ่งในสี่ของรอบ', 'แถวล่างลูกศรชี้ลง หมุนต่อไปหนึ่งในสี่ของรอบ จะชี้ไปทางซ้าย ตอบข้อ 3'],
        transferIds: ['sp-arrow-quarter-t'],
      },
    },
    {
      id: 'sp-arrow-latin', type: 'main', subject: 'spatial', skillIds: ['grid-missing'], familyId: 'grid-missing', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ในแต่ละแถวและแต่ละแถวตั้ง มีลูกศรครบสามแบบ คือ ชี้ขึ้น ชี้ขวา และชี้ลง ช่อง ? ควรเป็นลูกศรแบบใด' },
      visual: {
        type: 'figure-grid',
        rows: [
          [arrow('up'), arrow('right'), arrow('down')],
          [arrow('right'), arrow('down'), arrow('up')],
          [arrow('down'), arrow('up'), '?'],
        ],
      },
      options: [fig('a', arrow('right')), fig('b', arrow('up')), fig('c', arrow('down')), fig('d', arrow('left'))],
      correctOptionId: 'a',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหารูปที่ขาดให้ครบทุกแถวทุกหลัก',
      review: {
        summary: 'แถวล่างมีลูกศรชี้ลงกับชี้ขึ้นแล้ว ขาดลูกศรชี้ขวา',
        hints: ['ดูแถวล่างสุด มีลูกศรแบบไหนแล้วบ้าง'],
        steps: ['แถวล่างมีลูกศรชี้ลงและชี้ขึ้นแล้ว แต่ละแถวต้องมีครบสามแบบ', 'จึงขาดลูกศรชี้ขวา ตอบข้อ 1'],
        transferIds: ['sp-arrow-latin-t'],
      },
    },
    {
      id: 'r-chain-trees', type: 'main', subject: 'reasoning', skillIds: ['compare-chain'], familyId: 'compare-chain', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ต้นมะม่วงสูงกว่าต้นกล้วย ต้นกล้วยสูงกว่าต้นพริก ต้นไม้ชนิดใดเตี้ยที่สุด' },
      options: [{ id: 'a', text: 'ต้นมะม่วง' }, { id: 'b', text: 'ต้นพริก' }, { id: 'c', text: 'ต้นกล้วย' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการเปรียบเทียบความสูงต่อเนื่องสามอย่าง',
      review: {
        summary: 'ต้นพริกเตี้ยกว่าต้นกล้วย และต้นกล้วยเตี้ยกว่าต้นมะม่วง',
        hints: ['เรียงจากสูงที่สุดไปเตี้ยที่สุด'],
        steps: ['เรียงจากสูงไปเตี้ย ได้ ต้นมะม่วง ต้นกล้วย ต้นพริก', 'ต้นที่อยู่ท้ายสุดเตี้ยที่สุด คือต้นพริก ตอบข้อ 2'],
        transferIds: ['r-chain-kids-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'r-family-count-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-count'], familyId: 'story-count', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ที่บ้านของน้องเมฆ มีพ่อ แม่ ยาย พี่สาว และน้องเมฆ ที่บ้านของน้องเมฆมีสมาชิกกี่คน' },
      options: [{ id: 'a', text: '4 คน' }, { id: 'b', text: '5 คน' }, { id: 'c', text: '6 คน' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'พ่อ แม่ ยาย พี่สาว และน้องเมฆ รวม 5 คน', hints: [], steps: ['นับทีละคน พ่อ หนึ่ง แม่ สอง ยาย สาม พี่สาว สี่', 'น้องเมฆ ห้า รวมเป็น 5 คน'] },
    },
    {
      id: 'th-family-grandma-t', type: 'transfer', subject: 'thai', skillIds: ['kinship-words'], familyId: 'kinship', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ยายเป็นแม่ของใคร' },
      options: [{ id: 'a', text: 'แม่' }, { id: 'b', text: 'พี่สาว' }, { id: 'c', text: 'พ่อ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ยายเป็นแม่ของแม่', hints: [], steps: ['ยายและตาเป็นพ่อแม่ของแม่', 'ส่วนแม่ของพ่อเรียกว่าย่า'] },
    },
    {
      id: 'th-family-feel-t', type: 'transfer', subject: 'thai', skillIds: ['feelings'], familyId: 'feelings', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'พี่บอกน้องว่า "อย่าเล่นใกล้บันได เดี๋ยวตกลงมา" คำพูดของพี่ให้ความรู้สึกอย่างไร' },
      options: [{ id: 'a', text: 'สนุกสนาน' }, { id: 'b', text: 'ห่วงใย' }, { id: 'c', text: 'โกรธ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'พี่กลัวน้องตก จึงห่วงใย', hints: [], steps: ['พี่เตือนไม่ให้เล่นใกล้บันได เพราะกลัวน้องตกลงมา', 'คำพูดแบบนี้แสดงความห่วงใย'] },
    },
    {
      id: 'g-family-why-t', type: 'transfer', subject: 'general', skillIds: ['road-safety'], familyId: 'safety-road', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ทำไมเราต้องเดินบนทางเท้า ไม่เดินบนถนน' },
      options: [{ id: 'a', text: 'เพราะทางเท้าสวยกว่า' }, { id: 'b', text: 'เพราะบนถนนมีรถ อาจชนเราได้' }, { id: 'c', text: 'เพราะเดินบนถนนเหนื่อยกว่า' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ถนนเป็นที่ของรถ เดินบนทางเท้าปลอดภัยกว่า', hints: [], steps: ['รถวิ่งบนถนนและอาจชนคนที่เดินอยู่ได้', 'ทางเท้าไว้ให้คนเดิน จึงปลอดภัยกว่า'] },
    },
    {
      id: 'r-family-not-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'เช้าวันเสาร์ น้องฟ้าช่วยแม่ปลูกต้นไม้ และพ่อพาไปซื้อขนม ข้อใดไม่เกี่ยวข้องกับเรื่องนี้' },
      options: [{ id: 'a', text: 'น้องฟ้าช่วยแม่ปลูกต้นไม้' }, { id: 'b', text: 'พ่อพาไปซื้อขนม' }, { id: 'c', text: 'น้องฟ้าไปดูหนัง' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'เรื่องนี้ไม่มีการดูหนัง', hints: [], steps: ['เรื่องมีการปลูกต้นไม้กับการไปซื้อขนม', 'ไม่มีการไปดูหนัง'] },
    },
    {
      id: 'm-half-36-t', type: 'transfer', subject: 'math', skillIds: ['half-of-number'], familyId: 'half', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ครึ่งหนึ่งของ 36 คือเท่าไร' },
      options: [{ id: 'a', text: '16' }, { id: 'b', text: '18' }, { id: 'c', text: '72' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แบ่ง 36 เป็นสองส่วนเท่ากัน ได้ส่วนละ 18', hints: [], steps: ['30 แบ่งครึ่งได้ 15 และ 6 แบ่งครึ่งได้ 3', '15 บวก 3 เท่ากับ 18'] },
    },
    {
      id: 'm-times-stickers-t', type: 'transfer', subject: 'math', skillIds: ['times-as-many'], familyId: 'times-as-many', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'พี่มีสติกเกอร์ 6 ดวง น้องมีสติกเกอร์เป็น 2 เท่าของพี่ น้องมีสติกเกอร์กี่ดวง' },
      options: [{ id: 'a', text: '8 ดวง' }, { id: 'b', text: '12 ดวง' }, { id: 'c', text: '3 ดวง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '2 เท่าของ 6 คือ 6 บวก 6 เท่ากับ 12', hints: [], steps: ['2 เท่าของ 6 คือมี 6 สองชุด', '6 บวก 6 เท่ากับ 12'], column: { a: 6, op: '+', b: 6 } },
    },
    {
      id: 'sc-body-pairs-t', type: 'transfer', subject: 'science', skillIds: ['body-parts'], familyId: 'body-pairs', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดเป็นอวัยวะที่มีเป็นคู่' },
      options: [{ id: 'a', text: 'ปาก' }, { id: 'b', text: 'จมูก' }, { id: 'c', text: 'ตา' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ตามีสองข้าง จึงเป็นคู่', hints: [], steps: ['ปากและจมูกมีอย่างละหนึ่ง', 'ตามีสองข้าง จึงเป็นอวัยวะที่เป็นคู่'] },
    },
    {
      id: 'sc-animal-grass-t', type: 'transfer', subject: 'science', skillIds: ['animal-food'], familyId: 'animal-food', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์ชนิดใดกินหญ้าเป็นอาหาร' },
      options: [{ id: 'a', text: 'ควาย' }, { id: 'b', text: 'เสือ' }, { id: 'c', text: 'แมว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ควายกินหญ้า', hints: [], steps: ['เสือและแมวกินเนื้อ', 'ควายกินหญ้าเป็นอาหาร'] },
    },
    {
      id: 'g-sick-dentist-t', type: 'transfer', subject: 'general', skillIds: ['occupations'], familyId: 'occupations', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าปวดฟัน ควรไปพบใคร' },
      options: [{ id: 'a', text: 'ครู' }, { id: 'b', text: 'หมอฟัน' }, { id: 'c', text: 'ตำรวจ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'หมอฟันรักษาฟัน', hints: [], steps: ['ครูสอนหนังสือ ตำรวจดูแลความปลอดภัย', 'หมอฟันรักษาฟัน'] },
    },
    {
      id: 'th-short-vowel-t', type: 'transfer', subject: 'thai', skillIds: ['vowel-length'], familyId: 'vowel-length', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดใช้สระเสียงยาว' },
      options: [{ id: 'a', text: 'ละ' }, { id: 'b', text: 'ขา' }, { id: 'c', text: 'ดุ' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ขาใช้สระอา ซึ่งเป็นเสียงยาว', hints: [], steps: ['ละใช้สระอะ และดุใช้สระอุ ทั้งสองเป็นเสียงสั้น', 'ขาใช้สระอา เป็นเสียงยาว'] },
    },
    {
      id: 'th-final-kom-t', type: 'transfer', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีตัวสะกดในแม่ กม' },
      options: [{ id: 'a', text: 'ดิน' }, { id: 'b', text: 'ส้ม' }, { id: 'c', text: 'ผัก' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูพยัญชนะท้ายคำเอง',
      review: { summary: 'ส้มมี ม เป็นตัวสะกด อยู่ในแม่ กม', hints: [], steps: ['ดินมี น เป็นตัวสะกด และผักมี ก เป็นตัวสะกด', 'ส้มมี ม เป็นตัวสะกด'] },
    },
    {
      id: 'sp-arrow-quarter-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-analogy'], familyId: 'grid-analogy', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: RULE },
      visual: { type: 'figure-grid', rows: [[arrow('left'), arrow('up')], [arrow('right'), '?']] },
      options: [fig('a', arrow('up')), fig('b', arrow('down')), fig('c', arrow('left')), fig('d', arrow('right'))],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'ลูกศรหมุนตามเข็มนาฬิกาไปหนึ่งในสี่ของรอบ', hints: [], steps: ['แถวบนจากลูกศรชี้ซ้าย เป็นชี้ขึ้น คือหมุนตามเข็มนาฬิกาไปหนึ่งในสี่ของรอบ', 'แถวล่างลูกศรชี้ขวา หมุนต่อไปหนึ่งในสี่ของรอบ จะชี้ลง'] },
    },
    {
      id: 'sp-arrow-latin-t', type: 'transfer', subject: 'spatial', skillIds: ['grid-missing'], familyId: 'grid-missing', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ในแต่ละแถวและแต่ละแถวตั้ง มีลูกศรครบสามแบบ คือ ชี้ซ้าย ชี้ขึ้น และชี้ขวา ช่อง ? ควรเป็นลูกศรแบบใด' },
      visual: {
        type: 'figure-grid',
        rows: [
          [arrow('left'), arrow('up'), arrow('right')],
          [arrow('up'), arrow('right'), arrow('left')],
          [arrow('right'), arrow('left'), '?'],
        ],
      },
      options: [fig('a', arrow('left')), fig('b', arrow('up')), fig('c', arrow('right')), fig('d', arrow('down'))],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'แถวล่างมีลูกศรชี้ขวากับชี้ซ้ายแล้ว ขาดลูกศรชี้ขึ้น', hints: [], steps: ['แถวล่างมีลูกศรชี้ขวาและชี้ซ้ายแล้ว แต่ละแถวต้องมีครบสามแบบ', 'จึงขาดลูกศรชี้ขึ้น'] },
    },
    {
      id: 'r-chain-kids-t', type: 'transfer', subject: 'reasoning', skillIds: ['compare-chain'], familyId: 'compare-chain', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'แพรสูงกว่าฝน ฝนสูงกว่าฟ้า ใครเตี้ยที่สุด' },
      options: [{ id: 'a', text: 'แพร' }, { id: 'b', text: 'ฝน' }, { id: 'c', text: 'ฟ้า' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ฟ้าเตี้ยกว่าฝน และฝนเตี้ยกว่าแพร', hints: [], steps: ['เรียงจากสูงไปเตี้ย ได้ แพร ฝน ฟ้า', 'คนที่อยู่ท้ายสุดคือฟ้า เตี้ยที่สุด'] },
    },
  ],
};
