/*
 * ชุดที่ 20 — รูปแบบใหม่ 15 ข้อ (ดู docs/QUESTION-TYPES.md หัวข้อ "รูปแบบชุด 12 ขึ้นไป")
 * ช่วง 1 เรื่องเดียวถาม 5 ข้อ (น้องแพรกับสัตว์เลี้ยงสองตัว: กินอะไร ขนสีไหนเข้มกว่า ทำไมถึงให้อาหาร ความหมายคำ ข้อใดกล่าวไม่ถูกต้อง)
 * ช่วง 2 แผ่นภาพอาหารและผลไม้ 12 อย่าง ถาม 5 ข้อ (ได้จากสัตว์ นับผลไม้ เปลือกมีหนาม คำเรียกรวม ล้างก่อนกิน)
 * ช่วง 3 ข้อเดี่ยว: เงินทอน วัสดุที่เป็นผ้า ภาพต่อเนื่องรูปทรงสลับกัน ตารางรูปทรง 3x3 วรรณยุกต์ตรี
 * แต่งใหม่ทั้งหมด ตั้งชื่อตัวละครและตัวเลขใหม่ตามแนวข้อสอบเก่า; ใช้รูปที่มีอยู่แล้ว ไม่ต้องสร้างรูปใหม่จาก Gemini
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LISTEN = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const FOODS = 'ดูภาพอาหารแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';
const fig = (id, figure) => ({ id, svg: { figure } });
const shape = (name, fill = 'empty') => ({ shape: name, fill });
const BOARD = { type: 'board', items: ['pic-orange', 'pic-banana', 'pic-grapes', 'pic-watermelon', 'pic-mango', 'pic-durian', 'pic-rambutan', 'pic-carrot', 'pic-rice', 'pic-milk', 'pic-fried-egg', 'pic-egg'] };
const BOARD_TEXT = 'ในภาพมีอาหาร 12 อย่าง คือ ส้ม กล้วย องุ่น แตงโม มะม่วง ทุเรียน เงาะ แครอท ข้าว นม ไข่ดาว และไข่';

export default {
  id: 'set-20',
  version: 1,
  title: 'ชุดที่ 20',
  note: 'สัตว์เลี้ยงของน้องแพร อาหารและผลไม้ เงินทอน ผ้า วรรณยุกต์ตรี',
  order: [
    'th-pet-eat', 'r-pet-dark', 'g-pet-why', 'th-word-care', 'r-pet-wrong',
    'sc-food-animal', 'm-fruit-count', 'r-fruit-spiky', 'th-fruit-group', 'g-fruit-wash',
    'm-money-change', 'sc-cloth', 'sp-shape-pattern', 'sp-shape-latin', 'th-tone-tri',
  ],
  stimuli: {
    pets: {
      section: LISTEN,
      text: 'น้องแพรมีสัตว์เลี้ยงสองตัว คือ แมวสีส้มชื่อเจ้าส้ม และกระต่ายสีขาวชื่อเจ้าขาว ทั้งสองตัวอาศัยอยู่ในบ้านหลังเดียวกัน เจ้าส้มชอบนอนอาบแดดที่หน้าต่าง เจ้าขาวชอบกินแครอทที่น้องแพรให้ ทุกเช้าน้องแพรจะให้อาหารและเปลี่ยนน้ำให้สัตว์เลี้ยงทั้งสองตัว เพราะเธอรักและดูแลสัตว์เลี้ยงเป็นอย่างดี',
    },
    foods: { section: FOODS, text: BOARD_TEXT, visual: BOARD },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: เรื่องเดียว 5 ข้อ
    {
      id: 'th-pet-eat', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-what', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'pets',
      prompt: { text: 'เจ้าขาวชอบกินอะไร' },
      options: [{ id: 'a', text: 'ปลา' }, { id: 'b', text: 'แครอท' }, { id: 'c', text: 'ขนมปัง' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังจับรายละเอียดว่าสัตว์ตัวไหนกินอะไร',
      review: {
        summary: 'กระต่ายชื่อเจ้าขาวชอบกินแครอท',
        hints: ['ฟังประโยคที่พูดถึงเจ้าขาว'],
        steps: ['เรื่องบอกว่า เจ้าขาวชอบกินแครอทที่น้องแพรให้', 'ปลาและขนมปังไม่มีในเรื่อง ตอบข้อ 2'],
        transferIds: ['th-pet-eat-t'],
      },
    },
    {
      id: 'r-pet-dark', type: 'main', subject: 'reasoning', skillIds: ['compare-color'], familyId: 'story-compare', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'pets',
      prompt: { text: 'ขนของสัตว์ตัวใดมีสีเข้มกว่ากัน' },
      options: [{ id: 'a', text: 'เจ้าส้ม' }, { id: 'b', text: 'เจ้าขาว' }, { id: 'c', text: 'ตอบไม่ได้' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการเปรียบเทียบสีจากเรื่อง (ส้มเข้มกว่าขาว)',
      review: {
        summary: 'สีส้มเข้มกว่าสีขาว',
        hints: ['เรื่องบอกสีของสัตว์แต่ละตัวไว้แล้ว'],
        steps: ['เจ้าส้มเป็นแมวสีส้ม และเจ้าขาวเป็นกระต่ายสีขาว', 'สีส้มเข้มกว่าสีขาว จึงเป็นเจ้าส้ม ตอบข้อ 1'],
        transferIds: ['r-pet-dark-t'],
      },
    },
    {
      id: 'g-pet-why', type: 'main', subject: 'general', skillIds: ['story-why-good'], familyId: 'story-why-good', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'pets',
      prompt: { text: 'ทำไมน้องแพรจึงให้อาหารสัตว์เลี้ยงทุกเช้า' },
      options: [{ id: 'a', text: 'เพราะน้องแพรไม่มีอะไรทำ' }, { id: 'b', text: 'เพราะอยากเล่นกับเพื่อน' }, { id: 'c', text: 'เพราะรักและดูแลสัตว์เลี้ยง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการฟังหาเหตุผล',
      review: {
        summary: 'น้องแพรรักสัตว์เลี้ยงและอยากดูแลให้ดี',
        hints: ['ฟังประโยคสุดท้ายของเรื่อง'],
        steps: ['เรื่องบอกว่า น้องแพรให้อาหารทุกเช้า เพราะเธอรักและดูแลสัตว์เลี้ยง', 'เหตุผลอื่นไม่มีในเรื่อง ตอบข้อ 3'],
        transferIds: ['g-pet-why-t'],
      },
    },
    {
      id: 'th-word-care', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'pets',
      prompt: { text: 'คำว่า ดูแล หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'ปล่อยให้อยู่ตามลำพัง' }, { id: 'b', text: 'เอาใจใส่ให้อยู่ดีมีสุข' }, { id: 'c', text: 'ไล่ออกจากบ้าน' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ วัดความเข้าใจความหมายคำจากเรื่อง',
      review: {
        summary: 'ดูแล คือเอาใจใส่ให้สัตว์เลี้ยงสบายและปลอดภัย',
        hints: ['น้องแพรทำอะไรให้สัตว์เลี้ยงทุกเช้า'],
        steps: ['น้องแพรให้อาหารและเปลี่ยนน้ำให้สัตว์เลี้ยงทุกเช้า', 'นี่คือการเอาใจใส่ให้อยู่ดีมีสุข ตอบข้อ 2'],
        transferIds: ['th-word-care-t'],
      },
    },
    {
      id: 'r-pet-wrong', type: 'main', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'pets',
      prompt: { text: 'ข้อใดกล่าวไม่ถูกต้อง' },
      options: [{ id: 'a', text: 'เจ้าส้มเป็นแมวสีส้ม' }, { id: 'b', text: 'เจ้าขาวเป็นกระต่ายสีขาว' }, { id: 'c', text: 'เจ้าส้มชอบกินแครอท' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการจำรายละเอียดจากเรื่องแล้วหาข้อที่ผิด',
      review: {
        summary: 'แครอทเป็นของที่เจ้าขาวชอบกิน ไม่ใช่เจ้าส้ม',
        hints: ['ตรวจทีละข้อว่าตรงกับเรื่องหรือไม่'],
        steps: ['เจ้าส้มเป็นแมวสีส้ม และเจ้าขาวเป็นกระต่ายสีขาว ตรงกับเรื่อง', 'คนที่ชอบกินแครอทคือเจ้าขาว ข้อที่ผิดคือข้อ 3'],
        transferIds: ['r-pet-wrong-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: แผ่นภาพอาหารและผลไม้ 5 ข้อ
    {
      id: 'sc-food-animal', type: 'main', subject: 'science', skillIds: ['food-source'], familyId: 'board-classify', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'foods',
      prompt: { text: 'อาหารสองอย่างใดที่ได้มาจากสัตว์' },
      options: [{ id: 'a', text: 'นม, ไข่' }, { id: 'b', text: 'ข้าว, แครอท' }, { id: 'c', text: 'มะม่วง, ส้ม' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องที่มาของอาหาร',
      review: {
        summary: 'นมได้จากวัว ไข่ได้จากไก่',
        hints: ['อาหารอะไรที่ไม่ได้มาจากต้นไม้'],
        steps: ['ข้าว แครอท มะม่วง และส้ม ได้จากพืช', 'นมและไข่ได้จากสัตว์ ตอบข้อ 1'],
        transferIds: ['sc-food-animal-t'],
      },
    },
    {
      id: 'm-fruit-count', type: 'main', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'foods',
      prompt: { text: 'ในภาพมีผลไม้กี่อย่าง' },
      options: [{ id: 'a', text: '6 อย่าง' }, { id: 'b', text: '7 อย่าง' }, { id: 'c', text: '8 อย่าง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มแล้วนับ (แครอทเป็นผัก ไม่นับ)',
      review: {
        summary: 'ผลไม้มี ส้ม กล้วย องุ่น แตงโม มะม่วง ทุเรียน และเงาะ รวม 7 อย่าง',
        hints: ['เลือกเฉพาะผลไม้ แล้วนับทีละอย่าง'],
        steps: ['ผลไม้ในภาพ คือ ส้ม กล้วย องุ่น แตงโม มะม่วง ทุเรียน และเงาะ', 'แครอทเป็นผัก ข้าวเป็นอาหารหลัก นมและไข่ได้จากสัตว์ ไม่นับ รวมเป็น 7 อย่าง ตอบข้อ 2'],
        transferIds: ['m-fruit-count-t'],
      },
    },
    {
      id: 'r-fruit-spiky', type: 'main', subject: 'reasoning', skillIds: ['classify'], familyId: 'board-classify', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'foods',
      prompt: { text: 'ผลไม้สองอย่างใดที่เปลือกนอกมีหนามหรือขน' },
      options: [{ id: 'a', text: 'ส้ม, กล้วย' }, { id: 'b', text: 'องุ่น, แตงโม' }, { id: 'c', text: 'ทุเรียน, เงาะ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มตามลักษณะของเปลือก',
      review: {
        summary: 'ทุเรียนมีหนาม เงาะมีขนอ่อนๆ ที่เปลือก',
        hints: ['นึกถึงผลไม้ที่จับแล้วสะดุ้ง หรือมีขนยาวๆ'],
        steps: ['ส้ม กล้วย องุ่น และแตงโม เปลือกเรียบ', 'ทุเรียนมีหนาม เงาะมีขนที่เปลือก ตอบข้อ 3'],
        transferIds: ['r-fruit-spiky-t'],
      },
    },
    {
      id: 'th-fruit-group', type: 'main', subject: 'thai', skillIds: ['group-words'], familyId: 'group-words', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'foods',
      prompt: { text: 'ส้ม กล้วย องุ่น เรียกรวมกันว่าอะไร' },
      options: [{ id: 'a', text: 'ผัก' }, { id: 'b', text: 'ผลไม้' }, { id: 'c', text: 'ขนม' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจคำเรียกรวมของกลุ่มคำ',
      review: {
        summary: 'ส้ม กล้วย องุ่น เป็นผลไม้',
        hints: ['ของที่กินได้จากต้นไม้ และมักมีรสหวาน'],
        steps: ['ผักคือพืชอย่างแครอท ส่วนขนมเป็นของที่ทำขึ้น', 'ส้ม กล้วย องุ่น เรียกรวมกันว่าผลไม้ ตอบข้อ 2'],
        transferIds: ['th-fruit-group-t'],
      },
    },
    {
      id: 'g-fruit-wash', type: 'main', subject: 'general', skillIds: ['hygiene-reason'], familyId: 'hygiene-reason', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'foods',
      prompt: { text: 'ก่อนกินผลไม้ ควรทำอย่างไร' },
      options: [{ id: 'a', text: 'ล้างให้สะอาด' }, { id: 'b', text: 'เช็ดกับพื้น' }, { id: 'c', text: 'ทิ้งไว้ตากฝน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องความสะอาดของอาหาร',
      review: {
        summary: 'ล้างผลไม้ให้สะอาดก่อนกิน จะได้ไม่ท้องเสีย',
        hints: ['ผลไม้อาจมีฝุ่นและเชื้อโรคติดอยู่'],
        steps: ['เช็ดกับพื้นหรือทิ้งไว้ตากฝน ทำให้ผลไม้สกปรก', 'ควรล้างให้สะอาดก่อนกิน ตอบข้อ 1'],
        transferIds: ['g-fruit-wash-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3: เงินทอน ผ้า ภาพรูปทรง วรรณยุกต์ตรี
    {
      id: 'm-money-change', type: 'main', subject: 'math', skillIds: ['money-change'], familyId: 'money-change', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'แม่ให้เงินน้องฝน 10 บาท น้องฝนซื้อขนม 6 บาท น้องฝนจะได้เงินทอนกี่บาท' },
      options: [{ id: 'a', text: '16 บาท' }, { id: 'b', text: '6 บาท' }, { id: 'c', text: '4 บาท' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการหาเงินทอนด้วยการลบ',
      review: {
        summary: 'จ่ายไป 6 บาท จากเงิน 10 บาท เหลือทอน 4 บาท',
        hints: ['เงินทอนคือเงินที่เหลือหลังจากจ่ายค่าขนม'],
        steps: ['มีเงิน 10 บาท ซื้อขนม 6 บาท ต้องเอา 6 ไปลบออกจาก 10', '10 ลบ 6 เท่ากับ 4 ตอบข้อ 3'],
        column: { a: 10, op: '-', b: 6 },
        transferIds: ['m-money-change-t'],
      },
    },
    {
      id: 'sc-cloth', type: 'main', subject: 'science', skillIds: ['materials'], familyId: 'materials', difficulty: 1,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'สิ่งของสองอย่างใดทำมาจากผ้า' },
      options: [{ id: 'a', text: 'เสื้อ, ผ้าเช็ดตัว' }, { id: 'b', text: 'จาน, แก้วน้ำ' }, { id: 'c', text: 'ช้อน, ส้อม' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องวัสดุที่ใช้ทำของใช้',
      review: {
        summary: 'เสื้อและผ้าเช็ดตัวทำจากผ้า',
        hints: ['ของที่นุ่มและซับน้ำได้ ใส่หรือเช็ดตัวได้'],
        steps: ['จานและแก้วน้ำเป็นของแข็ง ช้อนและส้อมทำจากโลหะ', 'เสื้อและผ้าเช็ดตัวทำจากผ้า ตอบข้อ 1'],
        transferIds: ['sc-cloth-t'],
      },
    },
    {
      id: 'sp-shape-pattern', type: 'main', subject: 'spatial', skillIds: ['pattern-continue'], familyId: 'shape-pattern', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'รูปในช่อง ? ควรเป็นรูปใด' },
      visual: { type: 'figure-row', items: [shape('circle', 'solid'), shape('square'), shape('circle', 'solid'), shape('square'), '?'] },
      options: [fig('a', shape('circle')), fig('b', shape('square', 'solid')), fig('c', shape('circle', 'solid')), fig('d', shape('square'))],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหาแบบที่สลับกันเป็นรอบ',
      review: {
        summary: 'วงกลมทึบกับสี่เหลี่ยมว่างสลับกันเป็นรอบ',
        hints: ['ดูว่ารูปไหนมาก่อน แล้วรูปไหนตามมา เป็นรอบๆ'],
        steps: ['เรียงเป็น วงกลมทึบ สี่เหลี่ยมว่าง วงกลมทึบ สี่เหลี่ยมว่าง สลับกัน', 'ต่อจากสี่เหลี่ยมว่างต้องเป็นวงกลมทึบ ตอบข้อ 3'],
        transferIds: ['sp-shape-pattern-t'],
      },
    },
    {
      id: 'sp-shape-latin', type: 'main', subject: 'spatial', skillIds: ['grid-missing'], familyId: 'grid-missing', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ในแต่ละแถวและแต่ละแถวตั้ง มีรูปครบสามแบบ คือ วงกลม สี่เหลี่ยม และสามเหลี่ยม ช่อง ? ควรเป็นรูปใด' },
      visual: {
        type: 'figure-grid',
        rows: [
          [shape('circle'), shape('square'), shape('triangle')],
          [shape('square'), shape('triangle'), shape('circle')],
          [shape('triangle'), shape('circle'), '?'],
        ],
      },
      options: [fig('a', shape('square')), fig('b', shape('circle')), fig('c', shape('hexagon')), fig('d', shape('triangle'))],
      correctOptionId: 'a',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหารูปที่ขาดให้ครบทุกแถวทุกหลัก',
      review: {
        summary: 'แถวล่างมีสามเหลี่ยมกับวงกลมแล้ว ขาดสี่เหลี่ยม',
        hints: ['ดูแถวล่างสุด มีรูปแบบไหนแล้วบ้าง'],
        steps: ['แถวล่างมีสามเหลี่ยมและวงกลมแล้ว แต่ละแถวต้องมีครบสามแบบ', 'จึงขาดสี่เหลี่ยม ตอบข้อ 1'],
        transferIds: ['sp-shape-latin-t'],
      },
    },
    {
      id: 'th-tone-tri', type: 'main', subject: 'thai', skillIds: ['tone-mark'], familyId: 'tone-mark', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีวรรณยุกต์ตรี' },
      options: [{ id: 'a', text: 'ปู่' }, { id: 'b', text: 'โต๊ะ' }, { id: 'c', text: 'เสื้อ' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูเครื่องหมายวรรณยุกต์เอง (ฟังเสียงอย่างเดียวบอกไม่ได้)',
      review: {
        summary: 'โต๊ะมีไม้ตรี เป็นเครื่องหมายคล้ายบวกเล็กๆ เหนือตัว ต',
        hints: ['ไม้ตรีเป็นเครื่องหมายที่ดูเหมือนเครื่องหมายบวกเล็กๆ'],
        steps: ['ปู่มีไม้เอก และเสื้อมีไม้โท ซึ่งรูปไม่เหมือนไม้ตรี', 'โต๊ะมีไม้ตรีอยู่เหนือตัว ต ตอบข้อ 2'],
        transferIds: ['th-tone-tri-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-pet-eat-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-what', difficulty: 1,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'น้องบีมีแมวชื่อเจ้าเหมียว เจ้าเหมียวชอบกินปลา และชอบนอนบนโซฟา เจ้าเหมียวชอบกินอะไร' },
      options: [{ id: 'a', text: 'ปลา' }, { id: 'b', text: 'แครอท' }, { id: 'c', text: 'หญ้า' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'เจ้าเหมียวชอบกินปลา', hints: [], steps: ['เรื่องบอกว่า เจ้าเหมียวชอบกินปลา', 'โซฟาเป็นที่นอน ไม่ใช่อาหาร'] },
    },
    {
      id: 'r-pet-dark-t', type: 'transfer', subject: 'reasoning', skillIds: ['compare-color'], familyId: 'story-compare', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'น้องกานต์มีแมวสีดำและไก่สีขาว ขนของสัตว์ตัวใดมีสีเข้มกว่ากัน' },
      options: [{ id: 'a', text: 'แมวสีดำ' }, { id: 'b', text: 'ไก่สีขาว' }, { id: 'c', text: 'ตอบไม่ได้' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'สีดำเข้มกว่าสีขาว', hints: [], steps: ['แมวสีดำ ไก่สีขาว', 'สีดำเข้มกว่าสีขาว จึงเป็นแมว'] },
    },
    {
      id: 'g-pet-why-t', type: 'transfer', subject: 'general', skillIds: ['story-why-good'], familyId: 'story-why-good', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'น้องเมฆให้อาหารไก่ทุกเช้า เพราะอะไร' },
      options: [{ id: 'a', text: 'เพราะไก่ต้องการอาหาร จะได้แข็งแรง' }, { id: 'b', text: 'เพราะอยากให้ไก่ร้องเสียงดัง' }, { id: 'c', text: 'เพราะไม่มีอะไรทำ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'สัตว์เลี้ยงต้องมีคนให้อาหารจึงอยู่ได้', hints: [], steps: ['ไก่หาอาหารเองในกรงไม่ได้', 'น้องเมฆจึงให้อาหาร เพื่อให้ไก่แข็งแรง'] },
    },
    {
      id: 'th-word-care-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า ใส่ใจ หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'ไม่สนใจเลย' }, { id: 'b', text: 'ตั้งใจและเอาใจจดจ่อกับสิ่งนั้น' }, { id: 'c', text: 'ง่วงนอน' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ใส่ใจ คือตั้งใจและไม่ละเลย', hints: [], steps: ['คนที่ใส่ใจ จะสนใจและตั้งใจกับสิ่งที่ทำ', 'ไม่สนใจเลย หรือง่วงนอน ไม่ใช่ใส่ใจ'] },
    },
    {
      id: 'r-pet-wrong-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ปลาอาศัยอยู่ในน้ำ นกบินได้ ข้อใดกล่าวไม่ถูกต้อง' },
      options: [{ id: 'a', text: 'ปลาอาศัยอยู่ในน้ำ' }, { id: 'b', text: 'นกบินได้' }, { id: 'c', text: 'ปลาเดินบนบกได้' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ปลาเดินบนบกไม่ได้', hints: [], steps: ['ข้อความบอกว่า ปลาอาศัยอยู่ในน้ำ และนกบินได้', 'ไม่ได้บอกว่าปลาเดินบนบกได้ ข้อนี้จึงไม่ถูกต้อง'] },
    },
    {
      id: 'sc-food-animal-t', type: 'transfer', subject: 'science', skillIds: ['food-source'], familyId: 'board-classify', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'อาหารในข้อใดได้มาจากสัตว์' },
      options: [{ id: 'a', text: 'ผักกาด' }, { id: 'b', text: 'ไข่ไก่' }, { id: 'c', text: 'ข้าวสวย' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไข่ไก่ได้จากไก่', hints: [], steps: ['ผักกาดและข้าวสวยได้จากพืช', 'ไข่ไก่ได้จากไก่'] },
    },
    {
      id: 'm-fruit-count-t', type: 'transfer', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ในตะกร้ามี ส้ม กล้วย แครอท และมะม่วง ในตะกร้ามีผลไม้กี่อย่าง' },
      options: [{ id: 'a', text: '2 อย่าง' }, { id: 'b', text: '3 อย่าง' }, { id: 'c', text: '4 อย่าง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ส้ม กล้วย และมะม่วง เป็นผลไม้ รวม 3 อย่าง', hints: [], steps: ['แครอทเป็นผัก ไม่ใช่ผลไม้', 'ผลไม้มี ส้ม กล้วย มะม่วง รวม 3 อย่าง'] },
    },
    {
      id: 'r-fruit-spiky-t', type: 'transfer', subject: 'reasoning', skillIds: ['classify'], familyId: 'board-classify', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ผลไม้ชนิดใดมีหนามแหลมที่เปลือก' },
      options: [{ id: 'a', text: 'ทุเรียน' }, { id: 'b', text: 'กล้วย' }, { id: 'c', text: 'องุ่น' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ทุเรียนมีหนามแหลม', hints: [], steps: ['กล้วยและองุ่นเปลือกเรียบ ไม่มีหนาม', 'ทุเรียนมีหนามแหลมที่เปลือก'] },
    },
    {
      id: 'th-fruit-group-t', type: 'transfer', subject: 'thai', skillIds: ['group-words'], familyId: 'group-words', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ไก่ เป็ด วัว เรียกรวมกันว่าอะไร' },
      options: [{ id: 'a', text: 'สัตว์น้ำ' }, { id: 'b', text: 'สัตว์เลี้ยง' }, { id: 'c', text: 'ผลไม้' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไก่ เป็ด วัว เป็นสัตว์เลี้ยง', hints: [], steps: ['สัตว์น้ำอาศัยอยู่ในน้ำ ส่วนผลไม้คือของที่กินได้จากต้นไม้', 'ไก่ เป็ด วัว คนเลี้ยงไว้ จึงเรียกว่าสัตว์เลี้ยง'] },
    },
    {
      id: 'g-fruit-wash-t', type: 'transfer', subject: 'general', skillIds: ['hygiene-reason'], familyId: 'hygiene-reason', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ก่อนกินข้าว ควรทำอย่างไร' },
      options: [{ id: 'a', text: 'ล้างมือให้สะอาด' }, { id: 'b', text: 'จับพื้นก่อน' }, { id: 'c', text: 'ขยี้ตา' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ล้างมือก่อนกินข้าวทุกครั้ง', hints: [], steps: ['มือที่สกปรกมีเชื้อโรค', 'ล้างมือให้สะอาดก่อนกินข้าว'] },
    },
    {
      id: 'm-money-change-t', type: 'transfer', subject: 'math', skillIds: ['money-change'], familyId: 'money-change', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'น้องมีเงิน 20 บาท ซื้อไอศกรีม 15 บาท น้องจะได้เงินทอนกี่บาท' },
      options: [{ id: 'a', text: '5 บาท' }, { id: 'b', text: '35 บาท' }, { id: 'c', text: '15 บาท' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '20 ลบ 15 เท่ากับ 5 บาท', hints: [], steps: ['มีเงิน 20 บาท จ่ายไป 15 บาท ต้องเอา 15 ไปลบจาก 20', '20 ลบ 15 เท่ากับ 5'], column: { a: 20, op: '-', b: 15 } },
    },
    {
      id: 'sc-cloth-t', type: 'transfer', subject: 'science', skillIds: ['materials'], familyId: 'materials', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สิ่งของในข้อใดทำมาจากผ้า' },
      options: [{ id: 'a', text: 'ช้อน' }, { id: 'b', text: 'ผ้าห่ม' }, { id: 'c', text: 'แก้วน้ำ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ผ้าห่มทำจากผ้า', hints: [], steps: ['ช้อนทำจากโลหะ และแก้วน้ำเป็นของแข็ง', 'ผ้าห่มทำจากผ้า'] },
    },
    {
      id: 'sp-shape-pattern-t', type: 'transfer', subject: 'spatial', skillIds: ['pattern-continue'], familyId: 'shape-pattern', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'รูปในช่อง ? ควรเป็นรูปใด' },
      visual: { type: 'figure-row', items: [shape('triangle', 'solid'), shape('circle'), shape('triangle', 'solid'), shape('circle'), '?'] },
      options: [fig('a', shape('circle')), fig('b', shape('triangle', 'solid')), fig('c', shape('triangle')), fig('d', shape('circle', 'solid'))],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'สามเหลี่ยมทึบกับวงกลมว่างสลับกันเป็นรอบ', hints: [], steps: ['เรียงเป็น สามเหลี่ยมทึบ วงกลมว่าง สลับกัน', 'ต่อจากวงกลมว่างต้องเป็นสามเหลี่ยมทึบ'] },
    },
    {
      id: 'sp-shape-latin-t', type: 'transfer', subject: 'spatial', skillIds: ['grid-missing'], familyId: 'grid-missing', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ในแต่ละแถวและแต่ละแถวตั้ง มีรูปครบสามแบบ คือ ข้าวหลามตัด วงกลม และสี่เหลี่ยม ช่อง ? ควรเป็นรูปใด' },
      visual: {
        type: 'figure-grid',
        rows: [
          [shape('diamond'), shape('circle'), shape('square')],
          [shape('circle'), shape('square'), shape('diamond')],
          [shape('square'), shape('diamond'), '?'],
        ],
      },
      options: [fig('a', shape('square')), fig('b', shape('circle')), fig('c', shape('diamond')), fig('d', shape('triangle'))],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'แถวล่างมีสี่เหลี่ยมกับข้าวหลามตัดแล้ว ขาดวงกลม', hints: [], steps: ['แถวล่างมีสี่เหลี่ยมและข้าวหลามตัดแล้ว แต่ละแถวต้องมีครบสามแบบ', 'จึงขาดวงกลม'] },
    },
    {
      id: 'th-tone-tri-t', type: 'transfer', subject: 'thai', skillIds: ['tone-mark'], familyId: 'tone-mark', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีวรรณยุกต์ตรี' },
      options: [{ id: 'a', text: 'ขา' }, { id: 'b', text: 'ก๊อก' }, { id: 'c', text: 'น้ำ' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูเครื่องหมายวรรณยุกต์เอง',
      review: { summary: 'ก๊อกมีไม้ตรี', hints: [], steps: ['ขาไม่มีเครื่องหมายเหนือพยัญชนะ ส่วนน้ำมีไม้โท', 'ก๊อกมีไม้ตรีอยู่เหนือตัว ก'] },
    },
  ],
};
