/*
 * ชุดที่ 26 — รูปแบบใหม่ 15 ข้อ (ดู docs/QUESTION-TYPES.md หัวข้อ "รูปแบบชุด 12 ขึ้นไป")
 * ช่วง 1 เรื่องฟาร์มของลุงสมชาย (สัตว์มีชื่อเล่น) ถาม 5 ข้อ: ชื่อเล่นคือสัตว์อะไร ใครให้นม จำนวนชนิด ข้อใดกล่าวไม่ถูกต้อง สัตว์กินอะไร
 * ช่วง 2 เดือนและวันสำคัญ (ข้อความ) 5 ข้อ: เดือนแรกของปี นับเดือน วันแม่ เดือนถัดไป ชื่อเดือน
 * ช่วง 3 ข้อเดี่ยว: ตัวสะกดแม่ กบ, คำควบกล้ำ, โลหะ, ภาพจุดลดลง, นับเพิ่มทีละ 4, ภาพที่อยู่ระหว่างสองภาพ
 * แต่งใหม่ทั้งหมด ตั้งชื่อตัวละคร สถานที่ และตัวเลขใหม่ตามแนวข้อสอบเก่า; ใช้รูปที่มีอยู่แล้ว
 * (ผู้ปกครองรายงาน 2026-10-02: ข้อสอบจริงมีโจทย์เป็นตัวหนังสือให้เด็กดูด้วย — ทุกข้อในชุดนี้อ่านรู้เรื่องจากตัวหนังสือได้)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LISTEN = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const MONTHS = 'ตอบคำถามเกี่ยวกับเดือนและวันสำคัญให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';
const fig = (id, figure) => ({ id, svg: { figure } });

export default {
  id: 'set-26',
  version: 1,
  title: 'ชุดที่ 26',
  note: 'ฟาร์มลุงสมชาย ชื่อเดือน วันสำคัญ ตัวสะกดแม่ กบ คำควบกล้ำ',
  order: [
    'th-farm-nick', 'sc-farm-milk', 'm-farm-kinds', 'r-farm-wrong', 'sc-farm-eat',
    'g-month-first', 'm-months-count', 'g-mother-day', 'r-month-next', 'th-month-word',
    'th-final-kb', 'th-cluster', 'sp-dots-minus2', 'm-egg-trays', 'sp-between-frog',
  ],
  stimuli: {
    farm: {
      section: LISTEN,
      text: 'ที่ฟาร์มของลุงสมชาย มีสัตว์เลี้ยงหลายชนิด เจ้าโต้งเป็นไก่ตัวผู้สีแดง ขันปลุกทุกคนตอนเช้า เจ้าด่างเป็นวัวสีขาวดำ ให้นมสดทุกวัน เจ้าเหมียวเป็นแมว ชอบจับหนูในยุ้งข้าว ส่วนเจ้าก้านเป็นเป็ดที่ชอบว่ายน้ำในบ่อ ลุงสมชายรักสัตว์ทุกตัวและให้อาหารทุกเช้าเย็น',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: ฟาร์มของลุงสมชาย 5 ข้อ
    {
      id: 'th-farm-nick', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-nickname', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'farm',
      prompt: { text: 'เจ้าโต้งคือสัตว์ชนิดใด' },
      options: [{ id: 'a', text: 'วัว' }, { id: 'b', text: 'ไก่' }, { id: 'c', text: 'เป็ด' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการจับว่าชื่อเล่นหมายถึงสัตว์ชนิดใด',
      review: {
        summary: 'เจ้าโต้งเป็นไก่ตัวผู้สีแดง',
        hints: ['ฟังประโยคแรกที่พูดถึงเจ้าโต้ง'],
        steps: ['เรื่องบอกว่า เจ้าโต้งเป็นไก่ตัวผู้สีแดง', 'เจ้าด่างเป็นวัว และเจ้าก้านเป็นเป็ด ตอบข้อ 2'],
        transferIds: ['th-farm-nick-t'],
      },
    },
    {
      id: 'sc-farm-milk', type: 'main', subject: 'science', skillIds: ['animal-products'], familyId: 'animal-products', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'farm',
      prompt: { text: 'สัตว์ชนิดใดให้นมสดแก่คน' },
      options: [{ id: 'a', text: 'วัว' }, { id: 'b', text: 'ไก่' }, { id: 'c', text: 'แมว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสิ่งที่ได้จากสัตว์',
      review: {
        summary: 'วัวให้นมสด',
        hints: ['ฟังว่าใครให้นมสดทุกวัน'],
        steps: ['ไก่ให้ไข่ และแมวไม่ให้นมแก่คน', 'เจ้าด่างเป็นวัวและให้นมสด ตอบข้อ 1'],
        transferIds: ['sc-farm-milk-t'],
      },
    },
    {
      id: 'm-farm-kinds', type: 'main', subject: 'math', skillIds: ['story-count-kinds'], familyId: 'story-kinds', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'farm',
      prompt: { text: 'ที่ฟาร์มของลุงสมชายมีสัตว์เลี้ยงกี่ชนิด' },
      options: [{ id: 'a', text: '3 ชนิด' }, { id: 'b', text: '5 ชนิด' }, { id: 'c', text: '4 ชนิด' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการนับชนิดสัตว์จากเรื่อง',
      review: {
        summary: 'ไก่ วัว แมว และเป็ด รวม 4 ชนิด',
        hints: ['นับทีละชนิด อย่านับลุงสมชาย'],
        steps: ['เรื่องมี ไก่ หนึ่ง วัว สอง แมว สาม เป็ด สี่', 'รวมเป็น 4 ชนิด ตอบข้อ 3'],
        transferIds: ['m-farm-kinds-t'],
      },
    },
    {
      id: 'r-farm-wrong', type: 'main', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'farm',
      prompt: { text: 'ข้อใดกล่าวไม่ถูกต้อง' },
      options: [{ id: 'a', text: 'เจ้าเหมียวเป็นไก่' }, { id: 'b', text: 'เจ้าโต้งเป็นไก่' }, { id: 'c', text: 'เจ้าก้านเป็นเป็ด' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการจำรายละเอียดจากเรื่องแล้วหาข้อที่ผิด',
      review: {
        summary: 'เจ้าเหมียวเป็นแมว ไม่ใช่ไก่',
        hints: ['ตรวจทีละข้อว่าชื่อเล่นกับสัตว์ตรงกับเรื่องไหม'],
        steps: ['เจ้าโต้งเป็นไก่ และเจ้าก้านเป็นเป็ด ตรงกับเรื่อง', 'เจ้าเหมียวเป็นแมว ข้อที่ผิดคือข้อ 1'],
        transferIds: ['r-farm-wrong-t'],
      },
    },
    {
      id: 'sc-farm-eat', type: 'main', subject: 'science', skillIds: ['animal-food'], familyId: 'animal-food', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'farm',
      prompt: { text: 'วัวกินอะไรเป็นอาหาร' },
      options: [{ id: 'a', text: 'เนื้อ' }, { id: 'b', text: 'หญ้า' }, { id: 'c', text: 'ปลา' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องอาหารของสัตว์',
      review: {
        summary: 'วัวกินหญ้าเป็นอาหาร',
        hints: ['นึกถึงวัวที่เดินกินอะไรในทุ่ง'],
        steps: ['เนื้อและปลาเป็นอาหารของสัตว์กินเนื้อ', 'วัวกินหญ้า ตอบข้อ 2'],
        transferIds: ['sc-farm-eat-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: เดือนและวันสำคัญ
    {
      id: 'g-month-first', type: 'main', subject: 'general', skillIds: ['months'], familyId: 'months', difficulty: 1,
      sourceId: SRC, ...R, section: MONTHS,
      prompt: { text: 'เดือนแรกของปีคือเดือนใด' },
      options: [{ id: 'a', text: 'ธันวาคม' }, { id: 'b', text: 'มิถุนายน' }, { id: 'c', text: 'มกราคม' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องชื่อเดือน',
      review: {
        summary: 'ปีใหม่เริ่มที่เดือนมกราคม',
        hints: ['วันขึ้นปีใหม่ 1 มกราคม'],
        steps: ['ธันวาคมเป็นเดือนสุดท้ายของปี และมิถุนายนอยู่กลางปี', 'เดือนแรกของปีคือมกราคม ตอบข้อ 3'],
        transferIds: ['g-month-first-t'],
      },
    },
    {
      id: 'm-months-count', type: 'main', subject: 'math', skillIds: ['months'], familyId: 'months-count', difficulty: 2,
      sourceId: SRC, ...R, section: MONTHS,
      prompt: { text: 'ตั้งแต่เดือนมกราคมถึงเดือนมีนาคม มีกี่เดือน' },
      options: [{ id: 'a', text: '2 เดือน' }, { id: 'b', text: '3 เดือน' }, { id: 'c', text: '4 เดือน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับเดือนต่อเนื่อง',
      review: {
        summary: 'มกราคม กุมภาพันธ์ มีนาคม รวม 3 เดือน',
        hints: ['นับเดือนแรกและเดือนสุดท้ายด้วย'],
        steps: ['เดือนเรียงกันคือ มกราคม กุมภาพันธ์ มีนาคม', 'นับ 1 2 3 ได้ 3 เดือน ตอบข้อ 2'],
        transferIds: ['m-months-count-t'],
      },
    },
    {
      id: 'g-mother-day', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 2,
      sourceId: SRC, ...R, section: MONTHS,
      prompt: { text: 'วันแม่แห่งชาติตรงกับเดือนใด' },
      options: [{ id: 'a', text: 'สิงหาคม' }, { id: 'b', text: 'เมษายน' }, { id: 'c', text: 'ธันวาคม' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องวันสำคัญ (วันแม่ 12 สิงหาคม) ผู้ปกครองควรตรวจ',
      review: {
        summary: 'วันแม่แห่งชาติคือวันที่ 12 สิงหาคม',
        hints: ['เดือนที่เด็กๆ ไปกราบแม่และมอบดอกมะลิ'],
        steps: ['เมษายนมีวันสงกรานต์ และธันวาคมมีวันพ่อและวันสิ้นปี', 'วันแม่แห่งชาติตรงกับเดือนสิงหาคม ตอบข้อ 1'],
        transferIds: ['g-mother-day-t'],
      },
    },
    {
      id: 'r-month-next', type: 'main', subject: 'reasoning', skillIds: ['months'], familyId: 'months-order', difficulty: 2,
      sourceId: SRC, ...R, section: MONTHS,
      prompt: { text: 'เดือนใดอยู่ถัดจากเดือนเมษายน' },
      options: [{ id: 'a', text: 'มีนาคม' }, { id: 'b', text: 'มิถุนายน' }, { id: 'c', text: 'พฤษภาคม' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงลำดับเดือน',
      review: {
        summary: 'เมษายนตามด้วยพฤษภาคม',
        hints: ['ลองท่องชื่อเดือนเรียงกันจากมกราคม'],
        steps: ['เรียงเดือนได้ มีนาคม เมษายน พฤษภาคม มิถุนายน', 'ถัดจากเมษายนคือพฤษภาคม ตอบข้อ 3'],
        transferIds: ['r-month-next-t'],
      },
    },
    {
      id: 'th-month-word', type: 'main', subject: 'thai', skillIds: ['classify-words'], familyId: 'classify-words', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดเป็นชื่อเดือน' },
      options: [{ id: 'a', text: 'พุธ' }, { id: 'b', text: 'กรกฎาคม' }, { id: 'c', text: 'ศุกร์' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ วัดการแยกชื่อเดือนออกจากชื่อวัน',
      review: {
        summary: 'กรกฎาคมเป็นชื่อเดือน ส่วนพุธและศุกร์เป็นชื่อวัน',
        hints: ['ชื่อวันมี 7 วัน ชื่อเดือนมี 12 เดือน'],
        steps: ['พุธและศุกร์เป็นชื่อวันในสัปดาห์', 'กรกฎาคมเป็นชื่อเดือน ตอบข้อ 2'],
        transferIds: ['th-month-word-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3: ตัวสะกด คำควบกล้ำ โลหะ ภาพ นับเพิ่ม
    {
      id: 'th-final-kb', type: 'main', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีตัวสะกดในแม่ กบ' },
      options: [{ id: 'a', text: 'ครับ' }, { id: 'b', text: 'มด' }, { id: 'c', text: 'ลิง' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูพยัญชนะท้ายคำเอง',
      review: {
        summary: 'ครับมี บ เป็นตัวสะกด อยู่ในแม่ กบ',
        hints: ['แม่ กบ ตัวสะกดออกเสียงท้ายเหมือนตัว บ'],
        steps: ['มดมี ด เป็นตัวสะกด อยู่ในแม่ กด และลิงมี ง เป็นตัวสะกด อยู่ในแม่ กง', 'ครับมี บ เป็นตัวสะกด ตอบข้อ 1'],
        transferIds: ['th-final-kb-t'],
      },
    },
    {
      id: 'th-cluster', type: 'main', subject: 'thai', skillIds: ['consonant-cluster'], familyId: 'consonant-cluster', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดเป็นคำควบกล้ำ คือมีพยัญชนะสองตัวควบกันอยู่ตอนต้นคำ' },
      options: [{ id: 'a', text: 'นก' }, { id: 'b', text: 'มด' }, { id: 'c', text: 'ปลา' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูพยัญชนะต้นคำเอง',
      review: {
        summary: 'ปลามี ป กับ ล ควบกัน',
        hints: ['ดูตอนต้นคำว่ามีพยัญชนะสองตัวออกเสียงควบกันไหม'],
        steps: ['นกและมดขึ้นต้นด้วยพยัญชนะตัวเดียว', 'ปลาขึ้นต้นด้วย ป กับ ล ออกเสียงควบกัน ตอบข้อ 3'],
        transferIds: ['th-cluster-t'],
      },
    },
    {
      id: 'sp-dots-minus2', type: 'main', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'dots-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'จุดลดลงทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ dots: 8 }, { dots: 6 }, { dots: 4 }, '?'] },
      options: [fig('a', { dots: 1 }), fig('b', { dots: 3 }), fig('c', { dots: 2 }), fig('d', { dots: 5 })],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการนับจุดที่ลดลงทีละ 2',
      review: {
        summary: 'จุดลดลงทีละ 2 จุด จาก 8 6 4 ต่อไปคือ 2',
        hints: ['นับจุดในแต่ละภาพ ดูว่าลดลงทีละกี่จุด'],
        steps: ['ภาพมีจุด 8 จุด 6 จุด 4 จุด ลดลงทีละ 2 จุด', '4 ลดลงอีก 2 เหลือ 2 จุด ตอบข้อ 3'],
        transferIds: ['sp-dots-minus2-t'],
      },
    },
    {
      id: 'm-egg-trays', type: 'main', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ไข่แผงละ 4 ฟอง มีไข่ 5 แผง รวมมีไข่กี่ฟอง' },
      options: [{ id: 'a', text: '20 ฟอง' }, { id: 'b', text: '9 ฟอง' }, { id: 'c', text: '16 ฟอง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการนับเพิ่มทีละเท่ากัน',
      review: {
        summary: 'นับเพิ่มทีละ 4 ห้าครั้ง ได้ 20 ฟอง',
        hints: ['นับเพิ่มทีละ 4 ตามจำนวนแผง'],
        steps: ['นับเพิ่มทีละ 4 ได้ 4 8 12 16 20', 'นับห้าครั้ง ได้ไข่ 20 ฟอง ตอบข้อ 1'],
        transferIds: ['m-sweet-bags-t'],
      },
    },
    {
      id: 'sp-between-frog', type: 'main', subject: 'spatial', skillIds: ['position-between'], familyId: 'position-between', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดอยู่ระหว่างปลากับม้า' },
      visual: { type: 'row', items: ['pic-fish', 'pic-frog', 'pic-horse', 'pic-owl'] },
      options: [{ id: 'a', text: 'นกฮูก' }, { id: 'b', text: 'กบ' }, { id: 'c', text: 'ปู' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบอกตำแหน่งที่อยู่ระหว่างสองภาพ',
      review: {
        summary: 'กบอยู่ระหว่างปลากับม้า',
        hints: ['ดูภาพที่ยืนอยู่ตรงกลางระหว่างปลากับม้า'],
        steps: ['ภาพเรียงจากซ้ายไปขวา คือ ปลา กบ ม้า นกฮูก', 'ภาพที่อยู่ระหว่างปลากับม้าคือกบ ตอบข้อ 2'],
        transferIds: ['sp-between-frog-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-farm-nick-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-nickname', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ที่บ้านของน้องบี เจ้าแดงเป็นกระต่ายสีขาว ชอบกินแครอท ส่วนเจ้าดำเป็นแมวสีดำ เจ้าแดงคือสัตว์ชนิดใด' },
      options: [{ id: 'a', text: 'แมว' }, { id: 'b', text: 'กระต่าย' }, { id: 'c', text: 'ปลา' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'เจ้าแดงเป็นกระต่าย', hints: [], steps: ['เรื่องบอกว่า เจ้าแดงเป็นกระต่ายสีขาว', 'เจ้าดำเป็นแมว'] },
    },
    {
      id: 'sc-farm-milk-t', type: 'transfer', subject: 'science', skillIds: ['animal-products'], familyId: 'animal-products', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์ชนิดใดให้ไข่แก่คน' },
      options: [{ id: 'a', text: 'วัว' }, { id: 'b', text: 'ไก่' }, { id: 'c', text: 'แมว' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไก่ให้ไข่', hints: [], steps: ['วัวให้นม และแมวไม่ให้ไข่แก่คน', 'ไก่ให้ไข่'] },
    },
    {
      id: 'm-farm-kinds-t', type: 'transfer', subject: 'math', skillIds: ['story-count-kinds'], familyId: 'story-kinds', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ลุงมีวัว 2 ตัว ไก่ 3 ตัว และเป็ด 4 ตัว ลุงมีสัตว์เลี้ยงกี่ชนิด' },
      options: [{ id: 'a', text: '3 ชนิด' }, { id: 'b', text: '9 ชนิด' }, { id: 'c', text: '2 ชนิด' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'วัว ไก่ และเป็ด รวม 3 ชนิด', hints: [], steps: ['นับเป็นชนิด ไม่นับเป็นตัว', 'วัว หนึ่ง ไก่ สอง เป็ด สาม รวม 3 ชนิด'] },
    },
    {
      id: 'r-farm-wrong-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 3,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'เจ้าขาวเป็นแมว เจ้าดำเป็นไก่ ข้อใดกล่าวไม่ถูกต้อง' },
      options: [{ id: 'a', text: 'เจ้าขาวเป็นแมว' }, { id: 'b', text: 'เจ้าดำเป็นไก่' }, { id: 'c', text: 'เจ้าขาวเป็นไก่' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'เจ้าขาวเป็นแมว ไม่ใช่ไก่', hints: [], steps: ['เรื่องบอกว่า เจ้าขาวเป็นแมว และเจ้าดำเป็นไก่', 'ข้อที่บอกว่าเจ้าขาวเป็นไก่จึงผิด'] },
    },
    {
      id: 'sc-farm-eat-t', type: 'transfer', subject: 'science', skillIds: ['animal-food'], familyId: 'animal-food', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'แมวกินอะไรเป็นอาหาร' },
      options: [{ id: 'a', text: 'หญ้า' }, { id: 'b', text: 'ปลา' }, { id: 'c', text: 'ใบไม้' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แมวกินปลาและเนื้อ', hints: [], steps: ['หญ้าและใบไม้เป็นอาหารของสัตว์กินพืช', 'แมวกินปลาและเนื้อ'] },
    },
    {
      id: 'g-month-first-t', type: 'transfer', subject: 'general', skillIds: ['months'], familyId: 'months', difficulty: 1,
      sourceId: SRC, ...R, section: MONTHS,
      prompt: { text: 'เดือนสุดท้ายของปีคือเดือนใด' },
      options: [{ id: 'a', text: 'ธันวาคม' }, { id: 'b', text: 'มกราคม' }, { id: 'c', text: 'มีนาคม' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ปีมี 12 เดือน เดือนสุดท้ายคือธันวาคม', hints: [], steps: ['มกราคมเป็นเดือนแรก และมีนาคมเป็นเดือนที่สาม', 'เดือนสุดท้ายของปีคือธันวาคม'] },
    },
    {
      id: 'm-months-count-t', type: 'transfer', subject: 'math', skillIds: ['months'], familyId: 'months-count', difficulty: 2,
      sourceId: SRC, ...R, section: MONTHS,
      prompt: { text: 'ตั้งแต่เดือนเมษายนถึงเดือนมิถุนายน มีกี่เดือน' },
      options: [{ id: 'a', text: '2 เดือน' }, { id: 'b', text: '4 เดือน' }, { id: 'c', text: '3 เดือน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เมษายน พฤษภาคม มิถุนายน รวม 3 เดือน', hints: [], steps: ['เดือนเรียงกันคือ เมษายน พฤษภาคม มิถุนายน', 'นับ 1 2 3 ได้ 3 เดือน'] },
    },
    {
      id: 'g-mother-day-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 2,
      sourceId: SRC, ...R, section: MONTHS,
      prompt: { text: 'วันสงกรานต์ตรงกับเดือนใด' },
      options: [{ id: 'a', text: 'เมษายน' }, { id: 'b', text: 'สิงหาคม' }, { id: 'c', text: 'มกราคม' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ (วันสงกรานต์ 13 เมษายน) ผู้ปกครองควรตรวจ',
      review: { summary: 'วันสงกรานต์คือวันที่ 13 เมษายน', hints: [], steps: ['สิงหาคมมีวันแม่ และมกราคมมีวันขึ้นปีใหม่', 'วันสงกรานต์ตรงกับเดือนเมษายน'] },
    },
    {
      id: 'r-month-next-t', type: 'transfer', subject: 'reasoning', skillIds: ['months'], familyId: 'months-order', difficulty: 2,
      sourceId: SRC, ...R, section: MONTHS,
      prompt: { text: 'เดือนใดอยู่ก่อนเดือนกรกฎาคม' },
      options: [{ id: 'a', text: 'สิงหาคม' }, { id: 'b', text: 'มิถุนายน' }, { id: 'c', text: 'กันยายน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มิถุนายนอยู่ก่อนกรกฎาคม', hints: [], steps: ['เรียงเดือนได้ มิถุนายน กรกฎาคม สิงหาคม กันยายน', 'ก่อนกรกฎาคมคือมิถุนายน'] },
    },
    {
      id: 'th-month-word-t', type: 'transfer', subject: 'thai', skillIds: ['classify-words'], familyId: 'classify-words', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดเป็นชื่อวันในสัปดาห์' },
      options: [{ id: 'a', text: 'ตุลาคม' }, { id: 'b', text: 'อังคาร' }, { id: 'c', text: 'กุมภาพันธ์' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'อังคารเป็นชื่อวัน ส่วนตุลาคมและกุมภาพันธ์เป็นชื่อเดือน', hints: [], steps: ['ตุลาคมและกุมภาพันธ์เป็นชื่อเดือน', 'อังคารเป็นชื่อวันในสัปดาห์'] },
    },
    {
      id: 'th-final-kb-t', type: 'transfer', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีตัวสะกดในแม่ กบ' },
      options: [{ id: 'a', text: 'ปลา' }, { id: 'b', text: 'รูป' }, { id: 'c', text: 'หมู' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูพยัญชนะท้ายคำเอง',
      review: { summary: 'รูปมี ป เป็นตัวสะกด อยู่ในแม่ กบ', hints: [], steps: ['ปลาและหมูไม่มีตัวสะกด', 'รูปมี ป เป็นตัวสะกด ออกเสียงท้ายเหมือน บ จึงอยู่ในแม่ กบ'] },
    },
    {
      id: 'th-cluster-t', type: 'transfer', subject: 'thai', skillIds: ['consonant-cluster'], familyId: 'consonant-cluster', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดเป็นคำควบกล้ำ คือมีพยัญชนะสองตัวควบกันอยู่ตอนต้นคำ' },
      options: [{ id: 'a', text: 'กิน' }, { id: 'b', text: 'กลอง' }, { id: 'c', text: 'แมว' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'กลองมี ก กับ ล ควบกัน', hints: [], steps: ['กินและแมวขึ้นต้นด้วยพยัญชนะตัวเดียว', 'กลองขึ้นต้นด้วย ก กับ ล ออกเสียงควบกัน'] },
    },
    {
      id: 'sp-dots-minus2-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'dots-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'จุดลดลงทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ dots: 9 }, { dots: 7 }, { dots: 5 }, '?'] },
      options: [fig('a', { dots: 4 }), fig('b', { dots: 3 }), fig('c', { dots: 2 }), fig('d', { dots: 5 })],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'จุดลดลงทีละ 2 จุด จาก 9 7 5 ต่อไปคือ 3', hints: [], steps: ['ภาพมีจุด 9 จุด 7 จุด 5 จุด ลดลงทีละ 2 จุด', '5 ลดลงอีก 2 เหลือ 3 จุด'] },
    },
    {
      id: 'm-sweet-bags-t', type: 'transfer', subject: 'math', skillIds: ['repeated-addition'], familyId: 'repeated-addition', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ขนมถุงละ 3 ชิ้น มีขนม 4 ถุง รวมมีขนมกี่ชิ้น' },
      options: [{ id: 'a', text: '7 ชิ้น' }, { id: 'b', text: '12 ชิ้น' }, { id: 'c', text: '9 ชิ้น' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'นับเพิ่มทีละ 3 สี่ครั้ง ได้ 12 ชิ้น', hints: [], steps: ['นับเพิ่มทีละ 3 ได้ 3 6 9 12', 'นับสี่ครั้ง ได้ขนม 12 ชิ้น'] },
    },
    {
      id: 'sp-between-frog-t', type: 'transfer', subject: 'spatial', skillIds: ['position-between'], familyId: 'position-between', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดอยู่ระหว่างแมวกับปลา' },
      visual: { type: 'row', items: ['pic-cat', 'pic-duck', 'pic-fish', 'pic-owl'] },
      options: [{ id: 'a', text: 'นกฮูก' }, { id: 'b', text: 'เป็ด' }, { id: 'c', text: 'ช้าง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เป็ดอยู่ระหว่างแมวกับปลา', hints: [], steps: ['ภาพเรียงจากซ้ายไปขวา คือ แมว เป็ด ปลา นกฮูก', 'ภาพที่อยู่ระหว่างแมวกับปลาคือเป็ด'] },
    },
  ],
};
