/*
 * ชุดที่ 8 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 8) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * ใช้รูปเดิมทั้งหมด; กลอนแต่งใหม่
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const GRID = 'ดูภาพในตารางแล้วตอบคำถามให้ถูกต้อง';
const GRID_A = { type: 'grid', rows: [['pic-fish', 'pic-cat', 'pic-umbrella'], ['pic-egg', 'pic-elephant', 'pic-orange'], ['pic-car', 'pic-ball', 'pic-chair']] };
const GRID_B = { type: 'grid', rows: [['pic-duck', 'pic-house', 'pic-bicycle'], ['pic-banana', 'pic-owl', 'pic-spoon'], ['pic-frog', 'pic-leaf', 'pic-horse']] };
const ROW = { type: 'row', items: ['pic-duck', 'pic-car', 'pic-ball', 'pic-cat', 'pic-leaf'], sides: true };

export default {
  id: 'set-08',
  version: 1,
  title: 'ชุดที่ 8',
  note: 'กลอนลูกแมว นับจากซ้าย มุมตาราง แบ่งของ ชั่งน้ำหนัก',
  order: [
    'th-kitten-where', 'th-kitten-fluffy', 'm-share-candy', 'r-shortest', 'sc-lays-eggs',
    'sp-grid-corner', 'sp-count-from-left', 'r-small-to-big', 'g-library', 'sc-brush-when',
    'm-weigh-market', 'g-unity',
  ],
  stimuli: {
    kitten: {
      section: 'ฟังกลอนแล้วตอบคำถามให้ถูกต้อง',
      text: 'ลูกแมวน้อย ขนปุยปุย นอนขดตัว อยู่บนเบาะนุ่ม ตื่นเช้ามา ร้องเหมียวเหมียว หิวนมแล้ว เรียกหาแม่',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'th-kitten-where', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'kitten',
      prompt: { text: 'ลูกแมวนอนอยู่ที่ไหน' },
      options: [{ id: 'a', text: 'ในกล่อง' }, { id: 'b', text: 'ใต้ต้นไม้' }, { id: 'c', text: 'บนเบาะนุ่ม' }],
      correctOptionId: 'c',
      narration: 'ฟังกลอนและตัวเลือกได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'ลูกแมวนอนขดตัวอยู่บนเบาะ',
        hints: ['ฟังกลอนท่อนที่สองอีกครั้ง'],
        steps: ['กลอนบอกว่า นอนขดตัว อยู่บนเบาะนุ่ม', 'ลูกแมวจึงนอนบนเบาะ ตอบข้อ 3'],
        transferIds: ['th-puppy-where-t'],
      },
    },
    {
      id: 'th-kitten-fluffy', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'kitten',
      prompt: { text: 'ในกลอน คำว่า ขนปุยปุย หมายถึงขนแบบใด' },
      options: [{ id: 'a', text: 'ขนนุ่มฟู' }, { id: 'b', text: 'ขนเปียกน้ำ' }, { id: 'c', text: 'ขนสั้นและแข็ง' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ วัดความเข้าใจความหมายของคำ',
      review: {
        summary: 'ปุยปุย คือนุ่มๆ ฟูๆ เหมือนปุยนุ่น',
        hints: ['นึกถึงปุยนุ่นหรือตุ๊กตาขนนุ่ม'],
        steps: ['ปุย คือสิ่งที่นุ่มและฟู เช่น ปุยนุ่น ปุยเมฆ', 'ขนปุยปุยจึงเป็นขนที่นุ่มและฟู ตอบข้อ 1'],
        transferIds: ['th-word-tiny-t'],
      },
    },
    {
      id: 'm-share-candy', type: 'main', subject: 'math', skillIds: ['equal-share'], familyId: 'equal-share', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีลูกอม 10 เม็ด แบ่งให้เพื่อน 2 คน คนละเท่าๆ กัน ได้คนละกี่เม็ด' },
      options: [{ id: 'a', text: '8 เม็ด' }, { id: 'b', text: '5 เม็ด' }, { id: 'c', text: '12 เม็ด' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการแบ่งเท่าๆ กัน',
      review: {
        summary: 'แบ่ง 10 เม็ดเป็น 2 กองเท่ากัน ได้กองละ 5 เม็ด',
        hints: ['แจกทีละเม็ด คนละเม็ด จนหมด'],
        steps: ['แจกให้เพื่อนทีละคน คนละ 1 เม็ด สลับกันไปจนครบ 10 เม็ด', 'แต่ละคนได้ 5 เม็ด เพราะ 5 บวก 5 เท่ากับ 10 ตอบข้อ 2'],
        transferIds: ['m-share-oranges-t'],
      },
    },
    {
      id: 'r-shortest', type: 'main', subject: 'reasoning', skillIds: ['compare-chain'], familyId: 'compare-chain', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ต้นสูงกว่าตาล ตาลสูงกว่าบัว ใครเตี้ยที่สุด' },
      options: [{ id: 'a', text: 'ต้น' }, { id: 'b', text: 'ตาล' }, { id: 'c', text: 'บัว' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการเปรียบเทียบต่อเนื่อง',
      review: {
        summary: 'เรียงจากสูงไปเตี้ย คือ ต้น ตาล บัว บัวจึงเตี้ยสุด',
        hints: ['ลองเรียงสามคนจากสูงไปเตี้ย'],
        steps: ['ต้นสูงกว่าตาล ต้นจึงอยู่หน้าตาล', 'ตาลสูงกว่าบัว บัวจึงอยู่ท้ายสุด เรียงได้ ต้น ตาล บัว', 'คนท้ายสุดคือบัว ตอบข้อ 3'],
        transferIds: ['r-fastest-t'],
      },
    },
    {
      id: 'sc-lays-eggs', type: 'main', subject: 'science', skillIds: ['animal-birth'], familyId: 'animal-birth', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สัตว์ใดออกลูกเป็นไข่' },
      options: [{ id: 'a', image: 'pic-duck', speech: 'เป็ด' }, { id: 'b', image: 'pic-cat', speech: 'แมว' }, { id: 'c', image: 'pic-elephant', speech: 'ช้าง' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ วัดความรู้เรื่องการออกลูกของสัตว์',
      review: {
        summary: 'เป็ดวางไข่ แล้วลูกเป็ดฟักออกมาจากไข่',
        hints: ['สัตว์ที่มีปีกและขนนกมักวางไข่'],
        steps: ['แมวกับช้างออกลูกเป็นตัว และให้ลูกกินนม', 'เป็ดวางไข่ แล้วลูกเป็ดฟักออกจากไข่ ตอบข้อ 1'],
        transferIds: ['sc-live-birth-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'sp-grid-corner', type: 'main', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-corner', difficulty: 2,
      sourceId: SRC, ...R, section: GRID,
      prompt: { text: 'ภาพใดอยู่มุมล่างด้านซ้าย' },
      visual: GRID_B,
      options: [{ id: 'a', image: 'pic-horse', speech: 'ม้า' }, { id: 'b', image: 'pic-frog', speech: 'กบ' }, { id: 'c', image: 'pic-duck', speech: 'เป็ด' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกตำแหน่ง เด็กต้องดูตารางเอง',
      review: {
        summary: 'มุมล่างด้านซ้ายคือกบ',
        hints: ['ไปแถวล่างสุดก่อน แล้วดูช่องซ้ายสุด'],
        steps: ['แถวล่างสุดเรียง กบ ใบไม้ ม้า', 'ช่องซ้ายสุดของแถวล่างคือกบ ม้าอยู่มุมล่างด้านขวา ตอบข้อ 2'],
        transferIds: ['sp-grid-corner-t'],
      },
    },
    {
      id: 'sp-count-from-left', type: 'main', subject: 'spatial', skillIds: ['ordinal-position'], familyId: 'count-from-side', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'นับจากทางซ้าย ภาพที่ 3 คือภาพใด' },
      visual: ROW,
      options: [{ id: 'a', image: 'pic-ball', speech: 'ลูกบอล' }, { id: 'b', image: 'pic-car', speech: 'รถ' }, { id: 'c', image: 'pic-cat', speech: 'แมว' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกลำดับ เด็กต้องนับเอง',
      review: {
        summary: 'นับจากซ้าย เป็ด รถ ลูกบอล ภาพที่ 3 คือลูกบอล',
        hints: ['เริ่มนับจากภาพซ้ายสุดเป็นหนึ่ง'],
        steps: ['เริ่มที่ด้านซ้าย เป็ดคือหนึ่ง รถคือสอง', 'ลูกบอลคือสาม ตอบข้อ 1'],
        transferIds: ['sp-count-from-right-t'],
      },
    },
    {
      id: 'r-small-to-big', type: 'main', subject: 'reasoning', skillIds: ['seriation'], familyId: 'seriation', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดเรียงขนาดสัตว์จากเล็กไปใหญ่' },
      options: [{ id: 'a', text: 'ช้าง แมว มด' }, { id: 'b', text: 'มด ช้าง แมว' }, { id: 'c', text: 'มด แมว ช้าง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงลำดับขนาด',
      review: {
        summary: 'มดเล็กสุด แมวกลาง ช้างใหญ่สุด',
        hints: ['หาตัวที่เล็กที่สุดก่อน'],
        steps: ['มดตัวเล็กที่สุด ช้างตัวใหญ่ที่สุด แมวอยู่ตรงกลาง', 'เรียงเล็กไปใหญ่ได้ มด แมว ช้าง ตอบข้อ 3'],
        transferIds: ['r-big-to-small-t'],
      },
    },
    {
      id: 'g-library', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าอยากยืมหนังสือนิทานมาอ่าน ควรไปที่ใด' },
      options: [{ id: 'a', text: 'โรงพยาบาล' }, { id: 'b', text: 'ห้องสมุด' }, { id: 'c', text: 'สถานีตำรวจ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสถานที่ในชุมชน',
      review: {
        summary: 'ห้องสมุดมีหนังสือให้ยืมอ่าน',
        hints: ['ที่ไหนมีหนังสือเยอะๆ'],
        steps: ['โรงพยาบาลรักษาคนป่วย สถานีตำรวจช่วยดูแลความปลอดภัย', 'ห้องสมุดมีหนังสือให้อ่านและยืม ตอบข้อ 2'],
        transferIds: ['g-hospital-t'],
      },
    },
    {
      id: 'sc-brush-when', type: 'main', subject: 'science', skillIds: ['hygiene'], familyId: 'hygiene', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เราควรแปรงฟันเมื่อใด' },
      visual: { type: 'image', asset: 'pic-toothbrush' },
      options: [{ id: 'a', text: 'เฉพาะตอนเที่ยง' }, { id: 'b', text: 'เมื่อปวดฟัน' }, { id: 'c', text: 'ตอนเช้าและก่อนนอน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสุขอนามัย',
      review: {
        summary: 'แปรงฟันวันละ 2 ครั้ง ตอนตื่นนอนและก่อนเข้านอน',
        hints: ['วันหนึ่งควรแปรงฟันกี่ครั้ง'],
        steps: ['ถ้ารอให้ปวดฟันก่อน ฟันอาจผุไปแล้ว', 'ควรแปรงฟันทุกวัน ตอนเช้าและก่อนนอน ตอบข้อ 3'],
        transferIds: ['sc-wash-before-eat-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-weigh-market', type: 'main', subject: 'math', skillIds: ['measurement'], familyId: 'measure-kind', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ที่ตลาด แม่ค้าขายสิ่งใดโดยการชั่งน้ำหนัก' },
      options: [{ id: 'a', text: 'ผ้า' }, { id: 'b', text: 'ส้ม' }, { id: 'c', text: 'ริบบิ้น' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการชั่ง การวัด',
      review: {
        summary: 'ส้มขายเป็นกิโลกรัม ใช้ตาชั่ง',
        hints: ['ผ้ากับริบบิ้นขายเป็นความยาว'],
        steps: ['ผ้าและริบบิ้นซื้อขายโดยวัดความยาว', 'ส้มซื้อขายโดยชั่งน้ำหนักบนตาชั่ง ตอบข้อ 2'],
        transferIds: ['m-cloth-measure-t'],
      },
    },
    {
      id: 'g-unity', type: 'main', subject: 'general', skillIds: ['good-habits'], familyId: 'unity', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'นักเรียนทุกคนช่วยกันทำความสะอาดห้องเรียน แสดงว่านักเรียนมีนิสัยใด' },
      options: [{ id: 'a', text: 'สามัคคี' }, { id: 'b', text: 'ขี้เกียจ' }, { id: 'c', text: 'เห็นแก่ตัว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องคุณธรรม',
      review: {
        summary: 'ทุกคนร่วมมือกันทำงาน เรียกว่ามีความสามัคคี',
        hints: ['ทุกคนทำงานด้วยกัน เรียกว่าอะไร'],
        steps: ['คนขี้เกียจไม่ช่วยทำงาน คนเห็นแก่ตัวคิดถึงแต่ตัวเอง', 'ทุกคนช่วยกันทำงานจนเสร็จ คือความสามัคคี ตอบข้อ 1'],
        transferIds: ['g-help-friend-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-puppy-where-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, section: 'ฟังกลอนแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ลูกหมาน้อย วิ่งเล่นซน ใต้ต้นมะม่วง หน้าบ้านฉัน ลูกหมาวิ่งเล่นอยู่ที่ไหน' },
      options: [{ id: 'a', text: 'ในห้องครัว' }, { id: 'b', text: 'ใต้ต้นมะม่วง' }, { id: 'c', text: 'บนหลังคา' }],
      correctOptionId: 'b',
      narration: 'ฟังกลอนได้',
      review: { summary: 'ลูกหมาเล่นอยู่ใต้ต้นมะม่วงหน้าบ้าน', hints: [], steps: ['กลอนบอกว่า วิ่งเล่นซน ใต้ต้นมะม่วง', 'ลูกหมาจึงเล่นอยู่ใต้ต้นมะม่วง'] },
    },
    {
      id: 'th-word-tiny-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า จิ๋ว หมายถึงอะไร' },
      options: [{ id: 'a', text: 'ใหญ่มาก' }, { id: 'b', text: 'ร้อนมาก' }, { id: 'c', text: 'เล็กมาก' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'จิ๋ว คือตัวเล็กนิดเดียว', hints: [], steps: ['เรามักพูดว่า มดตัวจิ๋ว', 'จิ๋ว จึงหมายถึงเล็กมาก'] },
    },
    {
      id: 'm-share-oranges-t', type: 'transfer', subject: 'math', skillIds: ['equal-share'], familyId: 'equal-share', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีส้ม 6 ผล แบ่งใส่จาน 3 ใบ ใบละเท่าๆ กัน ได้จานละกี่ผล' },
      options: [{ id: 'a', text: '2 ผล' }, { id: 'b', text: '3 ผล' }, { id: 'c', text: '9 ผล' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แบ่ง 6 ผลใส่ 3 จาน ได้จานละ 2 ผล', hints: [], steps: ['วางส้มทีละผล จานละผล วนไปจนหมด', 'แต่ละจานได้ 2 ผล เพราะ 2 บวก 2 บวก 2 เท่ากับ 6'] },
    },
    {
      id: 'r-fastest-t', type: 'transfer', subject: 'reasoning', skillIds: ['compare-chain'], familyId: 'compare-chain', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'แมววิ่งเร็วกว่าเป็ด เป็ดวิ่งเร็วกว่าเต่า ใครวิ่งเร็วที่สุด' },
      options: [{ id: 'a', text: 'เต่า' }, { id: 'b', text: 'แมว' }, { id: 'c', text: 'เป็ด' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เรียงจากเร็วไปช้า คือ แมว เป็ด เต่า', hints: [], steps: ['แมวเร็วกว่าเป็ด และเป็ดเร็วกว่าเต่า', 'แมวจึงเร็วที่สุด'] },
    },
    {
      id: 'sc-live-birth-t', type: 'transfer', subject: 'science', skillIds: ['animal-birth'], familyId: 'animal-birth', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สัตว์ใดออกลูกเป็นตัว' },
      options: [{ id: 'a', image: 'pic-chicken', speech: 'ไก่' }, { id: 'b', image: 'pic-frog', speech: 'กบ' }, { id: 'c', image: 'pic-horse', speech: 'ม้า' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ม้าคลอดลูกออกมาเป็นตัว', hints: [], steps: ['ไก่และกบวางไข่', 'ม้าออกลูกเป็นตัว และลูกม้ากินนมแม่'] },
    },
    {
      id: 'sp-grid-corner-t', type: 'transfer', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-corner', difficulty: 2,
      sourceId: SRC, ...R, section: GRID,
      prompt: { text: 'ภาพใดอยู่มุมบนด้านขวา' },
      visual: GRID_A,
      options: [{ id: 'a', image: 'pic-fish', speech: 'ปลา' }, { id: 'b', image: 'pic-chair', speech: 'เก้าอี้' }, { id: 'c', image: 'pic-umbrella', speech: 'ร่ม' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'มุมบนด้านขวาคือร่ม', hints: [], steps: ['ไปแถวบนสุดก่อน แล้วดูช่องขวาสุด', 'ช่องนั้นคือร่ม'] },
    },
    {
      id: 'sp-count-from-right-t', type: 'transfer', subject: 'spatial', skillIds: ['ordinal-position'], familyId: 'count-from-side', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'นับจากทางขวา ภาพที่ 2 คือภาพใด' },
      visual: ROW,
      options: [{ id: 'a', image: 'pic-leaf', speech: 'ใบไม้' }, { id: 'b', image: 'pic-cat', speech: 'แมว' }, { id: 'c', image: 'pic-car', speech: 'รถ' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'นับจากขวา ใบไม้ แมว ภาพที่ 2 คือแมว', hints: [], steps: ['เริ่มที่ด้านขวา ใบไม้คือหนึ่ง', 'แมวคือสอง'] },
    },
    {
      id: 'r-big-to-small-t', type: 'transfer', subject: 'reasoning', skillIds: ['seriation'], familyId: 'seriation', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดเรียงผลไม้จากใหญ่ไปเล็ก' },
      options: [{ id: 'a', text: 'แตงโม ส้ม องุ่น' }, { id: 'b', text: 'องุ่น ส้ม แตงโม' }, { id: 'c', text: 'ส้ม แตงโม องุ่น' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แตงโมใหญ่สุด ส้มกลาง องุ่นเล็กสุด', hints: [], steps: ['แตงโมผลใหญ่ที่สุด องุ่นผลเล็กที่สุด', 'เรียงใหญ่ไปเล็กได้ แตงโม ส้ม องุ่น'] },
    },
    {
      id: 'g-hospital-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าไม่สบาย มีไข้สูง ควรไปที่ใด' },
      options: [{ id: 'a', text: 'โรงพยาบาล' }, { id: 'b', text: 'สวนสนุก' }, { id: 'c', text: 'ตลาด' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไปหาหมอที่โรงพยาบาล', hints: [], steps: ['ที่โรงพยาบาลมีหมอและพยาบาล', 'หมอช่วยรักษาให้หายป่วย'] },
    },
    {
      id: 'sc-wash-before-eat-t', type: 'transfer', subject: 'science', skillIds: ['hygiene'], familyId: 'hygiene', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ก่อนกินข้าว เราควรทำอย่างไร' },
      options: [{ id: 'a', text: 'วิ่งเล่น' }, { id: 'b', text: 'ล้างมือด้วยสบู่' }, { id: 'c', text: 'ดูโทรทัศน์' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ล้างมือให้สะอาดก่อนกินข้าว', hints: [], steps: ['มือเราจับของหลายอย่าง อาจมีเชื้อโรค', 'จึงต้องล้างมือด้วยสบู่ก่อนกินข้าว'] },
    },
    {
      id: 'm-cloth-measure-t', type: 'transfer', subject: 'math', skillIds: ['measurement'], familyId: 'measure-kind', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'แม่ไปซื้อผ้ามาตัดชุด แม่ค้าขายผ้าโดยวิธีใด' },
      options: [{ id: 'a', text: 'ชั่งน้ำหนัก' }, { id: 'b', text: 'นับเป็นผล' }, { id: 'c', text: 'วัดความยาว' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ผ้าขายเป็นความยาว เช่น เป็นเมตร', hints: [], steps: ['แม่ค้าใช้ไม้เมตรวัดผ้า', 'ผ้าจึงซื้อขายโดยวัดความยาว'] },
    },
    {
      id: 'g-help-friend-t', type: 'transfer', subject: 'general', skillIds: ['good-habits'], familyId: 'unity', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เพื่อนหกล้มในสนาม เราควรทำอย่างไร' },
      options: [{ id: 'a', text: 'ช่วยพยุงเพื่อน แล้วบอกครู' }, { id: 'b', text: 'หัวเราะเพื่อน' }, { id: 'c', text: 'เดินหนีไป' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ช่วยเพื่อนลุก แล้วให้ครูดูแผล', hints: [], steps: ['เพื่อนเจ็บ ต้องการคนช่วย', 'เราจึงช่วยพยุงเพื่อน และบอกครูให้มาดู'] },
    },
  ],
};
