/*
 * ชุดที่ 18 — รูปแบบใหม่ 15 ข้อ (ดู docs/QUESTION-TYPES.md หัวข้อ "รูปแบบชุด 12 ขึ้นไป")
 * ช่วง 1 เรื่องเดียวถาม 5 ข้อ (คุณตาพาหลานไปสวนสาธารณะ: ใคร กี่คน ความหมายคำ ทำไมถึงชม ข้อใดไม่ได้กล่าวถึง)
 * ช่วง 2 แผ่นภาพสัตว์ 12 ชนิด ถาม 5 ข้อ (ปีก ออกลูกเป็นไข่ นับสัตว์สองขา ไม่มีขา ประโยชน์ของสัตว์)
 * ช่วง 3 แบบโจทย์ที่ยังไม่เคยมีในชุดก่อน: ตัวสะกด วรรณยุกต์ (ภาษาไทย) เลขแบ่งเป็นกลุ่ม ตารางภาพ 2x2 ที่เปลี่ยนตามกฎ (จุดเพิ่ม ระบายสี)
 * แต่งใหม่ทั้งหมด ตั้งชื่อตัวละคร สถานที่ และตัวเลขใหม่ตามแนวข้อสอบเก่า; ไม่ต้องใช้รูปใหม่จาก Gemini
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LISTEN = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const ANIMALS = 'ดูภาพสัตว์แล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';
const fig = (id, figure) => ({ id, svg: { figure } });
const BOARD = { type: 'board', items: ['pic-fish', 'pic-crab', 'pic-chicken', 'pic-horse', 'pic-owl', 'pic-butterfly', 'pic-frog', 'pic-duck', 'pic-bee', 'pic-snail', 'pic-cat', 'pic-mouse'] };
const BOARD_TEXT = 'ในภาพมีสัตว์ 12 ชนิด คือ ปลา ปู ไก่ ม้า นกฮูก ผีเสื้อ กบ เป็ด ผึ้ง หอยทาก แมว และหนู';
const RULE = 'ภาพในแถวบนเปลี่ยนจากซ้ายไปขวา แถวล่างเปลี่ยนแบบเดียวกัน ช่อง ? ควรเป็นภาพใด';

export default {
  id: 'set-18',
  version: 1,
  title: 'ชุดที่ 18',
  note: 'คุณตากับหลาน สัตว์ในภาพ ตัวสะกด วรรณยุกต์ ภาพตามกฎ',
  order: [
    'th-park-who', 'r-park-kids', 'th-word-clean', 'g-park-why', 'r-park-not',
    'sc-animal-wings', 'sc-animal-eggs', 'm-animal-legs', 'r-animal-no-legs', 'g-animal-cat',
    'th-final-none', 'th-tone-ek', 'm-group-flowers', 'sp-analogy-dots', 'sp-analogy-fill',
  ],
  stimuli: {
    park: {
      section: LISTEN,
      text: 'ทุกเย็นหลังเลิกเรียน คุณตาพาน้องภูมิกับน้องสาวไปเดินเล่นที่สวนสาธารณะ คุณตาชอบนั่งอ่านหนังสือพิมพ์ใต้ต้นไม้ใหญ่ น้องภูมิชอบวิ่งเล่นกับเพื่อน ส่วนน้องสาวชอบเก็บใบไม้สวยๆ วันหนึ่งน้องภูมิเห็นถุงขนมตกอยู่บนพื้นหญ้า เขารีบเก็บไปทิ้งในถังขยะ คุณตายิ้มและชมว่า น้องภูมิเป็นเด็กรักความสะอาด',
    },
    animals: { section: ANIMALS, text: BOARD_TEXT, visual: BOARD },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: เรื่องเดียว 5 ข้อ
    {
      id: 'th-park-who', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-who', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'park',
      prompt: { text: 'ใครชอบนั่งอ่านหนังสือพิมพ์' },
      options: [{ id: 'a', text: 'น้องภูมิ' }, { id: 'b', text: 'คุณตา' }, { id: 'c', text: 'น้องสาว' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังจับรายละเอียดว่าใครทำอะไร',
      review: {
        summary: 'คุณตาเป็นคนนั่งอ่านหนังสือพิมพ์',
        hints: ['ฟังประโยคที่พูดถึงคุณตา'],
        steps: ['เรื่องบอกว่า คุณตาชอบนั่งอ่านหนังสือพิมพ์ใต้ต้นไม้ใหญ่', 'น้องภูมิวิ่งเล่น น้องสาวเก็บใบไม้ จึงเป็นคุณตา ตอบข้อ 2'],
        transferIds: ['th-park-who-t'],
      },
    },
    {
      id: 'r-park-kids', type: 'main', subject: 'reasoning', skillIds: ['story-count'], familyId: 'story-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'park',
      prompt: { text: 'คุณตาพาเด็กไปสวนสาธารณะกี่คน' },
      options: [{ id: 'a', text: '2 คน' }, { id: 'b', text: '3 คน' }, { id: 'c', text: '4 คน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการฟังและนับ (ระวังไม่นับคุณตาและเพื่อนที่ไปเล่นด้วย)',
      review: {
        summary: 'เด็กที่ไปกับคุณตามีน้องภูมิและน้องสาว',
        hints: ['นับเฉพาะเด็กที่คุณตาพาไป ไม่นับคุณตา'],
        steps: ['คุณตาพาน้องภูมิกับน้องสาวไปสวนสาธารณะ', 'น้องภูมิ หนึ่ง น้องสาว สอง เป็นเด็ก 2 คน ตอบข้อ 1'],
        transferIds: ['r-park-kids-t'],
      },
    },
    {
      id: 'th-word-clean', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'park',
      prompt: { text: 'คำว่า รักความสะอาด หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'ชอบวิ่งเล่นให้เหนื่อย' }, { id: 'b', text: 'ไม่ชอบเห็นขยะ และช่วยทำให้สะอาด' }, { id: 'c', text: 'ชอบอ่านหนังสือพิมพ์' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ วัดความเข้าใจความหมายคำจากเรื่อง',
      review: {
        summary: 'รักความสะอาด คือชอบให้ที่ต่างๆ สะอาด',
        hints: ['น้องภูมิทำอย่างไรเมื่อเห็นถุงขนมตกอยู่'],
        steps: ['น้องภูมิเห็นถุงขนมตกอยู่บนพื้นหญ้า จึงเก็บไปทิ้งในถังขยะ', 'คนที่ทำแบบนี้คือคนที่ไม่ชอบเห็นขยะ และช่วยทำให้สะอาด ตอบข้อ 2'],
        transferIds: ['th-word-clean-t'],
      },
    },
    {
      id: 'g-park-why', type: 'main', subject: 'general', skillIds: ['story-why-good'], familyId: 'story-why-good', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'park',
      prompt: { text: 'ทำไมคุณตาจึงชมน้องภูมิ' },
      options: [{ id: 'a', text: 'เพราะน้องภูมิวิ่งเร็วที่สุด' }, { id: 'b', text: 'เพราะน้องภูมิเก็บใบไม้สวยๆ' }, { id: 'c', text: 'เพราะน้องภูมิเก็บถุงขนมไปทิ้งในถังขยะ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการฟังหาเหตุผลและความรู้เรื่องการรักษาความสะอาด',
      review: {
        summary: 'น้องภูมิช่วยรักษาความสะอาดของสวน',
        hints: ['ฟังว่าน้องภูมิเห็นอะไรบนพื้นหญ้า แล้วทำอย่างไร'],
        steps: ['เรื่องไม่ได้บอกว่าวิ่งเร็ว และคนที่เก็บใบไม้คือน้องสาว', 'น้องภูมิเก็บถุงขนมไปทิ้งในถังขยะ คุณตาจึงชม ตอบข้อ 3'],
        transferIds: ['g-park-why-t'],
      },
    },
    {
      id: 'r-park-not', type: 'main', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'park',
      prompt: { text: 'ข้อใดไม่ได้กล่าวถึงในเรื่อง' },
      options: [{ id: 'a', text: 'น้องภูมิว่ายน้ำในสระ' }, { id: 'b', text: 'คุณตาอ่านหนังสือพิมพ์' }, { id: 'c', text: 'น้องสาวเก็บใบไม้' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการฟังและแยกสิ่งที่มีในเรื่องกับสิ่งที่ไม่มี',
      review: {
        summary: 'เรื่องนี้ไม่มีการว่ายน้ำ',
        hints: ['ตรวจทีละข้อว่าเรื่องพูดถึงหรือไม่'],
        steps: ['คุณตาอ่านหนังสือพิมพ์ และน้องสาวเก็บใบไม้ มีอยู่ในเรื่อง', 'เรื่องไม่ได้พูดถึงการว่ายน้ำ ตอบข้อ 1'],
        transferIds: ['r-park-not-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: แผ่นภาพสัตว์ 5 ข้อ
    {
      id: 'sc-animal-wings', type: 'main', subject: 'science', skillIds: ['animal-traits'], familyId: 'board-classify', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'animals',
      prompt: { text: 'สัตว์สองชนิดใดมีปีกและบินได้ทั้งคู่' },
      options: [{ id: 'a', text: 'ปลา, ปู' }, { id: 'b', text: 'หอยทาก, กบ' }, { id: 'c', text: 'ผีเสื้อ, ผึ้ง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องลักษณะของสัตว์',
      review: {
        summary: 'ผีเสื้อและผึ้งมีปีก บินได้',
        hints: ['สัตว์ที่บินในอากาศต้องมีอะไร'],
        steps: ['ปลา ปู หอยทาก และกบ ไม่มีปีก บินไม่ได้', 'ผีเสื้อและผึ้งมีปีกบินได้ ตอบข้อ 3'],
        transferIds: ['sc-animal-wings-t'],
      },
    },
    {
      id: 'sc-animal-eggs', type: 'main', subject: 'science', skillIds: ['animal-lifecycle'], familyId: 'board-classify', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'animals',
      prompt: { text: 'สัตว์สองชนิดใดออกลูกเป็นไข่' },
      options: [{ id: 'a', text: 'ไก่, เป็ด' }, { id: 'b', text: 'แมว, หนู' }, { id: 'c', text: 'ม้า, แมว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการออกลูกของสัตว์',
      review: {
        summary: 'ไก่และเป็ดวางไข่ ลูกฟักออกจากไข่',
        hints: ['ลูกไก่ ลูกเป็ด ออกมาจากอะไร'],
        steps: ['แมว หนู และม้า ออกลูกเป็นตัว', 'ไก่และเป็ดวางไข่ ลูกฟักออกจากไข่ ตอบข้อ 1'],
        transferIds: ['sc-animal-eggs-t'],
      },
    },
    {
      id: 'm-animal-legs', type: 'main', subject: 'math', skillIds: ['count-legs'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'animals',
      prompt: { text: 'สัตว์ที่มี 2 ขา ในภาพมีกี่ชนิด' },
      options: [{ id: 'a', text: '2 ชนิด' }, { id: 'b', text: '3 ชนิด' }, { id: 'c', text: '4 ชนิด' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มตามจำนวนขาแล้วนับ',
      review: {
        summary: 'ไก่ นกฮูก และเป็ด มีสองขา รวม 3 ชนิด',
        hints: ['นึกถึงสัตว์ที่ยืนด้วยสองขา'],
        steps: ['สัตว์ที่มีสองขาคือ ไก่ นกฮูก และเป็ด', 'ม้า กบ แมว และหนูมีสี่ขา ปลากับหอยทากไม่มีขา นับสัตว์สองขาได้ 3 ชนิด ตอบข้อ 2'],
        transferIds: ['m-animal-legs-t'],
      },
    },
    {
      id: 'r-animal-no-legs', type: 'main', subject: 'reasoning', skillIds: ['classify'], familyId: 'board-classify', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'animals',
      prompt: { text: 'สัตว์สองชนิดใดไม่มีขาเลย' },
      options: [{ id: 'a', text: 'ปลา, หอยทาก' }, { id: 'b', text: 'ปลา, กบ' }, { id: 'c', text: 'หอยทาก, ปู' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มตามลักษณะร่างกาย',
      review: {
        summary: 'ปลาและหอยทากไม่มีขา',
        hints: ['ปลาว่ายน้ำด้วยอะไร หอยทากเคลื่อนที่อย่างไร'],
        steps: ['กบมีสี่ขา และปูมีหลายขา', 'ปลาว่ายด้วยครีบ หอยทากคลานด้วยเท้าแผ่นๆ ทั้งสองไม่มีขา ตอบข้อ 1'],
        transferIds: ['r-animal-no-legs-t'],
      },
    },
    {
      id: 'g-animal-cat', type: 'main', subject: 'general', skillIds: ['animal-help'], familyId: 'animal-help', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'animals',
      prompt: { text: 'สัตว์ในภาพชนิดใดช่วยจับหนูให้เรา' },
      options: [{ id: 'a', text: 'ผึ้ง' }, { id: 'b', text: 'แมว' }, { id: 'c', text: 'ปลา' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้รอบตัวเรื่องประโยชน์ของสัตว์เลี้ยง',
      review: {
        summary: 'แมวชอบจับหนู',
        hints: ['สัตว์ที่ชอบวิ่งไล่หนูคืออะไร'],
        steps: ['ผึ้งทำน้ำผึ้ง ปลาอยู่ในน้ำ ไม่ได้จับหนู', 'แมวชอบจับหนู ตอบข้อ 2'],
        transferIds: ['g-animal-cat-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3: ตัวสะกด วรรณยุกต์ เลขแบ่งกลุ่ม ภาพตามกฎ
    {
      id: 'th-final-none', type: 'main', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดไม่มีตัวสะกด' },
      options: [{ id: 'a', text: 'ช้าง' }, { id: 'b', text: 'นก' }, { id: 'c', text: 'ปลา' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูท้ายคำเองว่ามีตัวสะกดหรือไม่ (ฟังเสียงอย่างเดียวบอกไม่ได้)',
      review: {
        summary: 'ปลาจบด้วยสระ ไม่มีตัวสะกด',
        hints: ['ตัวสะกดคือพยัญชนะที่อยู่ท้ายคำ ถ้าท้ายคำเป็นสระ ก็ไม่มีตัวสะกด'],
        steps: ['ช้างมี ง เป็นตัวสะกด และนกมี ก เป็นตัวสะกด', 'ปลาจบด้วยสระอา ไม่มีตัวสะกด ตอบข้อ 3'],
        transferIds: ['th-final-none-t'],
      },
    },
    {
      id: 'th-tone-ek', type: 'main', subject: 'thai', skillIds: ['tone-mark'], familyId: 'tone-mark', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีวรรณยุกต์เอก' },
      options: [{ id: 'a', text: 'ไก่' }, { id: 'b', text: 'ปู' }, { id: 'c', text: 'ม้า' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูเครื่องหมายวรรณยุกต์เอง (ฟังเสียงอย่างเดียวบอกไม่ได้)',
      review: {
        summary: 'ไก่มีไม้เอก เป็นขีดเล็กๆ อยู่เหนือตัว ก',
        hints: ['ไม้เอกเป็นขีดเอียงเล็กๆ อยู่เหนือพยัญชนะ'],
        steps: ['ปูไม่มีเครื่องหมายเหนือพยัญชนะ ส่วนม้ามีไม้โท ซึ่งรูปไม่เหมือนไม้เอก', 'ไก่มีไม้เอกอยู่เหนือตัว ก ตอบข้อ 1'],
        transferIds: ['th-tone-ek-t'],
      },
    },
    {
      id: 'm-group-flowers', type: 'main', subject: 'math', skillIds: ['sharing-groups'], familyId: 'group-division', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เอกมีดอกกุหลาบ 18 ดอก จะมัดเป็นกำ กำละ 3 ดอก เอกจะมัดได้กี่กำ' },
      options: [{ id: 'a', text: '5 กำ' }, { id: 'b', text: '9 กำ' }, { id: 'c', text: '6 กำ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการแบ่งของเป็นกลุ่มเท่ากัน (นับทีละ 3)',
      review: {
        summary: 'นับทีละ 3 จนครบ 18 ดอก ได้ 6 กำ',
        hints: ['นับทีละ 3 ไปเรื่อยๆ จนถึง 18'],
        steps: ['นับทีละ 3 ได้ 3 6 9 12 15 18', 'นับได้ 6 ครั้ง จึงมัดได้ 6 กำ ตอบข้อ 3'],
        transferIds: ['m-group-flowers-t'],
      },
    },
    {
      id: 'sp-analogy-dots', type: 'main', subject: 'spatial', skillIds: ['figure-analogy'], familyId: 'grid-analogy', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: RULE },
      visual: { type: 'figure-grid', rows: [[{ dots: 1 }, { dots: 3 }], [{ dots: 4 }, '?']] },
      options: [fig('a', { dots: 4 }), fig('b', { dots: 5 }), fig('c', { dots: 6 }), fig('d', { dots: 8 })],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหากฎการเปลี่ยนของแถวบนแล้วใช้กับแถวล่าง',
      review: {
        summary: 'จุดเพิ่มขึ้นทีละ 2 จุด',
        hints: ['นับจุดในแถวบน ดูว่าเพิ่มขึ้นหรือลดลงกี่จุด'],
        steps: ['แถวบนจาก 1 จุด เป็น 3 จุด คือเพิ่มขึ้น 2 จุด', 'แถวล่างมี 4 จุด เพิ่มอีก 2 จุด เป็น 6 จุด ตอบข้อ 3'],
        transferIds: ['sp-analogy-dots-t'],
      },
    },
    {
      id: 'sp-analogy-fill', type: 'main', subject: 'spatial', skillIds: ['figure-analogy'], familyId: 'grid-analogy', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: RULE },
      visual: {
        type: 'figure-grid',
        rows: [[{ shape: 'circle', fill: 'empty' }, { shape: 'circle', fill: 'solid' }], [{ shape: 'triangle', fill: 'empty' }, '?']],
      },
      options: [fig('a', { shape: 'triangle', fill: 'dots' }), fig('b', { shape: 'triangle', fill: 'solid' }), fig('c', { shape: 'triangle', fill: 'empty' }), fig('d', { shape: 'circle', fill: 'solid' })],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหากฎการเปลี่ยนของแถวบนแล้วใช้กับแถวล่าง',
      review: {
        summary: 'รูปเดิมถูกระบายสีทึบ รูปร่างไม่เปลี่ยน',
        hints: ['ดูแถวบน รูปทางซ้ายกับทางขวาต่างกันตรงไหน'],
        steps: ['แถวบนจากวงกลมว่าง กลายเป็นวงกลมทึบ คือรูปเดิมแต่ระบายสีทึบ', 'แถวล่างเป็นสามเหลี่ยมว่าง จึงกลายเป็นสามเหลี่ยมทึบ ตอบข้อ 2'],
        transferIds: ['sp-analogy-fill-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-park-who-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-who', difficulty: 1,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ทุกเช้าวันอาทิตย์ คุณยายชอบปลูกดอกไม้หน้าบ้าน น้องมีนช่วยรดน้ำ ส่วนน้องชายชอบวิ่งไล่ผีเสื้อ ใครชอบปลูกดอกไม้' },
      options: [{ id: 'a', text: 'น้องมีน' }, { id: 'b', text: 'น้องชาย' }, { id: 'c', text: 'คุณยาย' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'คุณยายเป็นคนปลูกดอกไม้', hints: [], steps: ['เรื่องบอกว่า คุณยายชอบปลูกดอกไม้หน้าบ้าน', 'น้องมีนแค่ช่วยรดน้ำ และน้องชายวิ่งไล่ผีเสื้อ'] },
    },
    {
      id: 'r-park-kids-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-count'], familyId: 'story-count', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'แม่พาน้องแอนกับพี่ชายไปตลาด ที่ตลาดแม่ซื้อผักและปลา แม่พาเด็กไปตลาดกี่คน' },
      options: [{ id: 'a', text: '1 คน' }, { id: 'b', text: '2 คน' }, { id: 'c', text: '3 คน' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'เด็กมีน้องแอนและพี่ชาย รวม 2 คน', hints: [], steps: ['แม่พาน้องแอนกับพี่ชายไป ไม่นับแม่', 'น้องแอน หนึ่ง พี่ชาย สอง เป็นเด็ก 2 คน'] },
    },
    {
      id: 'th-word-clean-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า ขยัน หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'ตั้งใจทำงานทุกวัน ไม่ขี้เกียจ' }, { id: 'b', text: 'ชอบนอนตื่นสาย' }, { id: 'c', text: 'ไม่ชอบเรียนหนังสือ' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ขยัน คือตั้งใจทำงานอย่างสม่ำเสมอ', hints: [], steps: ['คนขยันไม่ขี้เกียจ ตั้งใจทำสิ่งที่ต้องทำทุกวัน', 'ชอบนอนตื่นสายหรือไม่ชอบเรียนไม่ใช่คนขยัน'] },
    },
    {
      id: 'g-park-why-t', type: 'transfer', subject: 'general', skillIds: ['story-why-good'], familyId: 'story-why-good', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'หลังกินข้าว น้องหญิงช่วยแม่เก็บจานไปล้าง แม่จึงชมน้องหญิง แม่ชมเพราะอะไร' },
      options: [{ id: 'a', text: 'เพราะน้องหญิงช่วยทำงานบ้าน' }, { id: 'b', text: 'เพราะน้องหญิงกินข้าวเร็ว' }, { id: 'c', text: 'เพราะน้องหญิงเข้านอนเร็ว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'น้องหญิงช่วยแม่ทำงานบ้าน แม่จึงชม', hints: [], steps: ['โจทย์บอกว่า น้องหญิงช่วยแม่เก็บจานไปล้าง', 'นี่คือการช่วยทำงานบ้าน แม่จึงชม'] },
    },
    {
      id: 'r-park-not-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ที่บ้านของน้องฝนมีต้นมะม่วง ต้นกล้วย และต้นมะพร้าว ข้อใดไม่ได้กล่าวถึง' },
      options: [{ id: 'a', text: 'ต้นมะม่วง' }, { id: 'b', text: 'ต้นไผ่' }, { id: 'c', text: 'ต้นกล้วย' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ที่บ้านน้องฝนไม่มีต้นไผ่', hints: [], steps: ['ที่บ้านมีต้นมะม่วง ต้นกล้วย และต้นมะพร้าว', 'ไม่มีต้นไผ่'] },
    },
    {
      id: 'sc-animal-wings-t', type: 'transfer', subject: 'science', skillIds: ['animal-traits'], familyId: 'board-classify', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์สองชนิดใดบินได้ทั้งคู่' },
      options: [{ id: 'a', text: 'ม้า, กบ' }, { id: 'b', text: 'นกฮูก, ผีเสื้อ' }, { id: 'c', text: 'ปลา, ปู' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'นกฮูกและผีเสื้อมีปีก บินได้', hints: [], steps: ['ม้า กบ ปลา และปู ไม่มีปีก', 'นกฮูกและผีเสื้อมีปีกบินได้'] },
    },
    {
      id: 'sc-animal-eggs-t', type: 'transfer', subject: 'science', skillIds: ['animal-lifecycle'], familyId: 'board-classify', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์สองชนิดใดออกลูกเป็นไข่' },
      options: [{ id: 'a', text: 'ปลา, กบ' }, { id: 'b', text: 'หนู, แมว' }, { id: 'c', text: 'ม้า, หนู' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ปลาและกบวางไข่', hints: [], steps: ['หนู แมว และม้า ออกลูกเป็นตัว', 'ปลาและกบวางไข่ ลูกฟักออกจากไข่'] },
    },
    {
      id: 'm-animal-legs-t', type: 'transfer', subject: 'math', skillIds: ['count-legs'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เป็ด 3 ตัว เป็ดแต่ละตัวมี 2 ขา เป็ดทั้งหมดมีกี่ขา' },
      options: [{ id: 'a', text: '5 ขา' }, { id: 'b', text: '6 ขา' }, { id: 'c', text: '8 ขา' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '2 บวก 2 บวก 2 เท่ากับ 6 ขา', hints: [], steps: ['เป็ดตัวที่หนึ่ง สอง และสาม ตัวละ 2 ขา', 'นับทีละ 2 ได้ 2 4 6 เป็ดทั้งหมดมี 6 ขา'] },
    },
    {
      id: 'r-animal-no-legs-t', type: 'transfer', subject: 'reasoning', skillIds: ['classify'], familyId: 'board-classify', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์สองชนิดใดมี 4 ขาทั้งคู่' },
      options: [{ id: 'a', text: 'ไก่, ปลา' }, { id: 'b', text: 'ปู, ผึ้ง' }, { id: 'c', text: 'แมว, ม้า' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'แมวและม้ามีสี่ขา', hints: [], steps: ['ไก่มีสองขา ปลาไม่มีขา ปูมีหลายขา ผึ้งมีหกขา', 'แมวและม้าเดินด้วยสี่ขา'] },
    },
    {
      id: 'g-animal-cat-t', type: 'transfer', subject: 'general', skillIds: ['animal-help'], familyId: 'animal-help', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์ชนิดใดช่วยทำน้ำผึ้งให้เรากิน' },
      options: [{ id: 'a', text: 'ผีเสื้อ' }, { id: 'b', text: 'ผึ้ง' }, { id: 'c', text: 'หอยทาก' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ผึ้งทำน้ำผึ้ง', hints: [], steps: ['ผึ้งเก็บน้ำหวานจากดอกไม้มาทำเป็นน้ำผึ้ง', 'ผีเสื้อและหอยทากไม่ได้ทำน้ำผึ้ง'] },
    },
    {
      id: 'th-final-none-t', type: 'transfer', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดไม่มีตัวสะกด' },
      options: [{ id: 'a', text: 'ผัก' }, { id: 'b', text: 'ดิน' }, { id: 'c', text: 'ตา' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ตาจบด้วยสระ ไม่มีตัวสะกด', hints: [], steps: ['ผักมี ก เป็นตัวสะกด และดินมี น เป็นตัวสะกด', 'ตาจบด้วยสระอา ไม่มีตัวสะกด'] },
    },
    {
      id: 'th-tone-ek-t', type: 'transfer', subject: 'thai', skillIds: ['tone-mark'], familyId: 'tone-mark', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีวรรณยุกต์โท' },
      options: [{ id: 'a', text: 'ปลา' }, { id: 'b', text: 'ข้าว' }, { id: 'c', text: 'ไข่' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ข้าวมีไม้โท', hints: [], steps: ['ปลาไม่มีเครื่องหมายเหนือพยัญชนะ ส่วนไข่มีไม้เอก', 'ข้าวมีไม้โท อยู่เหนือตัว ข'] },
    },
    {
      id: 'm-group-flowers-t', type: 'transfer', subject: 'math', skillIds: ['sharing-groups'], familyId: 'group-division', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ครูมีขนม 12 ชิ้น แบ่งใส่ถุง ถุงละ 4 ชิ้น จะได้กี่ถุง' },
      options: [{ id: 'a', text: '3 ถุง' }, { id: 'b', text: '4 ถุง' }, { id: 'c', text: '8 ถุง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'นับทีละ 4 จนครบ 12 ได้ 3 ถุง', hints: [], steps: ['นับทีละ 4 ได้ 4 8 12', 'นับได้ 3 ครั้ง จึงได้ 3 ถุง'] },
    },
    {
      id: 'sp-analogy-dots-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-analogy'], familyId: 'grid-analogy', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: RULE },
      visual: { type: 'figure-grid', rows: [[{ dots: 5 }, { dots: 4 }], [{ dots: 8 }, '?']] },
      options: [fig('a', { dots: 6 }), fig('b', { dots: 7 }), fig('c', { dots: 9 }), fig('d', { dots: 5 })],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'จุดลดลงทีละ 1 จุด', hints: [], steps: ['แถวบนจาก 5 จุด เหลือ 4 จุด คือลดลง 1 จุด', 'แถวล่างมี 8 จุด ลดลง 1 จุด เหลือ 7 จุด'] },
    },
    {
      id: 'sp-analogy-fill-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-analogy'], familyId: 'grid-analogy', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: RULE },
      visual: {
        type: 'figure-grid',
        rows: [[{ shape: 'square', fill: 'solid' }, { shape: 'square', fill: 'dots' }], [{ shape: 'diamond', fill: 'solid' }, '?']],
      },
      options: [fig('a', { shape: 'diamond', fill: 'solid' }), fig('b', { shape: 'diamond', fill: 'dots' }), fig('c', { shape: 'square', fill: 'dots' }), fig('d', { shape: 'diamond', fill: 'empty' })],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'รูปทึบกลายเป็นรูปมีจุด รูปร่างไม่เปลี่ยน', hints: [], steps: ['แถวบนจากสี่เหลี่ยมทึบ กลายเป็นสี่เหลี่ยมมีจุด', 'แถวล่างเป็นข้าวหลามตัดทึบ จึงกลายเป็นข้าวหลามตัดมีจุด'] },
    },
  ],
};
