/*
 * ชุดที่ 15 — รูปแบบใหม่ 15 ข้อ (ดู docs/QUESTION-TYPES.md หัวข้อ "รูปแบบชุด 12 ขึ้นไป")
 * ช่วง 1 เรื่องเดียวถาม 5 ข้อ (แม่ค้าตลาดริมน้ำ: ที่ไหน กี่ชนิด มากที่สุด มากกว่ากี่ตัว ทำไม)
 * ช่วง 2 โจทย์แนวใหม่ที่วาดด้วยโค้ด: ตัวเลือกนับรูป, แผนภาพดาว, ตารางภาพที่มีช่องหาย
 * ช่วง 3 ข้อเดี่ยว: นับรูปสองขั้น, ภาพต่อเนื่อง, มารยาท, คำตรงข้าม, แสงสว่าง
 * แต่งใหม่ทั้งหมด ตั้งชื่อตัวละคร สถานที่ และตัวเลขใหม่ตามแนวข้อสอบเก่า
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LISTEN = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';
const cnt = (id, asset, n, say) => ({ id, svg: { count: { asset, n } }, speech: say });
const fig = (id, figure) => ({ id, svg: { figure } });
const venn = (id, where) => ({ id, svg: { venn: where } });
const row = (asset, n) => ({ type: 'row', items: Array.from({ length: n }, () => asset) });

export default {
  id: 'set-15',
  version: 1,
  title: 'ชุดที่ 15',
  note: 'แม่ค้าตลาดริมน้ำ นับรูป ดาวในวงกลม ภาพที่หายไป',
  order: [
    'th-stall-where', 'r-stall-kinds', 'm-stall-most', 'm-stall-diff', 'g-stall-why',
    'm-mango-picture', 'sp-star-both', 'r-corner-missing', 'r-shape-missing', 'sc-water-animal',
    'm-pencil-picture', 'sp-half-ccw', 'g-greet-teacher', 'th-opposite-hot', 'sc-day-light',
  ],
  stimuli: {
    stall: {
      section: LISTEN,
      text: 'ลุงพงษ์ขายอาหารทะเลที่ตลาดริมน้ำ วันนี้ลุงพงษ์ขายปลาทูได้ 12 ตัว ปลาหมึก 7 ตัว กุ้ง 9 ตัว และปูม้า 5 ตัว ลุงพงษ์เป็นคนใจดี ชอบแถมของให้ลูกค้าเสมอ ลูกค้าจึงมาซื้อกันมากมาย',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: เรื่องเดียว 5 ข้อ
    {
      id: 'th-stall-where', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-where', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'stall',
      prompt: { text: 'ลุงพงษ์ขายของที่ไหน' },
      options: [{ id: 'a', text: 'ตลาดริมน้ำ' }, { id: 'b', text: 'ตลาดบนภูเขา' }, { id: 'c', text: 'ตลาดในห้างสรรพสินค้า' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'ลุงพงษ์ขายของอยู่ที่ตลาดริมน้ำ',
        hints: ['ฟังประโยคแรกของเรื่อง'],
        steps: ['ต้นเรื่องบอกว่า ลุงพงษ์ขายอาหารทะเลที่ตลาดริมน้ำ', 'จึงเป็นตลาดริมน้ำ ตอบข้อ 1'],
        transferIds: ['th-stall-where-t'],
      },
    },
    {
      id: 'r-stall-kinds', type: 'main', subject: 'reasoning', skillIds: ['story-count-kinds'], familyId: 'story-kinds', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'stall',
      prompt: { text: 'ลุงพงษ์ขายอาหารทะเลกี่ชนิด' },
      options: [{ id: 'a', text: '3 ชนิด' }, { id: 'b', text: '4 ชนิด' }, { id: 'c', text: '5 ชนิด' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับชนิดของจากเรื่อง (ไม่ใช่นับจำนวนตัว)',
      review: {
        summary: 'ปลาทู ปลาหมึก กุ้ง และปูม้า รวมเป็น 4 ชนิด',
        hints: ['นับชื่ออาหารทะเลแต่ละอย่างในเรื่อง อย่านับจำนวนตัว'],
        steps: ['อาหารทะเลที่ขายมี ปลาทู หนึ่ง ปลาหมึก สอง กุ้ง สาม ปูม้า สี่', 'มี 4 ชนิด ตอบข้อ 2'],
        transferIds: ['r-stall-kinds-t'],
      },
    },
    {
      id: 'm-stall-most', type: 'main', subject: 'math', skillIds: ['compare-most'], familyId: 'story-most', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'stall',
      prompt: { text: 'ลุงพงษ์ขายอะไรได้มากที่สุด' },
      options: [{ id: 'a', text: 'ปลาหมึก' }, { id: 'b', text: 'กุ้ง' }, { id: 'c', text: 'ปลาทู' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ วัดการเปรียบเทียบจำนวนจากเรื่อง',
      review: {
        summary: 'ปลาทู 12 ตัว มากกว่าอย่างอื่น',
        hints: ['เทียบจำนวนตัวของปลาทู ปลาหมึก กุ้ง และปูม้า'],
        steps: ['ปลาทู 12 ตัว ปลาหมึก 7 ตัว กุ้ง 9 ตัว ปูม้า 5 ตัว', '12 มากที่สุด จึงขายปลาทูได้มากที่สุด ตอบข้อ 3'],
        transferIds: ['m-stall-most-t'],
      },
    },
    {
      id: 'm-stall-diff', type: 'main', subject: 'math', skillIds: ['compare-difference'], familyId: 'story-diff', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'stall',
      prompt: { text: 'ลุงพงษ์ขายกุ้งได้มากกว่าปูม้ากี่ตัว' },
      options: [{ id: 'a', text: '4 ตัว' }, { id: 'b', text: '14 ตัว' }, { id: 'c', text: '2 ตัว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการหาผลต่างจากข้อมูลในเรื่อง',
      review: {
        summary: 'กุ้ง 9 ตัว ปูม้า 5 ตัว ต่างกัน 4 ตัว',
        hints: ['หาว่ามากกว่ากี่ตัว ใช้การลบ'],
        steps: ['กุ้งขายได้ 9 ตัว ปูม้าขายได้ 5 ตัว', 'หาว่ามากกว่ากี่ตัว ใช้การลบ 9 ลบ 5 เท่ากับ 4 ตัว ตอบข้อ 1'],
        column: { a: 9, op: '-', b: 5 },
        transferIds: ['m-stall-diff-t'],
      },
    },
    {
      id: 'g-stall-why', type: 'main', subject: 'general', skillIds: ['story-why-good'], familyId: 'story-why-good', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'stall',
      prompt: { text: 'ทำไมลูกค้าจึงมาซื้อของลุงพงษ์มากมาย' },
      options: [{ id: 'a', text: 'เพราะลุงพงษ์ขายของแพง' }, { id: 'b', text: 'เพราะลุงพงษ์ใจดี แถมของให้เสมอ' }, { id: 'c', text: 'เพราะตลาดริมน้ำอยู่ใกล้บ้าน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการฟังหาเหตุผลและคุณธรรม',
      review: {
        summary: 'ลุงพงษ์ใจดี ลูกค้าจึงชอบมาซื้อ',
        hints: ['ฟังประโยคสุดท้ายของเรื่อง'],
        steps: ['เรื่องไม่ได้บอกว่าลุงพงษ์ขายของแพง หรือตลาดอยู่ใกล้บ้าน', 'เรื่องบอกว่าลุงใจดี ชอบแถมของ ลูกค้าจึงมาซื้อมาก ตอบข้อ 2'],
        transferIds: ['g-stall-why-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: โจทย์แนวใหม่
    {
      id: 'm-mango-picture', type: 'main', subject: 'math', skillIds: ['multi-step-picture'], familyId: 'picture-answer', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'แม่มีมะม่วง 6 ผล ซื้อมาเพิ่ม 3 ผล แล้วแบ่งให้ป้า 4 ผล ตอนนี้แม่เหลือมะม่วงกี่ผล' },
      visual: row('pic-mango', 6),
      options: [cnt('a', 'pic-mango', 9, 'มะม่วง 9 ผล'), cnt('b', 'pic-mango', 4, 'มะม่วง 4 ผล'), cnt('c', 'pic-mango', 5, 'มะม่วง 5 ผล')],
      correctOptionId: 'c',
      narration: 'อ่านจำนวนของรูปในตัวเลือกได้ วัดการคิดสองขั้น บวกแล้วลบ และการนับรูป',
      review: {
        summary: 'ซื้อเพิ่มได้ 9 แบ่งให้ป้า 4 เหลือ 5 ผล',
        hints: ['ทำทีละขั้น ซื้อมาเพิ่มก่อน แล้วค่อยแบ่งให้ป้า'],
        steps: ['แม่มี 6 ผล ซื้อเพิ่ม 3 ผล 6 บวก 3 เท่ากับ 9 ผล', 'แบ่งให้ป้า 4 ผล 9 ลบ 4 เท่ากับ 5 ผล ตอบข้อ 3'],
        column: { a: 9, op: '-', b: 4 },
        transferIds: ['m-mango-picture-t'],
      },
    },
    {
      id: 'sp-star-both', type: 'main', subject: 'spatial', skillIds: ['region-overlap'], familyId: 'star-region', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ดาวอยู่ในวงกลมและอยู่ในสี่เหลี่ยมพร้อมกัน ภาพใดถูกต้อง' },
      options: [venn('a', 'circle'), venn('b', 'none'), venn('c', 'square'), venn('d', 'both')],
      correctOptionId: 'd',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการมองว่าดาวอยู่ในรูปใด',
      review: {
        summary: 'ดาวต้องอยู่ตรงส่วนที่วงกลมกับสี่เหลี่ยมซ้อนกัน',
        hints: ['หาส่วนที่รูปสองรูปซ้อนทับกัน แล้วดูว่าดาวอยู่ตรงนั้นไหม'],
        steps: ['ข้อที่ดาวอยู่นอกรูป หรืออยู่ในรูปเดียว ยังไม่ถูก', 'ดาวอยู่ตรงกลาง ส่วนที่ทั้งวงกลมและสี่เหลี่ยมซ้อนกัน ตอบข้อ 4'],
        transferIds: ['sp-star-circle-t'],
      },
    },
    {
      id: 'r-corner-missing', type: 'main', subject: 'reasoning', skillIds: ['grid-missing'], familyId: 'grid-missing', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ตารางนี้มีภาพสี่ภาพ ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-grid', rows: [[{ half: 'tl' }, { half: 'tr' }], [{ half: 'br' }, '?']] },
      options: [fig('a', { half: 'tl' }), fig('b', { half: 'bl' }), fig('c', { half: 'tr' }), fig('d', { half: 'br' })],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหาภาพที่ขาดในชุดภาพสี่มุม',
      review: {
        summary: 'สี่มุมต้องมีครบ ขาดมุมล่างซ้าย',
        hints: ['ดูว่าในตารางมีสีเข้มอยู่มุมไหนแล้วบ้าง'],
        steps: ['ในตารางมีสีเข้มอยู่มุมบนซ้าย มุมบนขวา และมุมล่างขวาแล้ว', 'ยังขาดมุมล่างซ้าย ตอบข้อ 2'],
        transferIds: ['r-corner-missing-t'],
      },
    },
    {
      id: 'r-shape-missing', type: 'main', subject: 'reasoning', skillIds: ['grid-missing'], familyId: 'grid-missing', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ในแต่ละแถวและแต่ละแถวตั้ง มีรูปครบทั้งสามแบบ ช่อง ? ควรเป็นรูปใด' },
      visual: {
        type: 'figure-grid',
        rows: [
          [{ shape: 'circle' }, { shape: 'square' }, { shape: 'triangle' }],
          [{ shape: 'square' }, { shape: 'triangle' }, { shape: 'circle' }],
          [{ shape: 'triangle' }, { shape: 'circle' }, '?'],
        ],
      },
      options: [fig('a', { shape: 'circle' }), fig('b', { shape: 'hexagon' }), fig('c', { shape: 'square' }), fig('d', { shape: 'triangle' })],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหารูปที่ขาดให้ครบทุกแถวทุกหลัก',
      review: {
        summary: 'แถวล่างมีสามเหลี่ยมกับวงกลมแล้ว ขาดสี่เหลี่ยม',
        hints: ['ดูแถวล่างสุด มีรูปอะไรแล้วบ้าง ยังขาดรูปไหน'],
        steps: ['แถวล่างมีสามเหลี่ยมและวงกลมแล้ว แต่ละแถวต้องมีครบสามแบบ', 'จึงขาดสี่เหลี่ยม ตอบข้อ 3'],
        transferIds: ['r-shape-missing-t'],
      },
    },
    {
      id: 'sc-water-animal', type: 'main', subject: 'science', skillIds: ['animal-home'], familyId: 'animal-home', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สัตว์ใดอาศัยอยู่ในน้ำ' },
      options: [{ id: 'a', image: 'pic-fish', speech: 'ปลา' }, { id: 'b', image: 'pic-elephant', speech: 'ช้าง' }, { id: 'c', image: 'pic-chicken', speech: 'ไก่' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ วัดความรู้เรื่องที่อยู่อาศัยของสัตว์',
      review: {
        summary: 'ปลาว่ายน้ำและหายใจในน้ำได้',
        hints: ['สัตว์ตัวไหนมีครีบ'],
        steps: ['ช้างและไก่อาศัยอยู่บนบก', 'ปลามีครีบ อยู่ในน้ำ ตอบข้อ 1'],
        transferIds: ['sc-water-animal-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-pencil-picture', type: 'main', subject: 'math', skillIds: ['multi-step-picture'], familyId: 'picture-answer', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ต้นมีดินสอ 5 แท่ง แม่ซื้อให้เพิ่ม 4 แท่ง ต้นให้เพื่อนไป 2 แท่ง ตอนนี้ต้นมีดินสอกี่แท่ง' },
      visual: row('pic-pencil', 5),
      options: [cnt('a', 'pic-pencil', 6, 'ดินสอ 6 แท่ง'), cnt('b', 'pic-pencil', 7, 'ดินสอ 7 แท่ง'), cnt('c', 'pic-pencil', 8, 'ดินสอ 8 แท่ง')],
      correctOptionId: 'b',
      narration: 'อ่านจำนวนของรูปในตัวเลือกได้ วัดการคิดสองขั้น บวกแล้วลบ และการนับรูป',
      review: {
        summary: 'ได้เพิ่มเป็น 9 ให้เพื่อน 2 เหลือ 7 แท่ง',
        hints: ['ทำทีละขั้น ได้เพิ่มก่อน แล้วค่อยให้เพื่อน'],
        steps: ['ต้นมี 5 แท่ง แม่ให้เพิ่ม 4 แท่ง 5 บวก 4 เท่ากับ 9 แท่ง', 'ให้เพื่อนไป 2 แท่ง 9 ลบ 2 เท่ากับ 7 แท่ง ตอบข้อ 2'],
        column: { a: 9, op: '-', b: 2 },
        transferIds: ['m-pencil-picture-t'],
      },
    },
    {
      id: 'sp-half-ccw', type: 'main', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'half-sequence', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ส่วนที่ระบายสีเลื่อนไปทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ half: 'tl' }, { half: 'bl' }, { half: 'br' }, '?'] },
      options: [fig('a', { half: 'bl' }), fig('b', { half: 'tr' }), fig('c', { half: 'tl' }), fig('d', { half: 'br' })],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหาแบบรูปของการหมุนทวนเข็มนาฬิกา',
      review: {
        summary: 'สีเข้มเลื่อนทวนเข็มนาฬิกาทีละมุม ต่อไปอยู่มุมบนขวา',
        hints: ['ดูว่าสีเข้มย้ายจากมุมบนซ้ายไปมุมไหนก่อน'],
        steps: ['สีเข้มย้ายจากบนซ้าย ลงมาล่างซ้าย แล้วไปล่างขวา วนทวนเข็มนาฬิกา', 'ต่อไปจึงขึ้นไปอยู่มุมบนขวา ตอบข้อ 2'],
        transferIds: ['sp-half-ccw-t'],
      },
    },
    {
      id: 'g-greet-teacher', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'manners-greet', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อพบคุณครูที่หน้าโรงเรียน หนูควรทำอย่างไร' },
      options: [{ id: 'a', text: 'ยกมือไหว้ และกล่าวสวัสดี' }, { id: 'b', text: 'ทำเป็นไม่เห็น แล้วเดินผ่านไป' }, { id: 'c', text: 'วิ่งเข้าไปชนคุณครู' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ วัดมารยาทการทักทาย',
      review: {
        summary: 'ไหว้ผู้ใหญ่และทักทายอย่างสุภาพ',
        hints: ['เราเคารพผู้ใหญ่ด้วยการทำอย่างไร'],
        steps: ['การทำเป็นไม่เห็นหรือวิ่งชนไม่สุภาพ', 'ต้องยกมือไหว้และพูดสวัสดี ตอบข้อ 1'],
        transferIds: ['g-greet-monk-t'],
      },
    },
    {
      id: 'th-opposite-hot', type: 'main', subject: 'thai', skillIds: ['opposite-words'], familyId: 'opposite-words', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า ร้อน มีความหมายตรงข้ามกับคำใด' },
      options: [{ id: 'a', text: 'สวย' }, { id: 'b', text: 'ใหญ่' }, { id: 'c', text: 'เย็น' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ วัดคำที่มีความหมายตรงข้ามกัน',
      review: {
        summary: 'ร้อนกับเย็น ความหมายตรงข้ามกัน',
        hints: ['น้ำแข็งเป็นอย่างไร ตรงข้ามกับน้ำเดือด'],
        steps: ['สวยกับใหญ่ ไม่ได้ตรงข้ามกับร้อน', 'น้ำเดือดร้อน น้ำแข็งเย็น จึงตรงข้ามกัน ตอบข้อ 3'],
        transferIds: ['th-opposite-big-t'],
      },
    },
    {
      id: 'sc-day-light', type: 'main', subject: 'science', skillIds: ['light-source'], familyId: 'light-source', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ตอนกลางวัน แสงสว่างมาจากสิ่งใด' },
      options: [{ id: 'a', image: 'pic-sun', speech: 'ดวงอาทิตย์' }, { id: 'b', image: 'pic-rain-cloud', speech: 'เมฆฝน' }, { id: 'c', image: 'pic-rainbow', speech: 'รุ้ง' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ วัดความรู้เรื่องแหล่งกำเนิดแสง',
      review: {
        summary: 'ดวงอาทิตย์ส่องแสงให้โลกสว่าง',
        hints: ['ตื่นเช้ามา เราเห็นอะไรขึ้นมาบนท้องฟ้า'],
        steps: ['เมฆฝนและรุ้งไม่ได้ให้แสงสว่างด้วยตัวเอง', 'ดวงอาทิตย์ให้แสงสว่างตอนกลางวัน ตอบข้อ 1'],
        transferIds: ['sc-night-light-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-stall-where-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-where', difficulty: 1,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ป้าสมหญิงขายผักสดที่ตลาดนัดหน้าวัด ทุกวันอาทิตย์ป้าตื่นตั้งแต่ตีสี่ ป้าสมหญิงขายผักที่ไหน' },
      options: [{ id: 'a', text: 'ตลาดนัดหน้าวัด' }, { id: 'b', text: 'ตลาดน้ำ' }, { id: 'c', text: 'ร้านขายของในห้าง' }],
      correctOptionId: 'a',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ป้าสมหญิงขายผักที่ตลาดนัดหน้าวัด', hints: [], steps: ['เรื่องบอกว่า ป้าขายผักที่ตลาดนัดหน้าวัด', 'จึงเป็นตลาดนัดหน้าวัด'] },
    },
    {
      id: 'r-stall-kinds-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-count-kinds'], familyId: 'story-kinds', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ป้าแดงขายผลไม้ส้ม 10 ผล มะม่วง 6 ผล และกล้วย 8 ลูก ป้าแดงขายผลไม้กี่ชนิด' },
      options: [{ id: 'a', text: '2 ชนิด' }, { id: 'b', text: '3 ชนิด' }, { id: 'c', text: '24 ชนิด' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ส้ม มะม่วง กล้วย เป็น 3 ชนิด', hints: [], steps: ['นับชื่อผลไม้ ส้ม หนึ่ง มะม่วง สอง กล้วย สาม', 'ไม่ต้องนับจำนวนผล จึงมี 3 ชนิด'] },
    },
    {
      id: 'm-stall-most-t', type: 'transfer', subject: 'math', skillIds: ['compare-most'], familyId: 'story-most', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'วันนี้พี่ขายน้ำได้ 15 แก้ว ขายขนมได้ 22 ชิ้น และขายผลไม้ได้ 18 ถุง พี่ขายอะไรได้มากที่สุด' },
      options: [{ id: 'a', text: 'น้ำ' }, { id: 'b', text: 'ผลไม้' }, { id: 'c', text: 'ขนม' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ขนม 22 ชิ้น มากที่สุด', hints: [], steps: ['น้ำ 15 ขนม 22 ผลไม้ 18', '22 มากที่สุด จึงขายขนมได้มากที่สุด'] },
    },
    {
      id: 'm-stall-diff-t', type: 'transfer', subject: 'math', skillIds: ['compare-difference'], familyId: 'story-diff', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ตาขายไข่ไก่ได้ 14 ฟอง ขายไข่เป็ดได้ 6 ฟอง ตาขายไข่ไก่ได้มากกว่าไข่เป็ดกี่ฟอง' },
      options: [{ id: 'a', text: '20 ฟอง' }, { id: 'b', text: '8 ฟอง' }, { id: 'c', text: '10 ฟอง' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: '14 ลบ 6 เท่ากับ 8 ฟอง', hints: [], steps: ['ไข่ไก่ 14 ฟอง ไข่เป็ด 6 ฟอง', 'หาว่ามากกว่ากี่ฟอง ใช้การลบ 14 ลบ 6 เท่ากับ 8'], column: { a: 14, op: '-', b: 6 } },
    },
    {
      id: 'g-stall-why-t', type: 'transfer', subject: 'general', skillIds: ['story-why-good'], familyId: 'story-why-good', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'น้องฝนช่วยคุณแม่ล้างจานทุกวัน คุณแม่จึงรักและชมน้องฝนเสมอ ทำไมคุณแม่จึงชมน้องฝน' },
      options: [{ id: 'a', text: 'เพราะน้องฝนตัวสูง' }, { id: 'b', text: 'เพราะน้องฝนชอบเล่น' }, { id: 'c', text: 'เพราะน้องฝนช่วยงานบ้าน' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'น้องฝนช่วยทำงานบ้าน จึงได้รับคำชม', hints: [], steps: ['เรื่องบอกว่าน้องฝนช่วยล้างจานทุกวัน', 'คุณแม่จึงชมเพราะน้องฝนช่วยงานบ้าน'] },
    },
    {
      id: 'm-mango-picture-t', type: 'transfer', subject: 'math', skillIds: ['multi-step-picture'], familyId: 'picture-answer', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'บนจานมีส้ม 4 ผล แม่วางเพิ่ม 3 ผล น้องหยิบไปกิน 2 ผล บนจานเหลือส้มกี่ผล' },
      visual: row('pic-orange', 4),
      options: [cnt('a', 'pic-orange', 5, 'ส้ม 5 ผล'), cnt('b', 'pic-orange', 7, 'ส้ม 7 ผล'), cnt('c', 'pic-orange', 9, 'ส้ม 9 ผล')],
      correctOptionId: 'a',
      narration: 'อ่านจำนวนของรูปในตัวเลือกได้',
      review: { summary: '4 บวก 3 เป็น 7 ลบ 2 เหลือ 5 ผล', hints: [], steps: ['4 บวก 3 เท่ากับ 7 ผล', '7 ลบ 2 เท่ากับ 5 ผล'], column: { a: 7, op: '-', b: 2 } },
    },
    {
      id: 'sp-star-circle-t', type: 'transfer', subject: 'spatial', skillIds: ['region-overlap'], familyId: 'star-region', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ดาวอยู่ในวงกลมเท่านั้น ไม่อยู่ในสี่เหลี่ยม ภาพใดถูกต้อง' },
      options: [venn('a', 'square'), venn('b', 'circle'), venn('c', 'both'), venn('d', 'none')],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'ดาวอยู่ในวงกลมและไม่ซ้อนกับสี่เหลี่ยม', hints: [], steps: ['ดาวต้องอยู่ในวงกลม แต่ต้องอยู่ห่างจากสี่เหลี่ยม', 'ภาพที่ดาวอยู่ทางซ้ายในวงกลมเท่านั้นคือข้อที่ถูก'] },
    },
    {
      id: 'r-corner-missing-t', type: 'transfer', subject: 'reasoning', skillIds: ['grid-missing'], familyId: 'grid-missing', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ตารางนี้มีภาพสี่ภาพ ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-grid', rows: [[{ half: 'bl' }, { half: 'br' }], [{ half: 'tl' }, '?']] },
      options: [fig('a', { half: 'bl' }), fig('b', { half: 'br' }), fig('c', { half: 'tl' }), fig('d', { half: 'tr' })],
      correctOptionId: 'd',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'สี่มุมต้องครบ ขาดมุมบนขวา', hints: [], steps: ['ในตารางมีสีเข้มที่มุมล่างซ้าย ล่างขวา และบนซ้ายแล้ว', 'ยังขาดมุมบนขวา'] },
    },
    {
      id: 'r-shape-missing-t', type: 'transfer', subject: 'reasoning', skillIds: ['grid-missing'], familyId: 'grid-missing', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ในแต่ละแถวและแต่ละแถวตั้ง มีรูปครบทั้งสามแบบ ช่อง ? ควรเป็นรูปใด' },
      visual: {
        type: 'figure-grid',
        rows: [
          [{ shape: 'hexagon' }, { shape: 'diamond' }, { shape: 'circle' }],
          [{ shape: 'diamond' }, { shape: 'circle' }, { shape: 'hexagon' }],
          [{ shape: 'circle' }, { shape: 'hexagon' }, '?'],
        ],
      },
      options: [fig('a', { shape: 'circle' }), fig('b', { shape: 'diamond' }), fig('c', { shape: 'hexagon' }), fig('d', { shape: 'square' })],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'แถวล่างมีวงกลมกับหกเหลี่ยมแล้ว ขาดข้าวหลามตัด', hints: [], steps: ['แถวล่างมีวงกลมและหกเหลี่ยมแล้ว', 'ยังขาดรูปข้าวหลามตัด'] },
    },
    {
      id: 'sc-water-animal-t', type: 'transfer', subject: 'science', skillIds: ['animal-home'], familyId: 'animal-home', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สัตว์ใดอาศัยอยู่บนบก ไม่ได้อยู่ในน้ำ' },
      options: [{ id: 'a', image: 'pic-crab', speech: 'ปู' }, { id: 'b', image: 'pic-fish', speech: 'ปลา' }, { id: 'c', image: 'pic-horse', speech: 'ม้า' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ม้าอาศัยและวิ่งอยู่บนบก', hints: [], steps: ['ปูและปลาอาศัยอยู่ในน้ำ', 'ม้าวิ่งบนบก'] },
    },
    {
      id: 'm-pencil-picture-t', type: 'transfer', subject: 'math', skillIds: ['multi-step-picture'], familyId: 'picture-answer', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'พี่มีลูกบอล 6 ลูก ซื้อใหม่อีก 2 ลูก แล้วให้น้องไป 3 ลูก พี่เหลือลูกบอลกี่ลูก' },
      visual: row('pic-ball', 6),
      options: [cnt('a', 'pic-ball', 8, 'ลูกบอล 8 ลูก'), cnt('b', 'pic-ball', 5, 'ลูกบอล 5 ลูก'), cnt('c', 'pic-ball', 3, 'ลูกบอล 3 ลูก')],
      correctOptionId: 'b',
      narration: 'อ่านจำนวนของรูปในตัวเลือกได้',
      review: { summary: '6 บวก 2 เป็น 8 ลบ 3 เหลือ 5 ลูก', hints: [], steps: ['6 บวก 2 เท่ากับ 8 ลูก', '8 ลบ 3 เท่ากับ 5 ลูก'], column: { a: 8, op: '-', b: 3 } },
    },
    {
      id: 'sp-half-ccw-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'half-sequence', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ส่วนที่ระบายสีเลื่อนไปทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ half: 'tr' }, { half: 'br' }, { half: 'bl' }, '?'] },
      options: [fig('a', { half: 'br' }), fig('b', { half: 'tr' }), fig('c', { half: 'tl' }), fig('d', { half: 'bl' })],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'สีเข้มเลื่อนตามเข็มนาฬิกา ต่อไปอยู่มุมบนซ้าย', hints: [], steps: ['สีเข้มย้ายจากบนขวา ลงล่างขวา แล้วไปล่างซ้าย', 'ต่อไปจึงขึ้นไปอยู่มุมบนซ้าย'] },
    },
    {
      id: 'g-greet-monk-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'manners-greet', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อไปวัดแล้วพบพระสงฆ์ หนูควรทำอย่างไร' },
      options: [{ id: 'a', text: 'วิ่งเล่นส่งเสียงดัง' }, { id: 'b', text: 'ประนมมือไหว้' }, { id: 'c', text: 'ชี้หน้าพระ' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'พบพระสงฆ์ ให้ประนมมือไหว้ด้วยความเคารพ', hints: [], steps: ['การวิ่งเล่นเสียงดังหรือชี้หน้าไม่สุภาพ', 'เราประนมมือไหว้เพื่อแสดงความเคารพ'] },
    },
    {
      id: 'th-opposite-big-t', type: 'transfer', subject: 'thai', skillIds: ['opposite-words'], familyId: 'opposite-words', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า ใหญ่ มีความหมายตรงข้ามกับคำใด' },
      options: [{ id: 'a', text: 'เล็ก' }, { id: 'b', text: 'ร้อน' }, { id: 'c', text: 'สูง' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ใหญ่กับเล็ก ความหมายตรงข้ามกัน', hints: [], steps: ['ช้างตัวใหญ่ มดตัวเล็ก', 'ใหญ่จึงตรงข้ามกับเล็ก'] },
    },
    {
      id: 'sc-night-light-t', type: 'transfer', subject: 'science', skillIds: ['light-source'], familyId: 'light-source', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ตอนกลางคืน ถ้าไม่มีไฟฟ้า เรามองเห็นแสงสลัวบนท้องฟ้าจากสิ่งใด' },
      options: [{ id: 'a', image: 'pic-rainbow', speech: 'รุ้ง' }, { id: 'b', image: 'pic-night', speech: 'พระจันทร์และดาว' }, { id: 'c', image: 'pic-sun', speech: 'ดวงอาทิตย์' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'พระจันทร์และดาวให้แสงตอนกลางคืน', hints: [], steps: ['ดวงอาทิตย์ส่องแสงตอนกลางวัน รุ้งเกิดหลังฝน', 'ตอนกลางคืนเห็นพระจันทร์และดาว'] },
    },
  ],
};
