/*
 * ชุดที่ 32 — วันสำคัญของไทย (แผ่นรูป O: design/PROMPTS-gemini-12.md) แบบ 15 ข้อ
 * ช่วง 1: ภาพใดเป็นวันสงกรานต์ ลอยกระทง วันแม่ วันเด็ก วันพ่อ (ตัวเลือกเป็นภาพ ใช้ scene: true)
 * ช่วง 2: ดอกไม้วันแม่ มารยาทวันสงกรานต์ พระจันทร์วันลอยกระทง นับคนในภาพ ซ้ายขวาของภาพวันไหว้ครู
 * ช่วง 3: นับวันถึงปีใหม่ เทียนพรรษา พยัญชนะต้นของ กระทง ลำดับวันสำคัญในปี เหตุผลของวันไหว้ครู
 * แต่งใหม่ทั้งหมด; ข้อที่ผู้ปกครองควรตรวจ: วันที่ของวันสำคัญ (สงกรานต์ 13 เมษายน วันแม่ 12 สิงหาคม วันพ่อ 5 ธันวาคม ปีใหม่ 1 มกราคม)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const DAYS = 'ดูภาพวันสำคัญของไทยแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const PICS = 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดความรู้เรื่องวันสำคัญของไทย';
const day = (id, name) => ({ id, image: `pic-day-${name}` });
const scene = (name) => ({ type: 'image', asset: `pic-day-${name}` });
const words = (...list) => list.map((text, i) => ({ id: 'abc'[i], text }));
const letters = (...list) => list.map((text, i) => ({ id: 'abc'[i], text, speech: '' }));

export default {
  id: 'set-32',
  version: 1,
  title: 'ชุดที่ 32',
  note: 'วันสำคัญของไทย สงกรานต์ ลอยกระทง วันแม่ วันพ่อ ปีใหม่',
  order: [
    'g-day-songkran', 'g-day-loy', 'g-day-mother', 'g-day-children', 'g-day-father',
    'g-day-flower', 'g-day-water', 'sc-day-moon', 'm-day-people', 'sp-day-teacher',
    'm-day-newyear', 'g-day-lent', 'th-day-initial', 'r-day-order', 'g-day-teacher-why',
  ],
  stimuli: {},
  items: [
    // ================================================================ ช่วงที่ 1: ภาพใดเป็นวันอะไร
    {
      id: 'g-day-songkran', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันสงกรานต์ ซึ่งคนไทยเล่นสาดน้ำกันในหน้าร้อน' },
      options: [day('a', 'songkran'), day('b', 'loy'), day('c', 'newyear')],
      correctOptionId: 'a',
      narration: PICS,
      review: {
        summary: 'วันสงกรานต์เล่นสาดน้ำและรดน้ำขอพรผู้ใหญ่ ตรงกับวันที่ 13 เมษายน',
        hints: ['ดูภาพที่มีแดดจ้าและเด็กๆ ถือขันน้ำกับปืนฉีดน้ำ'],
        steps: ['ภาพลอยกระทงเป็นกลางคืนและภาพปีใหม่มีดอกไม้ไฟ ไม่มีการสาดน้ำ', 'ภาพที่เล่นสาดน้ำกลางแดดคือวันสงกรานต์ ตอบข้อ 1'],
        transferIds: ['g-day-songkran-t'],
      },
    },
    {
      id: 'g-day-loy', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันลอยกระทง ซึ่งคนไทยนำกระทงไปลอยในน้ำตอนกลางคืน' },
      options: [day('a', 'children'), day('b', 'father'), day('c', 'loy')],
      correctOptionId: 'c',
      narration: PICS,
      review: {
        summary: 'วันลอยกระทงนำกระทงไปลอยในแม่น้ำตอนกลางคืนที่พระจันทร์เต็มดวง',
        hints: ['ดูภาพที่เป็นกลางคืนและมีกระทงลอยอยู่บนน้ำ'],
        steps: ['ภาพวันเด็กและภาพวันพ่อเป็นตอนกลางวันและไม่มีกระทง', 'ภาพที่มีกระทงลอยในน้ำตอนกลางคืนคือวันลอยกระทง ตอบข้อ 3'],
        transferIds: ['g-day-loy-t'],
      },
    },
    {
      id: 'g-day-mother', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันแม่ ซึ่งลูกมอบพวงมาลัยดอกมะลิให้แม่' },
      options: [day('a', 'teacher'), day('b', 'mother'), day('c', 'father')],
      correctOptionId: 'b',
      narration: PICS,
      review: {
        summary: 'วันแม่แห่งชาติตรงกับวันที่ 12 สิงหาคม ลูกมอบดอกมะลิให้แม่',
        hints: ['ดูภาพที่ลูกยื่นพวงมาลัยสีขาวให้แม่'],
        steps: ['ภาพวันไหว้ครูมีพานดอกไม้ให้ครู และภาพวันพ่อมีดอกไม้สีส้มให้พ่อ', 'ภาพที่ลูกมอบพวงมาลัยดอกมะลิให้แม่คือวันแม่ ตอบข้อ 2'],
        transferIds: ['g-day-mother-t'],
      },
    },
    {
      id: 'g-day-children', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันเด็ก ซึ่งเด็กๆ ได้เล่นสนุกและรับของขวัญ' },
      options: [day('a', 'children'), day('b', 'lent'), day('c', 'newyear')],
      correctOptionId: 'a',
      narration: PICS,
      review: {
        summary: 'วันเด็กแห่งชาติตรงกับวันเสาร์ที่สองของเดือนมกราคม เด็กๆ ได้เล่นสนุกและรับของขวัญ',
        hints: ['ดูภาพที่มีลูกโป่งและกลองของเด็กๆ'],
        steps: ['ภาพวันเข้าพรรษามีพระภิกษุที่วัด และภาพปีใหม่มีดอกไม้ไฟตอนกลางคืน', 'ภาพที่มีเด็กๆ ถือลูกโป่งและเล่นสนุกคือวันเด็ก ตอบข้อ 1'],
        transferIds: ['g-day-children-t'],
      },
    },
    {
      id: 'g-day-father', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันพ่อ ซึ่งลูกมอบดอกพุทธรักษาให้พ่อ' },
      options: [day('a', 'mother'), day('b', 'songkran'), day('c', 'father')],
      correctOptionId: 'c',
      narration: PICS,
      review: {
        summary: 'วันพ่อแห่งชาติตรงกับวันที่ 5 ธันวาคม ลูกมอบดอกพุทธรักษาสีเหลืองส้มให้พ่อ',
        hints: ['ดูภาพที่ลูกชายยื่นช่อดอกไม้สีเหลืองส้มให้พ่อ'],
        steps: ['ภาพวันแม่เป็นพวงมาลัยสีขาวให้แม่ และภาพวันสงกรานต์เป็นการเล่นน้ำ', 'ภาพที่ลูกมอบดอกพุทธรักษาให้พ่อคือวันพ่อ ตอบข้อ 3'],
        transferIds: ['g-day-father-t'],
      },
    },

    // ================================================================ ช่วงที่ 2: ข้อเดี่ยวจากภาพ
    {
      id: 'g-day-flower', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'day-flower', difficulty: 2,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในวันแม่ ลูกๆ นิยมมอบดอกไม้อะไรให้แม่' },
      visual: scene('mother'),
      options: words('ดอกทานตะวัน', 'ดอกมะลิ', 'ดอกพุทธรักษา'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องดอกไม้ประจำวันแม่ (ดอกมะลิ)',
      review: {
        summary: 'ดอกไม้ของวันแม่คือดอกมะลิสีขาว',
        hints: ['ดูพวงมาลัยสีขาวในภาพที่ลูกมอบให้แม่'],
        steps: ['ดอกพุทธรักษาเป็นดอกไม้ของวันพ่อ ส่วนดอกทานตะวันไม่ใช่ดอกไม้ของวันแม่', 'ดอกมะลิสีขาวเป็นดอกไม้ของวันแม่ ตอบข้อ 2'],
        transferIds: ['g-day-flower-t'],
      },
    },
    {
      id: 'g-day-water', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'manners-songkran', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในวันสงกรานต์ ข้อใดทำได้อย่างสุภาพ' },
      visual: scene('songkran'),
      options: words('รดน้ำที่มือผู้ใหญ่เบาๆ และขอพร', 'สาดน้ำใส่คนที่ไม่รู้จัก', 'สาดน้ำใส่คนที่กำลังขับรถ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดมารยาทและความปลอดภัยในวันสงกรานต์',
      review: {
        summary: 'รดน้ำที่มือผู้ใหญ่เบาๆ และขอพร เป็นประเพณีที่สุภาพ',
        hints: ['ดูว่าคุณยายในภาพถือขันน้ำ และเด็กๆ รดน้ำเบาๆ อย่างไร'],
        steps: ['สาดน้ำใส่คนที่ไม่รู้จักหรือคนที่ขับรถไม่สุภาพและอันตราย', 'รดน้ำที่มือผู้ใหญ่เบาๆ และขอพรสุภาพ ตอบข้อ 1'],
        transferIds: ['g-day-water-t'],
      },
    },
    {
      id: 'sc-day-moon', type: 'main', subject: 'science', skillIds: ['sky'], familyId: 'sky', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในภาพวันลอยกระทง ท้องฟ้ามีอะไรส่องแสงสว่างตอนกลางคืน' },
      visual: scene('loy'),
      options: words('ดวงอาทิตย์', 'รุ้ง', 'ดวงจันทร์'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องท้องฟ้ากลางคืน',
      review: {
        summary: 'ตอนกลางคืนมีดวงจันทร์ส่องแสง วันลอยกระทงพระจันทร์เต็มดวง',
        hints: ['ดูที่ท้องฟ้าด้านบนของภาพ'],
        steps: ['ดวงอาทิตย์เห็นตอนกลางวัน และรุ้งเห็นหลังฝนตกที่มีแดด', 'ตอนกลางคืนเห็นดวงจันทร์ ตอบข้อ 3'],
        transferIds: ['sc-day-moon-t'],
      },
    },
    {
      id: 'm-day-people', type: 'main', subject: 'math', skillIds: ['story-count'], familyId: 'picture-count', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในภาพวันสงกรานต์ มีคนกี่คน' },
      visual: scene('songkran'),
      options: words('3 คน', '4 คน', '5 คน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับคนในภาพ',
      review: {
        summary: 'ในภาพมีเด็กชาย 3 คนและคุณยาย 1 คน รวม 4 คน',
        hints: ['นับคนทีละคนจากซ้ายไปขวา'],
        steps: ['มีเด็กชาย 3 คน และคุณยายผมสีขาวอีก 1 คน', '3 บวก 1 เท่ากับ 4 ตอบข้อ 2'],
        column: { a: 3, op: '+', b: 1 },
        transferIds: ['m-day-people-t'],
      },
    },
    {
      id: 'sp-day-teacher', type: 'main', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 2,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในภาพวันไหว้ครู ใครอยู่ทางขวามือของภาพ' },
      visual: scene('teacher'),
      options: words('นักเรียน', 'ครู', 'ไม่มีใคร'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบอกตำแหน่งซ้ายขวาในภาพ (ซ้ายขวาของภาพ ไม่ใช่ของตัวคนในภาพ)',
      review: {
        summary: 'ครูอยู่ทางขวามือของภาพ',
        hints: ['มองภาพ แล้วดูว่าใครอยู่ด้านขวามือของเรา'],
        steps: ['นักเรียนที่คุกเข่าอยู่ทางซ้ายของภาพ', 'ครูนั่งอยู่ทางขวาของภาพ ตอบข้อ 2'],
        transferIds: ['sp-day-teacher-t'],
      },
    },

    // ================================================================ ช่วงที่ 3
    {
      id: 'm-day-newyear', type: 'main', subject: 'math', skillIds: ['date-difference'], familyId: 'date-difference', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'วันขึ้นปีใหม่คือวันที่ 1 มกราคม ถ้าวันนี้เป็นวันที่ 29 ธันวาคม อีกกี่วันจะถึงวันขึ้นปีใหม่' },
      options: words('2 วัน', '3 วัน', '4 วัน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับวันข้ามเดือน (ธันวาคมมี 31 วัน)',
      review: {
        summary: 'วันที่ 30 31 ธันวาคม และ 1 มกราคม นับได้ 3 วัน',
        hints: ['นับวันต่อไปทีละวัน ธันวาคมมี 31 วัน'],
        steps: ['อีก 1 วันเป็นวันที่ 30 อีก 2 วันเป็นวันที่ 31 ธันวาคม', 'อีก 3 วันเป็นวันที่ 1 มกราคม ตอบข้อ 2'],
        transferIds: ['m-day-newyear-t'],
      },
    },
    {
      id: 'g-day-lent', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 2,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในวันเข้าพรรษา ผู้คนนิยมนำสิ่งใดไปถวายพระ' },
      visual: scene('lent'),
      options: words('เทียนพรรษา', 'ดอกไม้ไฟ', 'กระทง'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องวันเข้าพรรษา (ผู้ปกครองควรตรวจถ้อยคำ)',
      review: {
        summary: 'วันเข้าพรรษาผู้คนนำเทียนพรรษาไปถวายพระที่วัด',
        hints: ['ดูของสูงสีทองที่ครอบครัวในภาพถวายพระ'],
        steps: ['ดอกไม้ไฟเป็นของวันปีใหม่ และกระทงเป็นของวันลอยกระทง', 'เทียนพรรษาถวายพระในวันเข้าพรรษา ตอบข้อ 1'],
        transferIds: ['g-day-lent-t'],
      },
    },
    {
      id: 'th-day-initial', type: 'main', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ภาพนี้คือ กระทง ที่ใช้ลอยในวันลอยกระทง คำว่า กระทง ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: scene('loy'),
      options: letters('ท', 'ล', 'ก'),
      correctOptionId: 'c',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก เด็กต้องรู้จักตัวอักษรเอง',
      review: {
        summary: 'กระทง ขึ้นต้นด้วย กอ ไก่',
        hints: ['ออกเสียงคำแรก กระ ช้าๆ'],
        steps: ['กระทง มีสองพยางค์ คือ กระ กับ ทง ตัว ท อยู่ในพยางค์หลัง', 'พยางค์แรกขึ้นต้นด้วย กอ ไก่ ตอบข้อ 3'],
        transferIds: ['th-day-initial-t'],
      },
    },
    {
      id: 'r-day-order', type: 'main', subject: 'reasoning', skillIds: ['date-order'], familyId: 'date-order', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ตอนนี้เป็นเดือนมีนาคม วันสงกรานต์ตรงกับ 13 เมษายน วันแม่ตรงกับ 12 สิงหาคม และวันพ่อตรงกับ 5 ธันวาคม วันใดจะมาถึงก่อน' },
      options: words('วันสงกรานต์', 'วันแม่', 'วันพ่อ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงลำดับเดือนในปี (มีนาคม เมษายน ... สิงหาคม ... ธันวาคม)',
      review: {
        summary: 'หลังมีนาคมคือเมษายน จึงถึงวันสงกรานต์ก่อน',
        hints: ['เรียงเดือนต่อจากมีนาคมไปทีละเดือน'],
        steps: ['เดือนต่อจากมีนาคมคือเมษายน แล้วจึงถึงสิงหาคมและธันวาคม', 'วันสงกรานต์อยู่เดือนเมษายน จึงมาก่อน ตอบข้อ 1'],
        transferIds: ['r-day-order-t'],
      },
    },
    {
      id: 'g-day-teacher-why', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'teacher-day', difficulty: 2,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'เหตุใดนักเรียนจึงนำพานดอกไม้ไปไหว้ครู' },
      visual: scene('teacher'),
      options: words('เพื่อให้ครูให้คะแนนเพิ่ม', 'เพื่อเล่นกับเพื่อนในห้อง', 'เพื่อแสดงความเคารพและขอบคุณครู'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจความหมายของวันไหว้ครู',
      review: {
        summary: 'นักเรียนไหว้ครูเพื่อแสดงความเคารพและขอบคุณครูที่สอนเรา',
        hints: ['นึกว่าครูทำอะไรให้เรา และเราควรตอบแทนด้วยอะไร'],
        steps: ['การไหว้ครูไม่ใช่การขอคะแนนและไม่ใช่การเล่น', 'เป็นการแสดงความเคารพและขอบคุณครู ตอบข้อ 3'],
        transferIds: ['g-day-teacher-why-t'],
      },
    },

    // ================================================================ โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'g-day-songkran-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันขึ้นปีใหม่ ซึ่งมีดอกไม้ไฟสวยงามบนท้องฟ้า' },
      options: [day('a', 'newyear'), day('b', 'songkran'), day('c', 'teacher')],
      correctOptionId: 'a',
      narration: PICS,
      review: { summary: 'วันขึ้นปีใหม่ตรงกับวันที่ 1 มกราคม มีดอกไม้ไฟ', hints: [], steps: ['ภาพวันสงกรานต์เล่นน้ำตอนกลางวัน และภาพวันไหว้ครูอยู่ในห้องเรียน', 'ภาพที่มีดอกไม้ไฟบนท้องฟ้าคือวันขึ้นปีใหม่'] },
    },
    {
      id: 'g-day-loy-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันเข้าพรรษา ซึ่งผู้คนนำเทียนพรรษาไปถวายพระที่วัด' },
      options: [day('a', 'mother'), day('b', 'lent'), day('c', 'children')],
      correctOptionId: 'b',
      narration: PICS,
      review: { summary: 'วันเข้าพรรษามีการถวายเทียนพรรษาแด่พระภิกษุที่วัด', hints: [], steps: ['ภาพวันแม่และวันเด็กไม่ได้อยู่ที่วัด', 'ภาพที่มีวัดและพระภิกษุรับเทียนคือวันเข้าพรรษา'] },
    },
    {
      id: 'g-day-mother-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันไหว้ครู ซึ่งนักเรียนนำพานดอกไม้ไปไหว้ครู' },
      options: [day('a', 'loy'), day('b', 'father'), day('c', 'teacher')],
      correctOptionId: 'c',
      narration: PICS,
      review: { summary: 'วันไหว้ครูนักเรียนนำพานดอกไม้ไปไหว้ครูในห้องเรียน', hints: [], steps: ['ภาพลอยกระทงอยู่ริมน้ำ และภาพวันพ่อมีดอกพุทธรักษา', 'ภาพที่นักเรียนคุกเข่าถือพานดอกไม้ให้ครูคือวันไหว้ครู'] },
    },
    {
      id: 'g-day-children-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันแม่' },
      options: [day('a', 'newyear'), day('b', 'lent'), day('c', 'mother')],
      correctOptionId: 'c',
      narration: PICS,
      review: { summary: 'วันแม่ลูกมอบพวงมาลัยดอกมะลิให้แม่', hints: [], steps: ['ภาพปีใหม่มีดอกไม้ไฟ และภาพเข้าพรรษามีพระภิกษุ', 'ภาพที่ลูกมอบพวงมาลัยให้แม่คือวันแม่'] },
    },
    {
      id: 'g-day-father-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS, scene: true,
      prompt: { text: 'ภาพใดเป็นวันเด็ก' },
      options: [day('a', 'songkran'), day('b', 'father'), day('c', 'children')],
      correctOptionId: 'c',
      narration: PICS,
      review: { summary: 'วันเด็กมีลูกโป่งและของเล่นให้เด็กๆ', hints: [], steps: ['ภาพวันสงกรานต์เล่นน้ำ และภาพวันพ่อมีดอกไม้ให้พ่อ', 'ภาพที่มีลูกโป่ง กลอง และของขวัญคือวันเด็ก'] },
    },
    {
      id: 'g-day-flower-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'day-flower', difficulty: 2,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในวันพ่อ ลูกๆ นิยมมอบดอกไม้อะไรให้พ่อ' },
      visual: scene('father'),
      options: words('ดอกมะลิ', 'ดอกพุทธรักษา', 'ดอกทานตะวัน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ดอกไม้ของวันพ่อคือดอกพุทธรักษา', hints: [], steps: ['ดอกมะลิเป็นดอกไม้ของวันแม่', 'ดอกพุทธรักษาสีเหลืองส้มเป็นดอกไม้ของวันพ่อ'] },
    },
    {
      id: 'g-day-water-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'manners-songkran', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในวันสงกรานต์ ข้อใดไม่ควรทำ' },
      visual: scene('songkran'),
      options: words('สาดน้ำใส่คนที่ไม่ได้เล่นด้วย', 'รดน้ำขอพรผู้ใหญ่', 'เล่นน้ำกับเพื่อนอย่างสนุก'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไม่ควรสาดน้ำใส่คนที่ไม่ได้เล่นด้วย', hints: [], steps: ['รดน้ำขอพรผู้ใหญ่และเล่นน้ำกับเพื่อนอย่างสนุกเป็นสิ่งที่ทำได้', 'การสาดน้ำใส่คนที่ไม่ได้เล่นด้วยไม่สุภาพ'] },
    },
    {
      id: 'sc-day-moon-t', type: 'transfer', subject: 'science', skillIds: ['sky'], familyId: 'sky', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในภาพวันขึ้นปีใหม่ ท้องฟ้ามีอะไรสวยงาม' },
      visual: scene('newyear'),
      options: words('ดอกไม้ไฟ', 'รุ้ง', 'ฝนตก'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ท้องฟ้ามีดอกไม้ไฟหลากสี', hints: [], steps: ['ไม่มีรุ้งและไม่มีฝนตกในภาพ', 'บนท้องฟ้ามีดอกไม้ไฟหลากสี'] },
    },
    {
      id: 'm-day-people-t', type: 'transfer', subject: 'math', skillIds: ['story-count'], familyId: 'picture-count', difficulty: 1,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในภาพวันเด็ก มีเด็กกี่คน' },
      visual: scene('children'),
      options: words('2 คน', '3 คน', '4 คน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ในภาพมีเด็ก 3 คน', hints: [], steps: ['เด็กหญิงถือตุ๊กตาอยู่ทางซ้าย เด็กชายถือลูกโป่งอยู่ตรงกลาง', 'เด็กชายตีกลองอยู่ทางขวา นับได้ 3 คน'] },
    },
    {
      id: 'sp-day-teacher-t', type: 'transfer', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 2,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในภาพวันพ่อ ใครอยู่ทางซ้ายมือของภาพ' },
      visual: scene('father'),
      options: words('คุณพ่อ', 'เด็กชาย', 'ไม่มีใคร'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เด็กชายอยู่ทางซ้ายมือของภาพ', hints: [], steps: ['คุณพ่อคุกเข่าอยู่ทางขวาของภาพ', 'เด็กชายอยู่ทางซ้ายของภาพ'] },
    },
    {
      id: 'm-day-newyear-t', type: 'transfer', subject: 'math', skillIds: ['date-difference'], familyId: 'date-difference', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'วันขึ้นปีใหม่คือวันที่ 1 มกราคม ถ้าวันนี้เป็นวันที่ 28 ธันวาคม อีกกี่วันจะถึงวันขึ้นปีใหม่' },
      options: words('3 วัน', '4 วัน', '5 วัน'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วันที่ 29 30 31 ธันวาคม และ 1 มกราคม นับได้ 4 วัน', hints: [], steps: ['อีก 3 วันเป็นวันที่ 31 ธันวาคม', 'อีก 4 วันเป็นวันที่ 1 มกราคม'] },
    },
    {
      id: 'g-day-lent-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 2,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'ในภาพวันแม่ ลูกมอบสิ่งใดให้แม่' },
      visual: scene('mother'),
      options: words('พวงมาลัยดอกมะลิ', 'เทียนพรรษา', 'กระทง'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ลูกมอบพวงมาลัยดอกมะลิให้แม่', hints: [], steps: ['เทียนพรรษาถวายพระ และกระทงใช้ลอยน้ำ', 'ในภาพลูกยื่นพวงมาลัยดอกมะลิให้แม่'] },
    },
    {
      id: 'th-day-initial-t', type: 'transfer', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ภาพนี้คือ สงกรานต์ คำว่า สงกรานต์ ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: scene('songkran'),
      options: letters('ก', 'ส', 'ม'),
      correctOptionId: 'b',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก',
      review: { summary: 'สงกรานต์ ขึ้นต้นด้วย สอ เสือ', hints: [], steps: ['สงกรานต์ มีสองพยางค์ คือ สง กับ กราน', 'พยางค์แรกขึ้นต้นด้วย สอ เสือ'] },
    },
    {
      id: 'r-day-order-t', type: 'transfer', subject: 'reasoning', skillIds: ['date-order'], familyId: 'date-order', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ตอนนี้เป็นเดือนกรกฎาคม วันสงกรานต์ตรงกับ 13 เมษายน วันแม่ตรงกับ 12 สิงหาคม และวันพ่อตรงกับ 5 ธันวาคม วันใดจะมาถึงก่อน' },
      options: words('วันสงกรานต์', 'วันแม่', 'วันพ่อ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'หลังกรกฎาคมคือสิงหาคม จึงถึงวันแม่ก่อน', hints: [], steps: ['เมษายนผ่านไปแล้ว เดือนต่อจากกรกฎาคมคือสิงหาคม', 'วันแม่อยู่เดือนสิงหาคม จึงมาก่อนวันพ่อ'] },
    },
    {
      id: 'g-day-teacher-why-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'teacher-day', difficulty: 2,
      sourceId: SRC, ...R, section: DAYS,
      prompt: { text: 'เหตุใดลูกจึงมอบพวงมาลัยดอกมะลิให้แม่ในวันแม่' },
      visual: scene('mother'),
      options: words('เพื่อให้แม่ซื้อของเล่นให้', 'เพื่อเล่นซ่อนหากับแม่', 'เพื่อแสดงความรักและขอบคุณแม่'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ลูกมอบดอกมะลิเพื่อแสดงความรักและขอบคุณแม่', hints: [], steps: ['การมอบดอกไม้ไม่ใช่การขอของเล่นหรือเล่นซ่อนหา', 'เป็นการแสดงความรักและขอบคุณแม่'] },
    },
  ],
};
