/*
 * ชุดที่ 5 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 5 และ docs/QUESTION-TYPES.md) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * รูปจากแผ่น C (design/PROMPTS-gemini-3.md) และแผ่น A/B; ภาพเทียบปริมาตร ภาพของปนกัน และเค้กตัดแบ่งวาดด้วยโค้ด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const MAP = 'ดูแผนที่และทิศ แล้วตอบคำถามให้ถูกต้อง';
const WATER = { type: 'equivalence', rows: [{ left: 'pic-jug', right: 'pic-glass', count: 4 }, { left: 'pic-bottle', right: 'pic-glass', count: 2 }] };
const WATER_TEXT = 'เหยือก 1 ใบ ใส่น้ำได้เท่ากับแก้ว 4 ใบ ขวด 1 ขวด ใส่น้ำได้เท่ากับแก้ว 2 ใบ';

export default {
  id: 'set-05',
  version: 1,
  title: 'ชุดที่ 5',
  note: 'เรียงลำดับภาพ วงจรผีเสื้อ ฤดู เทียบปริมาตร แบ่งเค้ก',
  order: [
    'r-wash-order', 'sc-butterfly-next', 'g-season-rain', 'm-ant-legs', 'th-veg-kinds',
    'sp-cake-share', 'sc-bat-night', 'r-scatter-most', 'th-word-khayan', 'g-greet-elders',
    'm-jug-bottles', 'sp-map-hospital',
  ],
  stimuli: {},
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'r-wash-order', type: 'main', subject: 'reasoning', skillIds: ['sequence-events'], familyId: 'sequence-order', difficulty: 3,
      sourceId: SRC, ...R, section: 'เรียงลำดับเหตุการณ์ให้ถูกต้อง',
      prompt: { text: 'ภาพล้างมือถูกสลับที่ ข้อใดเรียงลำดับเหตุการณ์ได้ถูกต้อง' },
      visual: { type: 'row', labels: true, items: ['pic-wash-3', 'pic-wash-1', 'pic-wash-4', 'pic-wash-2'] },
      options: [
        { id: 'a', text: 'ข ง ก ค', speech: 'ขอ งอ กอ คอ' },
        { id: 'b', text: 'ค ก ง ข', speech: 'คอ กอ งอ ขอ' },
        { id: 'c', text: 'ก ข ค ง', speech: 'กอ ขอ คอ งอ' },
      ],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ (เป็นชื่อป้ายภาพ ไม่ได้วัดการอ่าน) เด็กต้องดูภาพและเรียงลำดับเอง',
      review: {
        summary: 'มือเปื้อน เปิดน้ำล้าง ถูสบู่ แล้วเช็ดมือ เรียงได้ ข ง ก ค',
        hints: ['ภาพไหนมือยังสกปรกที่สุด ภาพไหนมือสะอาดแล้ว'],
        steps: [
          'ภาพ ข มือเปื้อนโคลน เป็นภาพแรก',
          'ภาพ ง เปิดน้ำล้างมือ ภาพ ก ถูสบู่จนมีฟอง',
          'ภาพ ค เช็ดมือด้วยผ้าเป็นภาพสุดท้าย เรียงได้ ข ง ก ค ตอบข้อ 1',
        ],
        transferIds: ['r-chicken-order-t'],
      },
    },
    {
      id: 'sc-butterfly-next', type: 'main', subject: 'science', skillIds: ['animal-lifecycle'], familyId: 'lifecycle-butterfly', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'หนอนผีเสื้อโตขึ้น จะกลายเป็นอะไรต่อไป' },
      visual: { type: 'image', asset: 'pic-caterpillar' },
      options: [{ id: 'a', image: 'pic-bfly-egg', speech: 'ไข่' }, { id: 'b', image: 'pic-bfly-adult', speech: 'ผีเสื้อ' }, { id: 'c', image: 'pic-chrysalis', speech: 'ดักแด้' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้ วัดความรู้ลำดับวงจรชีวิตผีเสื้อ',
      review: {
        summary: 'หนอนกลายเป็นดักแด้ก่อน แล้วจึงเป็นผีเสื้อ',
        hints: ['ก่อนจะเป็นผีเสื้อ หนอนต้องห่อตัวเองก่อน'],
        steps: ['ผีเสื้อวางไข่ ไข่ฟักเป็นหนอน', 'หนอนห่อตัวเป็นดักแด้ แล้วจึงออกมาเป็นผีเสื้อ ต่อจากหนอนคือดักแด้ ตอบข้อ 3'],
        transferIds: ['sc-butterfly-first-t'],
      },
    },
    {
      id: 'g-season-rain', type: 'main', subject: 'general', skillIds: ['seasons'], familyId: 'seasons', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดเป็นฤดูฝน' },
      options: [{ id: 'a', image: 'pic-season-hot', speech: '' }, { id: 'b', image: 'pic-season-rain', speech: '' }, { id: 'c', image: 'pic-season-cool', speech: '' }],
      correctOptionId: 'b',
      narration: 'ตัวเลือกอ่านแค่หมายเลข เพื่อให้เด็กดูภาพเอง',
      review: {
        summary: 'ภาพที่มีเมฆดำ ฝนตก และน้ำขังคือฤดูฝน',
        hints: ['ฤดูฝนท้องฟ้าเป็นอย่างไร'],
        steps: ['ประเทศไทยมีฤดูร้อน ฤดูฝน และฤดูหนาว', 'ภาพที่ 2 มีเมฆดำ ฝนตก และแอ่งน้ำ จึงเป็นฤดูฝน ตอบข้อ 2'],
        transferIds: ['g-season-hot-t'],
      },
    },
    {
      id: 'm-ant-legs', type: 'main', subject: 'math', skillIds: ['count-legs'], familyId: 'count-legs', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'มด 1 ตัวมี 6 ขา มด 2 ตัว มีขารวมกันกี่ขา' },
      visual: { type: 'row', items: ['pic-ant', 'pic-ant'] },
      options: [{ id: 'a', text: '8 ขา' }, { id: 'b', text: '12 ขา' }, { id: 'c', text: '16 ขา' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบวกจำนวนขา',
      review: {
        summary: '6 บวก 6 เท่ากับ 12 ขา',
        hints: ['มดแต่ละตัวมี 6 ขา บวกกัน'],
        steps: ['มด 2 ตัว ตัวละ 6 ขา จึงเป็น 6 บวก 6', 'หลักหน่วย 6 บวก 6 ได้ 12 เขียน 2 ทด 1 ได้ 12 ขา ตอบข้อ 2'],
        column: { a: 6, op: '+', b: 6 },
        transferIds: ['m-ant-chicken-legs-t'],
      },
    },
    {
      id: 'th-veg-kinds', type: 'main', subject: 'thai', skillIds: ['listening-detail'], familyId: 'listen-classify', difficulty: 2,
      sourceId: SRC, ...R, section: 'ฟังข้อความแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ป้าซื้อผักบุ้ง คะน้า และกล้วยมาจากตลาด ป้าซื้อผักมากี่ชนิด' },
      options: [{ id: 'a', text: '2 ชนิด' }, { id: 'b', text: '3 ชนิด' }, { id: 'c', text: '1 ชนิด' }],
      correctOptionId: 'a',
      narration: 'ฟังข้อความและตัวเลือกได้ วัดการฟังแล้วแยกประเภท',
      review: {
        summary: 'ผักมี 2 ชนิด คือผักบุ้งกับคะน้า',
        hints: ['กล้วยเป็นผักหรือผลไม้'],
        steps: ['ป้าซื้อผักบุ้ง คะน้า และกล้วย', 'ผักบุ้งกับคะน้าเป็นผัก ส่วนกล้วยเป็นผลไม้ ผักจึงมี 2 ชนิด ตอบข้อ 1'],
        transferIds: ['th-fruit-kinds-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'sp-cake-share', type: 'main', subject: 'spatial', skillIds: ['equal-parts'], familyId: 'equal-parts', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'แบ่งเค้กให้เพื่อน 4 คน ให้ได้คนละเท่าๆ กัน ควรตัดแบบใด' },
      options: [{ id: 'a', svg: { cut: 'halves' } }, { id: 'b', svg: { cut: 'uneven-quarters' } }, { id: 'c', svg: { cut: 'quarters' } }],
      correctOptionId: 'c',
      narration: 'ตัวเลือกอ่านแค่หมายเลข เด็กต้องดูรอยตัดเอง',
      review: {
        summary: 'ตัดเป็น 4 ชิ้นเท่าๆ กัน',
        hints: ['นับชิ้น และดูว่าทุกชิ้นใหญ่เท่ากันไหม'],
        steps: ['เพื่อน 4 คน ต้องได้ 4 ชิ้น', 'ภาพที่ 3 มี 4 ชิ้นและทุกชิ้นเท่ากัน ภาพที่ 2 มี 4 ชิ้นแต่ใหญ่ไม่เท่ากัน ตอบข้อ 3'],
        transferIds: ['sp-cake-halves-t'],
      },
    },
    {
      id: 'sc-bat-night', type: 'main', subject: 'science', skillIds: ['animal-traits'], familyId: 'nocturnal', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'สัตว์ในข้อใดออกหากินเวลากลางคืน' },
      options: [{ id: 'a', image: 'pic-bat', speech: 'ค้างคาว' }, { id: 'b', image: 'pic-chicken', speech: 'ไก่' }, { id: 'c', image: 'pic-bfly-adult', speech: 'ผีเสื้อ' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อสัตว์ได้ วัดความรู้เรื่องสัตว์',
      review: {
        summary: 'ค้างคาวออกหากินเวลากลางคืน',
        hints: ['สัตว์ตัวไหนนอนห้อยหัวตอนกลางวัน'],
        steps: ['ค้างคาวนอนห้อยหัวในถ้ำตอนกลางวัน แล้วบินออกหากินตอนกลางคืน', 'ไก่และผีเสื้อหากินตอนกลางวัน ตอบข้อ 1'],
        transferIds: ['sc-bat-when-t'],
      },
    },
    {
      id: 'r-scatter-most', type: 'main', subject: 'reasoning', skillIds: ['count-compare'], familyId: 'scatter-count', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ในภาพ สิ่งใดมีมากที่สุด' },
      visual: { type: 'scatter', items: [{ asset: 'pic-ant', count: 3 }, { asset: 'pic-leaf', count: 5 }, { asset: 'pic-egg', count: 4 }] },
      options: [{ id: 'a', image: 'pic-ant', speech: 'มด' }, { id: 'b', image: 'pic-egg', speech: 'ไข่' }, { id: 'c', image: 'pic-leaf', speech: 'ใบไม้' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อได้ เสียงไม่บอกจำนวน เด็กต้องนับจากภาพเอง',
      review: {
        summary: 'ใบไม้มีมากที่สุด 5 ใบ',
        hints: ['นับทีละอย่าง แตะนับแล้วจำไว้'],
        steps: ['นับได้ มด 3 ตัว ไข่ 4 ฟอง ใบไม้ 5 ใบ', '5 มากที่สุด ใบไม้จึงมีมากที่สุด ตอบข้อ 3'],
        transferIds: ['r-scatter-least-t'],
      },
    },
    {
      id: 'th-word-khayan', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า ขยัน หมายถึงข้อใด' },
      options: [{ id: 'a', text: 'ชอบนอนตื่นสาย' }, { id: 'b', text: 'ตั้งใจทำงานไม่ย่อท้อ' }, { id: 'c', text: 'พูดเสียงดัง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจความหมายคำ',
      review: {
        summary: 'ขยัน คือ ตั้งใจทำงานไม่ย่อท้อ',
        hints: ['คนขยันทำการบ้านอย่างไร'],
        steps: ['คนขยันจะตั้งใจทำงานจนเสร็จ ไม่ท้อ', 'ชอบนอนตื่นสายตรงข้ามกับขยัน ตอบข้อ 2'],
        transferIds: ['th-word-prayat-t'],
      },
    },
    {
      id: 'g-greet-elders', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'manners-greeting', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อพบคุณครูหรือผู้ใหญ่ เราควรทำอย่างไร' },
      options: [{ id: 'a', text: 'ยกมือไหว้' }, { id: 'b', text: 'วิ่งหนี' }, { id: 'c', text: 'ทำเป็นไม่เห็น' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดมารยาทไทย',
      review: {
        summary: 'พบผู้ใหญ่ควรยกมือไหว้',
        hints: ['คนไทยทักทายผู้ใหญ่อย่างไร'],
        steps: ['คนไทยแสดงความเคารพผู้ใหญ่ด้วยการไหว้', 'เมื่อพบคุณครูหรือผู้ใหญ่ จึงควรยกมือไหว้และพูดสวัสดี ตอบข้อ 1'],
        transferIds: ['g-thank-you-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-jug-bottles', type: 'main', subject: 'math', skillIds: ['volume-compare'], familyId: 'volume', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: `${WATER_TEXT} เหยือก 1 ใบ ใส่น้ำได้เท่ากับขวดกี่ขวด` },
      visual: WATER,
      options: [{ id: 'a', text: '1 ขวด' }, { id: 'b', text: '4 ขวด' }, { id: 'c', text: '2 ขวด' }],
      correctOptionId: 'c',
      narration: 'อ่านโจทย์และตัวเลือกได้ วัดการเทียบปริมาตรจากภาพ',
      review: {
        summary: 'เหยือก 1 ใบเท่ากับแก้ว 4 ใบ เท่ากับขวด 2 ขวด',
        hints: ['ขวด 2 ขวดเท่ากับแก้วกี่ใบ'],
        steps: ['เหยือก 1 ใบเท่ากับแก้ว 4 ใบ', 'ขวด 1 ขวดเท่ากับแก้ว 2 ใบ ขวด 2 ขวดจึงเท่ากับแก้ว 4 ใบ เท่ากับเหยือก 1 ใบ ตอบข้อ 3'],
        transferIds: ['m-bottles-glasses-t'],
      },
    },
    {
      id: 'sp-map-hospital', type: 'main', subject: 'spatial', skillIds: ['compass-direction'], familyId: 'compass-map', difficulty: 2,
      sourceId: SRC, ...R, section: MAP,
      prompt: { text: 'โรงพยาบาลอยู่ทางทิศใดของบ้าน' },
      visual: { type: 'compass-map', center: 'บ้าน', places: { north: 'ตลาด', east: 'วัด', south: 'สวน', west: 'โรงพยาบาล' } },
      options: [{ id: 'a', text: 'ทิศเหนือ' }, { id: 'b', text: 'ทิศตะวันตก' }, { id: 'c', text: 'ทิศใต้' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ เสียงไม่บอกตำแหน่งบนแผนที่',
      review: {
        summary: 'โรงพยาบาลอยู่ทางทิศตะวันตกของบ้าน',
        hints: ['ดูลูกศรบอกทิศ ข้างซ้ายคือทิศอะไร'],
        steps: ['ลูกศรบอกทิศ ข้างซ้ายคือทิศตะวันตก', 'โรงพยาบาลอยู่ข้างซ้ายของบ้าน จึงอยู่ทางทิศตะวันตก ตอบข้อ 2'],
        transferIds: ['sp-map-temple-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'r-chicken-order-t', type: 'transfer', subject: 'reasoning', skillIds: ['sequence-events'], familyId: 'sequence-order', difficulty: 2,
      sourceId: SRC, ...R, section: 'เรียงลำดับเหตุการณ์ให้ถูกต้อง',
      prompt: { text: 'ภาพถูกสลับที่ ข้อใดเรียงลำดับการเติบโตของไก่ได้ถูกต้อง' },
      visual: { type: 'row', labels: true, items: ['pic-egg', 'pic-chicken', 'pic-chick'] },
      options: [
        { id: 'a', text: 'ข ค ก', speech: 'ขอ คอ กอ' },
        { id: 'b', text: 'ก ค ข', speech: 'กอ คอ ขอ' },
        { id: 'c', text: 'ค ก ข', speech: 'คอ กอ ขอ' },
      ],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไข่ ลูกเจี๊ยบ แม่ไก่ เรียงได้ ก ค ข', hints: [], steps: ['ภาพ ก คือไข่ เกิดก่อน ภาพ ค คือลูกเจี๊ยบ', 'ภาพ ข คือแม่ไก่ที่โตแล้ว เรียงได้ ก ค ข'] },
    },
    {
      id: 'sc-butterfly-first-t', type: 'transfer', subject: 'science', skillIds: ['animal-lifecycle'], familyId: 'lifecycle-butterfly', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'วงจรชีวิตของผีเสื้อ เริ่มจากอะไร' },
      options: [{ id: 'a', image: 'pic-caterpillar', speech: 'หนอน' }, { id: 'b', image: 'pic-bfly-egg', speech: 'ไข่' }, { id: 'c', image: 'pic-chrysalis', speech: 'ดักแด้' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ผีเสื้อเริ่มจากไข่', hints: [], steps: ['ผีเสื้อวางไข่ไว้บนใบไม้', 'ไข่ฟักเป็นหนอน หนอนเป็นดักแด้ แล้วเป็นผีเสื้อ'] },
    },
    {
      id: 'g-season-hot-t', type: 'transfer', subject: 'general', skillIds: ['seasons'], familyId: 'seasons', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดเป็นฤดูร้อน' },
      options: [{ id: 'a', image: 'pic-season-cool', speech: '' }, { id: 'b', image: 'pic-season-rain', speech: '' }, { id: 'c', image: 'pic-season-hot', speech: '' }],
      correctOptionId: 'c',
      narration: 'ตัวเลือกอ่านแค่หมายเลข',
      review: { summary: 'ภาพที่แดดจ้าและหญ้าแห้งคือฤดูร้อน', hints: [], steps: ['ฤดูร้อนแดดแรง ท้องฟ้าใส หญ้าแห้ง', 'ภาพที่ 3 มีดวงอาทิตย์จ้าและหญ้าสีเหลือง'] },
    },
    {
      id: 'm-ant-chicken-legs-t', type: 'transfer', subject: 'math', skillIds: ['count-legs'], familyId: 'count-legs', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'มด 1 ตัว และไก่ 1 ตัว มีขารวมกันกี่ขา' },
      visual: { type: 'row', items: ['pic-ant', 'pic-chicken'] },
      options: [{ id: 'a', text: '6 ขา' }, { id: 'b', text: '8 ขา' }, { id: 'c', text: '10 ขา' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มด 6 ขา ไก่ 2 ขา รวม 8 ขา', hints: [], steps: ['มดมี 6 ขา ไก่มี 2 ขา', '6 บวก 2 เท่ากับ 8 ขา'], column: { a: 6, op: '+', b: 2 } },
    },
    {
      id: 'th-fruit-kinds-t', type: 'transfer', subject: 'thai', skillIds: ['listening-detail'], familyId: 'listen-classify', difficulty: 2,
      sourceId: SRC, ...R, section: 'ฟังข้อความแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'แม่ซื้อส้ม มะม่วง และแครอทมาจากตลาด แม่ซื้อผลไม้มากี่ชนิด' },
      options: [{ id: 'a', text: '1 ชนิด' }, { id: 'b', text: '2 ชนิด' }, { id: 'c', text: '3 ชนิด' }],
      correctOptionId: 'b',
      narration: 'ฟังข้อความได้',
      review: { summary: 'ผลไม้มี 2 ชนิด คือส้มกับมะม่วง', hints: [], steps: ['ส้มกับมะม่วงเป็นผลไม้', 'แครอทเป็นผัก ผลไม้จึงมี 2 ชนิด'] },
    },
    {
      id: 'sp-cake-halves-t', type: 'transfer', subject: 'spatial', skillIds: ['equal-parts'], familyId: 'equal-parts', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'แบ่งเค้กให้ 2 คน ให้ได้คนละเท่าๆ กัน ควรตัดแบบใด' },
      options: [{ id: 'a', svg: { cut: 'uneven-halves' } }, { id: 'b', svg: { cut: 'halves' } }, { id: 'c', svg: { cut: 'quarters' } }],
      correctOptionId: 'b',
      narration: 'ตัวเลือกอ่านแค่หมายเลข',
      review: { summary: 'ตัดครึ่งตรงกลางได้ 2 ชิ้นเท่ากัน', hints: [], steps: ['2 คน ต้องได้ 2 ชิ้นที่ใหญ่เท่ากัน', 'ภาพที่ 2 ตัดตรงกลางพอดี จึงได้ชิ้นเท่ากัน'] },
    },
    {
      id: 'sc-bat-when-t', type: 'transfer', subject: 'science', skillIds: ['animal-traits'], familyId: 'nocturnal', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'นกฮูกออกหากินเวลาใด' },
      options: [{ id: 'a', text: 'ตอนเช้า' }, { id: 'b', text: 'ตอนเที่ยง' }, { id: 'c', text: 'ตอนกลางคืน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'นกฮูกออกหากินตอนกลางคืน', hints: [], steps: ['นกฮูกตาโต มองเห็นในที่มืดได้ดี', 'จึงออกหากินตอนกลางคืน เหมือนค้างคาว'] },
    },
    {
      id: 'r-scatter-least-t', type: 'transfer', subject: 'reasoning', skillIds: ['count-compare'], familyId: 'scatter-count', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ในภาพ สิ่งใดมีน้อยที่สุด' },
      visual: { type: 'scatter', items: [{ asset: 'pic-ball', count: 2 }, { asset: 'pic-coin', count: 5 }, { asset: 'pic-stone', count: 3 }] },
      options: [{ id: 'a', image: 'pic-coin', speech: 'เหรียญ' }, { id: 'b', image: 'pic-ball', speech: 'ลูกบอล' }, { id: 'c', image: 'pic-stone', speech: 'ก้อนหิน' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อได้',
      review: { summary: 'ลูกบอลมีน้อยที่สุด 2 ลูก', hints: [], steps: ['นับได้ ลูกบอล 2 ลูก เหรียญ 5 เหรียญ ก้อนหิน 3 ก้อน', '2 น้อยที่สุด ลูกบอลจึงมีน้อยที่สุด'] },
    },
    {
      id: 'th-word-prayat-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-meaning', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า ประหยัด หมายถึงข้อใด' },
      options: [{ id: 'a', text: 'ใช้เงินเท่าที่จำเป็น' }, { id: 'b', text: 'ซื้อของทุกอย่างที่อยากได้' }, { id: 'c', text: 'ทิ้งอาหารที่กินไม่หมด' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ประหยัด คือ ใช้เท่าที่จำเป็น', hints: [], steps: ['คนประหยัดใช้เงินและของเท่าที่จำเป็น', 'ไม่ซื้อของเกินจำเป็น และไม่ทิ้งของเสียเปล่า'] },
    },
    {
      id: 'g-thank-you-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'manners-greeting', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อมีคนให้ของขวัญ เราควรพูดว่าอะไร' },
      options: [{ id: 'a', text: 'ขอโทษ' }, { id: 'b', text: 'ขอบคุณ' }, { id: 'c', text: 'ลาก่อน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ได้รับของควรพูดว่าขอบคุณ', hints: [], steps: ['เมื่อมีคนให้ของหรือช่วยเหลือ', 'เราควรยกมือไหว้และพูดว่าขอบคุณ'] },
    },
    {
      id: 'm-bottles-glasses-t', type: 'transfer', subject: 'math', skillIds: ['volume-compare'], familyId: 'volume', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: `${WATER_TEXT} ขวด 3 ขวด ใส่น้ำได้เท่ากับแก้วกี่ใบ` },
      visual: WATER,
      options: [{ id: 'a', text: '3 ใบ' }, { id: 'b', text: '5 ใบ' }, { id: 'c', text: '6 ใบ' }],
      correctOptionId: 'c',
      narration: 'อ่านโจทย์และตัวเลือกได้',
      review: { summary: 'ขวด 3 ขวดเท่ากับแก้ว 6 ใบ', hints: [], steps: ['ขวด 1 ขวดเท่ากับแก้ว 2 ใบ', 'ขวด 3 ขวดจึงเท่ากับ 2 บวก 2 บวก 2 เท่ากับแก้ว 6 ใบ'] },
    },
    {
      id: 'sp-map-temple-t', type: 'transfer', subject: 'spatial', skillIds: ['compass-direction'], familyId: 'compass-map', difficulty: 2,
      sourceId: SRC, ...R, section: MAP,
      prompt: { text: 'วัดอยู่ทางทิศใดของบ้าน' },
      visual: { type: 'compass-map', center: 'บ้าน', places: { north: 'วัด', east: 'สวน', south: 'ตลาด', west: 'โรงเรียน' } },
      options: [{ id: 'a', text: 'ทิศเหนือ' }, { id: 'b', text: 'ทิศใต้' }, { id: 'c', text: 'ทิศตะวันออก' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วัดอยู่ทางทิศเหนือของบ้าน', hints: [], steps: ['ข้างบนของแผนที่คือทิศเหนือ', 'วัดอยู่ข้างบนบ้าน จึงอยู่ทางทิศเหนือ'] },
    },
  ],
};
