/*
 * ชุดที่ 10 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 10) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * ใช้รูปแผ่น E (สถานที่ เครื่องใช้ไฟฟ้า ของใช้ เครื่องเขียน; design/PROMPTS-gemini-5.md)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const GRID = 'ดูภาพในตารางแล้วตอบคำถามให้ถูกต้อง';
const LETTER = 'ฟังชื่อภาพแล้วตอบคำถามให้ถูกต้อง';
const HOME = { type: 'grid', rows: [['pic-fan', 'pic-fridge', 'pic-tv'], ['pic-broom', 'pic-soap', 'pic-towel'], ['pic-pencil', 'pic-eraser', 'pic-ruler']] };

export default {
  id: 'set-10',
  version: 1,
  title: 'ชุดที่ 10',
  note: 'สถานที่ ของใช้ในบ้าน เครื่องใช้ไฟฟ้า เครื่องเขียน',
  order: [
    'th-sunday-first', 'g-temple-merit', 'm-pencil-shop', 'r-go-together', 'sc-needs-power',
    'sp-grid-right', 'sp-ruler-shape', 'r-power-cut', 'm-measure-tool', 'g-save-power',
    'th-first-letter', 'sc-fridge-cold',
  ],
  stimuli: {
    sunday: {
      section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      text: 'วันอาทิตย์ แม่พาฝนไปตลาดตอนเช้า ซื้อผักและผลไม้ แล้วไปทำบุญที่วัด ตอนบ่ายฝนไปเล่นชิงช้าที่สนามเด็กเล่น',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'th-sunday-first', type: 'main', subject: 'thai', skillIds: ['listening-sequence'], familyId: 'listen-order', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'sunday',
      prompt: { text: 'ฝนไปที่ใดเป็นที่แรก' },
      options: [{ id: 'a', image: 'pic-temple', speech: 'วัด' }, { id: 'b', image: 'pic-market', speech: 'ตลาด' }, { id: 'c', image: 'pic-playground', speech: 'สนามเด็กเล่น' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและชื่อภาพได้ วัดการฟังลำดับเหตุการณ์',
      review: {
        summary: 'ตอนเช้าฝนไปตลาดก่อน',
        hints: ['ฟังว่าตอนเช้าไปที่ไหน'],
        steps: ['เรื่องเรียงไว้ว่า ตลาดตอนเช้า แล้ววัด ตอนบ่ายสนามเด็กเล่น', 'ที่แรกคือตลาด ตอบข้อ 2'],
        transferIds: ['th-school-first-t'],
      },
    },
    {
      id: 'g-temple-merit', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'sunday',
      prompt: { text: 'ฝนกับแม่ไปทำบุญที่ใด' },
      options: [{ id: 'a', image: 'pic-school', speech: 'โรงเรียน' }, { id: 'b', image: 'pic-playground', speech: 'สนามเด็กเล่น' }, { id: 'c', image: 'pic-temple', speech: 'วัด' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้ วัดการฟังและความรู้เรื่องสถานที่ในชุมชน',
      review: {
        summary: 'คนไทยไปทำบุญที่วัด',
        hints: ['ที่ไหนมีพระสงฆ์ให้เราไปทำบุญ'],
        steps: ['เรื่องบอกว่า ไปทำบุญที่วัด', 'วัดเป็นที่ทำบุญ ตอบข้อ 3'],
        transferIds: ['g-buy-vegetables-t'],
      },
    },
    {
      id: 'm-pencil-shop', type: 'main', subject: 'math', skillIds: ['money-add'], familyId: 'money-total', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ดินสอแท่งละ 5 บาท ยางลบก้อนละ 3 บาท ซื้อดินสอ 2 แท่ง และยางลบ 1 ก้อน ต้องจ่ายเงินกี่บาท' },
      options: [{ id: 'a', text: '13 บาท' }, { id: 'b', text: '8 บาท' }, { id: 'c', text: '10 บาท' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการบวกเงินหลายขั้น',
      review: {
        summary: 'ดินสอ 2 แท่ง 10 บาท รวมยางลบเป็น 13 บาท',
        hints: ['คิดราคาดินสอ 2 แท่งก่อน'],
        steps: ['ดินสอ 2 แท่ง 5 บวก 5 เท่ากับ 10 บาท', 'รวมยางลบอีก 3 บาท 10 บวก 3 เท่ากับ 13 บาท ตอบข้อ 1'],
        column: { a: 10, op: '+', b: 3 },
        transferIds: ['m-ruler-scissors-t'],
      },
    },
    {
      id: 'r-go-together', type: 'main', subject: 'reasoning', skillIds: ['relationship'], familyId: 'pair-use', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ไม้กวาดใช้คู่กับสิ่งใด' },
      visual: { type: 'image', asset: 'pic-broom' },
      options: [{ id: 'a', image: 'pic-towel', speech: 'ผ้าเช็ดตัว' }, { id: 'b', image: 'pic-dustpan', speech: 'ที่ตักผง' }, { id: 'c', image: 'pic-ruler', speech: 'ไม้บรรทัด' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ วัดการจับคู่ของที่ใช้ด้วยกัน',
      review: {
        summary: 'กวาดขยะมารวมกัน แล้วใช้ที่ตักผงตักขึ้นมา',
        hints: ['กวาดบ้านเสร็จ เราตักขยะด้วยอะไร'],
        steps: ['ผ้าเช็ดตัวใช้หลังอาบน้ำ ไม้บรรทัดใช้วัดความยาว', 'ไม้กวาดใช้คู่กับที่ตักผง ตอบข้อ 2'],
        transferIds: ['r-pencil-pair-t'],
      },
    },
    {
      id: 'sc-needs-power', type: 'main', subject: 'science', skillIds: ['electricity'], familyId: 'electric-use', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สิ่งใดต้องใช้ไฟฟ้าจึงจะทำงานได้' },
      options: [{ id: 'a', image: 'pic-broom', speech: 'ไม้กวาด' }, { id: 'b', image: 'pic-pencil', speech: 'ดินสอ' }, { id: 'c', image: 'pic-fan', speech: 'พัดลม' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้ วัดความรู้เรื่องเครื่องใช้ไฟฟ้า',
      review: {
        summary: 'พัดลมต้องเสียบปลั๊กไฟจึงหมุนได้',
        hints: ['สิ่งไหนต้องเสียบปลั๊ก'],
        steps: ['ไม้กวาดกับดินสอใช้มือของเราทำงาน', 'พัดลมต้องใช้ไฟฟ้าจึงจะหมุนได้ ตอบข้อ 3'],
        transferIds: ['sc-no-power-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'sp-grid-right', type: 'main', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-left-right', difficulty: 2,
      sourceId: SRC, ...R, section: GRID,
      prompt: { text: 'ภาพใดอยู่ทางขวาของสบู่ ติดกันพอดี' },
      visual: HOME,
      options: [{ id: 'a', image: 'pic-towel', speech: 'ผ้าเช็ดตัว' }, { id: 'b', image: 'pic-broom', speech: 'ไม้กวาด' }, { id: 'c', image: 'pic-fridge', speech: 'ตู้เย็น' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกตำแหน่ง เด็กต้องดูตารางเอง',
      review: {
        summary: 'ทางขวาของสบู่คือผ้าเช็ดตัว',
        hints: ['หาสบู่ก่อน แล้วมองไปทางมือขวาหนึ่งช่อง'],
        steps: ['สบู่อยู่ตรงกลางตาราง ไม้กวาดอยู่ทางซ้ายของสบู่', 'ช่องทางขวาของสบู่คือผ้าเช็ดตัว ตอบข้อ 1'],
        transferIds: ['sp-grid-left-t'],
      },
    },
    {
      id: 'sp-ruler-shape', type: 'main', subject: 'spatial', skillIds: ['shape-in-objects'], familyId: 'object-shape', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ไม้บรรทัดมีรูปร่างคล้ายรูปใด' },
      visual: { type: 'image', asset: 'pic-ruler' },
      options: [{ id: 'a', text: 'วงกลม' }, { id: 'b', text: 'สี่เหลี่ยมผืนผ้า' }, { id: 'c', text: 'สามเหลี่ยม' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการมองรูปทรงในสิ่งของ',
      review: {
        summary: 'ไม้บรรทัดยาว มี 4 มุม เหมือนสี่เหลี่ยมผืนผ้า',
        hints: ['นับมุมของไม้บรรทัด'],
        steps: ['ไม้บรรทัดมี 4 มุม ด้านยาว 2 ด้าน ด้านสั้น 2 ด้าน', 'จึงคล้ายรูปสี่เหลี่ยมผืนผ้า ตอบข้อ 2'],
        transferIds: ['sp-wheel-shape-t'],
      },
    },
    {
      id: 'r-power-cut', type: 'main', subject: 'reasoning', skillIds: ['inference'], familyId: 'power-cut', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ถ้าไฟดับทั้งบ้าน สิ่งใดยังใช้งานได้' },
      options: [{ id: 'a', image: 'pic-tv', speech: 'โทรทัศน์' }, { id: 'b', image: 'pic-ricecooker', speech: 'หม้อหุงข้าว' }, { id: 'c', image: 'pic-broom', speech: 'ไม้กวาด' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้ วัดการคิดหาเหตุผล',
      review: {
        summary: 'ไม้กวาดไม่ใช้ไฟฟ้า ไฟดับก็ยังกวาดได้',
        hints: ['สิ่งไหนไม่ต้องเสียบปลั๊ก'],
        steps: ['โทรทัศน์กับหม้อหุงข้าวต้องใช้ไฟฟ้า ไฟดับจึงใช้ไม่ได้', 'ไม้กวาดใช้แรงมือ ยังใช้ได้ ตอบข้อ 3'],
        transferIds: ['r-flashlight-t'],
      },
    },
    {
      id: 'm-measure-tool', type: 'main', subject: 'math', skillIds: ['measurement'], familyId: 'measure-tool', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ถ้าจะวัดความยาวของหนังสือ ควรใช้สิ่งใด' },
      options: [{ id: 'a', image: 'pic-ruler', speech: 'ไม้บรรทัด' }, { id: 'b', image: 'pic-scissors', speech: 'กรรไกร' }, { id: 'c', image: 'pic-eraser', speech: 'ยางลบ' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ วัดความรู้เรื่องเครื่องมือวัด',
      review: {
        summary: 'ไม้บรรทัดมีขีดไว้วัดความยาว',
        hints: ['สิ่งไหนมีขีดเรียงกันไว้นับ'],
        steps: ['กรรไกรใช้ตัด ยางลบใช้ลบ', 'ไม้บรรทัดใช้วัดความยาว ตอบข้อ 1'],
        transferIds: ['m-scale-weigh-t'],
      },
    },
    {
      id: 'g-save-power', type: 'main', subject: 'general', skillIds: ['saving'], familyId: 'save-energy', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ดูโทรทัศน์เสร็จแล้ว และจะออกจากห้อง ควรทำอย่างไร' },
      options: [{ id: 'a', text: 'เปิดทิ้งไว้' }, { id: 'b', text: 'ปิดโทรทัศน์และพัดลม' }, { id: 'c', text: 'เปิดเสียงให้ดังขึ้น' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการประหยัดไฟ',
      review: {
        summary: 'ปิดเมื่อไม่ใช้ ช่วยประหยัดไฟ',
        hints: ['ถ้าไม่มีคนดู ควรเปิดไว้ไหม'],
        steps: ['เปิดทิ้งไว้ทำให้เสียไฟฟ้าเปล่าๆ', 'ออกจากห้องต้องปิดทุกอย่างที่ไม่ใช้ ตอบข้อ 2'],
        transferIds: ['g-save-water-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'th-first-letter', type: 'main', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: LETTER,
      prompt: { text: 'ภาพนี้คือ พัดลม คำว่า พัดลม ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: { type: 'image', asset: 'pic-fan' },
      options: [{ id: 'a', text: 'ม', speech: '' }, { id: 'b', text: 'ด', speech: '' }, { id: 'c', text: 'พ', speech: '' }],
      correctOptionId: 'c',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก เด็กต้องรู้จักตัวอักษรเอง',
      review: {
        summary: 'พัดลม ขึ้นต้นด้วย พอ พาน',
        hints: ['ออกเสียงคำแรก พัด ช้าๆ'],
        steps: ['พัดลม มีสองพยางค์ คือ พัด กับ ลม', 'พยางค์แรก พัด ขึ้นต้นด้วย พอ พาน ตอบข้อ 3'],
        transferIds: ['th-first-letter-t'],
      },
    },
    {
      id: 'sc-fridge-cold', type: 'main', subject: 'science', skillIds: ['food-keeping'], familyId: 'food-keeping', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เราเก็บนมและผักไว้ในตู้เย็นเพื่ออะไร' },
      visual: { type: 'image', asset: 'pic-fridge' },
      options: [{ id: 'a', text: 'ให้อาหารเย็นและไม่เสียเร็ว' }, { id: 'b', text: 'ให้อาหารร้อนขึ้น' }, { id: 'c', text: 'ให้ห้องครัวสว่าง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการเก็บรักษาอาหาร',
      review: {
        summary: 'ความเย็นช่วยให้อาหารอยู่ได้นาน',
        hints: ['นมที่วางไว้ข้างนอกนานๆ จะเป็นอย่างไร'],
        steps: ['อาหารที่วางไว้ในที่ร้อนจะบูดเสียเร็ว', 'ตู้เย็นทำให้อาหารเย็น จึงเก็บได้นานขึ้น ตอบข้อ 1'],
        transferIds: ['sc-milk-spoil-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-school-first-t', type: 'transfer', subject: 'thai', skillIds: ['listening-sequence'], familyId: 'listen-order', difficulty: 2,
      sourceId: SRC, ...R, section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ต้นตื่นนอนแล้วไปโรงเรียน ตอนเย็นไปเล่นที่สนามเด็กเล่น ต้นไปที่ใดก่อน' },
      options: [{ id: 'a', image: 'pic-playground', speech: 'สนามเด็กเล่น' }, { id: 'b', image: 'pic-school', speech: 'โรงเรียน' }, { id: 'c', image: 'pic-market', speech: 'ตลาด' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ต้นไปโรงเรียนก่อน', hints: [], steps: ['เรื่องบอกว่า ตื่นนอนแล้วไปโรงเรียน', 'สนามเด็กเล่นไปตอนเย็น จึงไปทีหลัง'] },
    },
    {
      id: 'g-buy-vegetables-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ถ้าแม่อยากซื้อผักสดๆ ควรไปที่ใด' },
      options: [{ id: 'a', image: 'pic-temple', speech: 'วัด' }, { id: 'b', image: 'pic-school', speech: 'โรงเรียน' }, { id: 'c', image: 'pic-market', speech: 'ตลาด' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ตลาดมีผักและผลไม้ขาย', hints: [], steps: ['ที่ตลาดมีแม่ค้าขายผักสด', 'จึงไปซื้อผักที่ตลาด'] },
    },
    {
      id: 'm-ruler-scissors-t', type: 'transfer', subject: 'math', skillIds: ['money-add'], familyId: 'money-total', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ไม้บรรทัดราคา 7 บาท กรรไกรราคา 12 บาท ซื้อทั้งสองอย่าง ต้องจ่ายกี่บาท' },
      options: [{ id: 'a', text: '5 บาท' }, { id: 'b', text: '19 บาท' }, { id: 'c', text: '17 บาท' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '12 บวก 7 เท่ากับ 19 บาท', hints: [], steps: ['ซื้อสองอย่าง ต้องรวมราคา', 'หลักหน่วย 2 บวก 7 ได้ 9 หลักสิบ 1 จึงได้ 19 บาท'], column: { a: 12, op: '+', b: 7 } },
    },
    {
      id: 'r-pencil-pair-t', type: 'transfer', subject: 'reasoning', skillIds: ['relationship'], familyId: 'pair-use', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'เขียนหนังสือด้วยดินสอแล้วเขียนผิด ควรใช้สิ่งใด' },
      options: [{ id: 'a', image: 'pic-eraser', speech: 'ยางลบ' }, { id: 'b', image: 'pic-broom', speech: 'ไม้กวาด' }, { id: 'c', image: 'pic-soap', speech: 'สบู่' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ดินสอใช้คู่กับยางลบ', hints: [], steps: ['เขียนผิดต้องลบออก', 'ยางลบใช้ลบรอยดินสอ'] },
    },
    {
      id: 'sc-no-power-t', type: 'transfer', subject: 'science', skillIds: ['electricity'], familyId: 'electric-use', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'สิ่งใดไม่ต้องใช้ไฟฟ้า' },
      options: [{ id: 'a', image: 'pic-tv', speech: 'โทรทัศน์' }, { id: 'b', image: 'pic-scissors', speech: 'กรรไกร' }, { id: 'c', image: 'pic-ricecooker', speech: 'หม้อหุงข้าว' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'กรรไกรใช้มือตัด ไม่ต้องเสียบปลั๊ก', hints: [], steps: ['โทรทัศน์กับหม้อหุงข้าวต้องเสียบปลั๊ก', 'กรรไกรใช้แรงมือ ไม่ต้องใช้ไฟฟ้า'] },
    },
    {
      id: 'sp-grid-left-t', type: 'transfer', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-left-right', difficulty: 2,
      sourceId: SRC, ...R, section: GRID,
      prompt: { text: 'ภาพใดอยู่ทางซ้ายของไม้บรรทัด ติดกันพอดี' },
      visual: HOME,
      options: [{ id: 'a', image: 'pic-pencil', speech: 'ดินสอ' }, { id: 'b', image: 'pic-tv', speech: 'โทรทัศน์' }, { id: 'c', image: 'pic-eraser', speech: 'ยางลบ' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ทางซ้ายของไม้บรรทัดคือยางลบ', hints: [], steps: ['ไม้บรรทัดอยู่มุมล่างด้านขวา', 'ช่องทางซ้ายติดกันคือยางลบ'] },
    },
    {
      id: 'sp-wheel-shape-t', type: 'transfer', subject: 'spatial', skillIds: ['shape-in-objects'], familyId: 'object-shape', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ล้อรถมีรูปร่างคล้ายรูปใด' },
      options: [{ id: 'a', text: 'สามเหลี่ยม' }, { id: 'b', text: 'สี่เหลี่ยม' }, { id: 'c', text: 'วงกลม' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ล้อรถกลม จึงหมุนไปได้', hints: [], steps: ['ล้อรถไม่มีมุมเลย', 'จึงคล้ายรูปวงกลม'] },
    },
    {
      id: 'r-flashlight-t', type: 'transfer', subject: 'reasoning', skillIds: ['inference'], familyId: 'power-cut', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ไฟดับตอนกลางคืน บ้านมืดมาก ควรใช้สิ่งใดให้แสงสว่าง' },
      options: [{ id: 'a', text: 'พัดลม' }, { id: 'b', text: 'ไฟฉาย' }, { id: 'c', text: 'ตู้เย็น' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไฟฉายใช้ถ่าน จึงส่องสว่างได้ตอนไฟดับ', hints: [], steps: ['พัดลมกับตู้เย็นใช้ไฟบ้าน และไม่ได้ให้แสง', 'ไฟฉายใช้ถ่าน ส่องแสงได้แม้ไฟดับ'] },
    },
    {
      id: 'm-scale-weigh-t', type: 'transfer', subject: 'math', skillIds: ['measurement'], familyId: 'measure-tool', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าอยากรู้ว่าส้มหนักเท่าไร ควรใช้สิ่งใด' },
      options: [{ id: 'a', text: 'ไม้บรรทัด' }, { id: 'b', text: 'นาฬิกา' }, { id: 'c', text: 'ตาชั่ง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ตาชั่งใช้ชั่งน้ำหนัก', hints: [], steps: ['ไม้บรรทัดวัดความยาว นาฬิกาบอกเวลา', 'ตาชั่งบอกว่าของหนักเท่าไร'] },
    },
    {
      id: 'g-save-water-t', type: 'transfer', subject: 'general', skillIds: ['saving'], familyId: 'save-energy', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ระหว่างแปรงฟัน ควรทำอย่างไรกับน้ำจากก๊อก' },
      options: [{ id: 'a', text: 'ปิดก๊อกน้ำไว้ก่อน' }, { id: 'b', text: 'เปิดน้ำไหลทิ้งไว้' }, { id: 'c', text: 'เปิดน้ำให้แรงที่สุด' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ปิดก๊อกระหว่างแปรงฟัน ช่วยประหยัดน้ำ', hints: [], steps: ['ถ้าเปิดน้ำไหลทิ้งไว้ น้ำจะหมดไปเปล่าๆ', 'จึงปิดก๊อกก่อน แล้วค่อยเปิดตอนบ้วนปาก'] },
    },
    {
      id: 'th-first-letter-t', type: 'transfer', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: LETTER,
      prompt: { text: 'ภาพนี้คือ ตู้เย็น คำว่า ตู้เย็น ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: { type: 'image', asset: 'pic-fridge' },
      options: [{ id: 'a', text: 'ย', speech: '' }, { id: 'b', text: 'ต', speech: '' }, { id: 'c', text: 'บ', speech: '' }],
      correctOptionId: 'b',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก',
      review: { summary: 'ตู้เย็น ขึ้นต้นด้วย ตอ เต่า', hints: [], steps: ['พยางค์แรกคือ ตู้', 'ตู้ ขึ้นต้นด้วย ตอ เต่า'] },
    },
    {
      id: 'sc-milk-spoil-t', type: 'transfer', subject: 'science', skillIds: ['food-keeping'], familyId: 'food-keeping', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าลืมวางนมไว้นอกตู้เย็นทั้งวันในวันที่อากาศร้อน นมจะเป็นอย่างไร' },
      options: [{ id: 'a', text: 'เย็นขึ้น' }, { id: 'b', text: 'กลายเป็นน้ำแข็ง' }, { id: 'c', text: 'บูดเสีย' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'อากาศร้อนทำให้นมบูด', hints: [], steps: ['นมที่ไม่ได้แช่เย็นจะเสียเร็ว', 'วางไว้ทั้งวันในที่ร้อน นมจึงบูดเสีย'] },
    },
  ],
};
