/*
 * ชุดที่ 2 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 2) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * รูปจากแผ่น A และแผ่น B (design/PROMPTS-gemini-1.md, -2.md), นาฬิกาและภาพเรียงแถววาดด้วยโค้ด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';

export default {
  id: 'set-02',
  version: 1,
  title: 'ชุดที่ 2',
  note: 'ครอบครัว เรียงลำดับ ลอยจม ซ้ายขวา นาฬิกา บวกลบ',
  order: [
    'th-family-count', 'g-grandpa', 'r-plant-first', 'sc-float', 'sp-row-right',
    'th-not-in-story', 'sp-clock-short', 'r-odd-car', 'sc-smell', 'g-crossing',
    'm-marbles-add', 'm-eggs-sub',
  ],
  stimuli: {
    family: {
      section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      text: 'ต้นกล้าอยู่บ้านกับพ่อ แม่ ปู่ ย่า และน้องสาว ตอนเย็นปู่พาต้นกล้าไปรดน้ำต้นไม้ ส่วนย่าทำขนมกล้วยให้ทุกคนกิน',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'th-family-count', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'family',
      prompt: { text: 'บ้านของต้นกล้ามีสมาชิกทั้งหมดกี่คน' },
      options: [{ id: 'a', text: '5 คน' }, { id: 'b', text: '6 คน' }, { id: 'c', text: '7 คน' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและตัวเลือกได้ วัดการฟังแล้วนับจากเรื่อง',
      review: {
        summary: 'บ้านของต้นกล้ามี 6 คน',
        hints: ['อย่าลืมนับต้นกล้าด้วย'],
        steps: ['คนในบ้านมี พ่อ แม่ ปู่ ย่า น้องสาว และต้นกล้าเอง', 'นับได้หนึ่ง สอง สาม สี่ ห้า หก รวม 6 คน ตอบข้อ 2'],
        transferIds: ['th-family-count-t'],
      },
    },
    {
      id: 'g-grandpa', type: 'main', subject: 'general', skillIds: ['family-relations'], familyId: 'family-relations', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'family',
      prompt: { text: 'ปู่ของต้นกล้าคือใคร' },
      options: [{ id: 'a', text: 'น้องของพ่อ' }, { id: 'b', text: 'พ่อของแม่' }, { id: 'c', text: 'พ่อของพ่อ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องคำเรียกญาติ',
      review: {
        summary: 'ปู่คือพ่อของพ่อ',
        hints: ['ปู่กับย่าเป็นพ่อแม่ของพ่อ ตากับยายเป็นพ่อแม่ของแม่'],
        steps: ['พ่อของพ่อเรียกว่าปู่ แม่ของพ่อเรียกว่าย่า', 'พ่อของแม่เรียกว่าตา ปู่จึงเป็นพ่อของพ่อ ตอบข้อ 3'],
        transferIds: ['g-grandma-t'],
      },
    },
    {
      id: 'r-plant-first', type: 'main', subject: 'reasoning', skillIds: ['sequence-events'], familyId: 'sequence', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ต้นไม้ค่อยๆ โตขึ้น ภาพใดเกิดขึ้นก่อน' },
      options: [{ id: 'a', image: 'pic-plant-seed' }, { id: 'b', image: 'pic-plant-flower' }, { id: 'c', image: 'pic-plant-sprout' }],
      correctOptionId: 'a',
      narration: 'ตัวเลือกอ่านแค่หมายเลข เด็กต้องดูภาพเอง',
      review: {
        summary: 'ปลูกเมล็ดก่อน แล้วจึงงอกและออกดอก',
        hints: ['ต้นไม้เริ่มจากอะไร'],
        steps: ['เราปลูกเมล็ดลงในดินก่อน', 'เมล็ดงอกเป็นต้นอ่อน แล้วโตจนออกดอก ภาพที่เกิดก่อนคือเมล็ด ตอบข้อ 1'],
        transferIds: ['r-egg-last-t'],
      },
    },
    {
      id: 'sc-float', type: 'main', subject: 'science', skillIds: ['float-sink'], familyId: 'float-sink', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้านำของเหล่านี้ใส่ลงในน้ำ สิ่งใดลอยน้ำได้' },
      options: [{ id: 'a', image: 'pic-stone', speech: 'ก้อนหิน' }, { id: 'b', image: 'pic-coin', speech: 'เหรียญ' }, { id: 'c', image: 'pic-leaf', speech: 'ใบไม้' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อของได้ วัดความรู้เรื่องการลอยและจม',
      review: {
        summary: 'ใบไม้เบา จึงลอยน้ำได้',
        hints: ['ของที่เบามากมักลอยน้ำ'],
        steps: ['ก้อนหินกับเหรียญหนักและแน่น จึงจมลงก้นน้ำ', 'ใบไม้เบามาก จึงลอยอยู่บนน้ำ ตอบข้อ 3'],
        transferIds: ['sc-sink-t'],
      },
    },
    {
      id: 'sp-row-right', type: 'main', subject: 'spatial', skillIds: ['left-right'], familyId: 'left-right', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพที่อยู่ถัดจากปลาไปทางขวามือคือภาพใด' },
      visual: { type: 'row', items: ['pic-cat', 'pic-fish', 'pic-bicycle', 'pic-umbrella'] },
      options: [{ id: 'a', image: 'pic-cat', speech: 'แมว' }, { id: 'b', image: 'pic-bicycle', speech: 'จักรยาน' }, { id: 'c', image: 'pic-umbrella', speech: 'ร่ม' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกตำแหน่ง เด็กต้องดูซ้ายขวาเอง',
      review: {
        summary: 'ถัดจากปลาไปทางขวามือคือจักรยาน',
        hints: ['หาปลาก่อน แล้วมองไปทางมือขวา'],
        steps: ['ภาพเรียงจากซ้ายไปขวา แมว ปลา จักรยาน ร่ม', 'ภาพที่ติดกับปลาทางขวามือคือจักรยาน ตอบข้อ 2'],
        transferIds: ['sp-row-left-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'th-not-in-story', type: 'main', subject: 'thai', skillIds: ['listening-detail'], familyId: 'not-in-story', difficulty: 1,
      sourceId: SRC, ...R, section: 'ฟังข้อความแล้วเลือกภาพที่ไม่มีในเรื่อง',
      prompt: { text: 'ที่บ้านของดาวเลี้ยงเป็ด ลูกเจี๊ยบ และปลา ภาพใดไม่มีในเรื่อง' },
      options: [{ id: 'a', image: 'pic-mouse', speech: 'หนู' }, { id: 'b', image: 'pic-duck', speech: 'เป็ด' }, { id: 'c', image: 'pic-fish', speech: 'ปลา' }],
      correctOptionId: 'a',
      narration: 'ฟังข้อความและชื่อภาพได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'ในเรื่องไม่มีหนู',
        hints: ['ฟังอีกครั้งว่าดาวเลี้ยงสัตว์อะไรบ้าง'],
        steps: ['ดาวเลี้ยงเป็ด ลูกเจี๊ยบ และปลา', 'หนูไม่ได้อยู่ในเรื่อง ตอบข้อ 1'],
        transferIds: ['th-not-in-story-t'],
      },
    },
    {
      id: 'sp-clock-short', type: 'main', subject: 'spatial', skillIds: ['read-clock-hands'], familyId: 'clock', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'เข็มสั้นของนาฬิกาชี้ที่เลขใด' },
      visual: { type: 'clock', hour: 3, minute: 0 },
      options: [{ id: 'a', text: 'เลข 12' }, { id: 'b', text: 'เลข 6' }, { id: 'c', text: 'เลข 3' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ เสียงไม่บอกว่าเข็มชี้ที่ไหน',
      review: {
        summary: 'เข็มสั้นชี้เลข 3 เป็นเวลาสามโมง',
        hints: ['เข็มสั้นคือเข็มที่สั้นกว่า'],
        steps: ['นาฬิกามีเข็มยาวกับเข็มสั้น เข็มยาวชี้เลข 12', 'เข็มสั้นชี้เลข 3 ตอบข้อ 3'],
        transferIds: ['sp-clock-long-t'],
      },
    },
    {
      id: 'r-odd-car', type: 'main', subject: 'reasoning', skillIds: ['classify'], familyId: 'odd-one-out', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดไม่เข้าพวก' },
      options: [{ id: 'a', image: 'pic-car' }, { id: 'b', image: 'pic-banana' }, { id: 'c', image: 'pic-grapes' }],
      correctOptionId: 'a',
      narration: 'ตัวเลือกอ่านแค่หมายเลข เพื่อให้เด็กดูและจัดกลุ่มเอง',
      review: {
        summary: 'รถไม่เข้าพวก เพราะกล้วยกับองุ่นเป็นผลไม้',
        hints: ['สองภาพไหนเป็นของประเภทเดียวกัน'],
        steps: ['กล้วยกับองุ่นเป็นผลไม้ กินได้', 'รถเป็นยานพาหนะ ไม่ใช่ผลไม้ จึงไม่เข้าพวก ตอบข้อ 1'],
        transferIds: ['r-odd-chair-t'],
      },
    },
    {
      id: 'sc-smell', type: 'main', subject: 'science', skillIds: ['senses'], familyId: 'senses', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เราใช้อวัยวะใดดมกลิ่น' },
      options: [{ id: 'a', text: 'ตา' }, { id: 'b', text: 'จมูก' }, { id: 'c', text: 'หู' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องประสาทสัมผัส',
      review: {
        summary: 'เราใช้จมูกดมกลิ่น',
        hints: ['เวลาได้กลิ่นขนมหอมๆ เราใช้อะไร'],
        steps: ['ตาใช้ดู หูใช้ฟัง', 'จมูกใช้ดมกลิ่น ตอบข้อ 2'],
        transferIds: ['sc-hear-t'],
      },
    },
    {
      id: 'g-crossing', type: 'main', subject: 'general', skillIds: ['road-safety'], familyId: 'road-safety', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เราควรข้ามถนนตรงไหน' },
      options: [{ id: 'a', text: 'ทางม้าลาย' }, { id: 'b', text: 'ข้างหลังรถที่จอดอยู่' }, { id: 'c', text: 'ตรงโค้งถนน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องความปลอดภัยบนถนน',
      review: {
        summary: 'ควรข้ามถนนที่ทางม้าลาย',
        hints: ['ตรงไหนที่รถต้องหยุดให้คนข้าม'],
        steps: ['หลังรถที่จอดและตรงโค้งถนน คนขับมองไม่เห็นเรา อันตรายมาก', 'ทางม้าลายเป็นที่ให้คนข้าม ข้ามพร้อมผู้ใหญ่และมองซ้ายขวาก่อน ตอบข้อ 1'],
        transferIds: ['g-traffic-light-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-marbles-add', type: 'main', subject: 'math', skillIds: ['word-problem-add'], familyId: 'add-2digit', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ต้นกล้ามีลูกแก้ว 23 ลูก เพื่อนให้อีก 14 ลูก ต้นกล้ามีลูกแก้วทั้งหมดกี่ลูก' },
      options: [{ id: 'a', text: '27 ลูก' }, { id: 'b', text: '37 ลูก' }, { id: 'c', text: '47 ลูก' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบวกเลขสองหลัก',
      review: {
        summary: '23 บวก 14 เท่ากับ 37 ลูก',
        hints: ['ได้เพิ่ม ต้องบวก บวกหลักหน่วยก่อน'],
        steps: [
          'ได้ลูกแก้วเพิ่ม จึงใช้การบวก 23 บวก 14',
          'หลักหน่วย 3 บวก 4 ได้ 7 หลักสิบ 2 บวก 1 ได้ 3',
          'ได้ 37 ลูก ตอบข้อ 2',
        ],
        column: { a: 23, op: '+', b: 14 },
        transferIds: ['m-add-crayons-t'],
      },
    },
    {
      id: 'm-eggs-sub', type: 'main', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'sub-2digit-borrow', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'แม่มีไข่ 25 ฟอง นำไปทำขนม 9 ฟอง แม่เหลือไข่กี่ฟอง' },
      options: [{ id: 'a', text: '24 ฟอง' }, { id: 'b', text: '14 ฟอง' }, { id: 'c', text: '16 ฟอง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการลบที่ต้องยืม',
      review: {
        summary: '25 ลบ 9 เท่ากับ 16 ฟอง',
        hints: ['ใช้ไปแล้วไข่น้อยลง ต้องลบ'],
        steps: [
          'นำไข่ไปใช้ ไข่น้อยลง จึงใช้การลบ 25 ลบ 9',
          'หลักหน่วย 5 ลบ 9 ไม่พอ ยืม 1 สิบ มาเป็น 15 แล้ว 15 ลบ 9 ได้ 6',
          'หลักสิบเหลือ 1 จึงได้ 16 ฟอง ตอบข้อ 3',
        ],
        column: { a: 25, op: '-', b: 9 },
        transferIds: ['m-sub-balloons-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-family-count-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-count', difficulty: 2,
      sourceId: SRC, ...R, section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ใบเตยอยู่บ้านกับพ่อ แม่ ยาย และพี่ชาย บ้านของใบเตยมีสมาชิกทั้งหมดกี่คน' },
      options: [{ id: 'a', text: '4 คน' }, { id: 'b', text: '5 คน' }, { id: 'c', text: '6 คน' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'บ้านของใบเตยมี 5 คน', hints: [], steps: ['พ่อ แม่ ยาย พี่ชาย และใบเตยเอง', 'นับได้ 5 คน'] },
    },
    {
      id: 'g-grandma-t', type: 'transfer', subject: 'general', skillIds: ['family-relations'], familyId: 'family-relations', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ยายคือใคร' },
      options: [{ id: 'a', text: 'แม่ของพ่อ' }, { id: 'b', text: 'แม่ของแม่' }, { id: 'c', text: 'พี่สาวของแม่' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ยายคือแม่ของแม่', hints: [], steps: ['แม่ของพ่อเรียกว่าย่า', 'แม่ของแม่เรียกว่ายาย'] },
    },
    {
      id: 'r-egg-last-t', type: 'transfer', subject: 'reasoning', skillIds: ['sequence-events'], familyId: 'sequence', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ไก่ค่อยๆ โตขึ้น ภาพใดเกิดขึ้นหลังสุด' },
      options: [{ id: 'a', image: 'pic-egg' }, { id: 'b', image: 'pic-chick' }, { id: 'c', image: 'pic-chicken' }],
      correctOptionId: 'c',
      narration: 'ตัวเลือกอ่านแค่หมายเลข',
      review: { summary: 'ไข่ฟักเป็นลูกเจี๊ยบ แล้วโตเป็นแม่ไก่', hints: [], steps: ['เริ่มจากไข่ ฟักออกมาเป็นลูกเจี๊ยบ', 'ลูกเจี๊ยบโตเป็นไก่ ภาพหลังสุดคือแม่ไก่'] },
    },
    {
      id: 'sc-sink-t', type: 'transfer', subject: 'science', skillIds: ['float-sink'], familyId: 'float-sink', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้านำของเหล่านี้ใส่ลงในน้ำ สิ่งใดจมน้ำ' },
      options: [{ id: 'a', image: 'pic-ball', speech: 'ลูกบอล' }, { id: 'b', image: 'pic-leaf', speech: 'ใบไม้' }, { id: 'c', image: 'pic-coin', speech: 'เหรียญ' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อของได้',
      review: { summary: 'เหรียญหนักและแน่น จึงจมน้ำ', hints: [], steps: ['ลูกบอลมีลมอยู่ข้างใน ใบไม้เบา จึงลอย', 'เหรียญเป็นโลหะหนัก จึงจม'] },
    },
    {
      id: 'sp-row-left-t', type: 'transfer', subject: 'spatial', skillIds: ['left-right'], familyId: 'left-right', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพที่อยู่ถัดจากเป็ดไปทางซ้ายมือคือภาพใด' },
      visual: { type: 'row', items: ['pic-banana', 'pic-car', 'pic-duck', 'pic-orange'] },
      options: [{ id: 'a', image: 'pic-banana', speech: 'กล้วย' }, { id: 'b', image: 'pic-car', speech: 'รถ' }, { id: 'c', image: 'pic-orange', speech: 'ส้ม' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ถัดจากเป็ดไปทางซ้ายมือคือรถ', hints: [], steps: ['ภาพเรียงจากซ้ายไปขวา กล้วย รถ เป็ด ส้ม', 'ภาพที่ติดกับเป็ดทางซ้ายมือคือรถ'] },
    },
    {
      id: 'th-not-in-story-t', type: 'transfer', subject: 'thai', skillIds: ['listening-detail'], familyId: 'not-in-story', difficulty: 1,
      sourceId: SRC, ...R, section: 'ฟังข้อความแล้วเลือกภาพที่ไม่มีในเรื่อง',
      prompt: { text: 'แม่ซื้อกล้วย องุ่น และแตงโมมาให้ฉันกิน ภาพใดไม่มีในเรื่อง' },
      options: [{ id: 'a', image: 'pic-banana', speech: 'กล้วย' }, { id: 'b', image: 'pic-carrot', speech: 'แครอท' }, { id: 'c', image: 'pic-grapes', speech: 'องุ่น' }],
      correctOptionId: 'b',
      narration: 'ฟังข้อความและชื่อภาพได้',
      review: { summary: 'ในเรื่องไม่มีแครอท', hints: [], steps: ['แม่ซื้อกล้วย องุ่น และแตงโม', 'แครอทไม่ได้อยู่ในเรื่อง'] },
    },
    {
      id: 'sp-clock-long-t', type: 'transfer', subject: 'spatial', skillIds: ['read-clock-hands'], familyId: 'clock', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'เข็มยาวของนาฬิกาชี้ที่เลขใด' },
      visual: { type: 'clock', hour: 9, minute: 30 },
      options: [{ id: 'a', text: 'เลข 6' }, { id: 'b', text: 'เลข 9' }, { id: 'c', text: 'เลข 12' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เข็มยาวชี้เลข 6', hints: [], steps: ['เข็มยาวคือเข็มที่ยาวกว่า', 'เข็มยาวชี้ลงข้างล่างที่เลข 6'] },
    },
    {
      id: 'r-odd-chair-t', type: 'transfer', subject: 'reasoning', skillIds: ['classify'], familyId: 'odd-one-out', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพใดไม่เข้าพวก' },
      options: [{ id: 'a', image: 'pic-cat' }, { id: 'b', image: 'pic-chair' }, { id: 'c', image: 'pic-elephant' }],
      correctOptionId: 'b',
      narration: 'ตัวเลือกอ่านแค่หมายเลข',
      review: { summary: 'เก้าอี้ไม่เข้าพวก เพราะแมวกับช้างเป็นสัตว์', hints: [], steps: ['แมวกับช้างเป็นสัตว์ มีชีวิต', 'เก้าอี้เป็นสิ่งของ จึงไม่เข้าพวก'] },
    },
    {
      id: 'sc-hear-t', type: 'transfer', subject: 'science', skillIds: ['senses'], familyId: 'senses', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เราใช้อวัยวะใดฟังเสียง' },
      options: [{ id: 'a', text: 'จมูก' }, { id: 'b', text: 'ตา' }, { id: 'c', text: 'หู' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เราใช้หูฟังเสียง', hints: [], steps: ['จมูกใช้ดมกลิ่น ตาใช้ดู', 'หูใช้ฟังเสียง'] },
    },
    {
      id: 'g-traffic-light-t', type: 'transfer', subject: 'general', skillIds: ['road-safety'], familyId: 'road-safety', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อไฟจราจรเป็นสีแดง รถต้องทำอย่างไร' },
      options: [{ id: 'a', text: 'ขับต่อไป' }, { id: 'b', text: 'หยุดรอ' }, { id: 'c', text: 'ขับให้เร็วขึ้น' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไฟแดงรถต้องหยุดรอ', hints: [], steps: ['ไฟแดงแปลว่าหยุด ไฟเขียวแปลว่าไปได้', 'รถจึงต้องหยุดรอจนไฟเขียว'] },
    },
    {
      id: 'm-add-crayons-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-add'], familyId: 'add-2digit', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีสีเทียน 32 แท่ง ซื้อเพิ่มอีก 15 แท่ง มีสีเทียนทั้งหมดกี่แท่ง' },
      options: [{ id: 'a', text: '37 แท่ง' }, { id: 'b', text: '47 แท่ง' }, { id: 'c', text: '57 แท่ง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '32 บวก 15 เท่ากับ 47 แท่ง', hints: [], steps: ['ซื้อเพิ่มต้องบวก 32 บวก 15', 'หลักหน่วย 2 บวก 5 ได้ 7 หลักสิบ 3 บวก 1 ได้ 4 รวมเป็น 47'], column: { a: 32, op: '+', b: 15 } },
    },
    {
      id: 'm-sub-balloons-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'sub-2digit-borrow', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'มีลูกโป่ง 31 ลูก ลูกโป่งแตกไป 7 ลูก เหลือลูกโป่งกี่ลูก' },
      options: [{ id: 'a', text: '22 ลูก' }, { id: 'b', text: '24 ลูก' }, { id: 'c', text: '26 ลูก' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '31 ลบ 7 เท่ากับ 24 ลูก', hints: [], steps: ['ลูกโป่งแตก เหลือน้อยลง ต้องลบ 31 ลบ 7', 'หลักหน่วย 1 ลบ 7 ไม่พอ ยืม 1 สิบ เป็น 11 ลบ 7 ได้ 4 หลักสิบเหลือ 2 ได้ 24'], column: { a: 31, op: '-', b: 7 } },
    },
  ],
};
