/*
 * ชุดที่ 14 — รูปแบบใหม่ 15 ข้อ (ดู docs/QUESTION-TYPES.md หัวข้อ "รูปแบบชุด 12 ขึ้นไป")
 * ช่วง 1 เรื่องไปเที่ยวน้ำตก ตอบเป็นภาพ 4 ตัวเลือก / ช่วง 2 แผ่นรูปของใช้ในครัว / ช่วง 3 เลขหลายขั้น ภาพต่อเนื่อง ต้นไม้ ความรู้สึก
 * ใช้รูปแผ่น G (design/PROMPTS-gemini-7.md); แต่งใหม่ทั้งหมด ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพจากข้อสอบเก่า
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LISTEN = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const BOARD_SECTION = 'ดูภาพของใช้แล้วตอบคำถามให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const SHORT = 'ฟังข้อความแล้วตอบคำถามให้ถูกต้อง';
const BOARD = { type: 'board', items: ['pic-knife', 'pic-scissors', 'pic-mortar', 'pic-pot', 'pic-plate', 'pic-spoon', 'pic-wok', 'pic-broom', 'pic-pencil', 'pic-towel', 'pic-ball', 'pic-soap'] };
const BOARD_TEXT = 'ในภาพมีของ 12 อย่าง คือ มีด กรรไกร ครกกับสาก หม้อ จาน ช้อน กระทะ ไม้กวาด ดินสอ ผ้าเช็ดตัว ลูกบอล และสบู่';
const PEOPLE = [{ id: 'a', image: 'pic-grandpa', speech: 'คุณตา' }, { id: 'b', image: 'pic-grandma', speech: 'คุณยาย' }, { id: 'c', image: 'pic-father', speech: 'คุณพ่อ' }, { id: 'd', image: 'pic-mother', speech: 'คุณแม่' }];

export default {
  id: 'set-14',
  version: 1,
  title: 'ชุดที่ 14',
  note: 'แบบใหม่ 15 ข้อ: เที่ยวน้ำตก ของใช้ในครัว ภาพต่อเนื่อง',
  order: [
    'th-trip-where', 'th-trip-who', 'sc-trip-bamboo', 'r-trip-not', 'g-trip-trash',
    'g-board-sharp', 'r-board-eat', 'sp-board-round', 'm-board-bathroom', 'th-board-mortar',
    'm-marbles-steps', 'sp-dots-down', 'sp-wheel-jump', 'sc-coconut-drink', 'th-feeling-sorry',
  ],
  stimuli: {
    waterfall: {
      section: LISTEN,
      text: 'ปิดเทอมนี้ คุณตากับคุณยายพาฝ้ายไปเที่ยวน้ำตกบนภูเขา ระหว่างทางมีต้นไผ่ขึ้นเป็นกอใหญ่ และมีกระรอกวิ่งไปมาบนกิ่งไม้ พอถึงน้ำตก ฝ้ายเล่นน้ำกับคุณตา ส่วนคุณยายนั่งรอพร้อมข้าวเหนียวกับไก่ย่าง ก่อนกลับ ฝ้ายเก็บถุงขนมของตัวเองใส่กระเป๋า เพราะไม่อยากทิ้งขยะไว้ในป่า',
    },
    kitchen: { section: BOARD_SECTION, text: BOARD_TEXT, visual: BOARD },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: เรื่องเดียว 5 ข้อ ตอบเป็นภาพ
    {
      id: 'th-trip-where', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-where', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'waterfall',
      prompt: { text: 'ฝ้ายไปเที่ยวที่ไหน' },
      options: [{ id: 'a', image: 'pic-beach', speech: 'ทะเล' }, { id: 'b', image: 'pic-market', speech: 'ตลาด' }, { id: 'c', image: 'pic-waterfall', speech: 'น้ำตก' }, { id: 'd', image: 'pic-ricefield', speech: 'ทุ่งนา' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องและชื่อภาพได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'ฝ้ายไปเที่ยวน้ำตกบนภูเขา',
        hints: ['ฟังประโยคแรกของเรื่อง'],
        steps: ['ต้นเรื่องบอกว่า พาฝ้ายไปเที่ยวน้ำตกบนภูเขา', 'ภาพน้ำตกคือข้อ 3 ตอบข้อ 3'],
        transferIds: ['th-ricefield-where-t'],
      },
    },
    {
      id: 'th-trip-who', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-who', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'waterfall',
      prompt: { text: 'ใครเล่นน้ำกับฝ้าย' },
      options: PEOPLE,
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ วัดการฟังว่าใครทำอะไร',
      review: {
        summary: 'ฝ้ายเล่นน้ำกับคุณตา คุณยายนั่งรอ',
        hints: ['เรื่องมีคุณตากับคุณยาย ใครเล่นน้ำ ใครนั่งรอ'],
        steps: ['เรื่องบอกว่า ฝ้ายเล่นน้ำกับคุณตา ส่วนคุณยายนั่งรอ', 'คนที่เล่นน้ำด้วยคือคุณตา ตอบข้อ 1'],
        transferIds: ['th-market-who-t'],
      },
    },
    {
      id: 'sc-trip-bamboo', type: 'main', subject: 'science', skillIds: ['plants'], familyId: 'trees', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'waterfall',
      prompt: { text: 'ระหว่างทาง มีต้นไม้ชนิดใดขึ้นเป็นกอใหญ่' },
      options: [{ id: 'a', image: 'pic-coconut-tree', speech: 'ต้นมะพร้าว' }, { id: 'b', image: 'pic-banana-tree', speech: 'ต้นกล้วย' }, { id: 'c', image: 'pic-mango-tree', speech: 'ต้นมะม่วง' }, { id: 'd', image: 'pic-bamboo', speech: 'ต้นไผ่' }],
      correctOptionId: 'd',
      narration: 'อ่านชื่อภาพได้ วัดการฟังและรู้จักต้นไม้',
      review: {
        summary: 'ต้นไผ่ขึ้นเป็นกอ มีลำต้นหลายต้นอยู่ด้วยกัน',
        hints: ['ต้นไม้ชนิดไหนมีลำต้นยาวๆ หลายต้นขึ้นรวมกัน'],
        steps: ['เรื่องบอกว่า ระหว่างทางมีต้นไผ่ขึ้นเป็นกอใหญ่', 'ภาพต้นไผ่คือข้อ 4 ตอบข้อ 4'],
        transferIds: ['sc-banana-leaf-t'],
      },
    },
    {
      id: 'r-trip-not', type: 'main', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'waterfall',
      prompt: { text: 'สิ่งใด ไม่ได้ กล่าวถึงในเรื่องนี้' },
      options: [{ id: 'a', text: 'กระรอก' }, { id: 'b', text: 'ข้าวเหนียว' }, { id: 'c', text: 'ปลา' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ วัดการฟังรายละเอียดและคำว่า ไม่ได้',
      review: {
        summary: 'เรื่องไม่ได้พูดถึงปลาเลย',
        hints: ['ลองนึกว่าเรื่องพูดถึงอะไรบ้าง แล้วหาสิ่งที่ไม่มี'],
        steps: ['เรื่องพูดถึงกระรอกบนกิ่งไม้ และข้าวเหนียวกับไก่ย่างของคุณยาย', 'ไม่มีตอนไหนพูดถึงปลา ตอบข้อ 3'],
        transferIds: ['r-zoo-not-t'],
      },
    },
    {
      id: 'g-trip-trash', type: 'main', subject: 'general', skillIds: ['environment'], familyId: 'story-why-good', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'waterfall',
      prompt: { text: 'ทำไมฝ้ายจึงเก็บถุงขนมใส่กระเป๋า' },
      options: [{ id: 'a', text: 'เพราะไม่อยากทิ้งขยะไว้ในป่า' }, { id: 'b', text: 'เพราะจะเอาไปขาย' }, { id: 'c', text: 'เพราะถุงสวย' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการฟังเหตุผลและการรักษาสิ่งแวดล้อม',
      review: {
        summary: 'ฝ้ายไม่ทิ้งขยะไว้ในป่า เก็บกลับไปทิ้งเอง',
        hints: ['ฟังคำว่า เพราะ ตอนท้ายเรื่อง'],
        steps: ['เรื่องบอกว่า ฝ้ายเก็บถุงขนมเพราะไม่อยากทิ้งขยะไว้ในป่า', 'ขยะในป่าทำให้ป่าสกปรกและสัตว์อาจกินเข้าไป ตอบข้อ 1'],
        transferIds: ['g-park-trash-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: แผ่นรูปของใช้ 5 ข้อ
    {
      id: 'g-board-sharp', type: 'main', subject: 'general', skillIds: ['safety'], familyId: 'board-sharp', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'kitchen',
      prompt: { text: 'ข้อใดเป็นของมีคม ต้องใช้อย่างระวัง' },
      options: [{ id: 'a', text: 'จาน, ช้อน' }, { id: 'b', text: 'มีด, กรรไกร' }, { id: 'c', text: 'ลูกบอล, ผ้าเช็ดตัว' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มและความปลอดภัย',
      review: {
        summary: 'มีดกับกรรไกรมีคม อาจบาดมือได้',
        hints: ['ของอะไรใช้ตัดหรือหั่นได้'],
        steps: ['จาน ช้อน ลูกบอล และผ้าเช็ดตัว ไม่มีคม', 'มีดกับกรรไกรมีคม ต้องใช้อย่างระวัง ตอบข้อ 2'],
        transferIds: ['g-board-chop-t'],
      },
    },
    {
      id: 'r-board-eat', type: 'main', subject: 'reasoning', skillIds: ['relationship'], familyId: 'board-pair', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'kitchen',
      prompt: { text: 'ของสองอย่างในข้อใดใช้ด้วยกันตอนกินข้าว' },
      options: [{ id: 'a', text: 'ครก, ไม้กวาด' }, { id: 'b', text: 'ดินสอ, สบู่' }, { id: 'c', text: 'จาน, ช้อน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการจับคู่ของที่ใช้ด้วยกัน',
      review: {
        summary: 'ตักข้าวใส่จาน แล้วใช้ช้อนตักกิน',
        hints: ['ตอนกินข้าวเราใช้อะไรบ้าง'],
        steps: ['ครก ไม้กวาด ดินสอ สบู่ ไม่ได้ใช้ตอนกินข้าว', 'จานกับช้อนใช้ด้วยกันตอนกินข้าว ตอบข้อ 3'],
        transferIds: ['r-board-pound-t'],
      },
    },
    {
      id: 'sp-board-round', type: 'main', subject: 'spatial', skillIds: ['shape-in-objects'], familyId: 'board-shape', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'kitchen',
      prompt: { text: 'ข้อใดมีรูปร่างกลมทั้งสองอย่าง' },
      options: [{ id: 'a', text: 'จาน, ลูกบอล' }, { id: 'b', text: 'มีด, ดินสอ' }, { id: 'c', text: 'ไม้กวาด, กรรไกร' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการมองรูปทรงของสิ่งของ',
      review: {
        summary: 'จานกลมแบน ลูกบอลกลมทั้งลูก',
        hints: ['ดูภาพว่าชิ้นไหนกลมไม่มีมุม'],
        steps: ['มีด ดินสอ ไม้กวาด กรรไกร เป็นแท่งยาว', 'จานกับลูกบอลมีรูปร่างกลม ตอบข้อ 1'],
        transferIds: ['sp-board-long-t'],
      },
    },
    {
      id: 'm-board-bathroom', type: 'main', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'kitchen',
      prompt: { text: 'ในภาพมีของที่ใช้ตอนอาบน้ำกี่อย่าง' },
      options: [{ id: 'a', text: '1 อย่าง' }, { id: 'b', text: '2 อย่าง' }, { id: 'c', text: '3 อย่าง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มแล้วนับ',
      review: {
        summary: 'สบู่กับผ้าเช็ดตัว ใช้ตอนอาบน้ำ 2 อย่าง',
        hints: ['ตอนอาบน้ำเราใช้อะไรถูตัว และใช้อะไรเช็ดตัว'],
        steps: ['อาบน้ำใช้สบู่ถูตัว แล้วใช้ผ้าเช็ดตัวเช็ดให้แห้ง', 'นับได้ 2 อย่าง ตอบข้อ 2'],
        transferIds: ['m-board-sharp-count-t'],
      },
    },
    {
      id: 'th-board-mortar', type: 'main', subject: 'thai', skillIds: ['pair-words'], familyId: 'pair-words', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'kitchen',
      prompt: { text: 'ครก ใช้คู่กับสิ่งใด' },
      options: [{ id: 'a', text: 'ช้อน' }, { id: 'b', text: 'จาน' }, { id: 'c', text: 'สาก' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้ วัดคำที่มักใช้คู่กัน',
      review: {
        summary: 'ใช้สากตำของในครก เราจึงพูดว่า ครกกับสาก',
        hints: ['ดูภาพครก มีไม้แท่งหนึ่งอยู่ในครก ไม้นั้นเรียกว่าอะไร'],
        steps: ['ไม้ที่ใช้ตำของในครกเรียกว่า สาก', 'ครกจึงใช้คู่กับสาก ตอบข้อ 3'],
        transferIds: ['th-spoon-fork-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-marbles-steps', type: 'main', subject: 'math', skillIds: ['multi-step'], familyId: 'multi-step', difficulty: 3,
      sourceId: SRC, ...R, section: 'ฟังโจทย์แล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ต้นมีลูกแก้ว 7 ลูก ให้น้องไป 3 ลูก แล้วพ่อซื้อให้อีก 5 ลูก ตอนนี้ต้นมีลูกแก้วกี่ลูก' },
      options: [{ id: 'a', text: '9 ลูก' }, { id: 'b', text: '15 ลูก' }, { id: 'c', text: '5 ลูก' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการคิดสองขั้น ลบแล้วบวก',
      review: {
        summary: 'ให้น้องไปเหลือ 4 ลูก ได้เพิ่ม 5 ลูก รวมเป็น 9 ลูก',
        hints: ['ทำทีละขั้น ให้น้องก่อน แล้วค่อยได้เพิ่ม'],
        steps: ['ให้น้องไป ลูกแก้วน้อยลง 7 ลบ 3 เหลือ 4 ลูก', 'พ่อซื้อให้เพิ่ม 4 บวก 5 เท่ากับ 9 ลูก ตอบข้อ 1'],
        transferIds: ['m-snack-steps-t'],
      },
    },
    {
      id: 'sp-dots-down', type: 'main', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'dots-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'จำนวนจุดลดลงทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ dots: 9 }, { dots: 7 }, { dots: 5 }, '?'] },
      options: [{ id: 'a', svg: { figure: { dots: 4 } } }, { id: 'b', svg: { figure: { dots: 1 } } }, { id: 'c', svg: { figure: { dots: 3 } } }, { id: 'd', svg: { figure: { dots: 2 } } }],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหาแบบรูปของจำนวนที่ลดลง',
      review: {
        summary: 'จุดลดลงทีละ 2 คือ 9 7 5 3',
        hints: ['นับจุดในแต่ละภาพ แล้วดูว่าลดลงทีละเท่าไร'],
        steps: ['ภาพแรกมี 9 จุด แล้วเป็น 7 จุด แล้วเป็น 5 จุด ลดลงทีละ 2', 'ภาพต่อไปจึงมี 3 จุด ตอบข้อ 3'],
        transferIds: ['sp-dots-down-t'],
      },
    },
    {
      id: 'sp-wheel-jump', type: 'main', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'wheel-sequence', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ช่องที่ระบายสีเลื่อนไปทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ wheel: 0 }, { wheel: 3 }, { wheel: 6 }, '?'] },
      options: [{ id: 'a', svg: { figure: { wheel: 4 } } }, { id: 'b', svg: { figure: { wheel: 7 } } }, { id: 'c', svg: { figure: { wheel: 2 } } }, { id: 'd', svg: { figure: { wheel: 1 } } }],
      correctOptionId: 'd',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหาแบบรูปของการหมุนที่ข้ามช่อง',
      review: {
        summary: 'ช่องสีดำเลื่อนตามเข็มนาฬิกาทีละ 3 ช่อง',
        hints: ['นับว่าจากภาพแรกไปภาพที่สอง ช่องสีดำข้ามไปกี่ช่อง'],
        steps: ['จากด้านบนเลื่อนตามเข็มนาฬิกา 3 ช่อง ไปอยู่ด้านล่างขวา แล้วอีก 3 ช่องไปอยู่ด้านซ้าย', 'เลื่อนอีก 3 ช่อง ผ่านด้านบนซ้าย ด้านบน ไปหยุดที่ด้านบนขวา ตอบข้อ 4'],
        transferIds: ['sp-wheel-jump-t'],
      },
    },
    {
      id: 'sc-coconut-drink', type: 'main', subject: 'science', skillIds: ['plants'], familyId: 'trees', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ต้นไม้ชนิดใดให้ผลที่มีน้ำอยู่ข้างใน ดื่มได้' },
      options: [{ id: 'a', image: 'pic-banana-tree', speech: 'ต้นกล้วย' }, { id: 'b', image: 'pic-coconut-tree', speech: 'ต้นมะพร้าว' }, { id: 'c', image: 'pic-mango-tree', speech: 'ต้นมะม่วง' }, { id: 'd', image: 'pic-bamboo', speech: 'ต้นไผ่' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ วัดความรู้เรื่องพืช',
      review: {
        summary: 'ลูกมะพร้าวมีน้ำมะพร้าวอยู่ข้างใน',
        hints: ['ผลไม้อะไรที่เจาะแล้วใช้หลอดดูดน้ำได้'],
        steps: ['กล้วยและมะม่วงมีเนื้อ ไม่มีน้ำให้ดื่ม ไผ่ไม่มีผลให้กิน', 'ลูกมะพร้าวมีน้ำอยู่ข้างใน ดื่มได้ ตอบข้อ 2'],
        transferIds: ['sc-mango-sweet-t'],
      },
    },
    {
      id: 'th-feeling-sorry', type: 'main', subject: 'thai', skillIds: ['feelings'], familyId: 'feelings', difficulty: 2,
      sourceId: SRC, ...R, section: SHORT,
      prompt: { text: 'ต้นทำแก้วน้ำของแม่ตกแตก แล้วรีบไปบอกแม่ว่า ขอโทษครับ ต้นรู้สึกอย่างไร' },
      options: [{ id: 'a', text: 'ดีใจ' }, { id: 'b', text: 'เสียใจ' }, { id: 'c', text: 'ภูมิใจ' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ วัดการเข้าใจความรู้สึกจากเหตุการณ์',
      review: {
        summary: 'ทำของแม่แตก ต้นจึงเสียใจและขอโทษ',
        hints: ['ถ้าหนูทำของคนอื่นแตก หนูรู้สึกอย่างไร'],
        steps: ['ต้นทำแก้วของแม่แตก และพูดว่าขอโทษ', 'คนที่ขอโทษเพราะทำผิดจะรู้สึกเสียใจ ตอบข้อ 2'],
        transferIds: ['th-feeling-happy-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-ricefield-where-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-where', difficulty: 1,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'วันหยุด ลุงพาบัวไปดูชาวนาปลูกข้าว บัวเห็นควายเดินอยู่กลางนา บัวไปที่ไหน' },
      options: [{ id: 'a', image: 'pic-beach', speech: 'ทะเล' }, { id: 'b', image: 'pic-waterfall', speech: 'น้ำตก' }, { id: 'c', image: 'pic-mountain', speech: 'ภูเขา' }, { id: 'd', image: 'pic-ricefield', speech: 'ทุ่งนา' }],
      correctOptionId: 'd',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ชาวนาปลูกข้าวในทุ่งนา', hints: [], steps: ['เรื่องบอกว่าไปดูชาวนาปลูกข้าว และเห็นควายกลางนา', 'ที่นั่นคือทุ่งนา'] },
    },
    {
      id: 'th-market-who-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'story-who', difficulty: 2,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ตอนเช้า คุณแม่พาตาลไปซื้อผักที่ตลาด ส่วนคุณพ่อไปทำงาน ใครไปตลาดกับตาล' },
      options: PEOPLE,
      correctOptionId: 'd',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'คุณแม่พาตาลไปตลาด', hints: [], steps: ['เรื่องบอกว่า คุณแม่พาตาลไปซื้อผัก คุณพ่อไปทำงาน', 'คนที่ไปตลาดด้วยคือคุณแม่'] },
    },
    {
      id: 'sc-banana-leaf-t', type: 'transfer', subject: 'science', skillIds: ['plants'], familyId: 'trees', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ต้นไม้ชนิดใดมีใบใหญ่ ใช้ห่อขนมได้' },
      options: [{ id: 'a', image: 'pic-bamboo', speech: 'ต้นไผ่' }, { id: 'b', image: 'pic-banana-tree', speech: 'ต้นกล้วย' }, { id: 'c', image: 'pic-coconut-tree', speech: 'ต้นมะพร้าว' }, { id: 'd', image: 'pic-mango-tree', speech: 'ต้นมะม่วง' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ใบตองจากต้นกล้วยใช้ห่อขนม', hints: [], steps: ['ใบกล้วยกว้างและใหญ่ เรียกว่าใบตอง', 'คนไทยใช้ใบตองห่อขนม'] },
    },
    {
      id: 'r-zoo-not-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 3,
      sourceId: SRC, ...R, section: LISTEN,
      prompt: { text: 'ต้นไปสวนสัตว์ เห็นช้างกินหญ้า ยีราฟกินใบไม้ และลิงห้อยโหนต้นไม้ สัตว์ใด ไม่ได้ กล่าวถึงในเรื่อง' },
      options: [{ id: 'a', text: 'ช้าง' }, { id: 'b', text: 'เสือ' }, { id: 'c', text: 'ลิง' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'เรื่องมีช้าง ยีราฟ ลิง ไม่มีเสือ', hints: [], steps: ['เรื่องพูดถึงช้าง ยีราฟ และลิง', 'เสือไม่ได้อยู่ในเรื่อง'] },
    },
    {
      id: 'g-park-trash-t', type: 'transfer', subject: 'general', skillIds: ['environment'], familyId: 'story-why-good', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'กินขนมที่สวนสาธารณะแล้วหาถังขยะไม่เจอ ควรทำอย่างไร' },
      options: [{ id: 'a', text: 'ทิ้งไว้ใต้ม้านั่ง' }, { id: 'b', text: 'โยนลงสระน้ำ' }, { id: 'c', text: 'เก็บถุงไว้ก่อน แล้วไปทิ้งที่ถังขยะ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เก็บขยะไว้ก่อน เจอถังขยะแล้วค่อยทิ้ง', hints: [], steps: ['ทิ้งขยะไว้ทำให้สวนสกปรก', 'เก็บไว้ก่อนแล้วไปทิ้งในถังขยะ'] },
    },
    {
      id: 'g-board-chop-t', type: 'transfer', subject: 'general', skillIds: ['safety'], familyId: 'board-sharp', difficulty: 1,
      sourceId: SRC, ...R, section: BOARD_SECTION,
      prompt: { text: 'ของอย่างใดในภาพ ที่แม่ใช้หั่นผัก' },
      visual: BOARD,
      options: [{ id: 'a', text: 'มีด' }, { id: 'b', text: 'จาน' }, { id: 'c', text: 'ลูกบอล' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แม่ใช้มีดหั่นผัก ต้องใช้อย่างระวัง', hints: [], steps: ['หั่นผักต้องใช้ของมีคม', 'ในภาพคือมีด'] },
    },
    {
      id: 'r-board-pound-t', type: 'transfer', subject: 'reasoning', skillIds: ['relationship'], familyId: 'board-pair', difficulty: 1,
      sourceId: SRC, ...R, section: BOARD_SECTION,
      prompt: { text: 'ของอย่างใดในภาพ ใช้ตำน้ำพริก' },
      visual: BOARD,
      options: [{ id: 'a', text: 'หม้อ' }, { id: 'b', text: 'ครกกับสาก' }, { id: 'c', text: 'กระทะ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ตำน้ำพริกใช้ครกกับสาก', hints: [], steps: ['หม้อใช้ต้ม กระทะใช้ผัด', 'ตำน้ำพริกใช้ครกกับสาก'] },
    },
    {
      id: 'sp-board-long-t', type: 'transfer', subject: 'spatial', skillIds: ['shape-in-objects'], familyId: 'board-shape', difficulty: 2,
      sourceId: SRC, ...R, section: BOARD_SECTION,
      prompt: { text: 'ข้อใดเป็นแท่งยาวทั้งสองอย่าง' },
      visual: BOARD,
      options: [{ id: 'a', text: 'จาน, ลูกบอล' }, { id: 'b', text: 'สบู่, หม้อ' }, { id: 'c', text: 'ดินสอ, ไม้กวาด' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ดินสอกับไม้กวาดเป็นแท่งยาว', hints: [], steps: ['จานกับลูกบอลกลม สบู่กับหม้อไม่ยาว', 'ดินสอกับไม้กวาดเป็นแท่งยาว'] },
    },
    {
      id: 'm-board-sharp-count-t', type: 'transfer', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R, section: BOARD_SECTION,
      prompt: { text: 'ในภาพมีของมีคมกี่อย่าง' },
      visual: BOARD,
      options: [{ id: 'a', text: '2 อย่าง' }, { id: 'b', text: '3 อย่าง' }, { id: 'c', text: '1 อย่าง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มีดกับกรรไกร เป็นของมีคม 2 อย่าง', hints: [], steps: ['ของที่ตัดหรือหั่นได้คือ มีด และกรรไกร', 'นับได้ 2 อย่าง'] },
    },
    {
      id: 'th-spoon-fork-t', type: 'transfer', subject: 'thai', skillIds: ['pair-words'], familyId: 'pair-words', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เวลากินข้าว ช้อน มักใช้คู่กับสิ่งใด' },
      options: [{ id: 'a', text: 'ครก' }, { id: 'b', text: 'ส้อม' }, { id: 'c', text: 'ไม้กวาด' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'เรากินข้าวด้วยช้อนกับส้อม', hints: [], steps: ['มือหนึ่งถือช้อน อีกมือถือส้อม', 'ช้อนจึงใช้คู่กับส้อม'] },
    },
    {
      id: 'm-snack-steps-t', type: 'transfer', subject: 'math', skillIds: ['multi-step'], familyId: 'multi-step', difficulty: 3,
      sourceId: SRC, ...R, section: 'ฟังโจทย์แล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'มีขนม 10 ชิ้น กินไป 4 ชิ้น แล้วแม่ให้มาอีก 2 ชิ้น ตอนนี้มีขนมกี่ชิ้น' },
      options: [{ id: 'a', text: '6 ชิ้น' }, { id: 'b', text: '8 ชิ้น' }, { id: 'c', text: '16 ชิ้น' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'กินไปเหลือ 6 ชิ้น ได้เพิ่ม 2 เป็น 8 ชิ้น', hints: [], steps: ['10 ลบ 4 เหลือ 6 ชิ้น', '6 บวก 2 เท่ากับ 8 ชิ้น'] },
    },
    {
      id: 'sp-dots-down-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'dots-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'จำนวนจุดลดลงทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ dots: 8 }, { dots: 6 }, { dots: 4 }, '?'] },
      options: [{ id: 'a', svg: { figure: { dots: 3 } } }, { id: 'b', svg: { figure: { dots: 2 } } }, { id: 'c', svg: { figure: { dots: 5 } } }, { id: 'd', svg: { figure: { dots: 1 } } }],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'จุดลดลงทีละ 2 คือ 8 6 4 2', hints: [], steps: ['8 จุด เป็น 6 จุด เป็น 4 จุด ลดลงทีละ 2', 'ภาพต่อไปจึงมี 2 จุด'] },
    },
    {
      id: 'sp-wheel-jump-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'wheel-sequence', difficulty: 3,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ช่องที่ระบายสีเลื่อนไปทีละเท่ากัน ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ wheel: 1 }, { wheel: 4 }, { wheel: 7 }, '?'] },
      options: [{ id: 'a', svg: { figure: { wheel: 2 } } }, { id: 'b', svg: { figure: { wheel: 0 } } }, { id: 'c', svg: { figure: { wheel: 5 } } }, { id: 'd', svg: { figure: { wheel: 6 } } }],
      correctOptionId: 'a',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'ช่องสีดำเลื่อนตามเข็มนาฬิกาทีละ 3 ช่อง', hints: [], steps: ['แต่ละภาพ ช่องสีดำข้ามไป 3 ช่องตามเข็มนาฬิกา', 'จากด้านบนซ้าย เลื่อนอีก 3 ช่องไปอยู่ด้านขวา'] },
    },
    {
      id: 'sc-mango-sweet-t', type: 'transfer', subject: 'science', skillIds: ['plants'], familyId: 'trees', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ต้นไม้ชนิดใดให้ผลสีเหลือง รสหวาน ที่คนไทยกินกับข้าวเหนียว' },
      options: [{ id: 'a', image: 'pic-bamboo', speech: 'ต้นไผ่' }, { id: 'b', image: 'pic-coconut-tree', speech: 'ต้นมะพร้าว' }, { id: 'c', image: 'pic-mango-tree', speech: 'ต้นมะม่วง' }, { id: 'd', image: 'pic-banana-tree', speech: 'ต้นกล้วย' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'ข้าวเหนียวมะม่วงใช้มะม่วงสุกสีเหลือง', hints: [], steps: ['มะม่วงสุกมีสีเหลืองและหวาน', 'คนไทยกินมะม่วงกับข้าวเหนียว'] },
    },
    {
      id: 'th-feeling-happy-t', type: 'transfer', subject: 'thai', skillIds: ['feelings'], familyId: 'feelings', difficulty: 2,
      sourceId: SRC, ...R, section: SHORT,
      prompt: { text: 'ลิลลี่ได้ดาวจากคุณครู เพราะอ่านหนังสือเก่ง ลิลลี่รู้สึกอย่างไร' },
      options: [{ id: 'a', text: 'เสียใจ' }, { id: 'b', text: 'กลัว' }, { id: 'c', text: 'ดีใจ' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ได้รางวัลเพราะทำดี จึงดีใจ', hints: [], steps: ['ลิลลี่ได้ดาวเพราะอ่านเก่ง', 'ได้รางวัลแล้วรู้สึกดีใจ'] },
    },
  ],
};
