/*
 * ชุดที่ 31 — สถานที่ในชุมชน 12 แห่ง (แผ่นรูป N: design/PROMPTS-gemini-11.md) แบบ 15 ข้อ
 * ตัวเลือกส่วนใหญ่เป็นภาพสถานที่ (pic-place-*) เด็กต้องดูภาพแล้วเลือกสถานที่ที่ตรงกับเหตุการณ์
 * ช่วง 1: โรงพยาบาล สถานีตำรวจ สถานีดับเพลิง ไปรษณีย์ ห้องสมุด
 * ช่วง 2: ซูเปอร์มาร์เก็ต ป้ายรถโดยสาร (ซ้าย-ขวา) ธนาคาร นับเด็กในห้องสมุด ร้านขนมปัง
 * ช่วง 3: ปั๊มน้ำมัน ร้านขายยา สวนสาธารณะ (ลมกับว่าว) ตัวอักษรตัวแรกของ ตลาด เปรียบเทียบอาชีพกับสถานที่ทำงาน
 * หมายเหตุภาพ: รปภ.ธนาคารแต่งตัวคล้ายตำรวจ จึงไม่ให้ธนาคารกับสถานีตำรวจอยู่ในตัวเลือกเดียวกัน
 * แต่งใหม่ทั้งหมด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const PLACES = 'ดูภาพสถานที่ในชุมชนแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const PICS = 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดความรู้เรื่องสถานที่ในชุมชน';
const place = (id, name) => ({ id, image: `pic-place-${name}` });
const scene = (name) => ({ type: 'image', asset: `pic-place-${name}` });
const words = (...list) => list.map((text, i) => ({ id: 'abc'[i], text }));

export default {
  id: 'set-31',
  version: 1,
  title: 'ชุดที่ 31',
  note: 'สถานที่ในชุมชน โรงพยาบาล ตำรวจ ไปรษณีย์ ธนาคาร ปั๊มน้ำมัน',
  order: [
    'g-place-hospital', 'g-place-police', 'g-place-fire', 'g-place-post', 'g-place-library',
    'g-place-market', 'sp-bus-right', 'g-place-bank', 'm-library-kids', 'g-place-bakery',
    'g-place-gas', 'g-place-pharmacy', 'sc-park-kite', 'th-place-initial', 'r-place-analogy',
  ],
  stimuli: {},
  items: [
    // ================================================================ ช่วงที่ 1
    {
      id: 'g-place-hospital', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'เมื่อเราป่วยหนักและต้องให้หมอตรวจรักษา ควรไปสถานที่ใด' },
      options: [place('a', 'bakery'), place('b', 'hospital'), place('c', 'post')],
      correctOptionId: 'b',
      narration: PICS,
      review: {
        summary: 'โรงพยาบาลมีหมอและพยาบาลรักษาคนป่วย',
        hints: ['นึกว่าใครรักษาคนป่วย และเขาทำงานที่ไหน'],
        steps: ['ร้านขนมปังขายขนม และที่ทำการไปรษณีย์ส่งจดหมาย ไม่ได้รักษาคนป่วย', 'โรงพยาบาลมีหมอและพยาบาลรักษาคนป่วย ตอบข้อ 2'],
        transferIds: ['g-place-hospital-t'],
      },
    },
    {
      id: 'g-place-police', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าเราหลงทางหรือของหาย ควรไปขอความช่วยเหลือจากเจ้าหน้าที่ที่สถานที่ใด' },
      options: [place('a', 'police'), place('b', 'bakery'), place('c', 'park'), place('d', 'gas')],
      correctOptionId: 'a',
      narration: PICS,
      review: {
        summary: 'สถานีตำรวจมีตำรวจคอยช่วยเหลือประชาชน',
        hints: ['นึกว่าใครคอยช่วยเหลือเวลาคนหลงทางหรือของหาย'],
        steps: ['ร้านขนมปัง สวนสาธารณะ และปั๊มน้ำมัน ไม่ได้มีเจ้าหน้าที่คอยช่วยเรื่องคนหลงทาง', 'สถานีตำรวจมีตำรวจช่วยเหลือประชาชน ตอบข้อ 1'],
        transferIds: ['g-place-police-t'],
      },
    },
    {
      id: 'g-place-fire', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'เมื่อเกิดไฟไหม้ ต้องเรียกเจ้าหน้าที่จากสถานที่ใดมาช่วยดับไฟ' },
      options: [place('a', 'supermarket'), place('b', 'library'), place('c', 'fire')],
      correctOptionId: 'c',
      narration: PICS,
      review: {
        summary: 'สถานีดับเพลิงมีนักดับเพลิงและรถดับเพลิง',
        hints: ['นึกว่ารถสีแดงที่มีน้ำดับไฟจอดอยู่ที่ไหน'],
        steps: ['ซูเปอร์มาร์เก็ตและห้องสมุดไม่มีรถดับเพลิง', 'สถานีดับเพลิงมีนักดับเพลิงและรถดับเพลิง ตอบข้อ 3'],
        transferIds: ['g-place-fire-t'],
      },
    },
    {
      id: 'g-place-post', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าต้องการส่งจดหมายหรือพัสดุไปให้ญาติ ควรไปสถานที่ใด' },
      options: [place('a', 'post'), place('b', 'gas'), place('c', 'hospital')],
      correctOptionId: 'a',
      narration: PICS,
      review: {
        summary: 'ที่ทำการไปรษณีย์ส่งจดหมายและพัสดุ',
        hints: ['ตู้สีแดงหน้าร้านมีซองจดหมาย'],
        steps: ['ปั๊มน้ำมันเติมน้ำมันรถ และโรงพยาบาลรักษาคนป่วย', 'ที่ทำการไปรษณีย์ส่งจดหมายและพัสดุ ตอบข้อ 1'],
        transferIds: ['g-place-post-t'],
      },
    },
    {
      id: 'g-place-library', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าต้องการยืมหนังสือไปอ่านที่บ้าน ควรไปสถานที่ใด' },
      options: [place('a', 'park'), place('b', 'gas'), place('c', 'library')],
      correctOptionId: 'c',
      narration: PICS,
      review: {
        summary: 'ห้องสมุดมีหนังสือให้ยืมไปอ่าน',
        hints: ['ดูว่าสถานที่ไหนมีชั้นหนังสือเต็มไปหมด'],
        steps: ['สวนสาธารณะไว้พักผ่อน และปั๊มน้ำมันไว้เติมน้ำมันรถ', 'ห้องสมุดมีชั้นหนังสือให้ยืมไปอ่าน ตอบข้อ 3'],
        transferIds: ['g-place-library-t'],
      },
    },

    // ================================================================ ช่วงที่ 2
    {
      id: 'g-place-market', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'แม่ต้องการซื้อผัก ผลไม้ และของใช้ในบ้านหลายอย่างในที่เดียว ควรไปสถานที่ใด' },
      options: [place('a', 'bakery'), place('b', 'supermarket'), place('c', 'hospital')],
      correctOptionId: 'b',
      narration: PICS,
      review: {
        summary: 'ซูเปอร์มาร์เก็ตขายของหลายอย่าง ใช้รถเข็นเลือกซื้อ',
        hints: ['ดูว่าที่ไหนมีรถเข็นและผักผลไม้'],
        steps: ['ร้านขนมปังขายแต่ขนมปังและเค้ก และโรงพยาบาลไม่ได้ขายของ', 'ซูเปอร์มาร์เก็ตขายผัก ผลไม้ และของใช้หลายอย่าง ตอบข้อ 2'],
        transferIds: ['g-place-market-t'],
      },
    },
    {
      id: 'sp-bus-right', type: 'main', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 2,
      sourceId: SRC, ...R, section: PLACES,
      prompt: { text: 'ในภาพ รถโดยสารอยู่ทางด้านใดของภาพ' },
      visual: scene('bus'),
      options: words('ทางซ้ายมือของภาพ', 'ทางขวามือของภาพ', 'ตรงกลางของภาพ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบอกตำแหน่งซ้ายขวาในภาพ',
      review: {
        summary: 'รถโดยสารอยู่ทางขวามือของภาพ',
        hints: ['มองภาพ แล้วดูว่ารถโดยสารอยู่ด้านซ้ายหรือด้านขวามือของเรา'],
        steps: ['ที่นั่งรอรถและคนรอรถอยู่ทางซ้ายของภาพ', 'รถโดยสารจอดอยู่ทางขวาของภาพ ตอบข้อ 2'],
        transferIds: ['sp-bus-right-t'],
      },
    },
    {
      id: 'g-place-bank', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 2,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าต้องการฝากเงินหรือถอนเงิน ควรไปสถานที่ใด' },
      options: [place('a', 'pharmacy'), place('b', 'bakery'), place('c', 'bank')],
      correctOptionId: 'c',
      narration: PICS,
      review: {
        summary: 'ธนาคารรับฝากและถอนเงิน มีเหรียญใหญ่อยู่เหนือประตู',
        hints: ['ดูอาคารที่มีเหรียญใหญ่อยู่ด้านบน'],
        steps: ['ร้านขายยาขายยา และร้านขนมปังขายขนม ไม่ได้รับฝากเงิน', 'ธนาคารรับฝากและถอนเงิน ตอบข้อ 3'],
        transferIds: ['g-place-bank-t'],
      },
    },
    {
      id: 'm-library-kids', type: 'main', subject: 'math', skillIds: ['story-count'], familyId: 'picture-count', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES,
      prompt: { text: 'ในภาพ มีเด็กกี่คน' },
      visual: scene('library'),
      options: words('3 คน', '2 คน', '4 คน'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการนับคนในภาพ',
      review: {
        summary: 'ในภาพมีเด็ก 3 คน กำลังถือหนังสือ',
        hints: ['นับเด็กทีละคนจากซ้ายไปขวา'],
        steps: ['เด็กหญิงสะพายกระเป๋าอยู่ทางซ้าย เด็กหญิงอีกคนอยู่ตรงกลาง และเด็กชายอยู่ทางขวา', 'นับได้ 3 คน ตอบข้อ 1'],
        transferIds: ['m-library-kids-t'],
      },
    },
    {
      id: 'g-place-bakery', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าอยากซื้อขนมปังและเค้กที่เพิ่งอบใหม่ๆ ควรไปร้านใด' },
      options: [place('a', 'bakery'), place('b', 'gas'), place('c', 'post')],
      correctOptionId: 'a',
      narration: PICS,
      review: {
        summary: 'ร้านเบเกอรี่ขายขนมปังและเค้ก',
        hints: ['ดูร้านที่มีขนมปังและเค้กวางขาย และมีพ่อครัวใส่หมวกสูง'],
        steps: ['ปั๊มน้ำมันและที่ทำการไปรษณีย์ไม่ได้ขายขนม', 'ร้านเบเกอรี่ขายขนมปังและเค้ก ตอบข้อ 1'],
        transferIds: ['g-place-bakery-t'],
      },
    },

    // ================================================================ ช่วงที่ 3
    {
      id: 'g-place-gas', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'รถของพ่อน้ำมันใกล้หมด ต้องไปเติมน้ำมันที่สถานที่ใด' },
      options: [place('a', 'library'), place('b', 'gas'), place('c', 'park')],
      correctOptionId: 'b',
      narration: PICS,
      review: {
        summary: 'ปั๊มน้ำมันมีตู้จ่ายน้ำมันและพนักงานเติมน้ำมันให้รถ',
        hints: ['ดูที่ไหนมีตู้จ่ายน้ำมันและรถจอดอยู่'],
        steps: ['ห้องสมุดไว้อ่านหนังสือ และสวนสาธารณะไว้พักผ่อน', 'ปั๊มน้ำมันเติมน้ำมันให้รถ ตอบข้อ 2'],
        transferIds: ['g-place-gas-t'],
      },
    },
    {
      id: 'g-place-pharmacy', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 2,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าเป็นหวัดเล็กน้อยและต้องการซื้อยาจากเภสัชกร ควรไปร้านใด' },
      options: [place('a', 'bakery'), place('b', 'gas'), place('c', 'pharmacy')],
      correctOptionId: 'c',
      narration: PICS,
      review: {
        summary: 'ร้านขายยามีเภสัชกรช่วยแนะนำและขายยา',
        hints: ['ดูร้านที่มีเครื่องหมายกากบาทสีเขียว'],
        steps: ['ร้านขนมปังขายขนม และปั๊มน้ำมันเติมน้ำมันรถ', 'ร้านขายยามีเภสัชกรขายยา ตอบข้อ 3'],
        transferIds: ['g-place-pharmacy-t'],
      },
    },
    {
      id: 'sc-park-kite', type: 'main', subject: 'science', skillIds: ['wind-uses'], familyId: 'wind-uses', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES,
      prompt: { text: 'เด็กๆ ในภาพจะเล่นว่าวให้ลอยสูงได้ดีเมื่อมีสิ่งใด' },
      visual: scene('park'),
      options: words('ฝนตกหนัก', 'หิมะตก', 'ลมพัด'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้ว่าลมช่วยให้ว่าวลอย',
      review: {
        summary: 'ลมพัดทำให้ว่าวลอยขึ้นสูง',
        hints: ['ว่าวต้องมีอะไรช่วยพยุงให้ลอยอยู่บนฟ้า'],
        steps: ['ฝนตกหนักทำให้ว่าวเปียกและตก และเมืองไทยไม่มีหิมะ', 'ลมพัดทำให้ว่าวลอยขึ้นสูง ตอบข้อ 3'],
        transferIds: ['sc-park-kite-t'],
      },
    },
    {
      id: 'th-place-initial', type: 'main', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ภาพนี้คือ ตลาด คำว่า ตลาด ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: { type: 'image', asset: 'pic-market' },
      options: [{ id: 'a', text: 'ม', speech: '' }, { id: 'b', text: 'ต', speech: '' }, { id: 'c', text: 'ส', speech: '' }],
      correctOptionId: 'b',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก เด็กต้องรู้จักตัวอักษรเอง',
      review: {
        summary: 'ตลาด ขึ้นต้นด้วย ตอ เต่า',
        hints: ['ออกเสียงคำแรก ตะ ช้าๆ'],
        steps: ['ตลาด มีสองพยางค์ คือ ตะ กับ หลาด', 'พยางค์แรกขึ้นต้นด้วย ตอ เต่า ตอบข้อ 2'],
        transferIds: ['th-place-initial-t'],
      },
    },
    {
      id: 'r-place-analogy', type: 'main', subject: 'reasoning', skillIds: ['relationship'], familyId: 'analogy', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'หมอทำงานที่โรงพยาบาล ครูทำงานที่โรงเรียน คนอบขนมปังทำงานที่ที่ใด' },
      options: words('ร้านเบเกอรี่', 'ปั๊มน้ำมัน', 'ห้องสมุด'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการหาความสัมพันธ์ระหว่างอาชีพกับสถานที่ทำงาน',
      review: {
        summary: 'คนอบขนมปังทำงานที่ร้านเบเกอรี่',
        hints: ['อาชีพแต่ละอย่างมีสถานที่ทำงานของตัวเอง นึกว่าคนอบขนมปังอยู่ที่ไหน'],
        steps: ['หมอ-โรงพยาบาล และครู-โรงเรียน คืออาชีพกับที่ทำงาน', 'คนอบขนมปังทำงานที่ร้านเบเกอรี่ ตอบข้อ 1'],
        transferIds: ['r-place-analogy-t'],
      },
    },

    // ================================================================ โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'g-place-hospital-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'หมอและพยาบาลทำงานรักษาคนป่วยที่สถานที่ใด' },
      options: [place('a', 'hospital'), place('b', 'post'), place('c', 'gas')],
      correctOptionId: 'a',
      narration: PICS,
      review: { summary: 'หมอและพยาบาลทำงานที่โรงพยาบาล', hints: [], steps: ['ที่ทำการไปรษณีย์ส่งจดหมาย และปั๊มน้ำมันเติมน้ำมัน', 'โรงพยาบาลมีหมอและพยาบาลรักษาคนป่วย'] },
    },
    {
      id: 'g-place-police-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ตำรวจจราจรและตำรวจประจำสถานี ทำงานที่สถานที่ใด' },
      options: [place('a', 'bakery'), place('b', 'library'), place('c', 'police')],
      correctOptionId: 'c',
      narration: PICS,
      review: { summary: 'ตำรวจทำงานที่สถานีตำรวจ', hints: [], steps: ['ร้านขนมปังและห้องสมุดไม่ใช่ที่ทำงานของตำรวจ', 'สถานีตำรวจมีรถตำรวจและตำรวจ'] },
    },
    {
      id: 'g-place-fire-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'รถดับเพลิงสีแดงจอดรออยู่ที่สถานที่ใด' },
      options: [place('a', 'park'), place('b', 'fire'), place('c', 'bank')],
      correctOptionId: 'b',
      narration: PICS,
      review: { summary: 'รถดับเพลิงจอดรออยู่ที่สถานีดับเพลิง', hints: [], steps: ['สวนสาธารณะและธนาคารไม่มีรถดับเพลิงจอดรอ', 'สถานีดับเพลิงมีรถดับเพลิงและนักดับเพลิง'] },
    },
    {
      id: 'g-place-post-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'บุรุษไปรษณีย์ปั่นจักรยานส่งจดหมาย ทำงานที่สถานที่ใด' },
      options: [place('a', 'post'), place('b', 'supermarket'), place('c', 'pharmacy')],
      correctOptionId: 'a',
      narration: PICS,
      review: { summary: 'บุรุษไปรษณีย์ทำงานที่ที่ทำการไปรษณีย์', hints: [], steps: ['ซูเปอร์มาร์เก็ตและร้านขายยาไม่ได้ส่งจดหมาย', 'ที่ทำการไปรษณีย์ส่งจดหมายและพัสดุ'] },
    },
    {
      id: 'g-place-library-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าต้องการนั่งอ่านหนังสือเงียบๆ ควรไปสถานที่ใด' },
      options: [place('a', 'gas'), place('b', 'bakery'), place('c', 'library')],
      correctOptionId: 'c',
      narration: PICS,
      review: { summary: 'ห้องสมุดมีหนังสือและที่นั่งอ่านเงียบๆ', hints: [], steps: ['ปั๊มน้ำมันและร้านขนมปังไม่ใช่ที่อ่านหนังสือ', 'ห้องสมุดมีชั้นหนังสือให้นั่งอ่าน'] },
    },
    {
      id: 'g-place-market-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าต้องการเข็นรถเลือกซื้อผักและผลไม้ ควรไปสถานที่ใด' },
      options: [place('a', 'bus'), place('b', 'supermarket'), place('c', 'hospital')],
      correctOptionId: 'b',
      narration: PICS,
      review: { summary: 'ซูเปอร์มาร์เก็ตมีรถเข็นให้เลือกซื้อของ', hints: [], steps: ['ป้ายรถโดยสารและโรงพยาบาลไม่ได้ขายของ', 'ซูเปอร์มาร์เก็ตมีรถเข็นและขายผักผลไม้'] },
    },
    {
      id: 'sp-bus-right-t', type: 'transfer', subject: 'spatial', skillIds: ['left-right-picture'], familyId: 'left-right-picture', difficulty: 2,
      sourceId: SRC, ...R, section: PLACES,
      prompt: { text: 'ในภาพ รถเข็นที่ว่างเปล่าสองคันอยู่ทางด้านใดของภาพ' },
      visual: scene('supermarket'),
      options: words('ทางซ้ายมือของภาพ', 'ทางขวามือของภาพ', 'ตรงกลางของภาพ'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'รถเข็นที่ว่างเปล่าสองคันอยู่ทางซ้ายมือของภาพ', hints: [], steps: ['คุณแม่เข็นรถที่มีผักอยู่ทางขวาของภาพ', 'รถเข็นว่างเปล่าสองคันอยู่ทางซ้ายของภาพ'] },
    },
    {
      id: 'g-place-bank-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 2,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าต้องการเก็บเงินออมไว้ในที่ปลอดภัย ควรนำไปฝากที่ใด' },
      options: [place('a', 'gas'), place('b', 'bank'), place('c', 'park')],
      correctOptionId: 'b',
      narration: PICS,
      review: { summary: 'ธนาคารรับฝากเงินให้อย่างปลอดภัย', hints: [], steps: ['ปั๊มน้ำมันและสวนสาธารณะไม่รับฝากเงิน', 'ธนาคารรับฝากเงินให้อย่างปลอดภัย'] },
    },
    {
      id: 'm-library-kids-t', type: 'transfer', subject: 'math', skillIds: ['story-count'], familyId: 'picture-count', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES,
      prompt: { text: 'ในภาพ มีเด็กกี่คน' },
      visual: scene('park'),
      options: words('1 คน', '3 คน', '2 คน'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ในภาพมีเด็ก 2 คน เด็กชายและเด็กหญิง', hints: [], steps: ['เด็กชายใส่เสื้อสีฟ้าอยู่ทางซ้าย', 'เด็กหญิงใส่เสื้อสีชมพูอยู่ทางขวา นับได้ 2 คน'] },
    },
    {
      id: 'g-place-bakery-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'ถ้าอยากซื้อเค้กไปงานวันเกิดของเพื่อน ควรไปร้านใด' },
      options: [place('a', 'pharmacy'), place('b', 'post'), place('c', 'bakery')],
      correctOptionId: 'c',
      narration: PICS,
      review: { summary: 'ร้านเบเกอรี่ขายเค้ก', hints: [], steps: ['ร้านขายยาขายยา และที่ทำการไปรษณีย์ส่งจดหมาย', 'ร้านเบเกอรี่ขายเค้กและขนมปัง'] },
    },
    {
      id: 'g-place-gas-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'พนักงานที่คอยเติมน้ำมันให้รถยนต์ทำงานที่สถานที่ใด' },
      options: [place('a', 'library'), place('b', 'bank'), place('c', 'gas')],
      correctOptionId: 'c',
      narration: PICS,
      review: { summary: 'พนักงานเติมน้ำมันทำงานที่ปั๊มน้ำมัน', hints: [], steps: ['ห้องสมุดและธนาคารไม่มีตู้จ่ายน้ำมัน', 'ปั๊มน้ำมันมีตู้จ่ายน้ำมันและพนักงานเติมน้ำมัน'] },
    },
    {
      id: 'g-place-pharmacy-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'community-places', difficulty: 2,
      sourceId: SRC, ...R, section: PLACES, scene: true,
      prompt: { text: 'เภสัชกรใส่เสื้อคลุมสีขาวคอยขายยาและแนะนำการใช้ยา ทำงานที่ร้านใด' },
      options: [place('a', 'pharmacy'), place('b', 'bakery'), place('c', 'fire')],
      correctOptionId: 'a',
      narration: PICS,
      review: { summary: 'เภสัชกรทำงานที่ร้านขายยา', hints: [], steps: ['ร้านขนมปังและสถานีดับเพลิงไม่ได้ขายยา', 'ร้านขายยามีเภสัชกรขายยา'] },
    },
    {
      id: 'sc-park-kite-t', type: 'transfer', subject: 'science', skillIds: ['wind-uses'], familyId: 'wind-uses', difficulty: 1,
      sourceId: SRC, ...R, section: PLACES,
      prompt: { text: 'ถ้าฝนตกหนักขณะที่เด็กๆ เล่นอยู่ในสวนสาธารณะ ควรทำอย่างไร' },
      visual: scene('park'),
      options: words('ยังเล่นว่าวกลางฝนต่อไป', 'เข้าไปหลบฝนในที่ร่ม', 'กระโดดลงไปในสระน้ำ'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ควรเข้าไปหลบฝนในที่ร่ม จะได้ไม่เปียกและไม่ป่วย', hints: [], steps: ['เล่นกลางฝนทำให้เปียกและป่วยได้ และกระโดดลงสระน้ำอันตราย', 'ควรเข้าไปหลบฝนในที่ร่ม'] },
    },
    {
      id: 'th-place-initial-t', type: 'transfer', subject: 'thai', skillIds: ['initial-consonant'], familyId: 'first-letter', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ภาพนี้คือ วัด คำว่า วัด ขึ้นต้นด้วยพยัญชนะตัวใด' },
      visual: { type: 'image', asset: 'pic-temple' },
      options: [{ id: 'a', text: 'ก', speech: '' }, { id: 'b', text: 'ว', speech: '' }, { id: 'c', text: 'ม', speech: '' }],
      correctOptionId: 'b',
      narration: 'เสียงอ่านชื่อภาพ แต่ไม่อ่านตัวอักษรในตัวเลือก',
      review: { summary: 'วัด ขึ้นต้นด้วย วอ แหวน', hints: [], steps: ['ออกเสียงคำว่า วัด ช้าๆ', 'เสียงแรกคือ วอ แหวน'] },
    },
    {
      id: 'r-place-analogy-t', type: 'transfer', subject: 'reasoning', skillIds: ['relationship'], familyId: 'analogy', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ครูสอนนักเรียนที่โรงเรียน คนขายยาทำงานที่ที่ใด' },
      options: words('สวนสาธารณะ', 'ธนาคาร', 'ร้านขายยา'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'คนขายยาทำงานที่ร้านขายยา', hints: [], steps: ['ครู-โรงเรียน คืออาชีพกับที่ทำงาน', 'คนขายยาทำงานที่ร้านขายยา'] },
    },
  ],
};
