/*
 * ชุดที่ 36 — ตลาดนัดของยาย (ชุดผสม ใช้รูปที่มีอยู่แล้ว) แบบ 15 ข้อ
 * ช่วง 1 ฟังเรื่องไปตลาดนัดกับยาย ถาม 5 ข้อ: วัน จำนวนชนิดผลไม้ เหตุผล มารยาท เหตุการณ์สุดท้าย
 * ช่วง 2 แผนภูมิรูปภาพเงินที่ร้านผลไม้ขายได้ (เหรียญ 1 เหรียญ = 5 บาท) ถาม 5 ข้อ
 * ช่วง 3 ข้อเดี่ยว: คำคล้องจอง รูปแบบภาพ ทอนเงิน วันก่อนวันอาทิตย์ ข้อใดไม่ใช่ผลไม้
 * แต่งใหม่ทั้งหมด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const STORY = 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง';
const CHART = 'ดูแผนภูมิรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const words = (...list) => list.map((text, i) => ({ id: 'abc'[i], text }));
const fig = (id, figure) => ({ id, svg: { figure } });
const shape = (name, fill = 'empty') => ({ shape: name, fill });

const STORY_TEXT = 'เช้าวันอาทิตย์ ยายพาก้อยไปตลาดนัด ยายซื้อมะม่วง 3 ผล และกล้วย 1 หวี ก้อยอยากได้แตงโม แต่ยายบอกว่าที่บ้านยังมีแตงโมอยู่ ขากลับยายซื้อขนมครกให้ก้อย 10 บาท ก้อยยกมือไหว้ขอบคุณยาย';
const SALES = {
  type: 'pictograph', icon: 'pic-coin', unit: 5, unitWord: 'บาท',
  rows: [{ asset: 'pic-mango', label: 'มะม่วง', count: 4 }, { asset: 'pic-banana', label: 'กล้วย', count: 2 }, { asset: 'pic-orange', label: 'ส้ม', count: 3 }],
};
const SALES_TEXT = 'แผนภูมิแสดงเงินที่ร้านผลไม้ขายได้ เหรียญ 1 เหรียญ แทนเงิน 5 บาท';

export default {
  id: 'set-36',
  version: 1,
  title: 'ชุดที่ 36',
  note: 'ตลาดนัดของยาย แผนภูมิเงินขายผลไม้ คำคล้องจอง ทอนเงิน',
  order: [
    'g-market-day', 'm-market-kinds', 'th-market-why', 'g-market-thanks', 'r-market-last',
    'm-sales-most', 'm-sales-mango', 'm-sales-sum', 'r-sales-diff', 'sc-wash-fruit',
    'th-rhyme-talad', 'sp-tri-pattern', 'm-change-money', 'g-before-sunday', 'r-not-fruit',
  ],
  stimuli: {
    story: { section: STORY, text: STORY_TEXT },
    sales: { section: CHART, text: SALES_TEXT, visual: SALES },
  },
  items: [
    // ================================================================ ช่วงที่ 1: เรื่องตลาดนัด
    {
      id: 'g-market-day', type: 'main', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ยายพาก้อยไปตลาดนัดวันอะไร' },
      options: words('วันเสาร์', 'วันอาทิตย์', 'วันจันทร์'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจำรายละเอียดจากเรื่องที่ฟัง',
      review: {
        summary: 'เรื่องเริ่มว่า เช้าวันอาทิตย์ ยายพาก้อยไปตลาดนัด',
        hints: ['ฟังประโยคแรกของเรื่องอีกครั้ง'],
        steps: ['ประโยคแรกบอกว่า เช้าวันอาทิตย์ ยายพาก้อยไปตลาดนัด', 'จึงไปวันอาทิตย์ ตอบข้อ 2'],
        transferIds: ['g-market-day-t'],
      },
    },
    {
      id: 'm-market-kinds', type: 'main', subject: 'math', skillIds: ['story-count-kinds'], familyId: 'story-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ยายซื้อผลไม้กี่ชนิด' },
      options: words('1 ชนิด', '2 ชนิด', '3 ชนิด'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับชนิด (ไม่ใช่นับผล) จากเรื่อง',
      review: {
        summary: 'ยายซื้อมะม่วงกับกล้วย เป็นผลไม้ 2 ชนิด',
        hints: ['นับว่ามีผลไม้กี่ชื่อ ไม่ต้องนับว่ากี่ผล แตงโมยายไม่ได้ซื้อ'],
        steps: ['ยายซื้อมะม่วงและกล้วย ส่วนแตงโมยายไม่ได้ซื้อ', 'มะม่วงกับกล้วยเป็น 2 ชนิด ตอบข้อ 2'],
        transferIds: ['m-market-kinds-t'],
      },
    },
    {
      id: 'th-market-why', type: 'main', subject: 'thai', skillIds: ['story-why-good'], familyId: 'story-why', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ทำไมยายจึงไม่ซื้อแตงโม' },
      options: words('เพราะแตงโมแพง', 'เพราะที่บ้านยังมีแตงโมอยู่', 'เพราะก้อยไม่ชอบแตงโม'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการหาเหตุผลจากเรื่อง',
      review: {
        summary: 'ยายบอกว่าที่บ้านยังมีแตงโมอยู่',
        hints: ['ฟังสิ่งที่ยายพูดตอนก้อยอยากได้แตงโม'],
        steps: ['เรื่องไม่ได้บอกว่าแตงโมแพง และก้อยอยากได้แตงโม แปลว่าก้อยชอบ', 'ยายบอกว่าที่บ้านยังมีแตงโมอยู่ ตอบข้อ 2'],
        transferIds: ['th-market-why-t'],
      },
    },
    {
      id: 'g-market-thanks', type: 'main', subject: 'general', skillIds: ['manners'], familyId: 'manners', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'ก้อยทำอย่างไรเมื่อยายซื้อขนมครกให้' },
      options: words('ยกมือไหว้ขอบคุณยาย', 'วิ่งไปเล่นทันที', 'ขอขนมเพิ่มอีก'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดมารยาทจากเรื่อง',
      review: {
        summary: 'ก้อยยกมือไหว้ขอบคุณยาย เป็นเด็กมีมารยาท',
        hints: ['ฟังประโยคสุดท้ายของเรื่อง'],
        steps: ['เรื่องไม่ได้บอกว่าก้อยวิ่งไปเล่นหรือขอเพิ่ม', 'ก้อยยกมือไหว้ขอบคุณยาย ตอบข้อ 1'],
        transferIds: ['g-market-thanks-t'],
      },
    },
    {
      id: 'r-market-last', type: 'main', subject: 'reasoning', skillIds: ['listening-sequence'], familyId: 'story-sequence', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'story',
      prompt: { text: 'เหตุการณ์ใดเกิดขึ้นเป็นอย่างสุดท้าย' },
      options: words('ยายซื้อมะม่วง', 'ยายซื้อขนมครก', 'ก้อยไหว้ขอบคุณยาย'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงลำดับเหตุการณ์ในเรื่อง',
      review: {
        summary: 'ซื้อผลไม้ แล้วซื้อขนมครกขากลับ สุดท้ายก้อยไหว้ขอบคุณยาย',
        hints: ['ไล่เรื่องตั้งแต่ต้นจนจบ อะไรเกิดหลังสุด'],
        steps: ['ยายซื้อมะม่วงก่อน แล้วขากลับซื้อขนมครก', 'หลังได้ขนม ก้อยไหว้ขอบคุณยายเป็นอย่างสุดท้าย ตอบข้อ 3'],
        transferIds: ['r-market-last-t'],
      },
    },

    // ================================================================ ช่วงที่ 2: แผนภูมิเงินขายผลไม้
    {
      id: 'm-sales-most', compact: true, type: 'main', subject: 'math', skillIds: ['pictograph'], familyId: 'pictograph-read', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'sales',
      prompt: { text: 'ร้านขายผลไม้ชนิดใดได้เงินมากที่สุด' },
      options: words('ส้ม', 'มะม่วง', 'กล้วย'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการอ่านแผนภูมิ (แถวที่มีเหรียญมากที่สุด)',
      review: {
        summary: 'มะม่วงมีเหรียญ 4 เหรียญ มากที่สุด',
        hints: ['นับเหรียญในแต่ละแถว แถวไหนมีมากที่สุด'],
        steps: ['มะม่วง 4 เหรียญ กล้วย 2 เหรียญ ส้ม 3 เหรียญ', 'มะม่วงมีเหรียญมากที่สุด ตอบข้อ 2'],
        transferIds: ['m-sales-most-t'],
      },
    },
    {
      id: 'm-sales-mango', compact: true, type: 'main', subject: 'math', skillIds: ['pictograph'], familyId: 'pictograph-unit', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'sales',
      prompt: { text: 'ร้านขายมะม่วงได้เงินกี่บาท' },
      options: words('4 บาท', '15 บาท', '20 บาท'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการอ่านแผนภูมิที่ 1 รูปแทนมากกว่า 1 (เหรียญละ 5 บาท)',
      review: {
        summary: 'มะม่วงมี 4 เหรียญ เหรียญละ 5 บาท เป็น 20 บาท',
        hints: ['1 เหรียญแทน 5 บาท นับทีละ 5'],
        steps: ['แถวมะม่วงมี 4 เหรียญ นับทีละ 5 ได้ 5 10 15 20', 'ขายมะม่วงได้ 20 บาท ตอบข้อ 3'],
        transferIds: ['m-sales-mango-t'],
      },
    },
    {
      id: 'm-sales-sum', compact: true, type: 'main', subject: 'math', skillIds: ['pictograph'], familyId: 'pictograph-unit', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'sales',
      prompt: { text: 'ร้านขายกล้วยกับส้มรวมกันได้เงินกี่บาท' },
      options: words('20 บาท', '25 บาท', '30 บาท'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการอ่านแผนภูมิแล้วบวก',
      review: {
        summary: 'กล้วย 10 บาท ส้ม 15 บาท รวม 25 บาท',
        hints: ['หาเงินของกล้วยและส้มทีละแถว แล้วบวกกัน'],
        steps: ['กล้วย 2 เหรียญเป็น 10 บาท ส้ม 3 เหรียญเป็น 15 บาท', '10 บวก 15 เท่ากับ 25 ตอบข้อ 2'],
        column: { a: 10, op: '+', b: 15 },
        transferIds: ['m-sales-sum-t'],
      },
    },
    {
      id: 'r-sales-diff', compact: true, type: 'main', subject: 'reasoning', skillIds: ['pictograph'], familyId: 'pictograph-compare', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'sales',
      prompt: { text: 'ร้านขายมะม่วงได้เงินมากกว่ากล้วยกี่บาท' },
      options: words('5 บาท', '10 บาท', '15 บาท'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการเปรียบเทียบสองแถวในแผนภูมิ',
      review: {
        summary: 'มะม่วง 20 บาท กล้วย 10 บาท ต่างกัน 10 บาท',
        hints: ['มะม่วงมีเหรียญมากกว่ากล้วยกี่เหรียญ แล้วคิดเป็นบาท'],
        steps: ['มะม่วงมากกว่ากล้วย 2 เหรียญ เหรียญละ 5 บาท', '20 ลบ 10 เท่ากับ 10 ตอบข้อ 2'],
        column: { a: 20, op: '-', b: 10 },
        transferIds: ['r-sales-diff-t'],
      },
    },
    {
      id: 'sc-wash-fruit', type: 'main', subject: 'science', skillIds: ['hygiene-reason'], familyId: 'food-safety', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ทำไมจึงควรล้างผลไม้ก่อนกิน' },
      options: words('เพื่อล้างสิ่งสกปรกและยาฆ่าแมลงออก', 'เพื่อให้ผลไม้หวานขึ้น', 'เพื่อให้ผลไม้ใหญ่ขึ้น'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องความสะอาดของอาหาร',
      review: {
        summary: 'ล้างผลไม้เพื่อเอาสิ่งสกปรกและยาฆ่าแมลงออก',
        hints: ['ผลไม้ผ่านมือคนหลายคนและอาจมียาฆ่าแมลงติดอยู่'],
        steps: ['การล้างไม่ได้ทำให้ผลไม้หวานขึ้นหรือใหญ่ขึ้น', 'ล้างเพื่อเอาสิ่งสกปรกและยาฆ่าแมลงออก ตอบข้อ 1'],
        transferIds: ['sc-wash-fruit-t'],
      },
    },

    // ================================================================ ช่วงที่ 3: ข้อเดี่ยว
    {
      id: 'th-rhyme-talad', type: 'main', subject: 'thai', skillIds: ['rhyme'], familyId: 'rhyme', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดคล้องจองกับคำว่า ตลาด' },
      options: words('ตะกร้า', 'สะอาด', 'ผลไม้'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการฟังเสียงท้ายคำที่คล้องจองกัน',
      review: {
        summary: 'ตลาด กับ สะอาด ลงท้ายด้วยเสียง าด เหมือนกัน',
        hints: ['ออกเสียงท้ายของคำว่า ตลาด แล้วหาคำที่ลงท้ายเสียงเดียวกัน'],
        steps: ['ตะกร้าลงท้ายเสียง า ผลไม้ลงท้ายเสียง ไม้', 'สะอาดลงท้ายเสียง าด เหมือน ตลาด ตอบข้อ 2'],
        transferIds: ['th-rhyme-talad-t'],
      },
    },
    {
      id: 'sp-tri-pattern', type: 'main', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'shape-pattern', difficulty: 2,
      sourceId: SRC, ...R, section: 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด',
      prompt: { text: 'ภาพเรียงต่อกันเป็นรูปแบบ ช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [shape('triangle'), shape('triangle', 'solid'), shape('circle'), shape('triangle'), '?'] },
      options: [fig('a', shape('triangle')), fig('b', shape('circle', 'solid')), fig('c', shape('square')), fig('d', shape('triangle', 'solid'))],
      correctOptionId: 'd',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการหารูปแบบที่ซ้ำ 3 ภาพ',
      review: {
        summary: 'รูปแบบซ้ำทีละ 3 ภาพ สามเหลี่ยมว่าง สามเหลี่ยมทึบ วงกลมว่าง',
        hints: ['ดูว่าภาพชุดแรก 3 ภาพเป็นอะไร แล้วชุดที่สองซ้ำแบบเดิม'],
        steps: ['ชุดแรกคือ สามเหลี่ยมว่าง สามเหลี่ยมทึบ วงกลมว่าง แล้วชุดที่สองเริ่มด้วยสามเหลี่ยมว่าง', 'ภาพถัดไปจึงเป็นสามเหลี่ยมทึบ ตอบข้อ 4'],
        transferIds: ['sp-tri-pattern-t'],
      },
    },
    {
      id: 'm-change-money', type: 'main', subject: 'math', skillIds: ['money-change'], familyId: 'money-change', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ก้อยมีเงิน 20 บาท ซื้อขนมครก 10 บาท จะเหลือเงินกี่บาท' },
      options: words('5 บาท', '15 บาท', '10 บาท'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดโจทย์ลบเรื่องเงิน',
      review: {
        summary: '20 ลบ 10 เท่ากับ 10 บาท',
        hints: ['เงินที่เหลือคือเงินที่มีลบด้วยราคาขนม'],
        steps: ['มีเงิน 20 บาท จ่ายไป 10 บาท ต้องเอา 10 ออกจาก 20', '20 ลบ 10 เท่ากับ 10 ตอบข้อ 3'],
        column: { a: 20, op: '-', b: 10 },
        transferIds: ['m-change-money-t'],
      },
    },
    {
      id: 'g-before-sunday', type: 'main', subject: 'general', skillIds: ['days-of-week'], familyId: 'days-of-week', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'วันก่อนวันอาทิตย์คือวันอะไร' },
      options: words('วันเสาร์', 'วันจันทร์', 'วันศุกร์'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดลำดับวันในสัปดาห์',
      review: {
        summary: 'วันเสาร์มาก่อนวันอาทิตย์',
        hints: ['ท่องวันเรียงกัน ศุกร์ เสาร์ อาทิตย์ จันทร์'],
        steps: ['วันจันทร์มาหลังวันอาทิตย์ และวันศุกร์อยู่ก่อนวันเสาร์', 'วันที่อยู่ติดก่อนวันอาทิตย์คือวันเสาร์ ตอบข้อ 1'],
        transferIds: ['g-before-sunday-t'],
      },
    },
    {
      id: 'r-not-fruit', type: 'main', subject: 'reasoning', skillIds: ['classify'], familyId: 'odd-word', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดไม่ใช่ผลไม้' },
      options: words('มะม่วง', 'กะหล่ำปลี', 'กล้วย'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่ม (ผัก กับ ผลไม้)',
      review: {
        summary: 'กะหล่ำปลีเป็นผัก ไม่ใช่ผลไม้',
        hints: ['ข้อไหนที่เรามักนำไปทำกับข้าว เช่น ผัดหรือต้ม'],
        steps: ['มะม่วงและกล้วยเป็นผลไม้', 'กะหล่ำปลีเป็นผัก ตอบข้อ 2'],
        transferIds: ['r-not-fruit-t'],
      },
    },

    // ================================================================ โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'g-market-day-t', type: 'transfer', subject: 'general', skillIds: ['story-detail'], familyId: 'story-detail', difficulty: 1,
      sourceId: SRC, ...R, section: STORY,
      prompt: { text: 'เช้าวันพุธ แม่พาบีมไปหาหมอฟัน บีมไปหาหมอฟันวันอะไร' },
      options: words('วันพุธ', 'วันพฤหัสบดี', 'วันอังคาร'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เรื่องบอกว่าเช้าวันพุธ', hints: [], steps: ['ประโยคบอกว่า เช้าวันพุธ แม่พาบีมไปหาหมอฟัน', 'บีมไปวันพุธ'] },
    },
    {
      id: 'm-market-kinds-t', type: 'transfer', subject: 'math', skillIds: ['story-count-kinds'], familyId: 'story-count', difficulty: 2,
      sourceId: SRC, ...R, section: STORY,
      prompt: { text: 'พ่อซื้อไก่ 2 ตัว ปลา 1 ตัว และไก่อีก 1 ตัว พ่อซื้อสัตว์กี่ชนิด' },
      options: words('2 ชนิด', '3 ชนิด', '4 ชนิด'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไก่กับปลาเป็น 2 ชนิด', hints: [], steps: ['ไก่ซื้อสองครั้งแต่เป็นชนิดเดียวกัน', 'มีไก่กับปลา 2 ชนิด'] },
    },
    {
      id: 'th-market-why-t', type: 'transfer', subject: 'thai', skillIds: ['story-why-good'], familyId: 'story-why', difficulty: 2,
      sourceId: SRC, ...R, section: STORY,
      prompt: { text: 'นิดไม่ได้ไปเล่นที่สนาม เพราะฝนตกหนัก ทำไมนิดจึงไม่ได้ไปเล่น' },
      options: words('เพราะนิดป่วย', 'เพราะฝนตกหนัก', 'เพราะสนามปิด'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เพราะฝนตกหนัก', hints: [], steps: ['คำว่า เพราะ บอกเหตุผล', 'เหตุผลคือฝนตกหนัก'] },
    },
    {
      id: 'g-market-thanks-t', type: 'transfer', subject: 'general', skillIds: ['manners'], familyId: 'manners', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อคุณครูให้ยืมดินสอ เราควรทำอย่างไร' },
      options: words('เงียบไม่พูดอะไร', 'กล่าวขอบคุณคุณครู', 'เอาดินสอไปเลย'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ควรกล่าวขอบคุณ', hints: [], steps: ['เมื่อมีคนช่วยเหลือเรา ควรขอบคุณ', 'กล่าวขอบคุณคุณครูเป็นมารยาทที่ดี'] },
    },
    {
      id: 'r-market-last-t', type: 'transfer', subject: 'reasoning', skillIds: ['listening-sequence'], familyId: 'story-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: STORY,
      prompt: { text: 'ต้นตื่นนอน แปรงฟัน กินข้าว แล้วไปโรงเรียน เหตุการณ์ใดเกิดขึ้นเป็นอย่างแรก' },
      options: words('แปรงฟัน', 'ไปโรงเรียน', 'ตื่นนอน'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ตื่นนอนเกิดขึ้นก่อน', hints: [], steps: ['เรื่องเรียงจาก ตื่นนอน แปรงฟัน กินข้าว ไปโรงเรียน', 'อย่างแรกคือตื่นนอน'] },
    },
    {
      id: 'm-sales-most-t', compact: true, type: 'transfer', subject: 'math', skillIds: ['pictograph'], familyId: 'pictograph-read', difficulty: 1,
      sourceId: SRC, ...R, section: CHART,
      prompt: { text: 'แผนภูมิแสดงเงินที่ร้านขายได้ เหรียญ 1 เหรียญแทน 5 บาท ร้านขายผลไม้ชนิดใดได้เงินน้อยที่สุด' },
      visual: SALES,
      options: words('กล้วย', 'ส้ม', 'มะม่วง'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'กล้วยมี 2 เหรียญ น้อยที่สุด', hints: [], steps: ['มะม่วง 4 เหรียญ กล้วย 2 เหรียญ ส้ม 3 เหรียญ', 'กล้วยมีน้อยที่สุด'] },
    },
    {
      id: 'm-sales-mango-t', compact: true, type: 'transfer', subject: 'math', skillIds: ['pictograph'], familyId: 'pictograph-unit', difficulty: 2,
      sourceId: SRC, ...R, section: CHART,
      prompt: { text: 'แผนภูมิแสดงเงินที่ร้านขายได้ เหรียญ 1 เหรียญแทน 5 บาท ร้านขายส้มได้เงินกี่บาท' },
      visual: SALES,
      options: words('3 บาท', '15 บาท', '10 บาท'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ส้ม 3 เหรียญ เหรียญละ 5 บาท เป็น 15 บาท', hints: [], steps: ['แถวส้มมี 3 เหรียญ นับทีละ 5 ได้ 5 10 15', 'ขายส้มได้ 15 บาท'] },
    },
    {
      id: 'm-sales-sum-t', compact: true, type: 'transfer', subject: 'math', skillIds: ['pictograph'], familyId: 'pictograph-unit', difficulty: 3,
      sourceId: SRC, ...R, section: CHART,
      prompt: { text: 'แผนภูมิแสดงเงินที่ร้านขายได้ เหรียญ 1 เหรียญแทน 5 บาท ร้านขายมะม่วงกับส้มรวมกันได้เงินกี่บาท' },
      visual: SALES,
      options: words('30 บาท', '35 บาท', '40 บาท'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มะม่วง 20 บาท ส้ม 15 บาท รวม 35 บาท', hints: [], steps: ['มะม่วง 4 เหรียญเป็น 20 บาท ส้ม 3 เหรียญเป็น 15 บาท', '20 บวก 15 เท่ากับ 35'], column: { a: 20, op: '+', b: 15 } },
    },
    {
      id: 'r-sales-diff-t', compact: true, type: 'transfer', subject: 'reasoning', skillIds: ['pictograph'], familyId: 'pictograph-compare', difficulty: 3,
      sourceId: SRC, ...R, section: CHART,
      prompt: { text: 'แผนภูมิแสดงเงินที่ร้านขายได้ เหรียญ 1 เหรียญแทน 5 บาท ร้านขายส้มได้เงินมากกว่ากล้วยกี่บาท' },
      visual: SALES,
      options: words('5 บาท', '10 บาท', '15 บาท'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ส้ม 15 บาท กล้วย 10 บาท ต่างกัน 5 บาท', hints: [], steps: ['ส้มมากกว่ากล้วย 1 เหรียญ', '1 เหรียญคือ 5 บาท'] },
    },
    {
      id: 'sc-wash-fruit-t', type: 'transfer', subject: 'science', skillIds: ['hygiene-reason'], familyId: 'food-safety', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'อาหารที่เหลือ ควรเก็บอย่างไรจึงไม่เสียเร็ว' },
      options: words('ปิดฝาแล้วเก็บในตู้เย็น', 'วางไว้กลางแดด', 'เปิดทิ้งไว้ให้แมลงวันตอม'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ปิดฝาแล้วเก็บในตู้เย็น', hints: [], steps: ['ความร้อนและแมลงวันทำให้อาหารเสียเร็ว', 'ปิดฝาและเก็บในที่เย็นช่วยให้อาหารไม่เสียเร็ว'] },
    },
    {
      id: 'th-rhyme-talad-t', type: 'transfer', subject: 'thai', skillIds: ['rhyme'], familyId: 'rhyme', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดคล้องจองกับคำว่า ขนม' },
      options: words('ผม', 'แม่', 'ขาว'),
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ขนม กับ ผม ลงท้ายด้วยเสียง อม เหมือนกัน', hints: [], steps: ['ออกเสียงท้ายของคำว่า ขนม คือ อม', 'ผมลงท้ายเสียง อม เหมือนกัน'] },
    },
    {
      id: 'sp-tri-pattern-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'shape-pattern', difficulty: 2,
      sourceId: SRC, ...R, section: 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด',
      prompt: { text: 'ภาพเรียงต่อกันเป็นรูปแบบ ช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [shape('square', 'solid'), shape('circle'), shape('circle'), shape('square', 'solid'), '?'] },
      options: [fig('a', shape('circle')), fig('b', shape('square', 'solid')), fig('c', shape('circle', 'solid')), fig('d', shape('square'))],
      correctOptionId: 'a',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'รูปแบบซ้ำ สี่เหลี่ยมทึบ วงกลม วงกลม', hints: [], steps: ['ชุดละ 3 ภาพ คือ สี่เหลี่ยมทึบ วงกลมว่าง วงกลมว่าง', 'ชุดที่สองเริ่มด้วยสี่เหลี่ยมทึบ ภาพถัดไปจึงเป็นวงกลมว่าง'] },
    },
    {
      id: 'm-change-money-t', type: 'transfer', subject: 'math', skillIds: ['money-change'], familyId: 'money-change', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีเงิน 50 บาท ซื้อสมุด 20 บาท จะเหลือเงินกี่บาท' },
      options: words('20 บาท', '30 บาท', '40 บาท'),
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '50 ลบ 20 เท่ากับ 30 บาท', hints: [], steps: ['มีเงิน 50 บาท จ่ายไป 20 บาท', '50 ลบ 20 เท่ากับ 30'], column: { a: 50, op: '-', b: 20 } },
    },
    {
      id: 'g-before-sunday-t', type: 'transfer', subject: 'general', skillIds: ['days-of-week'], familyId: 'days-of-week', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'วันหลังวันพุธคือวันอะไร' },
      options: words('วันอังคาร', 'วันศุกร์', 'วันพฤหัสบดี'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'หลังวันพุธคือวันพฤหัสบดี', hints: [], steps: ['วันเรียงกัน อังคาร พุธ พฤหัสบดี ศุกร์', 'หลังวันพุธคือวันพฤหัสบดี'] },
    },
    {
      id: 'r-not-fruit-t', type: 'transfer', subject: 'reasoning', skillIds: ['classify'], familyId: 'odd-word', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดไม่ใช่สัตว์' },
      options: words('ม้า', 'ปลา', 'ดอกไม้'),
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ดอกไม้เป็นพืช ไม่ใช่สัตว์', hints: [], steps: ['ม้าและปลาเป็นสัตว์', 'ดอกไม้เป็นพืช'] },
    },
  ],
};
