/*
 * ชุดที่ 27 — กลอน เรื่องในประโยคสั้น เรียงความสูง วัสดุ วันสำคัญ แบบ 15 ข้อ
 * ช่วง 1 บทกลอนสั้นๆ เรื่องกิจวัตรตอนเช้า ถาม 5 ข้อ: เล่าเรื่องอะไร ทำอะไรต่อ คำคล้องจอง ความหมายคำ ข้อใดไม่ได้กล่าวถึง
 * ช่วง 2 ข้อเดี่ยว: ประโยคสั้นถามจำนวนชนิด เรียงความสูงจากประโยค วัสดุ (แก้ว โลหะ) วันเด็ก
 * ช่วง 3 ข้อเดี่ยว: ตัวสะกดแม่ กง ศาสนา (ผู้ปกครองควรตรวจ) มองกล่องซ้อนจากด้านบน เลขลบ ภาพต่อเนื่องสลับขึ้นลง
 * แต่งใหม่ทั้งหมด ตั้งชื่อตัวละคร สถานที่ และตัวเลขใหม่ตามแนวข้อสอบเก่า; ใช้รูปที่มีอยู่แล้ว ไม่ต้องสร้างรูปใหม่
 * (ผู้ปกครองรายงาน 2026-10-02: ข้อสอบจริงมีโจทย์เป็นตัวหนังสือให้เด็กดูด้วย — ทุกข้อในชุดนี้อ่านรู้เรื่องจากตัวหนังสือได้)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const POEM = 'ฟังบทกลอนแล้วตอบคำถามให้ถูกต้อง';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';
const fig = (id, figure) => ({ id, svg: { figure } });
const arrow = (direction) => ({ arrow: direction });

export default {
  id: 'set-27',
  version: 1,
  title: 'ชุดที่ 27',
  note: 'บทกลอนตอนเช้า เรียงความสูง แก้วและโลหะ วันเด็ก แม่ กง',
  order: [
    'th-poem-main', 'g-poem-first', 'th-poem-rhyme', 'th-poem-word', 'r-poem-not',
    'm-sentence-kinds', 'r-height-words', 'sc-glass-things', 'sc-metal-things', 'g-children-day',
    'th-final-kong', 'g-temple', 'sp-stack-top', 'm-flowers-take', 'sp-arrow-alternate',
  ],
  stimuli: {
    poem: {
      section: POEM,
      text: 'ตื่นนอนแต่เช้า แปรงฟันล้างหน้า แต่งตัวไปโรงเรียน ขยันเรียนเขียนอ่าน ไหว้ครูสวัสดี ทักเพื่อนด้วยใจดี วันนี้มีความสุข สนุกทุกวันเอย',
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: บทกลอนตอนเช้า 5 ข้อ
    {
      id: 'th-poem-main', type: 'main', subject: 'thai', skillIds: ['main-idea'], familyId: 'passage-main', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'poem',
      prompt: { text: 'บทกลอนนี้เล่าเรื่องอะไร' },
      options: [{ id: 'a', text: 'กิจวัตรตอนเช้าก่อนไปโรงเรียน' }, { id: 'b', text: 'การไปเที่ยวทะเล' }, { id: 'c', text: 'การทำอาหารในครัว' }],
      correctOptionId: 'a',
      narration: 'ฟังบทกลอนและตัวเลือกได้ วัดการจับใจความสำคัญของบทกลอน',
      review: {
        summary: 'กลอนเล่าเรื่องการตื่นนอน แปรงฟัน แต่งตัว แล้วไปโรงเรียน',
        hints: ['ฟังว่าตัวละครทำอะไรบ้างตั้งแต่ตื่นนอน'],
        steps: ['กลอนบอกว่า ตื่นนอน แปรงฟัน ล้างหน้า แต่งตัวไปโรงเรียน', 'ไม่มีเรื่องทะเลหรือทำอาหาร ตอบข้อ 1'],
        transferIds: ['th-poem-main-t'],
      },
    },
    {
      id: 'g-poem-first', type: 'main', subject: 'general', skillIds: ['good-habits'], familyId: 'listening-sequence', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'poem',
      prompt: { text: 'ตื่นนอนแต่เช้าแล้ว ในกลอนบอกให้ทำอะไรต่อ' },
      options: [{ id: 'a', text: 'ไปตลาด' }, { id: 'b', text: 'แปรงฟันล้างหน้า' }, { id: 'c', text: 'นอนต่อ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจับลำดับกิจวัตรจากกลอน',
      review: {
        summary: 'หลังตื่นนอนให้แปรงฟันล้างหน้า',
        hints: ['ฟังคำที่อยู่ถัดจาก ตื่นนอนแต่เช้า'],
        steps: ['กลอนบอกว่า ตื่นนอนแต่เช้า แล้วต่อด้วย แปรงฟันล้างหน้า', 'ไปตลาดและนอนต่อไม่มีในกลอน ตอบข้อ 2'],
        transferIds: ['g-poem-first-t'],
      },
    },
    {
      id: 'th-poem-rhyme', type: 'main', subject: 'thai', skillIds: ['rhyme'], familyId: 'rhyme', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'poem',
      prompt: { text: 'คำใดในกลอนคล้องจองกับคำว่า เช้า' },
      options: [{ id: 'a', text: 'หน้า' }, { id: 'b', text: 'เรียน' }, { id: 'c', text: 'ครู' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ วัดการจับคำคล้องจอง (เสียงท้ายเหมือนกัน)',
      review: {
        summary: 'เช้า กับ หน้า เสียงท้ายเหมือนกัน คือ -า',
        hints: ['ลองออกเสียงท้ายของ เช้า แล้วหาคำที่เสียงท้ายเหมือนกัน'],
        steps: ['ในกลอนมีท่อนว่า ตื่นนอนแต่เช้า แปรงฟันล้างหน้า', 'เช้า กับ หน้า เสียงท้ายเหมือนกัน ตอบข้อ 1'],
        transferIds: ['th-poem-rhyme-t'],
      },
    },
    {
      id: 'th-poem-word', type: 'main', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'poem',
      prompt: { text: 'คำว่า ขยัน ในกลอน หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'ตั้งใจทำสิ่งที่ต้องทำอย่างสม่ำเสมอ' }, { id: 'b', text: 'ชอบนอนตื่นสาย' }, { id: 'c', text: 'ไม่อยากไปโรงเรียน' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ วัดความเข้าใจความหมายคำจากกลอน',
      review: {
        summary: 'ขยัน คือตั้งใจทำอย่างสม่ำเสมอ',
        hints: ['กลอนบอกว่าขยันทำอะไร'],
        steps: ['กลอนบอกว่า ขยันเรียนเขียนอ่าน คือตั้งใจเรียนทุกวัน', 'ชอบนอนตื่นสายหรือไม่อยากไปเรียนไม่ใช่ความขยัน ตอบข้อ 1'],
        transferIds: ['th-poem-word-t'],
      },
    },
    {
      id: 'r-poem-not', type: 'main', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'poem',
      prompt: { text: 'ข้อใดไม่ได้กล่าวถึงในบทกลอน' },
      options: [{ id: 'a', text: 'ไหว้ครู' }, { id: 'b', text: 'กินข้าวเช้า' }, { id: 'c', text: 'แปรงฟัน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการแยกสิ่งที่มีในกลอนกับสิ่งที่ไม่มี',
      review: {
        summary: 'ในกลอนไม่มีการกินข้าวเช้า',
        hints: ['ตรวจทีละข้อว่ากลอนพูดถึงหรือไม่'],
        steps: ['กลอนพูดถึงการไหว้ครูและการแปรงฟัน', 'กลอนไม่ได้พูดถึงการกินข้าวเช้า ตอบข้อ 2'],
        transferIds: ['r-poem-not-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: ประโยคสั้น ความสูง วัสดุ วันเด็ก
    {
      id: 'm-sentence-kinds', type: 'main', subject: 'math', skillIds: ['story-count-kinds'], familyId: 'story-kinds', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'แม่เลี้ยงไก่ เป็ด และปลา แม่เลี้ยงสัตว์กี่ชนิด' },
      options: [{ id: 'a', text: '2 ชนิด' }, { id: 'b', text: '3 ชนิด' }, { id: 'c', text: '4 ชนิด' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการนับชนิดจากประโยคสั้น',
      review: {
        summary: 'ไก่ เป็ด และปลา รวม 3 ชนิด',
        hints: ['นับทีละชนิดที่ประโยคบอกชื่อ'],
        steps: ['ประโยคบอกชื่อสัตว์ ไก่ หนึ่ง เป็ด สอง ปลา สาม', 'รวมเป็น 3 ชนิด ตอบข้อ 2'],
        transferIds: ['m-sentence-kinds-t'],
      },
    },
    {
      id: 'r-height-words', type: 'main', subject: 'reasoning', skillIds: ['seriation'], familyId: 'seriation', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ต้นกล้วยสูงกว่าต้นหญ้า ต้นมะพร้าวสูงกว่าต้นกล้วย ข้อใดเรียงจากเตี้ยไปสูงได้ถูกต้อง' },
      options: [{ id: 'a', text: 'ต้นมะพร้าว ต้นกล้วย ต้นหญ้า' }, { id: 'b', text: 'ต้นกล้วย ต้นหญ้า ต้นมะพร้าว' }, { id: 'c', text: 'ต้นหญ้า ต้นกล้วย ต้นมะพร้าว' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงลำดับความสูงจากประโยคเปรียบเทียบ',
      review: {
        summary: 'เตี้ยสุดคือต้นหญ้า ตามด้วยต้นกล้วย และสูงสุดคือต้นมะพร้าว',
        hints: ['หาต้นที่เตี้ยที่สุดก่อน คือต้นที่ไม่สูงกว่าใครเลย'],
        steps: ['ต้นกล้วยสูงกว่าต้นหญ้า และต้นมะพร้าวสูงกว่าต้นกล้วย', 'เรียงจากเตี้ยไปสูงได้ ต้นหญ้า ต้นกล้วย ต้นมะพร้าว ตอบข้อ 3'],
        transferIds: ['r-height-words-t'],
      },
    },
    {
      id: 'sc-glass-things', type: 'main', subject: 'science', skillIds: ['materials'], familyId: 'materials', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'สิ่งของสองอย่างใดทำมาจากแก้ว' },
      options: [{ id: 'a', text: 'แก้วน้ำ, กระจกหน้าต่าง' }, { id: 'b', text: 'ผ้าห่ม, เสื้อ' }, { id: 'c', text: 'ช้อน, กุญแจ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องวัสดุ (แก้ว)',
      review: {
        summary: 'แก้วน้ำและกระจกหน้าต่างทำจากแก้ว',
        hints: ['วัสดุใสๆ แข็ง ตกแล้วแตกง่าย'],
        steps: ['ผ้าห่มและเสื้อทำจากผ้า ช้อนและกุญแจทำจากโลหะ', 'แก้วน้ำและกระจกหน้าต่างทำจากแก้ว ตอบข้อ 1'],
        transferIds: ['sc-glass-things-t'],
      },
    },
    {
      id: 'sc-metal-things', type: 'main', subject: 'science', skillIds: ['materials'], familyId: 'materials', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'สิ่งของสองอย่างใดทำมาจากโลหะ' },
      options: [{ id: 'a', text: 'กระดาษ, สมุด' }, { id: 'b', text: 'จานกระเบื้อง, แก้วน้ำ' }, { id: 'c', text: 'ช้อน, กุญแจ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องวัสดุ (โลหะ)',
      review: {
        summary: 'ช้อนและกุญแจทำจากโลหะ',
        hints: ['ของแข็งมันวาว เคาะแล้วมีเสียงดังกริ๋ง'],
        steps: ['กระดาษและสมุดทำจากกระดาษ จานกระเบื้องและแก้วน้ำเป็นของแข็งที่ไม่ใช่โลหะ', 'ช้อนและกุญแจทำจากโลหะ ตอบข้อ 3'],
        transferIds: ['sc-metal-things-t'],
      },
    },
    {
      id: 'g-children-day', type: 'main', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'วันเด็กแห่งชาติตรงกับเดือนใด' },
      options: [{ id: 'a', text: 'มกราคม' }, { id: 'b', text: 'สิงหาคม' }, { id: 'c', text: 'ธันวาคม' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องวันสำคัญ (วันเด็กแห่งชาติ คือวันเสาร์ที่สองของเดือนมกราคม) ผู้ปกครองควรตรวจ',
      review: {
        summary: 'วันเด็กแห่งชาติคือวันเสาร์ที่สองของเดือนมกราคม',
        hints: ['วันเด็กอยู่ต้นปี หลังวันขึ้นปีใหม่ไม่นาน'],
        steps: ['สิงหาคมมีวันแม่ และธันวาคมมีวันพ่อกับวันสิ้นปี', 'วันเด็กแห่งชาติตรงกับเดือนมกราคม ตอบข้อ 1'],
        transferIds: ['g-children-day-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3: แม่ กง วัด กล่องซ้อน เลขลบ ภาพต่อเนื่อง
    {
      id: 'th-final-kong', type: 'main', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีตัวสะกดในแม่ กง' },
      options: [{ id: 'a', text: 'รถ' }, { id: 'b', text: 'ลิง' }, { id: 'c', text: 'ครับ' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูพยัญชนะท้ายคำเอง',
      review: {
        summary: 'ลิงมี ง เป็นตัวสะกด อยู่ในแม่ กง',
        hints: ['แม่ กง ตัวสะกดออกเสียงท้ายเหมือนตัว ง'],
        steps: ['รถมี ถ เป็นตัวสะกด อยู่ในแม่ กด และครับมี บ เป็นตัวสะกด อยู่ในแม่ กบ', 'ลิงมี ง เป็นตัวสะกด ตอบข้อ 2'],
        transferIds: ['th-final-kong-t'],
      },
    },
    {
      id: 'g-temple', type: 'main', subject: 'general', skillIds: ['community-places'], familyId: 'religion-places', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ชาวพุทธไปทำบุญและฟังธรรมที่ใด' },
      options: [{ id: 'a', text: 'ตลาด' }, { id: 'b', text: 'โรงพยาบาล' }, { id: 'c', text: 'วัด' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสถานที่ทางศาสนา (ผู้ปกครองควรตรวจถ้อยคำ)',
      review: {
        summary: 'วัดเป็นที่ที่ชาวพุทธไปทำบุญและฟังธรรม',
        hints: ['พระสงฆ์อยู่ที่ไหน'],
        steps: ['ตลาดใช้ซื้อของ โรงพยาบาลใช้รักษาคนป่วย', 'วัดเป็นสถานที่ที่ชาวพุทธไปทำบุญและฟังธรรม ตอบข้อ 3'],
        transferIds: ['g-temple-t'],
      },
    },
    {
      id: 'sp-stack-top', type: 'main', subject: 'spatial', skillIds: ['count-blocks'], familyId: 'stacks', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ถ้ามองกล่องที่ซ้อนกันนี้จากด้านบน จะเห็นสี่เหลี่ยมกี่รูป' },
      visual: { type: 'stack', columns: [2, 3, 1] },
      options: [{ id: 'a', text: '6 รูป' }, { id: 'b', text: '3 รูป' }, { id: 'c', text: '2 รูป' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ เสียงไม่บอกจำนวน เด็กต้องนับจากภาพเอง (มองจากด้านบนเห็นหนึ่งรูปต่อหนึ่งแถวตั้ง)',
      review: {
        summary: 'มี 3 แถวตั้ง มองจากด้านบนเห็นสี่เหลี่ยม 3 รูป',
        hints: ['มองจากด้านบน กล่องที่ซ้อนกันอยู่ใต้กล่องบนสุดจะมองไม่เห็น'],
        steps: ['กล่องซ้อนกันมี 3 แถวตั้ง', 'ด้านบนของแต่ละแถวตั้งเห็นเป็นสี่เหลี่ยมหนึ่งรูป รวม 3 รูป ตอบข้อ 2'],
        transferIds: ['sp-stack-top-t'],
      },
    },
    {
      id: 'm-flowers-take', type: 'main', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'story-number', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ในสวนมีดอกไม้ 14 ดอก เด็กเด็ดไป 6 ดอก เหลือดอกไม้ในสวนกี่ดอก' },
      options: [{ id: 'a', text: '8 ดอก' }, { id: 'b', text: '20 ดอก' }, { id: 'c', text: '9 ดอก' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดโจทย์ลบที่ต้องยืมสิบ',
      review: {
        summary: '14 ลบ 6 เท่ากับ 8 ดอก',
        hints: ['เหลือคือเอาที่หายไปออกจากทั้งหมด ใช้การลบ'],
        steps: ['มีดอกไม้ 14 ดอก เด็กเด็ดไป 6 ดอก ต้องเอา 6 ไปลบออกจาก 14', '14 ลบ 6 เท่ากับ 8 ตอบข้อ 1'],
        column: { a: 14, op: '-', b: 6 },
        transferIds: ['m-flowers-take-t'],
      },
    },
    {
      id: 'sp-arrow-alternate', type: 'main', subject: 'spatial', skillIds: ['pattern-continue'], familyId: 'arrow-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [arrow('up'), arrow('down'), arrow('up'), arrow('down'), '?'] },
      options: [fig('a', arrow('down')), fig('b', arrow('left')), fig('c', arrow('up')), fig('d', arrow('right'))],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการต่อภาพที่สลับขึ้นลง',
      review: {
        summary: 'ลูกศรชี้ขึ้นกับชี้ลงสลับกัน ต่อไปคือชี้ขึ้น',
        hints: ['ดูว่าลูกศรสลับกันอย่างไร แล้วภาพสุดท้ายก่อนช่องคืออะไร'],
        steps: ['เรียงเป็น ขึ้น ลง ขึ้น ลง สลับกันไปเรื่อยๆ', 'ต่อจากชี้ลงต้องเป็นชี้ขึ้น ตอบข้อ 3'],
        transferIds: ['sp-arrow-alternate-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-poem-main-t', type: 'transfer', subject: 'thai', skillIds: ['main-idea'], familyId: 'passage-main', difficulty: 2,
      sourceId: SRC, ...R, section: POEM,
      prompt: { text: 'ฟังกลอน ฝนตกพรำพรำ ชุ่มฉ่ำใบไม้ ต้นข้าวงามไสว ชาวนาดีใจ ฝนตกพรำๆ ทำให้ใคร ดีใจ' },
      options: [{ id: 'a', text: 'ชาวนา' }, { id: 'b', text: 'นักดับเพลิง' }, { id: 'c', text: 'หมอ' }],
      correctOptionId: 'a',
      narration: 'ฟังกลอนได้',
      review: { summary: 'ฝนทำให้ต้นข้าวงาม ชาวนาจึงดีใจ', hints: [], steps: ['กลอนบอกว่า ต้นข้าวงามไสว ชาวนาดีใจ', 'จึงตอบชาวนา'] },
    },
    {
      id: 'g-poem-first-t', type: 'transfer', subject: 'general', skillIds: ['good-habits'], familyId: 'listening-sequence', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ก่อนกินข้าว ควรทำอะไรก่อน' },
      options: [{ id: 'a', text: 'ล้างมือให้สะอาด' }, { id: 'b', text: 'วิ่งเล่นในดิน' }, { id: 'c', text: 'นอนหลับ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ล้างมือก่อนกินข้าวทุกครั้ง', hints: [], steps: ['วิ่งเล่นในดินทำให้มือสกปรก', 'ควรล้างมือให้สะอาดก่อนกินข้าว'] },
    },
    {
      id: 'th-poem-rhyme-t', type: 'transfer', subject: 'thai', skillIds: ['rhyme'], familyId: 'rhyme', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดคล้องจองกับคำว่า ปลา' },
      options: [{ id: 'a', text: 'นก' }, { id: 'b', text: 'ม้า' }, { id: 'c', text: 'ลิง' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ปลา กับ ม้า เสียงท้ายเหมือนกัน คือ -า', hints: [], steps: ['นกและลิงเสียงท้ายต่างจากปลา', 'ปลา กับ ม้า เสียงท้ายเหมือนกัน'] },
    },
    {
      id: 'th-poem-word-t', type: 'transfer', subject: 'thai', skillIds: ['word-meaning'], familyId: 'word-in-story', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'คำว่า ใจดี หมายความว่าอย่างไร' },
      options: [{ id: 'a', text: 'ชอบช่วยเหลือและเมตตาผู้อื่น' }, { id: 'b', text: 'ชอบทะเลาะกับเพื่อน' }, { id: 'c', text: 'ชอบนอนตลอดวัน' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ใจดี คือมีน้ำใจช่วยเหลือผู้อื่น', hints: [], steps: ['ทะเลาะกับเพื่อนไม่ใช่คนใจดี', 'คนใจดีชอบช่วยเหลือผู้อื่น'] },
    },
    {
      id: 'r-poem-not-t', type: 'transfer', subject: 'reasoning', skillIds: ['story-detail'], familyId: 'story-not', difficulty: 2,
      sourceId: SRC, ...R, section: POEM,
      prompt: { text: 'ฟังกลอน ลูกไก่เจี๊ยบเจี๊ยบ เดินเรียบริมรั้ว แม่ไก่ตามหลัง ระวังทุกตัว ข้อใดไม่ได้กล่าวถึงในกลอน' },
      options: [{ id: 'a', text: 'ลูกไก่' }, { id: 'b', text: 'แม่ไก่' }, { id: 'c', text: 'ลูกเป็ด' }],
      correctOptionId: 'c',
      narration: 'ฟังกลอนได้',
      review: { summary: 'ในกลอนไม่มีลูกเป็ด', hints: [], steps: ['กลอนพูดถึงลูกไก่และแม่ไก่', 'กลอนไม่ได้พูดถึงลูกเป็ด'] },
    },
    {
      id: 'm-sentence-kinds-t', type: 'transfer', subject: 'math', skillIds: ['story-count-kinds'], familyId: 'story-kinds', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ในตะกร้ามีส้ม กล้วย ส้ม มะม่วง และกล้วย ในตะกร้ามีผลไม้กี่ชนิด' },
      options: [{ id: 'a', text: '3 ชนิด' }, { id: 'b', text: '5 ชนิด' }, { id: 'c', text: '2 ชนิด' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ส้ม กล้วย มะม่วง รวม 3 ชนิด', hints: [], steps: ['ส้มกับกล้วยมีซ้ำกัน นับเป็นชนิดเดียวต่อชนิด', 'ส้ม กล้วย มะม่วง รวม 3 ชนิด'] },
    },
    {
      id: 'r-height-words-t', type: 'transfer', subject: 'reasoning', skillIds: ['seriation'], familyId: 'seriation', difficulty: 3,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'พ่อสูงกว่าแม่ แม่สูงกว่าน้อง ข้อใดเรียงจากสูงไปเตี้ยได้ถูกต้อง' },
      options: [{ id: 'a', text: 'พ่อ แม่ น้อง' }, { id: 'b', text: 'น้อง แม่ พ่อ' }, { id: 'c', text: 'แม่ พ่อ น้อง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'พ่อสูงสุด ตามด้วยแม่ และน้องเตี้ยที่สุด', hints: [], steps: ['พ่อสูงกว่าแม่ และแม่สูงกว่าน้อง', 'เรียงจากสูงไปเตี้ยได้ พ่อ แม่ น้อง'] },
    },
    {
      id: 'sc-glass-things-t', type: 'transfer', subject: 'science', skillIds: ['materials'], familyId: 'materials', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ของที่ทำจากแก้ว เมื่อตกลงพื้นแรงๆ มักจะเป็นอย่างไร' },
      options: [{ id: 'a', text: 'แตกได้ง่าย' }, { id: 'b', text: 'เด้งขึ้นไปในอากาศ' }, { id: 'c', text: 'ละลายหายไป' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แก้วแข็งแต่แตกง่าย', hints: [], steps: ['แก้วไม่เด้งและไม่ละลาย', 'ตกพื้นแรงๆ แก้วแตกได้ง่าย'] },
    },
    {
      id: 'sc-metal-things-t', type: 'transfer', subject: 'science', skillIds: ['materials'], familyId: 'materials', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'สิ่งของสองอย่างใดทำมาจากโลหะ' },
      options: [{ id: 'a', text: 'ส้อม, ตะปู' }, { id: 'b', text: 'ยางลบ, ดินสอ' }, { id: 'c', text: 'หมอน, ผ้าห่ม' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ส้อมและตะปูทำจากโลหะ', hints: [], steps: ['ยางลบทำจากยาง ดินสอทำจากไม้ หมอนและผ้าห่มทำจากผ้า', 'ส้อมและตะปูทำจากโลหะ'] },
    },
    {
      id: 'g-children-day-t', type: 'transfer', subject: 'general', skillIds: ['important-days'], familyId: 'important-days', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'วันขึ้นปีใหม่ตรงกับวันที่เท่าไร' },
      options: [{ id: 'a', text: '1 มกราคม' }, { id: 'b', text: '13 เมษายน' }, { id: 'c', text: '12 สิงหาคม' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วันขึ้นปีใหม่คือวันที่ 1 มกราคม', hints: [], steps: ['13 เมษายนคือวันสงกรานต์ และ 12 สิงหาคมคือวันแม่', 'วันขึ้นปีใหม่คือ 1 มกราคม'] },
    },
    {
      id: 'th-final-kong-t', type: 'transfer', subject: 'thai', skillIds: ['final-consonant'], familyId: 'final-consonant', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำในข้อใดมีตัวสะกดในแม่ กง' },
      options: [{ id: 'a', text: 'ช้าง' }, { id: 'b', text: 'นก' }, { id: 'c', text: 'ปลา' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ แต่ต้องดูพยัญชนะท้ายคำเอง',
      review: { summary: 'ช้างมี ง เป็นตัวสะกด อยู่ในแม่ กง', hints: [], steps: ['นกมี ก เป็นตัวสะกด และปลาไม่มีตัวสะกด', 'ช้างมี ง เป็นตัวสะกด'] },
    },
    {
      id: 'g-temple-t', type: 'transfer', subject: 'general', skillIds: ['community-places'], familyId: 'religion-places', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เด็กๆ เรียนหนังสือที่ใด' },
      options: [{ id: 'a', text: 'โรงเรียน' }, { id: 'b', text: 'ตลาด' }, { id: 'c', text: 'สนามบิน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เด็กๆ เรียนหนังสือที่โรงเรียน', hints: [], steps: ['ตลาดใช้ซื้อของ และสนามบินใช้เดินทางโดยเครื่องบิน', 'เด็กๆ เรียนหนังสือที่โรงเรียน'] },
    },
    {
      id: 'sp-stack-top-t', type: 'transfer', subject: 'spatial', skillIds: ['count-blocks'], familyId: 'stacks', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ถ้ามองกล่องที่ซ้อนกันนี้จากด้านบน จะเห็นสี่เหลี่ยมกี่รูป' },
      visual: { type: 'stack', columns: [1, 4, 2, 3] },
      options: [{ id: 'a', text: '10 รูป' }, { id: 'b', text: '3 รูป' }, { id: 'c', text: '4 รูป' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มี 4 แถวตั้ง มองจากด้านบนเห็นสี่เหลี่ยม 4 รูป', hints: [], steps: ['กล่องซ้อนกันมี 4 แถวตั้ง', 'ด้านบนของแต่ละแถวตั้งเห็นเป็นสี่เหลี่ยมหนึ่งรูป รวม 4 รูป'] },
    },
    {
      id: 'm-flowers-take-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'story-number', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'บนจานมีขนม 15 ชิ้น น้องกินไป 7 ชิ้น เหลือขนมกี่ชิ้น' },
      options: [{ id: 'a', text: '22 ชิ้น' }, { id: 'b', text: '9 ชิ้น' }, { id: 'c', text: '8 ชิ้น' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '15 ลบ 7 เท่ากับ 8 ชิ้น', hints: [], steps: ['มีขนม 15 ชิ้น กินไป 7 ชิ้น ต้องเอา 7 ไปลบออกจาก 15', '15 ลบ 7 เท่ากับ 8'], column: { a: 15, op: '-', b: 7 } },
    },
    {
      id: 'sp-arrow-alternate-t', type: 'transfer', subject: 'spatial', skillIds: ['pattern-continue'], familyId: 'arrow-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [arrow('left'), arrow('right'), arrow('left'), arrow('right'), '?'] },
      options: [fig('a', arrow('up')), fig('b', arrow('left')), fig('c', arrow('right')), fig('d', arrow('down'))],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'ลูกศรชี้ซ้ายกับชี้ขวาสลับกัน ต่อไปคือชี้ซ้าย', hints: [], steps: ['เรียงเป็น ซ้าย ขวา ซ้าย ขวา สลับกัน', 'ต่อจากชี้ขวาต้องเป็นชี้ซ้าย'] },
    },
  ],
};
