/*
 * ชุดที่ 28 — ปฏิทิน จิ๊กซอว์ และใกล้-ไกล (ภาพวาดด้วยโค้ดแบบใหม่ ดู docs/CONTENT-SPEC.md: calendar, jigsaw, distance, ตัวเลือก piece) แบบ 15 ข้อ
 * ช่วง 1 ปฏิทินเดือนตุลาคม 2026 (วันที่ 1 เป็นวันพฤหัสบดี) ถาม 5 ข้อ: วันที่ 1 วันที่ 10 นับวันอาทิตย์ บวก 7 วัน วันศุกร์วันแรก
 * ช่วง 2 ข้อเดี่ยว: จิ๊กซอว์ 2 ข้อ (ภาพขาดหนึ่งชิ้น) ใกล้-ไกล 2 ข้อ คำตรงข้าม
 * ช่วง 3 ข้อเดี่ยว: ท้องฟ้ากลางคืน ฤดูฝน พรุ่งนี้เป็นวันเสาร์ วันเด็ก เรียงคำเป็นประโยค
 * แต่งใหม่ทั้งหมด; จิ๊กซอว์ครอปจากรูปที่มีอยู่ ไม่ต้องสร้างรูปใหม่
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const CAL = 'ดูปฏิทินแล้วตอบคำถามให้ถูกต้อง';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const piece = (id, asset, cell) => ({ id, svg: { piece: { asset: `pic-${asset}`, cell } } });
// ปฏิทินจริงของเดือนตุลาคม 2026 และพฤศจิกายน 2026 (tests/visuals3.test.mjs ตรวจเทียบกับวันที่จริง)
const OCT = { type: 'calendar', month: 'ตุลาคม', start: 4, days: 31, marks: [10] };
const NOV = { type: 'calendar', month: 'พฤศจิกายน', start: 0, days: 30, marks: [] };
const houses = (...sizes) => ({ type: 'distance', items: sizes.map((size) => ({ asset: 'pic-house', size })) });

export default {
  id: 'set-28',
  version: 1,
  title: 'ชุดที่ 28',
  note: 'ปฏิทิน จิ๊กซอว์ ใกล้-ไกล พรุ่งนี้วันเสาร์ คำตรงข้าม',
  order: [
    'g-cal-first', 'r-cal-tenth', 'm-cal-sundays', 'm-cal-plus7', 'r-cal-friday',
    'sp-jigsaw-mountain', 'sp-jigsaw-school', 'sp-distance-far', 'sp-distance-near', 'th-opposite-near',
    'sc-sky-night', 'sc-rain-season', 'g-weekday-prev', 'm-children-day', 'th-sentence-order',
  ],
  stimuli: {
    cal: {
      section: CAL,
      text: 'ปฏิทินเดือนตุลาคม ตัวเลขสีแดงคือวันอาทิตย์ วันที่ 10 มีวงกลมล้อมไว้ ดูปฏิทินแล้วตอบคำถาม',
      visual: OCT,
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: ปฏิทินเดือนตุลาคม 5 ข้อ
    {
      id: 'g-cal-first', type: 'main', subject: 'general', skillIds: ['days-of-week'], familyId: 'date-weekday', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'cal',
      prompt: { text: 'วันที่ 1 ของเดือนนี้เป็นวันอะไร' },
      options: [{ id: 'a', text: 'วันพุธ' }, { id: 'b', text: 'วันพฤหัสบดี' }, { id: 'c', text: 'วันศุกร์' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการอ่านปฏิทิน (ตัวย่อ พฤ = พฤหัสบดี)',
      review: {
        summary: 'วันที่ 1 อยู่ใต้ พฤ จึงเป็นวันพฤหัสบดี',
        hints: ['ดูตัวเลข 1 อยู่ใต้ตัวอักษรอะไรในแถวบนสุด'],
        steps: ['แถวบนสุดคือ อา จ อ พ พฤ ศ ส เรียงเป็นวันอาทิตย์ถึงวันเสาร์', 'ตัวเลข 1 อยู่ใต้ พฤ คือวันพฤหัสบดี ตอบข้อ 2'],
        transferIds: ['g-cal-first-t'],
      },
    },
    {
      id: 'r-cal-tenth', type: 'main', subject: 'reasoning', skillIds: ['calendar'], familyId: 'date-weekday', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'cal',
      prompt: { text: 'วันที่ 10 ซึ่งมีวงกลมล้อมไว้ เป็นวันอะไร' },
      options: [{ id: 'a', text: 'วันศุกร์' }, { id: 'b', text: 'วันอาทิตย์' }, { id: 'c', text: 'วันเสาร์' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการอ่านปฏิทิน (ตัวย่อ ส = เสาร์)',
      review: {
        summary: 'วันที่ 10 อยู่ใต้ ส จึงเป็นวันเสาร์',
        hints: ['ดูวันที่ 10 อยู่ใต้ตัวอักษรอะไร'],
        steps: ['ตัวเลข 10 อยู่ใต้ ส คือวันเสาร์', 'วันที่ 4 เป็นวันอาทิตย์ นับต่อไปถึงวันที่ 10 ก็เป็นวันเสาร์ ตอบข้อ 3'],
        transferIds: ['r-cal-tenth-t'],
      },
    },
    {
      id: 'm-cal-sundays', type: 'main', subject: 'math', skillIds: ['calendar'], familyId: 'calendar-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'cal',
      prompt: { text: 'เดือนนี้มีวันอาทิตย์กี่วัน' },
      options: [{ id: 'a', text: '4 วัน' }, { id: 'b', text: '5 วัน' }, { id: 'c', text: '3 วัน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการนับวันในปฏิทิน (วันอาทิตย์เป็นตัวเลขสีแดง)',
      review: {
        summary: 'วันอาทิตย์คือวันที่ 4 11 18 และ 25 รวม 4 วัน',
        hints: ['นับตัวเลขสีแดงในปฏิทิน'],
        steps: ['ตัวเลขสีแดงคือวันที่ 4 วันที่ 11 วันที่ 18 และวันที่ 25', 'นับได้ 4 วัน ตอบข้อ 1'],
        transferIds: ['m-cal-sundays-t'],
      },
    },
    {
      id: 'm-cal-plus7', type: 'main', subject: 'math', skillIds: ['number-before-after'], familyId: 'date-next', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'cal',
      prompt: { text: 'วันที่ 15 ผ่านไปอีก 7 วัน จะเป็นวันที่เท่าไร' },
      options: [{ id: 'a', text: 'วันที่ 21' }, { id: 'b', text: 'วันที่ 22' }, { id: 'c', text: 'วันที่ 23' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบวกวันที่ (7 วันคือหนึ่งสัปดาห์ ตรงกับวันเดียวกันในแถวถัดไป)',
      review: {
        summary: '15 บวก 7 เท่ากับ 22 อยู่ใต้วันเดียวกันในแถวถัดไป',
        hints: ['หนึ่งสัปดาห์มี 7 วัน ลงมาแถวถัดไปใต้ตัวอักษรเดิม'],
        steps: ['วันที่ 15 ผ่านไป 7 วัน ต้องเอา 7 มาบวก', '15 บวก 7 เท่ากับ 22 ตอบข้อ 2'],
        column: { a: 15, op: '+', b: 7 },
        transferIds: ['m-cal-plus7-t'],
      },
    },
    {
      id: 'r-cal-friday', type: 'main', subject: 'reasoning', skillIds: ['calendar'], familyId: 'date-weekday', difficulty: 3,
      sourceId: SRC, ...R, stimulus: 'cal',
      prompt: { text: 'วันศุกร์วันแรกของเดือนนี้ตรงกับวันที่เท่าไร' },
      options: [{ id: 'a', text: 'วันที่ 1' }, { id: 'b', text: 'วันที่ 3' }, { id: 'c', text: 'วันที่ 2' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการหาวันที่ในปฏิทิน (ศ = ศุกร์)',
      review: {
        summary: 'วันที่ 2 อยู่ใต้ ศ เป็นวันศุกร์วันแรก',
        hints: ['ดูตัวเลขแถวแรกที่อยู่ใต้ ศ'],
        steps: ['วันที่ 1 อยู่ใต้ พฤ คือวันพฤหัสบดี วันถัดไปคือวันที่ 2', 'วันที่ 2 อยู่ใต้ ศ เป็นวันศุกร์ ตอบข้อ 3'],
        transferIds: ['r-cal-friday-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: จิ๊กซอว์ ใกล้-ไกล
    {
      id: 'sp-jigsaw-mountain', type: 'main', subject: 'spatial', skillIds: ['jigsaw'], familyId: 'jigsaw', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพนี้ขาดไปหนึ่งชิ้น ชิ้นส่วนใดใส่ในช่อง ? ได้พอดี' },
      visual: { type: 'jigsaw', asset: 'pic-mountain', missing: 'br' },
      options: [piece('a', 'mountain', 'tl'), piece('b', 'beach', 'br'), piece('c', 'mountain', 'br'), piece('d', 'waterfall', 'br')],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการมองว่าชิ้นส่วนใดต่อกับภาพที่เหลือ',
      review: {
        summary: 'ชิ้นที่ถูกคือชิ้นมุมขวาล่างของภูเขาภาพเดียวกัน',
        hints: ['ดูสีและเส้นที่ต่อจากภาพที่เหลือ'],
        steps: ['ชิ้นอื่นมาจากภาพทะเลหรือน้ำตก หรือเป็นมุมอื่นของภูเขา สีและเส้นไม่ต่อกัน', 'ชิ้นมุมขวาล่างของภูเขาต่อกับภาพได้พอดี ตอบข้อ 3'],
        transferIds: ['sp-jigsaw-beach-t'],
      },
    },
    {
      id: 'sp-jigsaw-school', type: 'main', subject: 'spatial', skillIds: ['jigsaw'], familyId: 'jigsaw', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพนี้ขาดไปหนึ่งชิ้น ชิ้นส่วนใดใส่ในช่อง ? ได้พอดี' },
      visual: { type: 'jigsaw', asset: 'pic-school', missing: 'tl' },
      options: [piece('a', 'school', 'tl'), piece('b', 'school', 'br'), piece('c', 'market', 'tl'), piece('d', 'school', 'tr')],
      correctOptionId: 'a',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการมองว่าชิ้นส่วนใดต่อกับภาพที่เหลือ',
      review: {
        summary: 'ชิ้นที่ถูกคือชิ้นมุมซ้ายบนของโรงเรียนภาพเดียวกัน',
        hints: ['ชิ้นนี้ต้องมาจากภาพโรงเรียน และต้องเป็นมุมซ้ายบน'],
        steps: ['ชิ้นของตลาดเป็นคนละภาพ และชิ้นมุมอื่นของโรงเรียนไม่ใช่มุมที่ขาด', 'ชิ้นมุมซ้ายบนของโรงเรียนต่อได้พอดี ตอบข้อ 1'],
        transferIds: ['sp-jigsaw-market-t'],
      },
    },
    {
      id: 'sp-distance-far', type: 'main', subject: 'spatial', skillIds: ['near-far'], familyId: 'near-far', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'บ้านหลังใดอยู่ไกลจากเรามากที่สุด' },
      visual: houses(0.4, 1, 0.7),
      options: [{ id: 'a', text: 'หลังที่ 1' }, { id: 'b', text: 'หลังที่ 2' }, { id: 'c', text: 'หลังที่ 3' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจว่าของที่อยู่ไกลจะดูเล็กกว่า',
      review: {
        summary: 'หลังที่ 1 เล็กที่สุด จึงอยู่ไกลที่สุด',
        hints: ['บ้านหลังเดียวกัน ถ้าอยู่ไกลจะดูเล็กลง'],
        steps: ['บ้านทุกหลังขนาดจริงเท่ากัน แต่ที่อยู่ไกลจะดูเล็กกว่า', 'หลังที่ 1 เล็กที่สุด อยู่ไกลที่สุด ตอบข้อ 1'],
        transferIds: ['sp-distance-trees-t'],
      },
    },
    {
      id: 'sp-distance-near', type: 'main', subject: 'spatial', skillIds: ['near-far'], familyId: 'near-far', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ต้นมะม่วงต้นใดอยู่ใกล้เรามากที่สุด' },
      visual: { type: 'distance', items: [{ asset: 'pic-mango-tree', size: 0.6 }, { asset: 'pic-mango-tree', size: 0.35 }, { asset: 'pic-mango-tree', size: 1 }, { asset: 'pic-mango-tree', size: 0.8 }] },
      options: [{ id: 'a', text: 'ต้นที่ 1' }, { id: 'b', text: 'ต้นที่ 2' }, { id: 'c', text: 'ต้นที่ 3' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจว่าของที่อยู่ใกล้จะดูใหญ่กว่า',
      review: {
        summary: 'ต้นที่ 3 ใหญ่ที่สุด จึงอยู่ใกล้ที่สุด',
        hints: ['ต้นไม้ที่อยู่ใกล้จะดูใหญ่ที่สุด'],
        steps: ['ต้นมะม่วงทุกต้นสูงเท่ากันจริงๆ แต่ที่อยู่ใกล้จะดูใหญ่กว่า', 'ต้นที่ 3 ใหญ่ที่สุด อยู่ใกล้ที่สุด ตอบข้อ 3'],
        transferIds: ['sp-distance-near-t'],
      },
    },
    {
      id: 'th-opposite-near', type: 'main', subject: 'thai', skillIds: ['opposite-words'], familyId: 'opposite-words', difficulty: 1,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำว่า ใกล้ มีความหมายตรงข้ามกับคำใด' },
      options: [{ id: 'a', text: 'ไกล' }, { id: 'b', text: 'สูง' }, { id: 'c', text: 'เร็ว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดคำตรงข้าม',
      review: {
        summary: 'ใกล้ ตรงข้ามกับ ไกล',
        hints: ['อะไรอยู่ตรงข้ามกับใกล้ คือห่างออกไปมาก'],
        steps: ['สูงตรงข้ามกับเตี้ย และเร็วตรงข้ามกับช้า', 'ใกล้ตรงข้ามกับไกล ตอบข้อ 1'],
        transferIds: ['th-opposite-near-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3: ท้องฟ้า ฤดู วัน วันเด็ก ประโยค
    {
      id: 'sc-sky-night', type: 'main', subject: 'science', skillIds: ['sky'], familyId: 'sky', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ตอนกลางคืนเรามักเห็นอะไรบนท้องฟ้า' },
      options: [{ id: 'a', text: 'ดวงอาทิตย์' }, { id: 'b', text: 'ดวงจันทร์และดาว' }, { id: 'c', text: 'รุ้ง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องท้องฟ้า',
      review: {
        summary: 'กลางคืนเห็นดวงจันทร์และดาว',
        hints: ['ตอนกลางคืนท้องฟ้ามืด มีอะไรส่องสว่างให้เห็น'],
        steps: ['ดวงอาทิตย์เห็นตอนกลางวัน และรุ้งเกิดหลังฝนตกตอนมีแดด', 'กลางคืนเห็นดวงจันทร์และดาว ตอบข้อ 2'],
        transferIds: ['sc-sky-night-t'],
      },
    },
    {
      id: 'sc-rain-season', type: 'main', subject: 'science', skillIds: ['seasons'], familyId: 'seasons', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ฤดูที่ฝนตกบ่อยที่สุดในประเทศไทยคือฤดูอะไร' },
      options: [{ id: 'a', text: 'ฤดูหนาว' }, { id: 'b', text: 'ฤดูร้อน' }, { id: 'c', text: 'ฤดูฝน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องฤดู',
      review: {
        summary: 'ฤดูฝนมีฝนตกบ่อยที่สุด',
        hints: ['ชื่อของฤดูบอกอยู่แล้วว่าฝนตกบ่อย'],
        steps: ['ฤดูหนาวอากาศเย็น ฤดูร้อนอากาศร้อน', 'ฤดูที่ฝนตกบ่อยคือฤดูฝน ตอบข้อ 3'],
        transferIds: ['sc-rain-season-t'],
      },
    },
    {
      id: 'g-weekday-prev', type: 'main', subject: 'general', skillIds: ['days-of-week'], familyId: 'days-of-week', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'พรุ่งนี้เป็นวันเสาร์ วันนี้เป็นวันอะไร' },
      options: [{ id: 'a', text: 'วันศุกร์' }, { id: 'b', text: 'วันอาทิตย์' }, { id: 'c', text: 'วันพฤหัสบดี' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการนับวันย้อนหลัง',
      review: {
        summary: 'ก่อนวันเสาร์คือวันศุกร์',
        hints: ['วันก่อนเสาร์คือวันอะไร'],
        steps: ['วันเรียงกัน พฤหัสบดี ศุกร์ เสาร์ อาทิตย์', 'ก่อนวันเสาร์คือวันศุกร์ ตอบข้อ 1'],
        transferIds: ['g-weekday-prev-t'],
      },
    },
    {
      id: 'm-children-day', type: 'main', subject: 'math', skillIds: ['number-before-after'], familyId: 'date-next', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'วันเด็กแห่งชาติตรงกับวันเสาร์ที่สองของเดือนมกราคม ถ้าวันเสาร์แรกของเดือนคือวันที่ 3 วันเด็กตรงกับวันที่เท่าไร' },
      options: [{ id: 'a', text: 'วันที่ 9' }, { id: 'b', text: 'วันที่ 10' }, { id: 'c', text: 'วันที่ 17' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบวกวันที่ของสัปดาห์ถัดไป (วันเด็กแห่งชาติ ผู้ปกครองควรตรวจ)',
      review: {
        summary: 'วันเสาร์ถัดไปคือ 3 บวก 7 เท่ากับวันที่ 10',
        hints: ['วันเสาร์วันถัดไป ผ่านไปหนึ่งสัปดาห์คือ 7 วัน'],
        steps: ['วันเสาร์แรกคือวันที่ 3 วันเสาร์ที่สองห่างออกไป 7 วัน', '3 บวก 7 เท่ากับ 10 ตอบข้อ 2'],
        column: { a: 3, op: '+', b: 7 },
        transferIds: ['m-children-day-t'],
      },
    },
    {
      id: 'th-sentence-order', type: 'main', subject: 'thai', skillIds: ['sentence-type'], familyId: 'sentence-order', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ข้อใดเรียงคำเป็นประโยคได้ถูกต้อง' },
      options: [{ id: 'a', text: 'ไปหนูโรงเรียน' }, { id: 'b', text: 'หนูไปโรงเรียน' }, { id: 'c', text: 'โรงเรียนไปหนู' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการเรียงคำเป็นประโยค',
      review: {
        summary: 'หนูไปโรงเรียน เรียงเป็นประโยคที่มีความหมาย',
        hints: ['ประโยคต้องบอกว่าใครทำอะไรที่ไหน'],
        steps: ['ไปหนูโรงเรียน และโรงเรียนไปหนู อ่านแล้วไม่มีความหมาย', 'หนูไปโรงเรียน บอกว่าใครทำอะไรที่ไหน ตอบข้อ 2'],
        transferIds: ['th-sentence-order-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'g-cal-first-t', type: 'transfer', subject: 'general', skillIds: ['days-of-week'], familyId: 'date-weekday', difficulty: 1,
      sourceId: SRC, ...R, section: CAL,
      prompt: { text: 'ปฏิทินเดือนพฤศจิกายน วันที่ 1 ของเดือนนี้เป็นวันอะไร' },
      visual: NOV,
      options: [{ id: 'a', text: 'วันอาทิตย์' }, { id: 'b', text: 'วันจันทร์' }, { id: 'c', text: 'วันเสาร์' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วันที่ 1 อยู่ใต้ อา เป็นวันอาทิตย์', hints: [], steps: ['แถวบนสุดคือ อา จ อ พ พฤ ศ ส', 'ตัวเลข 1 อยู่ใต้ อา คือวันอาทิตย์'] },
    },
    {
      id: 'r-cal-tenth-t', type: 'transfer', subject: 'reasoning', skillIds: ['calendar'], familyId: 'date-weekday', difficulty: 2,
      sourceId: SRC, ...R, section: CAL,
      prompt: { text: 'ปฏิทินเดือนพฤศจิกายน วันที่ 14 เป็นวันอะไร' },
      visual: NOV,
      options: [{ id: 'a', text: 'วันศุกร์' }, { id: 'b', text: 'วันเสาร์' }, { id: 'c', text: 'วันอาทิตย์' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วันที่ 14 อยู่ใต้ ส เป็นวันเสาร์', hints: [], steps: ['วันอาทิตย์คือวันที่ 1 8 15 วันก่อนวันที่ 15 คือวันที่ 14', 'วันที่ 14 อยู่ใต้ ส คือวันเสาร์'] },
    },
    {
      id: 'm-cal-sundays-t', type: 'transfer', subject: 'math', skillIds: ['calendar'], familyId: 'calendar-count', difficulty: 2,
      sourceId: SRC, ...R, section: CAL,
      prompt: { text: 'ปฏิทินเดือนพฤศจิกายน เดือนนี้มีวันอาทิตย์กี่วัน' },
      visual: NOV,
      options: [{ id: 'a', text: '4 วัน' }, { id: 'b', text: '3 วัน' }, { id: 'c', text: '5 วัน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วันอาทิตย์คือวันที่ 1 8 15 22 และ 29 รวม 5 วัน', hints: [], steps: ['ตัวเลขสีแดงคือวันที่ 1 8 15 22 และ 29', 'นับได้ 5 วัน'] },
    },
    {
      id: 'm-cal-plus7-t', type: 'transfer', subject: 'math', skillIds: ['number-before-after'], familyId: 'date-next', difficulty: 2,
      sourceId: SRC, ...R, section: CAL,
      prompt: { text: 'ปฏิทินเดือนพฤศจิกายน วันที่ 8 ผ่านไปอีก 7 วัน จะเป็นวันที่เท่าไร' },
      visual: NOV,
      options: [{ id: 'a', text: 'วันที่ 14' }, { id: 'b', text: 'วันที่ 16' }, { id: 'c', text: 'วันที่ 15' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '8 บวก 7 เท่ากับ 15', hints: [], steps: ['วันที่ 8 ผ่านไปอีก 7 วัน ต้องเอา 7 มาบวก', '8 บวก 7 เท่ากับ 15'], column: { a: 8, op: '+', b: 7 } },
    },
    {
      id: 'r-cal-friday-t', type: 'transfer', subject: 'reasoning', skillIds: ['calendar'], familyId: 'date-weekday', difficulty: 3,
      sourceId: SRC, ...R, section: CAL,
      prompt: { text: 'ปฏิทินเดือนพฤศจิกายน วันศุกร์วันแรกของเดือนนี้ตรงกับวันที่เท่าไร' },
      visual: NOV,
      options: [{ id: 'a', text: 'วันที่ 5' }, { id: 'b', text: 'วันที่ 6' }, { id: 'c', text: 'วันที่ 7' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'วันที่ 6 อยู่ใต้ ศ เป็นวันศุกร์วันแรก', hints: [], steps: ['วันที่ 1 เป็นวันอาทิตย์ นับต่อ จันทร์ 2 อังคาร 3 พุธ 4 พฤหัสบดี 5', 'วันศุกร์คือวันที่ 6'] },
    },
    {
      id: 'sp-jigsaw-beach-t', type: 'transfer', subject: 'spatial', skillIds: ['jigsaw'], familyId: 'jigsaw', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพนี้ขาดไปหนึ่งชิ้น ชิ้นส่วนใดใส่ในช่อง ? ได้พอดี' },
      visual: { type: 'jigsaw', asset: 'pic-beach', missing: 'tr' },
      options: [piece('a', 'beach', 'bl'), piece('b', 'beach', 'tr'), piece('c', 'mountain', 'tr'), piece('d', 'school', 'tr')],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'ชิ้นที่ถูกคือชิ้นมุมขวาบนของทะเลภาพเดียวกัน', hints: [], steps: ['ชิ้นของภูเขาและโรงเรียนเป็นคนละภาพ และชิ้นมุมซ้ายล่างของทะเลไม่ใช่มุมที่ขาด', 'ชิ้นมุมขวาบนของทะเลต่อได้พอดี'] },
    },
    {
      id: 'sp-jigsaw-market-t', type: 'transfer', subject: 'spatial', skillIds: ['jigsaw'], familyId: 'jigsaw', difficulty: 3,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพนี้ขาดไปหนึ่งชิ้น ชิ้นส่วนใดใส่ในช่อง ? ได้พอดี' },
      visual: { type: 'jigsaw', asset: 'pic-market', missing: 'bl' },
      options: [piece('a', 'waterfall', 'bl'), piece('b', 'market', 'tr'), piece('c', 'market', 'bl'), piece('d', 'market', 'br')],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'ชิ้นที่ถูกคือชิ้นมุมซ้ายล่างของตลาดภาพเดียวกัน', hints: [], steps: ['ชิ้นของน้ำตกเป็นคนละภาพ และชิ้นมุมอื่นของตลาดไม่ใช่มุมที่ขาด', 'ชิ้นมุมซ้ายล่างของตลาดต่อได้พอดี'] },
    },
    {
      id: 'sp-distance-trees-t', type: 'transfer', subject: 'spatial', skillIds: ['near-far'], familyId: 'near-far', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ต้นมะพร้าวต้นใดอยู่ไกลจากเรามากที่สุด' },
      visual: { type: 'distance', items: [{ asset: 'pic-coconut-tree', size: 1 }, { asset: 'pic-coconut-tree', size: 0.5 }, { asset: 'pic-coconut-tree', size: 0.75 }] },
      options: [{ id: 'a', text: 'ต้นที่ 1' }, { id: 'b', text: 'ต้นที่ 2' }, { id: 'c', text: 'ต้นที่ 3' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ต้นที่ 2 เล็กที่สุด จึงอยู่ไกลที่สุด', hints: [], steps: ['ต้นมะพร้าวทุกต้นสูงเท่ากันจริงๆ แต่ที่อยู่ไกลจะดูเล็กกว่า', 'ต้นที่ 2 เล็กที่สุด อยู่ไกลที่สุด'] },
    },
    {
      id: 'sp-distance-near-t', type: 'transfer', subject: 'spatial', skillIds: ['near-far'], familyId: 'near-far', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'บ้านหลังใดอยู่ใกล้เรามากที่สุด' },
      visual: houses(0.5, 0.9, 0.3, 0.7),
      options: [{ id: 'a', text: 'หลังที่ 1' }, { id: 'b', text: 'หลังที่ 2' }, { id: 'c', text: 'หลังที่ 4' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'หลังที่ 2 ใหญ่ที่สุด จึงอยู่ใกล้ที่สุด', hints: [], steps: ['บ้านที่อยู่ใกล้จะดูใหญ่กว่า', 'หลังที่ 2 ใหญ่ที่สุด อยู่ใกล้ที่สุด'] },
    },
    {
      id: 'th-opposite-near-t', type: 'transfer', subject: 'thai', skillIds: ['opposite-words'], familyId: 'opposite-words', difficulty: 1,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำว่า สูง มีความหมายตรงข้ามกับคำใด' },
      options: [{ id: 'a', text: 'ใหญ่' }, { id: 'b', text: 'เตี้ย' }, { id: 'c', text: 'ไกล' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'สูง ตรงข้ามกับ เตี้ย', hints: [], steps: ['ใหญ่ตรงข้ามกับเล็ก และไกลตรงข้ามกับใกล้', 'สูงตรงข้ามกับเตี้ย'] },
    },
    {
      id: 'sc-sky-night-t', type: 'transfer', subject: 'science', skillIds: ['sky'], familyId: 'sky', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ตอนกลางวันเรามักเห็นอะไรบนท้องฟ้า' },
      options: [{ id: 'a', text: 'ดาวหลายดวง' }, { id: 'b', text: 'ดวงอาทิตย์' }, { id: 'c', text: 'พระจันทร์เต็มดวงสว่างมาก' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'กลางวันเห็นดวงอาทิตย์', hints: [], steps: ['ดาวและพระจันทร์มองเห็นชัดตอนกลางคืน', 'กลางวันเห็นดวงอาทิตย์ส่องสว่าง'] },
    },
    {
      id: 'sc-rain-season-t', type: 'transfer', subject: 'science', skillIds: ['seasons'], familyId: 'seasons', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ฤดูที่อากาศเย็นที่สุดคือฤดูอะไร' },
      options: [{ id: 'a', text: 'ฤดูร้อน' }, { id: 'b', text: 'ฤดูหนาว' }, { id: 'c', text: 'ฤดูฝน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ฤดูหนาวอากาศเย็นที่สุด', hints: [], steps: ['ฤดูร้อนอากาศร้อน และฤดูฝนมีฝนตก', 'ฤดูหนาวอากาศเย็นที่สุด'] },
    },
    {
      id: 'g-weekday-prev-t', type: 'transfer', subject: 'general', skillIds: ['days-of-week'], familyId: 'days-of-week', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อวานเป็นวันจันทร์ วันนี้เป็นวันอะไร' },
      options: [{ id: 'a', text: 'วันอาทิตย์' }, { id: 'b', text: 'วันอังคาร' }, { id: 'c', text: 'วันพุธ' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ต่อจากวันจันทร์คือวันอังคาร', hints: [], steps: ['วันเรียงกัน อาทิตย์ จันทร์ อังคาร พุธ', 'หลังวันจันทร์คือวันอังคาร'] },
    },
    {
      id: 'm-children-day-t', type: 'transfer', subject: 'math', skillIds: ['number-before-after'], familyId: 'date-next', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'วันพ่อแห่งชาติตรงกับวันที่ 5 ธันวาคม ถ้าวันนี้เป็นวันที่ 1 ธันวาคม อีกกี่วันจะถึงวันพ่อ' },
      options: [{ id: 'a', text: '4 วัน' }, { id: 'b', text: '5 วัน' }, { id: 'c', text: '6 วัน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '5 ลบ 1 เท่ากับ 4 วัน', hints: [], steps: ['วันที่ 1 ถึงวันที่ 5 ต้องเอา 1 ไปลบออกจาก 5', '5 ลบ 1 เท่ากับ 4'], column: { a: 5, op: '-', b: 1 } },
    },
    {
      id: 'th-sentence-order-t', type: 'transfer', subject: 'thai', skillIds: ['sentence-type'], familyId: 'sentence-order', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ข้อใดเรียงคำเป็นประโยคได้ถูกต้อง' },
      options: [{ id: 'a', text: 'ทำแม่อาหาร' }, { id: 'b', text: 'อาหารทำแม่' }, { id: 'c', text: 'แม่ทำอาหาร' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แม่ทำอาหาร เรียงเป็นประโยคที่มีความหมาย', hints: [], steps: ['ทำแม่อาหาร และอาหารทำแม่ อ่านแล้วไม่มีความหมาย', 'แม่ทำอาหาร บอกว่าใครทำอะไร'] },
    },
  ],
};
