/*
 * ชุดที่ 7 — 12 ข้อหลัก (หมวดละ 2) + โจทย์ลองใหม่ 12 ข้อ
 * แต่งใหม่ทั้งหมด "ตามแนวข้อสอบเก่า" (ดู docs/RESEARCH.md หัวข้อชุดที่ 7) — ไม่ได้คัดลอกข้อความ ตัวเลข หรือภาพ
 * ใช้รูปเดิมทั้งหมด; ตาราง 3x3 (บน ล่าง ระหว่าง) และแถวภาพที่มีช่อง ? วาดด้วยโค้ด
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const LOOK = 'ดูรูปภาพแล้วตอบคำถามให้ถูกต้อง';
const GRID_A = { type: 'grid', rows: [['pic-fish', 'pic-cat', 'pic-umbrella'], ['pic-egg', 'pic-elephant', 'pic-orange'], ['pic-car', 'pic-ball', 'pic-chair']] };
const GRID_B = { type: 'grid', rows: [['pic-duck', 'pic-house', 'pic-bicycle'], ['pic-banana', 'pic-owl', 'pic-spoon'], ['pic-frog', 'pic-leaf', 'pic-horse']] };

export default {
  id: 'set-07',
  version: 1,
  title: 'ชุดที่ 7',
  note: 'สวนสัตว์ บน ล่าง ระหว่าง คล้องจอง แบบรูป บวกซ้ำ',
  order: [
    'th-zoo-banana', 'sc-zoo-owl', 'm-banana-bunches', 'r-all-fruit', 'th-rhyme-pla',
    'sp-grid-below', 'sp-grid-between', 'r-picture-pattern', 'g-lost-mall', 'sc-plant-needs',
    'm-money-left', 'g-trash-bin',
  ],
  stimuli: {
    zoo: {
      section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      text: 'ยายพาเมย์ไปเที่ยวสวนสัตว์ เมย์เห็นช้างกำลังกินกล้วย และเห็นนกฮูกนอนหลับอยู่บนต้นไม้ ตอนเย็นยายซื้อน้ำส้มให้เมย์ดื่ม',
    },
    grid: {
      section: 'ดูภาพในตารางแล้วตอบคำถามให้ถูกต้อง',
      text: 'ภาพในตารางมี 3 แถว แถวละ 3 ภาพ',
      visual: GRID_A,
    },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1
    {
      id: 'th-zoo-banana', type: 'main', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'zoo',
      prompt: { text: 'ที่สวนสัตว์ ช้างกำลังกินอะไร' },
      options: [{ id: 'a', image: 'pic-grapes', speech: 'องุ่น' }, { id: 'b', image: 'pic-banana', speech: 'กล้วย' }, { id: 'c', image: 'pic-carrot', speech: 'แครอท' }],
      correctOptionId: 'b',
      narration: 'ฟังเรื่องและชื่อภาพได้ วัดการฟังจับรายละเอียด',
      review: {
        summary: 'ช้างกำลังกินกล้วย',
        hints: ['ฟังตอนที่เรื่องพูดถึงช้าง'],
        steps: ['เรื่องบอกว่า เมย์เห็นช้างกำลังกินกล้วย', 'ช้างกินกล้วย ตอบข้อ 2'],
        transferIds: ['th-beach-crab-t'],
      },
    },
    {
      id: 'sc-zoo-owl', type: 'main', subject: 'science', skillIds: ['animal-traits'], familyId: 'nocturnal', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'zoo',
      prompt: { text: 'ทำไมนกฮูกจึงนอนหลับตอนกลางวัน' },
      options: [{ id: 'a', text: 'เพราะนกฮูกออกหากินตอนกลางคืน' }, { id: 'b', text: 'เพราะนกฮูกไม่ชอบต้นไม้' }, { id: 'c', text: 'เพราะนกฮูกไม่หิว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องสัตว์และการให้เหตุผล',
      review: {
        summary: 'นกฮูกออกหากินตอนกลางคืน จึงนอนตอนกลางวัน',
        hints: ['นกฮูกตื่นมาหากินตอนไหน'],
        steps: ['นกฮูกตาโต มองเห็นในที่มืดได้ดี จึงออกหากินตอนกลางคืน', 'ตอนกลางวันนกฮูกจึงนอนพัก ตอบข้อ 1'],
        transferIds: ['sc-bat-sleep-t'],
      },
    },
    {
      id: 'm-banana-bunches', type: 'main', subject: 'math', skillIds: ['repeated-addition'], familyId: 'groups-of', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'แม่ซื้อกล้วย 3 หวี หวีละ 4 ลูก แม่ซื้อกล้วยทั้งหมดกี่ลูก' },
      options: [{ id: 'a', text: '7 ลูก' }, { id: 'b', text: '16 ลูก' }, { id: 'c', text: '12 ลูก' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดการบวกซ้ำ (หวีละเท่ากัน)',
      review: {
        summary: '4 บวก 4 บวก 4 เท่ากับ 12 ลูก',
        hints: ['มี 3 หวี แต่ละหวีมี 4 ลูก บวกกันสามครั้ง'],
        steps: ['หวีแรก 4 ลูก หวีที่สอง 4 ลูก หวีที่สาม 4 ลูก', '4 บวก 4 ได้ 8 บวกอีก 4 ได้ 12 ลูก ตอบข้อ 3'],
        transferIds: ['m-egg-trays-t'],
      },
    },
    {
      id: 'r-all-fruit', type: 'main', subject: 'reasoning', skillIds: ['classify'], familyId: 'classify-groups', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดเป็นผลไม้ทั้งหมด' },
      options: [{ id: 'a', text: 'ส้ม แครอท ไข่' }, { id: 'b', text: 'ส้ม กล้วย องุ่น' }, { id: 'c', text: 'แตงโม ช้อน กล้วย' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่ม',
      review: {
        summary: 'ส้ม กล้วย องุ่น เป็นผลไม้ทั้งหมด',
        hints: ['ดูทีละคำ มีคำไหนไม่ใช่ผลไม้'],
        steps: ['ข้อ 1 มีแครอทเป็นผัก และไข่ ข้อ 3 มีช้อนเป็นของใช้', 'ข้อ 2 ส้ม กล้วย องุ่น เป็นผลไม้ทุกอย่าง ตอบข้อ 2'],
        transferIds: ['r-all-animals-t'],
      },
    },
    {
      id: 'th-rhyme-pla', type: 'main', subject: 'thai', skillIds: ['rhyme'], familyId: 'rhyme', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'คำใดคล้องจองกับคำว่า ปลา' },
      options: [{ id: 'a', text: 'หมา' }, { id: 'b', text: 'ปู' }, { id: 'c', text: 'ไก่' }],
      correctOptionId: 'a',
      narration: 'ฟังตัวเลือกได้ วัดการฟังเสียงท้ายคำ (คล้องจอง)',
      review: {
        summary: 'ปลา กับ หมา เสียงท้ายเหมือนกัน คือเสียง อา',
        hints: ['พูดคำว่า ปลา แล้วฟังเสียงท้าย'],
        steps: ['คำคล้องจองคือคำที่เสียงท้ายเหมือนกัน', 'ปลา ลงท้ายเสียง อา หมา ก็ลงท้ายเสียง อา ตอบข้อ 1'],
        transferIds: ['th-rhyme-kai-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2
    {
      id: 'sp-grid-below', type: 'main', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-position', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'grid',
      prompt: { text: 'ภาพใดอยู่ใต้แมวติดกันพอดี' },
      options: [{ id: 'a', image: 'pic-ball', speech: 'ลูกบอล' }, { id: 'b', image: 'pic-orange', speech: 'ส้ม' }, { id: 'c', image: 'pic-elephant', speech: 'ช้าง' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกตำแหน่ง เด็กต้องดูตารางเอง',
      review: {
        summary: 'ใต้แมวติดกันคือช้าง',
        hints: ['หาแมวก่อน แล้วมองลงมาหนึ่งช่อง'],
        steps: ['แมวอยู่แถวบน ตรงกลาง', 'ช่องที่อยู่ใต้แมวพอดีคือช้าง ลูกบอลอยู่ต่ำลงไปอีกแถว ตอบข้อ 3'],
        transferIds: ['sp-grid-above-t'],
      },
    },
    {
      id: 'sp-grid-between', type: 'main', subject: 'spatial', skillIds: ['position-between'], familyId: 'grid-between', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'grid',
      prompt: { text: 'ภาพใดอยู่ระหว่างรถกับเก้าอี้' },
      options: [{ id: 'a', image: 'pic-ball', speech: 'ลูกบอล' }, { id: 'b', image: 'pic-egg', speech: 'ไข่' }, { id: 'c', image: 'pic-chair', speech: 'เก้าอี้' }],
      correctOptionId: 'a',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกตำแหน่ง',
      review: {
        summary: 'ลูกบอลอยู่ระหว่างรถกับเก้าอี้',
        hints: ['รถกับเก้าอี้อยู่แถวไหน มีอะไรคั่นกลาง'],
        steps: ['แถวล่างสุดเรียง รถ ลูกบอล เก้าอี้', 'ลูกบอลอยู่ตรงกลาง ระหว่างรถกับเก้าอี้ ตอบข้อ 1'],
        transferIds: ['sp-grid-between-t'],
      },
    },
    {
      id: 'r-picture-pattern', type: 'main', subject: 'reasoning', skillIds: ['pattern-continue'], familyId: 'picture-pattern', difficulty: 1,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพเรียงกันแบบนี้ ภาพต่อไปควรเป็นภาพใด' },
      visual: { type: 'row', items: ['pic-orange', 'pic-banana', 'pic-orange', 'pic-banana', 'pic-orange', '?'] },
      options: [{ id: 'a', image: 'pic-orange', speech: 'ส้ม' }, { id: 'b', image: 'pic-banana', speech: 'กล้วย' }, { id: 'c', image: 'pic-grapes', speech: 'องุ่น' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้ เสียงไม่บอกลำดับ เด็กต้องดูแบบรูปเอง',
      review: {
        summary: 'ส้มกับกล้วยสลับกัน ต่อจากส้มจึงเป็นกล้วย',
        hints: ['ภาพสองภาพสลับกันไปเรื่อยๆ'],
        steps: ['ภาพเรียง ส้ม กล้วย ส้ม กล้วย ส้ม สลับกันทีละภาพ', 'ต่อจากส้มจึงเป็นกล้วย ตอบข้อ 2'],
        transferIds: ['r-picture-pattern-t'],
      },
    },
    {
      id: 'g-lost-mall', type: 'main', subject: 'general', skillIds: ['safety'], familyId: 'safety-lost', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าหลงกับคุณแม่ในห้างสรรพสินค้า หนูควรทำอย่างไร' },
      options: [{ id: 'a', text: 'เดินออกไปข้างนอกคนเดียว' }, { id: 'b', text: 'ไปกับคนแปลกหน้า' }, { id: 'c', text: 'บอกพนักงานหรือตำรวจ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องความปลอดภัย',
      review: {
        summary: 'บอกพนักงานหรือตำรวจให้ช่วยหาคุณแม่',
        hints: ['ใครในห้างที่ช่วยเราได้อย่างปลอดภัย'],
        steps: ['ไม่ควรออกไปข้างนอกคนเดียว และไม่ไปกับคนแปลกหน้า', 'ให้บอกพนักงานหรือตำรวจ แล้วรออยู่กับเขาให้คุณแม่มารับ ตอบข้อ 3'],
        transferIds: ['g-stranger-t'],
      },
    },
    {
      id: 'sc-plant-needs', type: 'main', subject: 'science', skillIds: ['plant-needs'], familyId: 'plant-needs', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ต้นไม้ต้องการสิ่งใดเพื่อเจริญเติบโต' },
      visual: { type: 'image', asset: 'pic-plant-sprout' },
      options: [{ id: 'a', text: 'น้ำและแสงแดด' }, { id: 'b', text: 'ขนมและนม' }, { id: 'c', text: 'ของเล่น' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องพืช',
      review: {
        summary: 'ต้นไม้ต้องการน้ำและแสงแดด',
        hints: ['เวลาปลูกต้นไม้ เราต้องทำอะไรทุกวัน'],
        steps: ['เรารดน้ำต้นไม้ และวางไว้ในที่มีแดด', 'ต้นไม้ใช้น้ำ แสงแดด และอากาศ ในการเจริญเติบโต ตอบข้อ 1'],
        transferIds: ['sc-no-water-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3
    {
      id: 'm-money-left', type: 'main', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'sub-2digit', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ลิลลี่มีเงิน 45 บาท ซื้อหนังสือนิทาน 20 บาท ลิลลี่เหลือเงินกี่บาท' },
      options: [{ id: 'a', text: '15 บาท' }, { id: 'b', text: '25 บาท' }, { id: 'c', text: '65 บาท' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการลบเลขสองหลัก',
      review: {
        summary: '45 ลบ 20 เท่ากับ 25 บาท',
        hints: ['จ่ายเงินไป เงินน้อยลง ต้องลบ'],
        steps: [
          'ซื้อหนังสือแล้วเงินน้อยลง จึงใช้การลบ 45 ลบ 20',
          'หลักหน่วย 5 ลบ 0 ได้ 5 หลักสิบ 4 ลบ 2 ได้ 2',
          'ได้ 25 บาท ตอบข้อ 2',
        ],
        column: { a: 45, op: '-', b: 20 },
        transferIds: ['m-money-left-t'],
      },
    },
    {
      id: 'g-trash-bin', type: 'main', subject: 'general', skillIds: ['environment'], familyId: 'environment', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'กินขนมเสร็จแล้ว เราควรทิ้งถุงขนมที่ไหน' },
      options: [{ id: 'a', text: 'ข้างถนน' }, { id: 'b', text: 'ในแม่น้ำ' }, { id: 'c', text: 'ถังขยะ' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการรักษาสิ่งแวดล้อม',
      review: {
        summary: 'ทิ้งถุงขนมลงถังขยะ',
        hints: ['ทิ้งตรงไหนแล้วบ้านเมืองสะอาด'],
        steps: ['ขยะข้างถนนและในแม่น้ำทำให้สกปรกและสัตว์ได้รับอันตราย', 'เราจึงควรทิ้งขยะลงถังขยะ ตอบข้อ 3'],
        transferIds: ['g-recycle-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'th-beach-crab-t', type: 'transfer', subject: 'thai', skillIds: ['listening-comprehension'], familyId: 'listen-detail', difficulty: 1,
      sourceId: SRC, ...R, section: 'ฟังเรื่องแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'พ่อพาต้นไปเที่ยวทะเล ต้นเก็บเปลือกหอย และเห็นปูตัวเล็กเดินบนหาดทราย ต้นเห็นสัตว์อะไรเดินบนหาด' },
      options: [{ id: 'a', image: 'pic-fish', speech: 'ปลา' }, { id: 'b', image: 'pic-frog', speech: 'กบ' }, { id: 'c', image: 'pic-crab', speech: 'ปู' }],
      correctOptionId: 'c',
      narration: 'ฟังเรื่องได้',
      review: { summary: 'ต้นเห็นปูเดินบนหาด', hints: [], steps: ['เรื่องบอกว่า เห็นปูตัวเล็กเดินบนหาดทราย', 'สัตว์ที่เดินบนหาดคือปู'] },
    },
    {
      id: 'sc-bat-sleep-t', type: 'transfer', subject: 'science', skillIds: ['animal-traits'], familyId: 'nocturnal', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ทำไมค้างคาวจึงนอนตอนกลางวัน' },
      options: [{ id: 'a', text: 'เพราะค้างคาวกลัวน้ำ' }, { id: 'b', text: 'เพราะค้างคาวออกหากินตอนกลางคืน' }, { id: 'c', text: 'เพราะค้างคาวชอบร้องเพลง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ค้างคาวหากินกลางคืน กลางวันจึงนอนพัก', hints: [], steps: ['ค้างคาวบินออกหากินตอนกลางคืน', 'กลางวันจึงนอนห้อยหัวพักผ่อน'] },
    },
    {
      id: 'm-egg-trays-t', type: 'transfer', subject: 'math', skillIds: ['repeated-addition'], familyId: 'groups-of', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีไข่ 2 ถาด ถาดละ 5 ฟอง มีไข่ทั้งหมดกี่ฟอง' },
      options: [{ id: 'a', text: '7 ฟอง' }, { id: 'b', text: '10 ฟอง' }, { id: 'c', text: '12 ฟอง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '5 บวก 5 เท่ากับ 10 ฟอง', hints: [], steps: ['ถาดแรก 5 ฟอง ถาดที่สอง 5 ฟอง', '5 บวก 5 เท่ากับ 10 ฟอง'], column: { a: 5, op: '+', b: 5 } },
    },
    {
      id: 'r-all-animals-t', type: 'transfer', subject: 'reasoning', skillIds: ['classify'], familyId: 'classify-groups', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ข้อใดเป็นสัตว์ทั้งหมด' },
      options: [{ id: 'a', text: 'แมว ช้าง ปลา' }, { id: 'b', text: 'แมว ร่ม ปลา' }, { id: 'c', text: 'ช้าง ส้ม ไก่' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แมว ช้าง ปลา เป็นสัตว์ทั้งหมด', hints: [], steps: ['ข้อ 2 มีร่มเป็นของใช้ ข้อ 3 มีส้มเป็นผลไม้', 'ข้อ 1 แมว ช้าง ปลา เป็นสัตว์ทุกตัว'] },
    },
    {
      id: 'th-rhyme-kai-t', type: 'transfer', subject: 'thai', skillIds: ['rhyme'], familyId: 'rhyme', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'คำใดคล้องจองกับคำว่า ไก่' },
      options: [{ id: 'a', text: 'ปลา' }, { id: 'b', text: 'แมว' }, { id: 'c', text: 'ไข่' }],
      correctOptionId: 'c',
      narration: 'ฟังตัวเลือกได้',
      review: { summary: 'ไก่ กับ ไข่ เสียงท้ายเหมือนกัน', hints: [], steps: ['ไก่ ลงท้ายเสียง ไอ', 'ไข่ ก็ลงท้ายเสียง ไอ จึงคล้องจองกัน'] },
    },
    {
      id: 'sp-grid-above-t', type: 'transfer', subject: 'spatial', skillIds: ['position-grid'], familyId: 'grid-position', difficulty: 2,
      sourceId: SRC, ...R, section: 'ดูภาพในตารางแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ภาพใดอยู่บนนกฮูกติดกันพอดี' },
      visual: GRID_B,
      options: [{ id: 'a', image: 'pic-leaf', speech: 'ใบไม้' }, { id: 'b', image: 'pic-house', speech: 'บ้าน' }, { id: 'c', image: 'pic-duck', speech: 'เป็ด' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'บนนกฮูกติดกันคือบ้าน', hints: [], steps: ['นกฮูกอยู่ตรงกลางตาราง', 'ช่องที่อยู่บนนกฮูกพอดีคือบ้าน'] },
    },
    {
      id: 'sp-grid-between-t', type: 'transfer', subject: 'spatial', skillIds: ['position-between'], familyId: 'grid-between', difficulty: 2,
      sourceId: SRC, ...R, section: 'ดูภาพในตารางแล้วตอบคำถามให้ถูกต้อง',
      prompt: { text: 'ภาพใดอยู่ระหว่างกล้วยกับช้อน' },
      visual: GRID_B,
      options: [{ id: 'a', image: 'pic-frog', speech: 'กบ' }, { id: 'b', image: 'pic-bicycle', speech: 'จักรยาน' }, { id: 'c', image: 'pic-owl', speech: 'นกฮูก' }],
      correctOptionId: 'c',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'นกฮูกอยู่ระหว่างกล้วยกับช้อน', hints: [], steps: ['แถวกลางเรียง กล้วย นกฮูก ช้อน', 'นกฮูกอยู่ตรงกลาง ระหว่างกล้วยกับช้อน'] },
    },
    {
      id: 'r-picture-pattern-t', type: 'transfer', subject: 'reasoning', skillIds: ['pattern-continue'], familyId: 'picture-pattern', difficulty: 2,
      sourceId: SRC, ...R, section: LOOK,
      prompt: { text: 'ภาพเรียงกันแบบนี้ ภาพต่อไปควรเป็นภาพใด' },
      visual: { type: 'row', items: ['pic-cat', 'pic-cat', 'pic-fish', 'pic-cat', 'pic-cat', '?'] },
      options: [{ id: 'a', image: 'pic-cat', speech: 'แมว' }, { id: 'b', image: 'pic-fish', speech: 'ปลา' }, { id: 'c', image: 'pic-duck', speech: 'เป็ด' }],
      correctOptionId: 'b',
      narration: 'อ่านชื่อภาพได้',
      review: { summary: 'แมว แมว ปลา เรียงซ้ำกัน', hints: [], steps: ['ชุดที่ซ้ำคือ แมว แมว ปลา', 'ต่อจาก แมว แมว จึงเป็น ปลา'] },
    },
    {
      id: 'g-stranger-t', type: 'transfer', subject: 'general', skillIds: ['safety'], familyId: 'safety-lost', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้ามีคนแปลกหน้าชวนไปกินขนม หนูควรทำอย่างไร' },
      options: [{ id: 'a', text: 'ไม่ไป แล้วบอกพ่อแม่หรือครู' }, { id: 'b', text: 'ไปกับเขา' }, { id: 'c', text: 'ชวนเพื่อนไปด้วย' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไม่ไปกับคนแปลกหน้า แล้วบอกผู้ใหญ่ที่ไว้ใจ', hints: [], steps: ['คนแปลกหน้าอาจพาเราไปที่อันตราย', 'ต้องไม่ไป แล้วรีบบอกพ่อแม่หรือครู'] },
    },
    {
      id: 'sc-no-water-t', type: 'transfer', subject: 'science', skillIds: ['plant-needs'], familyId: 'plant-needs', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ถ้าไม่รดน้ำต้นไม้เลยหลายวัน ต้นไม้จะเป็นอย่างไร' },
      options: [{ id: 'a', text: 'โตเร็วขึ้น' }, { id: 'b', text: 'เหี่ยวแห้ง' }, { id: 'c', text: 'ออกดอกเยอะขึ้น' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ต้นไม้ขาดน้ำจะเหี่ยวแห้ง', hints: [], steps: ['ต้นไม้ต้องใช้น้ำในการเจริญเติบโต', 'ถ้าขาดน้ำหลายวัน ใบจะเหี่ยวและแห้งตาย'] },
    },
    {
      id: 'm-money-left-t', type: 'transfer', subject: 'math', skillIds: ['word-problem-sub'], familyId: 'sub-2digit', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มีเงิน 38 บาท ซื้อดินสอ 10 บาท เหลือเงินกี่บาท' },
      options: [{ id: 'a', text: '18 บาท' }, { id: 'b', text: '48 บาท' }, { id: 'c', text: '28 บาท' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '38 ลบ 10 เท่ากับ 28 บาท', hints: [], steps: ['หลักหน่วย 8 ลบ 0 ได้ 8', 'หลักสิบ 3 ลบ 1 ได้ 2 รวมเป็น 28 บาท'], column: { a: 38, op: '-', b: 10 } },
    },
    {
      id: 'g-recycle-t', type: 'transfer', subject: 'general', skillIds: ['environment'], familyId: 'environment', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ขวดพลาสติกที่ดื่มน้ำหมดแล้ว ควรทำอย่างไร' },
      options: [{ id: 'a', text: 'โยนลงคลอง' }, { id: 'b', text: 'แยกใส่ถังขยะรีไซเคิล' }, { id: 'c', text: 'ทิ้งไว้ในห้องเรียน' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'แยกขวดพลาสติกใส่ถังขยะรีไซเคิล', hints: [], steps: ['ขวดพลาสติกนำกลับมาทำใหม่ได้', 'จึงควรแยกใส่ถังขยะรีไซเคิล'] },
    },
  ],
};
