/*
 * ชุดที่ 25 — ส่วนของร่างกาย (แผ่นรูป K: design/PROMPTS-gemini-10.md) แบบ 15 ข้อ
 * ช่วง 1 แผ่นภาพส่วนของร่างกาย 12 ภาพ ถาม 5 ข้อ: ดมกลิ่น ฟังเสียง (ตอบเป็นภาพ) นับอวัยวะที่เป็นคู่ นับนิ้ว คำเรียกรวม
 * ช่วง 2 ข้อเดี่ยว: จับคู่อวัยวะที่เป็นคู่ เปรียบเทียบหน้าที่ แปรงฟัน ล้างตา ชื่อส่วนของร่างกาย
 * ช่วง 3 ข้อเดี่ยว: หน้าที่ของฟัน นับเท้าของเด็กหลายคน ภาพต่อเนื่องสี่มุม นับสามเหลี่ยม ประโยคคำถาม
 * แต่งใหม่ทั้งหมด ตั้งชื่อตัวละคร สถานที่ และตัวเลขใหม่ตามแนวข้อสอบเก่า
 * (ผู้ปกครองรายงาน 2026-10-02: ข้อสอบจริงมีโจทย์เป็นตัวหนังสือให้เด็กดูด้วย — ทุกข้อในชุดนี้อ่านรู้เรื่องจากตัวหนังสือได้)
 */
const R = { provenance: 'original', rights: 'แต่งใหม่ทั้งหมด (ข้อความ ตัวเลข ภาพ) เผยแพร่ใน repo นี้ได้', reviewStatus: 'draft' };
const SRC = 'src-a24-compilation';
const BODY = 'ดูภาพส่วนของร่างกายแล้วตอบคำถามให้ถูกต้อง';
const WORDS = 'ตอบคำถามเกี่ยวกับคำให้ถูกต้อง';
const FIGURES = 'ภาพต่อเนื่อง ภาพที่หายไปควรเป็นภาพใด';
const body = (id, name) => ({ id, image: `pic-body-${name}` });
const fig = (id, figure) => ({ id, svg: { figure } });
const BOARD = { type: 'board', items: ['pic-body-eyes', 'pic-body-ears', 'pic-body-nose', 'pic-body-mouth', 'pic-body-hands', 'pic-body-feet', 'pic-body-teeth', 'pic-body-tongue', 'pic-body-hand5', 'pic-body-knee', 'pic-body-elbow', 'pic-body-hair'] };
const BOARD_TEXT = 'ในภาพมีส่วนของร่างกาย 12 ภาพ คือ ตาสองข้าง หูสองข้าง จมูก ปาก มือสองข้าง เท้าสองข้าง ฟัน ลิ้น มือข้างเดียวที่เห็นนิ้วมือห้านิ้ว เข่า ศอก และผม';

export default {
  id: 'set-25',
  version: 1,
  title: 'ชุดที่ 25',
  note: 'ส่วนของร่างกาย อวัยวะที่เป็นคู่ นับนิ้ว แปรงฟัน',
  order: [
    'sc-body-smell', 'sc-body-hear', 'm-body-pairs', 'm-body-fingers', 'th-body-group',
    'r-body-pairs', 'r-body-use', 'g-body-brush', 'g-body-eye', 'th-body-word',
    'sc-body-teeth', 'm-body-feet', 'sp-body-corners', 'sp-triangle-count', 'th-ask-sentence',
  ],
  stimuli: {
    body: { section: BODY, text: BOARD_TEXT, visual: BOARD },
  },
  items: [
    // ---------------------------------------------------------------- ช่วงที่ 1: แผ่นภาพส่วนของร่างกาย 5 ข้อ
    {
      id: 'sc-body-smell', type: 'main', subject: 'science', skillIds: ['senses'], familyId: 'board-senses', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'body',
      prompt: { text: 'ภาพใดเป็นอวัยวะที่ใช้ดมกลิ่น' },
      options: [body('a', 'eyes'), body('b', 'nose'), body('c', 'ears'), body('d', 'mouth')],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดความรู้เรื่องอวัยวะรับกลิ่น',
      review: {
        summary: 'จมูกใช้ดมกลิ่น',
        hints: ['เวลาได้กลิ่นหอมของอาหาร เราใช้ส่วนไหนของใบหน้า'],
        steps: ['ตาใช้ดู หูใช้ฟัง และปากใช้กินและพูด', 'จมูกใช้ดมกลิ่น ตอบข้อ 2'],
        transferIds: ['sc-body-smell-t'],
      },
    },
    {
      id: 'sc-body-hear', type: 'main', subject: 'science', skillIds: ['senses'], familyId: 'board-senses', difficulty: 1,
      sourceId: SRC, ...R, stimulus: 'body',
      prompt: { text: 'ภาพใดเป็นอวัยวะที่ใช้ฟังเสียง' },
      options: [body('a', 'mouth'), body('b', 'hands'), body('c', 'ears'), body('d', 'feet')],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดความรู้เรื่องอวัยวะรับเสียง',
      review: {
        summary: 'หูใช้ฟังเสียง',
        hints: ['เวลามีคนเรียกชื่อ เราใช้ส่วนไหนฟัง'],
        steps: ['ปากใช้พูดและกิน มือใช้จับ เท้าใช้เดิน', 'หูใช้ฟังเสียง ตอบข้อ 3'],
        transferIds: ['sc-body-hear-t'],
      },
    },
    {
      id: 'm-body-pairs', type: 'main', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'body',
      prompt: { text: 'ในภาพมีอวัยวะที่วาดไว้เป็นคู่กี่อย่าง' },
      options: [{ id: 'a', text: '4 อย่าง' }, { id: 'b', text: '3 อย่าง' }, { id: 'c', text: '6 อย่าง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มแล้วนับ (ตา หู มือ เท้า)',
      review: {
        summary: 'ตา หู มือ และเท้า วาดเป็นคู่ รวม 4 อย่าง',
        hints: ['ดูภาพที่มีสองข้างอยู่คู่กัน'],
        steps: ['ภาพที่วาดเป็นคู่คือ ตา หู มือ และเท้า', 'จมูก ปาก ฟัน ลิ้น เข่า ศอก ผม และมือข้างเดียว ไม่ได้เป็นคู่ รวมเป็น 4 อย่าง ตอบข้อ 1'],
        transferIds: ['m-body-pairs-t'],
      },
    },
    {
      id: 'm-body-fingers', type: 'main', subject: 'math', skillIds: ['repeated-addition'], familyId: 'fingers', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'body',
      prompt: { text: 'มือข้างเดียวมีนิ้ว 5 นิ้ว ถ้ามีมือสองข้าง จะมีนิ้วมือทั้งหมดกี่นิ้ว' },
      options: [{ id: 'a', text: '5 นิ้ว' }, { id: 'b', text: '10 นิ้ว' }, { id: 'c', text: '20 นิ้ว' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการบวกซ้ำสองครั้ง',
      review: {
        summary: 'มือสองข้างมีนิ้ว 5 บวก 5 เท่ากับ 10 นิ้ว',
        hints: ['มือแต่ละข้างมีนิ้วเท่ากัน เอามาบวกกัน'],
        steps: ['มือข้างหนึ่งมี 5 นิ้ว อีกข้างหนึ่งก็มี 5 นิ้ว', '5 บวก 5 เท่ากับ 10 ตอบข้อ 2'],
        column: { a: 5, op: '+', b: 5 },
        transferIds: ['m-body-fingers-t'],
      },
    },
    {
      id: 'th-body-group', type: 'main', subject: 'thai', skillIds: ['group-words'], familyId: 'group-words', difficulty: 2,
      sourceId: SRC, ...R, stimulus: 'body',
      prompt: { text: 'ตา หู จมูก ปาก เรียกรวมกันว่าอะไร' },
      options: [{ id: 'a', text: 'ส่วนของแขนขา' }, { id: 'b', text: 'อวัยวะที่เป็นคู่' }, { id: 'c', text: 'อวัยวะบนใบหน้า' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความเข้าใจคำเรียกรวมของกลุ่มคำ',
      review: {
        summary: 'ตา หู จมูก ปาก อยู่บนใบหน้าทั้งหมด',
        hints: ['อวัยวะเหล่านี้อยู่ที่ส่วนไหนของร่างกาย'],
        steps: ['แขนขาคือมือ เท้า เข่า ศอก ส่วนจมูกและปากไม่ได้เป็นคู่', 'ตา หู จมูก ปาก อยู่บนใบหน้า จึงเรียกว่าอวัยวะบนใบหน้า ตอบข้อ 3'],
        transferIds: ['th-body-group-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 2: ข้อเดี่ยว
    {
      id: 'r-body-pairs', type: 'main', subject: 'reasoning', skillIds: ['classify'], familyId: 'body-pairs', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'อวัยวะสองอย่างใดที่มีเป็นคู่ทั้งสองอย่าง' },
      options: [{ id: 'a', text: 'ตา, หู' }, { id: 'b', text: 'จมูก, ปาก' }, { id: 'c', text: 'ลิ้น, จมูก' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการจัดกลุ่มอวัยวะที่มีสองข้าง',
      review: {
        summary: 'ตาและหูมีสองข้างเป็นคู่',
        hints: ['ลองนับดูว่าอวัยวะไหนมีสองข้าง'],
        steps: ['จมูก ปาก และลิ้น มีอย่างละหนึ่ง ไม่เป็นคู่', 'ตามีสองข้าง หูมีสองข้าง จึงเป็นคู่ ตอบข้อ 1'],
        transferIds: ['r-body-pairs-t'],
      },
    },
    {
      id: 'r-body-use', type: 'main', subject: 'reasoning', skillIds: ['relationship'], familyId: 'analogy', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ตาใช้ดู หูใช้ทำอะไร' },
      options: [{ id: 'a', text: 'ดมกลิ่น' }, { id: 'b', text: 'ฟังเสียง' }, { id: 'c', text: 'พูด' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการเทียบหน้าที่ของอวัยวะ',
      review: {
        summary: 'ตาใช้ดู หูใช้ฟัง',
        hints: ['อวัยวะแต่ละอย่างรับรู้สิ่งรอบตัวต่างกัน'],
        steps: ['ดมกลิ่นเป็นหน้าที่ของจมูก และพูดเป็นหน้าที่ของปาก', 'หูใช้ฟังเสียง ตอบข้อ 2'],
        transferIds: ['r-body-use-t'],
      },
    },
    {
      id: 'g-body-brush', type: 'main', subject: 'general', skillIds: ['hygiene'], familyId: 'hygiene', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ควรแปรงฟันอย่างน้อยวันละกี่ครั้ง' },
      options: [{ id: 'a', text: '1 ครั้ง' }, { id: 'b', text: '5 ครั้ง' }, { id: 'c', text: '2 ครั้ง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการดูแลฟัน',
      review: {
        summary: 'แปรงฟันตอนเช้าและก่อนนอน อย่างน้อยวันละ 2 ครั้ง',
        hints: ['นึกถึงตอนตื่นนอนและก่อนเข้านอน'],
        steps: ['แปรงฟันครั้งเดียวไม่พอ ส่วนห้าครั้งมากเกินไป', 'ควรแปรงตอนเช้าและก่อนนอน คือวันละ 2 ครั้ง ตอบข้อ 3'],
        transferIds: ['g-body-brush-t'],
      },
    },
    {
      id: 'g-body-eye', type: 'main', subject: 'general', skillIds: ['safety'], familyId: 'safety-body', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อมีฝุ่นเข้าตา ควรทำอย่างไร' },
      options: [{ id: 'a', text: 'ล้างตาด้วยน้ำสะอาด' }, { id: 'b', text: 'ขยี้ตาแรงๆ' }, { id: 'c', text: 'เอานิ้วมือสกปรกแคะตา' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องการดูแลดวงตา',
      review: {
        summary: 'ล้างตาด้วยน้ำสะอาด ไม่ขยี้ตา',
        hints: ['ทำอย่างไรให้ฝุ่นออกโดยไม่ทำให้ตาเจ็บ'],
        steps: ['ขยี้ตาแรงๆ หรือเอามือสกปรกแคะตา ทำให้ตาเจ็บและติดเชื้อได้', 'ควรล้างตาด้วยน้ำสะอาด ตอบข้อ 1'],
        transferIds: ['g-body-eye-t'],
      },
    },
    {
      id: 'th-body-word', type: 'main', subject: 'thai', skillIds: ['classify-words'], familyId: 'classify-words', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดเป็นชื่อส่วนของร่างกาย' },
      options: [{ id: 'a', text: 'เก้าอี้' }, { id: 'b', text: 'เข่า' }, { id: 'c', text: 'เกลือ' }],
      correctOptionId: 'b',
      narration: 'ฟังตัวเลือกได้ วัดการแยกประเภทคำ',
      review: {
        summary: 'เข่าเป็นส่วนของร่างกาย',
        hints: ['คำไหนเป็นของที่ติดอยู่กับตัวเรา'],
        steps: ['เก้าอี้เป็นเฟอร์นิเจอร์ และเกลือเป็นเครื่องปรุงอาหาร', 'เข่าเป็นส่วนของขา ตอบข้อ 2'],
        transferIds: ['th-body-word-t'],
      },
    },

    // ---------------------------------------------------------------- ช่วงที่ 3: ฟัน เท้า ภาพ ประโยคคำถาม
    {
      id: 'sc-body-teeth', type: 'main', subject: 'science', skillIds: ['body-parts'], familyId: 'body-function', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ฟันมีหน้าที่ทำอะไร' },
      options: [{ id: 'a', text: 'ย่อยอาหารในท้อง' }, { id: 'b', text: 'ดมกลิ่นอาหาร' }, { id: 'c', text: 'เคี้ยวอาหาร' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้ วัดความรู้เรื่องหน้าที่ของฟัน',
      review: {
        summary: 'ฟันช่วยบดเคี้ยวอาหารให้ละเอียด',
        hints: ['ก่อนกลืนอาหาร เราใช้อะไรบดอาหารในปาก'],
        steps: ['การย่อยอาหารในท้องเป็นหน้าที่ของกระเพาะ และการดมกลิ่นเป็นหน้าที่ของจมูก', 'ฟันมีหน้าที่เคี้ยวอาหาร ตอบข้อ 3'],
        transferIds: ['sc-body-teeth-t'],
      },
    },
    {
      id: 'm-body-feet', type: 'main', subject: 'math', skillIds: ['count-legs'], familyId: 'count-legs', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เด็ก 1 คนมีเท้า 2 ข้าง เด็ก 3 คนมีเท้ารวมกันกี่ข้าง' },
      options: [{ id: 'a', text: '6 ข้าง' }, { id: 'b', text: '5 ข้าง' }, { id: 'c', text: '8 ข้าง' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ วัดการนับเพิ่มทีละ 2',
      review: {
        summary: 'เด็ก 3 คน นับทีละ 2 ได้ 6 ข้าง',
        hints: ['นับเพิ่มทีละ 2 ตามจำนวนเด็ก'],
        steps: ['เด็กคนที่หนึ่งมีเท้า 2 ข้าง คนที่สองเพิ่มอีก 2 เป็น 4', 'คนที่สามเพิ่มอีก 2 เป็น 6 ข้าง ตอบข้อ 1'],
        transferIds: ['m-body-feet-t'],
      },
    },
    {
      id: 'sp-body-corners', type: 'main', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'half-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ half: 'tl' }, { half: 'tr' }, { half: 'br' }, '?'] },
      options: [fig('a', { half: 'tl' }), fig('b', { half: 'tr' }), fig('c', { half: 'bl' }), fig('d', { half: 'br' })],
      correctOptionId: 'c',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ) วัดการต่อภาพที่เลื่อนไปตามเข็มนาฬิกา',
      review: {
        summary: 'ส่วนที่ระบายสีเลื่อนตามเข็มนาฬิกาทีละมุม ต่อไปคือมุมล่างซ้าย',
        hints: ['ดูว่าส่วนที่ระบายสีย้ายจากมุมไหนไปมุมไหนในแต่ละภาพ'],
        steps: ['ส่วนที่ระบายสีย้ายจากมุมบนซ้าย ไปมุมบนขวา แล้วไปมุมล่างขวา คือเลื่อนตามเข็มนาฬิกา', 'มุมต่อไปคือมุมล่างซ้าย ตอบข้อ 3'],
        transferIds: ['sp-body-corners-t'],
      },
    },
    {
      id: 'sp-triangle-count', type: 'main', subject: 'spatial', skillIds: ['count-shapes'], familyId: 'count-shapes', difficulty: 1,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ในภาพมีสามเหลี่ยมกี่รูป' },
      visual: { type: 'shape-count', shapes: ['triangle', 'circle', 'triangle', 'square', 'triangle', 'circle'] },
      options: [{ id: 'a', text: '3 รูป' }, { id: 'b', text: '4 รูป' }, { id: 'c', text: '2 รูป' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้ เสียงไม่บอกจำนวน เด็กต้องนับรูปจากภาพเอง',
      review: {
        summary: 'มีสามเหลี่ยม 3 รูป',
        hints: ['นับเฉพาะรูปสามเหลี่ยมทีละรูป'],
        steps: ['รูปในภาพมี สามเหลี่ยม วงกลม สี่เหลี่ยม ปนกัน', 'นับเฉพาะสามเหลี่ยมได้ 3 รูป ตอบข้อ 1'],
        transferIds: ['sp-triangle-count-t'],
      },
    },
    {
      id: 'th-ask-sentence', type: 'main', subject: 'thai', skillIds: ['sentence-type'], familyId: 'sentence-type', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ประโยคใดเป็นประโยคคำถาม' },
      options: [{ id: 'a', text: 'ฉันชื่อนิด' }, { id: 'b', text: 'เธอชื่ออะไร' }, { id: 'c', text: 'ช่วยปิดประตูหน่อย' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้ วัดการแยกประเภทประโยค',
      review: {
        summary: 'เธอชื่ออะไร เป็นประโยคที่ถามเพื่อให้ได้คำตอบ',
        hints: ['ประโยคคำถามมักมีคำว่า อะไร ใคร ที่ไหน'],
        steps: ['ฉันชื่อนิดเป็นประโยคบอกเล่า และช่วยปิดประตูหน่อยเป็นประโยคขอร้อง', 'เธอชื่ออะไรมีคำว่า อะไร เป็นประโยคคำถาม ตอบข้อ 2'],
        transferIds: ['th-ask-sentence-t'],
      },
    },

    // ---------------------------------------------------------------- โจทย์ลองใหม่ (เปิดในหน้าเฉลย ไม่นับเป็นข้อสอบ)
    {
      id: 'sc-body-smell-t', type: 'transfer', subject: 'science', skillIds: ['senses'], familyId: 'board-senses', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เราใช้อวัยวะใดดูสิ่งต่างๆ' },
      options: [{ id: 'a', text: 'ตา' }, { id: 'b', text: 'ปาก' }, { id: 'c', text: 'มือ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ตาใช้ดูสิ่งต่างๆ', hints: [], steps: ['ปากใช้กินและพูด มือใช้จับ', 'ตาใช้ดู'] },
    },
    {
      id: 'sc-body-hear-t', type: 'transfer', subject: 'science', skillIds: ['senses'], familyId: 'board-senses', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เราใช้อวัยวะใดชิมรสอาหาร' },
      options: [{ id: 'a', text: 'หู' }, { id: 'b', text: 'ลิ้น' }, { id: 'c', text: 'เท้า' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ลิ้นใช้ชิมรสอาหาร', hints: [], steps: ['หูใช้ฟัง และเท้าใช้เดิน', 'ลิ้นใช้ชิมรสอาหาร'] },
    },
    {
      id: 'm-body-pairs-t', type: 'transfer', subject: 'math', skillIds: ['classify-count'], familyId: 'board-count', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'ในกล่องมีของ ตา หู จมูก ปาก ของที่มีเป็นคู่มีกี่อย่าง' },
      options: [{ id: 'a', text: '1 อย่าง' }, { id: 'b', text: '3 อย่าง' }, { id: 'c', text: '2 อย่าง' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ตากับหูเป็นคู่ รวม 2 อย่าง', hints: [], steps: ['จมูกและปากมีอย่างละหนึ่ง ไม่เป็นคู่', 'ตากับหูเป็นคู่ รวม 2 อย่าง'] },
    },
    {
      id: 'm-body-fingers-t', type: 'transfer', subject: 'math', skillIds: ['repeated-addition'], familyId: 'fingers', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เท้าข้างเดียวมีนิ้วเท้า 5 นิ้ว ถ้ามีเท้าสองข้าง จะมีนิ้วเท้าทั้งหมดกี่นิ้ว' },
      options: [{ id: 'a', text: '10 นิ้ว' }, { id: 'b', text: '5 นิ้ว' }, { id: 'c', text: '15 นิ้ว' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: '5 บวก 5 เท่ากับ 10 นิ้ว', hints: [], steps: ['เท้าข้างหนึ่งมี 5 นิ้ว อีกข้างหนึ่งก็มี 5 นิ้ว', '5 บวก 5 เท่ากับ 10'], column: { a: 5, op: '+', b: 5 } },
    },
    {
      id: 'th-body-group-t', type: 'transfer', subject: 'thai', skillIds: ['group-words'], familyId: 'group-words', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'มือ เท้า ศอก เข่า เรียกรวมกันว่าอะไร' },
      options: [{ id: 'a', text: 'ส่วนของแขนและขา' }, { id: 'b', text: 'อวัยวะบนใบหน้า' }, { id: 'c', text: 'ของใช้ในบ้าน' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มือ ศอก เป็นส่วนของแขน เท้า เข่า เป็นส่วนของขา', hints: [], steps: ['อวัยวะบนใบหน้าคือ ตา หู จมูก ปาก', 'มือ ศอก เท้า เข่า เป็นส่วนของแขนและขา'] },
    },
    {
      id: 'r-body-pairs-t', type: 'transfer', subject: 'reasoning', skillIds: ['classify'], familyId: 'body-pairs', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'อวัยวะสองอย่างใดที่มีเป็นคู่ทั้งสองอย่าง' },
      options: [{ id: 'a', text: 'ปาก, ฟัน' }, { id: 'b', text: 'จมูก, ผม' }, { id: 'c', text: 'มือ, เท้า' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มือและเท้ามีสองข้างเป็นคู่', hints: [], steps: ['ปาก จมูก มีอย่างละหนึ่ง ส่วนฟันและผมมีหลายอัน ไม่เรียกว่าคู่', 'มือสองข้าง เท้าสองข้าง จึงเป็นคู่'] },
    },
    {
      id: 'r-body-use-t', type: 'transfer', subject: 'reasoning', skillIds: ['relationship'], familyId: 'analogy', difficulty: 3,
      sourceId: SRC, ...R,
      prompt: { text: 'ปากใช้พูด จมูกใช้ทำอะไร' },
      options: [{ id: 'a', text: 'ดมกลิ่น' }, { id: 'b', text: 'ฟังเสียง' }, { id: 'c', text: 'จับของ' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'จมูกใช้ดมกลิ่น', hints: [], steps: ['ปากใช้พูด คือบอกหน้าที่ของอวัยวะ', 'จมูกใช้ดมกลิ่น'] },
    },
    {
      id: 'g-body-brush-t', type: 'transfer', subject: 'general', skillIds: ['hygiene'], familyId: 'hygiene', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ควรตัดเล็บบ่อยๆ เพราะเหตุใด' },
      options: [{ id: 'a', text: 'เพื่อให้เล็บยาวสวย' }, { id: 'b', text: 'เพราะเล็บยาวมีสิ่งสกปรกสะสมได้' }, { id: 'c', text: 'เพราะเล็บทำให้ตัวสูงขึ้น' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เล็บยาวมีสิ่งสกปรกและเชื้อโรคซ่อนอยู่', hints: [], steps: ['เล็บไม่ได้ทำให้ตัวสูงขึ้น และเล็บยาวไม่ได้ทำให้สะอาดขึ้น', 'เล็บยาวมีสิ่งสกปรกสะสม จึงควรตัดบ่อยๆ'] },
    },
    {
      id: 'g-body-eye-t', type: 'transfer', subject: 'general', skillIds: ['safety'], familyId: 'safety-body', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'เมื่อจะอ่านหนังสือ ควรทำอย่างไรเพื่อถนอมสายตา' },
      options: [{ id: 'a', text: 'อ่านในที่มืด' }, { id: 'b', text: 'อ่านในที่มีแสงสว่างพอ' }, { id: 'c', text: 'ถือหนังสือชิดตา' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ควรอ่านในที่มีแสงสว่างพอ', hints: [], steps: ['อ่านในที่มืดหรือถือหนังสือชิดตา ทำให้ตาเมื่อยล้า', 'ควรอ่านในที่มีแสงสว่างพอ'] },
    },
    {
      id: 'th-body-word-t', type: 'transfer', subject: 'thai', skillIds: ['classify-words'], familyId: 'classify-words', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'คำใดเป็นชื่อส่วนของร่างกาย' },
      options: [{ id: 'a', text: 'ช้อน' }, { id: 'b', text: 'ชาม' }, { id: 'c', text: 'ไหล่' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ไหล่เป็นส่วนของร่างกาย', hints: [], steps: ['ช้อนและชามเป็นของใช้ในครัว', 'ไหล่เป็นส่วนของร่างกายที่ต่อกับแขน'] },
    },
    {
      id: 'sc-body-teeth-t', type: 'transfer', subject: 'science', skillIds: ['body-parts'], familyId: 'body-function', difficulty: 1,
      sourceId: SRC, ...R,
      prompt: { text: 'ลิ้นมีหน้าที่ทำอะไร' },
      options: [{ id: 'a', text: 'ชิมรสอาหาร' }, { id: 'b', text: 'ฟังเสียง' }, { id: 'c', text: 'มองเห็น' }],
      correctOptionId: 'a',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'ลิ้นช่วยชิมรสอาหาร', hints: [], steps: ['การฟังเป็นหน้าที่ของหู และการมองเห็นเป็นหน้าที่ของตา', 'ลิ้นช่วยชิมรสอาหาร'] },
    },
    {
      id: 'm-body-feet-t', type: 'transfer', subject: 'math', skillIds: ['count-legs'], familyId: 'count-legs', difficulty: 2,
      sourceId: SRC, ...R,
      prompt: { text: 'เด็ก 1 คนมีตา 2 ข้าง เด็ก 4 คนมีตารวมกันกี่ข้าง' },
      options: [{ id: 'a', text: '6 ข้าง' }, { id: 'b', text: '8 ข้าง' }, { id: 'c', text: '4 ข้าง' }],
      correctOptionId: 'b',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'เด็ก 4 คน นับทีละ 2 ได้ 8 ข้าง', hints: [], steps: ['นับเพิ่มทีละ 2 ตามจำนวนเด็ก ได้ 2 4 6 8', 'เด็ก 4 คนมีตารวมกัน 8 ข้าง'] },
    },
    {
      id: 'sp-body-corners-t', type: 'transfer', subject: 'spatial', skillIds: ['figure-sequence'], familyId: 'half-sequence', difficulty: 2,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ภาพในช่อง ? ควรเป็นภาพใด' },
      visual: { type: 'figure-row', items: [{ half: 'br' }, { half: 'bl' }, { half: 'tl' }, '?'] },
      options: [fig('a', { half: 'br' }), fig('b', { half: 'tr' }), fig('c', { half: 'bl' }), fig('d', { half: 'tl' })],
      correctOptionId: 'b',
      narration: 'ไม่อ่านตัวเลือก (เป็นภาพ)',
      review: { summary: 'ส่วนที่ระบายสีเลื่อนตามเข็มนาฬิกาทีละมุม ต่อไปคือมุมบนขวา', hints: [], steps: ['ส่วนที่ระบายสีย้ายจากมุมล่างขวา ไปล่างซ้าย แล้วบนซ้าย คือเลื่อนตามเข็มนาฬิกา', 'มุมต่อไปคือมุมบนขวา'] },
    },
    {
      id: 'sp-triangle-count-t', type: 'transfer', subject: 'spatial', skillIds: ['count-shapes'], familyId: 'count-shapes', difficulty: 1,
      sourceId: SRC, ...R, section: FIGURES,
      prompt: { text: 'ในภาพมีวงกลมกี่รูป' },
      visual: { type: 'shape-count', shapes: ['circle', 'square', 'circle', 'triangle', 'circle', 'square', 'circle'] },
      options: [{ id: 'a', text: '3 รูป' }, { id: 'b', text: '5 รูป' }, { id: 'c', text: '4 รูป' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'มีวงกลม 4 รูป', hints: [], steps: ['รูปในภาพมี วงกลม สี่เหลี่ยม สามเหลี่ยม ปนกัน', 'นับเฉพาะวงกลมได้ 4 รูป'] },
    },
    {
      id: 'th-ask-sentence-t', type: 'transfer', subject: 'thai', skillIds: ['sentence-type'], familyId: 'sentence-type', difficulty: 2,
      sourceId: SRC, ...R, section: WORDS,
      prompt: { text: 'ประโยคใดเป็นประโยคคำถาม' },
      options: [{ id: 'a', text: 'วันนี้ฝนตก' }, { id: 'b', text: 'ขอน้ำหน่อยค่ะ' }, { id: 'c', text: 'บ้านของเธออยู่ที่ไหน' }],
      correctOptionId: 'c',
      narration: 'อ่านตัวเลือกได้',
      review: { summary: 'บ้านของเธออยู่ที่ไหน เป็นประโยคที่ถามเพื่อให้ได้คำตอบ', hints: [], steps: ['วันนี้ฝนตกเป็นประโยคบอกเล่า และขอน้ำหน่อยค่ะเป็นประโยคขอร้อง', 'บ้านของเธออยู่ที่ไหนมีคำว่า ที่ไหน เป็นประโยคคำถาม'] },
    },
  ],
};
